:PROPERTIES:
:ID:       b043e085-a9d3-4da5-8686-938fb3bfdcda
:LAST_MODIFIED: [2023-02-12 Sun 09:45]
:END:
#+title: Adversarial interoperability
#+hugo_custom_front_matter: :slug "b043e085-a9d3-4da5-8686-938fb3bfdcda"
#+author: Cash Prokop-Weaver
#+date: [2022-10-12 Wed 10:35]
#+filetags: :concept:

A type of [[id:a41fccc0-fe85-462b-b8e9-5758fd6327b3][Interoperability]].

#+begin_quote
[[[id:b043e085-a9d3-4da5-8686-938fb3bfdcda][Adversarial interoperability]] is] when you create a new product or service that plugs into the existing ones without the permission of the companies that make them. Think of third-party printer ink, alternative app stores, or independent repair shops that use compatible parts from rival manufacturers to fix your car or your phone or your tractor.

[cite:@doctorowAdversarialInteroperability2019]
#+end_quote

#+begin_quote
What made iWork a success—and helped re-launch Apple—was the fact that Pages could open and save most Word files; Numbers could open and save most Excel files; and Keynote could open and save most PowerPoint presentations. Apple did not attain this compatibility through Microsoft's cooperation: it attained it despite Microsoft's noncooperation. Apple didn't just make an "interoperable" product that worked with an existing product in the market: they made an [[id:b043e085-a9d3-4da5-8686-938fb3bfdcda][adversarially interoperable]] product whose compatibility was wrested from the incumbent, through diligent reverse-engineering and reimplementation. What's more, Apple committed to maintaining that interoperability, even though Microsoft continued to update its products in ways that temporarily undermined the ability of Apple customers to exchange documents with Microsoft customers, paying engineers to unbreak everything that Microsoft's maneuvers broke. Apple's persistence paid off: over time, Microsoft's customers became dependent on compatibility with Apple customers, and they would complain if Microsoft changed its Office products in ways that broke their cross-platform workflow.

Since Pages' launch, document interoperability has stabilized, with multiple parties entering the market, including Google's cloud-based Docs offerings, and the free/open alternatives from LibreOffice. The convergence on this standard was not undertaken with the blessing of the dominant player: rather, it came about despite Microsoft's opposition. Docs are not just interoperable, they're adversarially interoperable: each has its own file format, but each can read Microsoft's file format.

[cite:@doctorowAdversarialInteroperabilityRevivingElegantWeaponMoreCivilizedAgeSlayToday2019]
#+end_quote
* Flashcards
** Definition :fc:
:PROPERTIES:
:CREATED: [2022-10-12 Wed 10:38]
:FC_CREATED: 2022-10-12T17:40:29Z
:FC_TYPE:  double
:ID:       d801da47-9c96-4c85-be81-2ea611fa1f60
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   6 |   131.53 | 2023-06-18T16:18:19Z |
| back     | 2.80 |   6 |   102.61 | 2023-05-26T08:20:06Z |
:END:

[[id:b043e085-a9d3-4da5-8686-938fb3bfdcda][Adversarial interoperability]]

*** Back

[[id:a41fccc0-fe85-462b-b8e9-5758fd6327b3][Interoperability]] achieved without the permission or support of, and sometimes in spite of resistance on the part of, the makers of the original thing.
*** Source
[cite:@doctorowAdversarialInteroperability2019]
** Example(s) :fc:
:PROPERTIES:
:CREATED: [2022-10-12 Wed 10:44]
:FC_CREATED: 2022-10-12T17:44:50Z
:FC_TYPE:  double
:ID:       589de867-a751-48b8-8b58-074abe7fcdd4
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 3.10 |   6 |   163.05 | 2023-06-29T03:14:51Z |
| back     | 2.65 |   6 |   104.80 | 2023-05-15T10:47:54Z |
:END:

[[id:b043e085-a9d3-4da5-8686-938fb3bfdcda][Adversarial interoperability]]

*** Back
- Apple's office suite recognizing Microsoft's Word/etc file formats
*** Source
[cite:@doctorowAdversarialInteroperabilityRevivingElegantWeaponMoreCivilizedAgeSlayToday2019]
#+print_bibliography: