:PROPERTIES:
:ROAM_REFS: [cite:@saint-exuperyLittlePrince2000]
:ID:       a83c34da-e718-477c-a8c0-5de6a2f788f1
:LAST_MODIFIED: [2024-02-05 Mon 09:07]
:END:
#+title: Antoine de Saint-Exupéry | The Little Prince
#+hugo_custom_front_matter: :slug "a83c34da-e718-477c-a8c0-5de6a2f788f1"
#+author: Cash Weaver
#+date: [2024-02-05 Mon 09:07]
#+filetags: :hastodo:reference:

TODO_AUTHOR, [cite:@saint-exuperyLittlePrince2000]

* TODO Summary
* TODO Thoughts
* TODO Notes
==========
﻿Prince, The - Niccolo Machiavelli, Harvey Mansfield
- Your Highlight on page 6-6 | Added on Tuesday, June 9, 2015 3:31:00 PM

The renown of The Prince is precisely to have been the first and the best book to argue that politics has and should have its own rules and should not accept rules of any kind or from any source where the object is not to win or prevail over others
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 3 | Location 46-47 | Added on Tuesday, June 9, 2015 3:39:42 PM

Grown-ups never understand anything by themselves, and it is tiresome for children to be always and forever explaining things to them.
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 4 | Location 51-55 | Added on Tuesday, June 9, 2015 3:40:37 PM

Whenever I met one of them who seemed to me at all clear-sighted, I tried the experiment of showing him my Drawing Number One, which I have always kept. I would try to find out, so, if this was a person of true understanding. But, whoever it was, he, or she, would always say: "That is a hat." Then I would never talk to that person about boa constrictors, or primeval forests, or stars. I would bring myself down to his level. I would talk to him about bridge, and golf, and politics, and neckties. And the grown-up would be greatly pleased to have met such a sensible man.
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 25 | Location 370-371 | Added on Tuesday, June 9, 2015 4:05:16 PM

For, to conceited men, all other men are admirers.
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 21 | Location 313-314 | Added on Tuesday, June 9, 2015 4:05:31 PM

He did not know how the world is simplified for kings. To them, all men are subjects.
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 35 | Location 531-532 | Added on Tuesday, June 9, 2015 4:19:48 PM

When one wishes to play the wit, he sometimes wanders a little from the truth.
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 34 | Location 517-518 | Added on Tuesday, June 9, 2015 4:20:19 PM

"What place would you advise me to visit now?" he asked. "The planet Earth," replied the geographer. "It has a good reputation."
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 36 | Location 549-550 | Added on Tuesday, June 9, 2015 4:21:34 PM

"Where are the men?" the little prince at last took up the conversation again. "It is a little lonely in the desert..." "It is also lonely among men," the snake said.
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 37 | Location 562-566 | Added on Tuesday, June 9, 2015 4:22:41 PM

"Good morning," said the little prince. "Good morning," said the flower. "Where are the men?" the little prince asked, politely. The flower had once seen a caravan passing. "Men?" she echoed. "I think there are six or seven of them in existence. I saw them, several years ago. But one never knows where to find them. The wind blows them away. They have no roots, and that makes their life very difficult." "Goodbye," said the little prince. "Goodbye," said the flower.
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 41 | Location 618-620 | Added on Tuesday, June 9, 2015 4:26:42 PM

"One only understands the things that one tames," said the fox. "Men have no more time to understand anything. They buy things all ready made at the shops. But there is no shop anywhere where one can buy friendship, and so men have no friends any more.
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 43 | Location 655-656 | Added on Tuesday, June 9, 2015 4:29:27 PM

"Goodbye," said the fox. "And now here is my secret, a very simple secret: It is only with the heart that one can see rightly; what is essential is invisible to the eye."
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 43 | Location 655-661 | Added on Tuesday, June 9, 2015 4:30:09 PM

"Goodbye," said the fox. "And now here is my secret, a very simple secret: It is only with the heart that one can see rightly; what is essential is invisible to the eye." "What is essential is invisible to the eye," the little prince repeated, so that he would be sure to remember. "It is the time you have wasted for your rose that makes your rose so important." "It is the time I have wasted for my rose --" said the little prince, so that he would be sure to remember. "Men have forgotten this truth," said the fox. "But you must not forget it. You become responsible, forever, for what you have tamed. You are responsible for your rose..." "I am responsible for my rose," the little prince repeated, so that he would be sure to remember.
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 44 | Location 668-670 | Added on Tuesday, June 9, 2015 4:30:44 PM

"Were they not satisfied where they were?" asked the little prince. "No one is ever satisfied where he is," said the switchman.
==========
﻿The Little Prince (Antoine de Saint-Exupery)
- Your Highlight on page 45 | Location 675-681 | Added on Tuesday, June 9, 2015 4:31:36 PM

"Good morning," said the little prince. "Good morning," said the merchant. This was a merchant who sold pills that had been invented to quench thirst. You need only swallow one pill a week, and you would feel no need of anything to drink. "Why are you selling those?" asked the little prince. "Because they save a tremendous amount of time," said the merchant. "Computations have been made by experts. With these pills, you save fifty-three minutes in every week." "And what do I do with those fifty-three minutes?" "Anything you like..." "As for me," said the little prince to himself, "if I had fifty-three minutes to spend as I liked, I should walk at my leisure toward a spring of fresh water."

* Bibliography
#+print_bibliography:
* TODO [#2] Flashcards :noexport:
