:PROPERTIES:
:ID:       fe2cc1fb-720e-4c0c-8ab3-87520a1bce39
:LAST_MODIFIED: [2023-10-27 Fri 09:12]
:END:
#+title: Be fast
#+hugo_custom_front_matter: :slug "fe2cc1fb-720e-4c0c-8ab3-87520a1bce39"
#+author: Cash Prokop-Weaver
#+date: [2023-10-26 Thu 20:01]
#+filetags: :concept:

Velocity, speed, pace --- they're important. They make your [[id:c8ed5ee6-7756-41d2-9134-8baf2c3abe8f][Feedback loops]] shorter when you're going in the wrong direction. They get you past the finish line sooner than the other person. They get you on to the next thing to you can experience more. Observe that I said "they're important" and not "they're the /only/ important thing". There's a place for [[id:ff009594-d69f-4d33-b0c2-65ed62eaf0b2][Festina lente]].

* Speed enables new workflows
:PROPERTIES:
:ID:       87558875-8743-437b-b543-afa6cafc264b
:END:

Let's say you're trying to improve two recipes: (1) a slow-cook lasagna which takes 6 hours from start to finish and (2) a vinaigrette dressing which takes around 30 seconds. You're going to err on the side of "think each change through before we try it" to the lasagna and "let's just try it!" for the vinaigrette. The time they take changes the way you interact with the "improve the recipe" task.

#+begin_quote
More generally, Fabian Giesen has noted that this kind of non-linear impact of velocity is common:

#+begin_quote2
There are "phase changes" as you cross certain thresholds (details depend on the problem to some extent) where your entire way of working changes. ... ​​There's a lot of things I could in theory do at any speed but in practice cannot, because as iteration time increases it first becomes so frustrating that I can't do it for long and eventually it takes so long that it literally drops out of my short-term memory, so I need to keep notes or otherwise organize it or I can't do it at all.

Certainly if I can do an experiment in an interactive UI by dragging on a slider and see the result in a fraction of a second, at that point it's very "no filter", if you want to try something you just do it.

Once you're at iteration times in the low seconds (say a compile-link cycle with a statically compiled lang) you don't just try stuff anymore, you also spend time thinking about whether it's gonna tell you anything because it takes long enough that you'd rather not waste a run.

Once you get into several-minute or multi-hour iteration times there's a lot of planning to not waste runs, and context switching because you do other stuff while you wait, and note-taking/bookkeeping; also at this level mistakes are both more expensive (because a wasted run wastes more time) and more common (because your attention is so divided).

As you scale that up even more you might now take significant resources for a noticeable amount of time and need to get that approved and budgeted, which takes its own meetings etc.
#+end_quote2

[cite:@luuReasonsWorkProductivityVelocity]
#+end_quote

* Flashcards :noexport:
* Bibliography
#+print_bibliography:
