:PROPERTIES:
:ID:       bcc5414e-4ad7-4a7d-ac84-75e08c02b017
:LAST_MODIFIED: [2022-12-14 Wed 13:17]
:END:
#+title: Be what they expect you to be
#+hugo_custom_front_matter: :slug "bcc5414e-4ad7-4a7d-ac84-75e08c02b017"
#+author: Cash Prokop-Weaver
#+date: [2022-11-10 Thu 17:02]
#+filetags: :has_todo:concept:
I'm not settled on the name.

To find the definition by encircling it:

- Change X to match your audience's expectations
  - Language
    - Drop key words/phrases in interviews. Your interviewer is looking for someone who can do the job well and they'll likely be listening for particular phrases and keywords which they expect to hear from someone who can do the job well.
    - Code-switching
    - Avoid filler words and sounds (e.g. "um")
  - Confidence
    - Fake it till you make it
  - Appearance
    - Clothing to match the occasion
  - Code interviews
    - They're looking to hire someone "good" but they're using "can answer this computer-science question" as a proxy. It's in your interest to be good at that proxy.

All of this is useful to reduce the friction between you and the other person. You aren't being your authentic self. However, that's not always the goal. I don't want to be my full authentic self with everybody I meet. Some interactions are transactional.

Related:

- [[id:4398317e-6aa1-4dd4-b2a5-6334256ca2cc][Play to win]]
* TODO [#2] Expand :noexport:
* TODO [#2] Flashcards
