:PROPERTIES:
:ID:       9948ab6c-23b4-4950-ba95-ee4a27fa2992
:LAST_MODIFIED: [2023-09-05 Tue 20:15]
:END:
#+title: Blind men and an elephant
#+hugo_custom_front_matter: :slug "9948ab6c-23b4-4950-ba95-ee4a27fa2992"
#+author: Cash Prokop-Weaver
#+date: [2022-12-16 Fri 18:43]
#+filetags: :concept:

#+begin_quote
The parable of the blind men and an elephant is a story of a group of blind men who have never come across an elephant before and who learn and imagine what the elephant is like by touching it. Each blind man feels a different part of the elephant's body, but only one part, such as the side or the tusk. They then describe the elephant based on their limited experience and their descriptions of the elephant are different from each other. In some versions, they come to suspect that the other person is dishonest and they come to blows. The moral of the parable is that humans have a tendency to claim absolute truth based on their limited, subjective experience as they ignore other people's limited, subjective experiences which may be equally true.

[...]

The earliest versions of the parable of blind men and elephant is found in Buddhist, Hindu and Jain texts, as they discuss the limits of perception and the importance of complete context. The parable has several Indian variations, but broadly goes as follows:[7][2]

#+begin_quote2
A group of blind men heard that a strange animal, called an elephant, had been brought to the town, but none of them were aware of its shape and form. Out of curiosity, they said: "We must inspect and know it by touch, of which we are capable". So, they sought it out, and when they found it they groped about it. The first person, whose hand landed on the trunk, said, "This being is like a thick snake". For another one whose hand reached its ear, it seemed like a kind of fan. As for another person, whose hand was upon its leg, said, the elephant is a pillar like a tree-trunk. The blind man who placed his hand upon its side said the elephant, "is a wall". Another who felt its tail, described it as a rope. The last felt its tusk, stating the elephant is that which is hard, smooth and like a spear.
#+end_quote2

In some versions, the blind men then discover their disagreements, suspect the others to be not telling the truth and come to blows. The stories also differ primarily in how the elephant's body parts are described, how violent the conflict becomes and how (or if) the conflict among the men and their perspectives is resolved. In some versions, they stop talking, start listening and collaborate to "see" the full elephant. In another, a sighted man enters the parable and describes the entire elephant from various perspectives, the blind men then learn that they were all partially correct and partially wrong. While one's subjective experience is true, it may not be the totality of truth.[4][7]

The parable has been used to illustrate a range of truths and fallacies; broadly, the parable implies that one's subjective experience can be true, but that such experience is inherently limited by its failure to account for other truths or a totality of truth. At various times the parable has provided insight into the relativism, opaqueness or inexpressible nature of truth, the behavior of experts in fields of contradicting theories, the need for deeper understanding, and respect for different perspectives on the same object of observation. In this respect, it provides an easily understood and practical example that illustrates ontologic reasoning. That is, simply put, what things exist, what is their true nature, and how can their relations to each other be accurately categorized? For example, is the elephant's trunk a snake, or its legs trees, just because they share some similarities with those? Or is that just a misapprehension that differs from an underlying reality? And how should human beings treat each other as they strive to understand better (anger, respect, tolerance or intolerance)?

[cite:@BlindMenElephant2022]
#+end_quote

Related: [[id:9b054cbc-f7f4-4443-b28a-65d66eef4880][Lowercase-a accurate without being capital-T True]]

* Flashcards
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-12-16 Fri 18:44]
:FC_CREATED: 2022-12-17T02:45:29Z
:FC_TYPE:  double
:ID:       19401921-e3da-4f93-a4f5-f1b7ac137f14
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.65 |   7 |   313.16 | 2024-05-04T20:18:39Z |
| back     | 2.80 |   7 |   383.15 | 2024-08-29T02:40:50Z |
:END:

[[id:9948ab6c-23b4-4950-ba95-ee4a27fa2992][Blind men and an elephant]]

*** Back
Humans tend to:

1. claim absolute truth based on limited, subjective, experience
1. ignore other people's limited, subjective, experiences which may be equally true
*** Source
[cite:@BlindMenElephant2022]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-12-16 Fri 18:45]
:FC_CREATED: 2022-12-17T02:47:41Z
:FC_TYPE:  normal
:ID:       092fad0f-6fa0-4b2e-bb52-70316bc06752
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.65 |   7 |   379.02 | 2024-08-23T01:14:21Z |
:END:

Tell the parable of the [[id:9948ab6c-23b4-4950-ba95-ee4a27fa2992][Blind men and an elephant]]

*** Back
A group of blind men who have never come across an elephant come across one. Each blind man feels a different part of the elephant's body, but only one part, such as the side or the tusk. They then describe the elephant based on their limited experience and their descriptions of the elephant are different from each other. In some versions, they come to suspect that the other person is dishonest and they come to blows.
*** Source
[cite:@BlindMenElephant2022]
#+print_bibliography: