:PROPERTIES:
:ID:       d1f735d6-a30b-494f-a536-7042b6fd0329
:LAST_MODIFIED: [2023-07-31 Mon 18:27]
:END:
#+title: Branch and bound
#+hugo_custom_front_matter: :slug "d1f735d6-a30b-494f-a536-7042b6fd0329"
#+author: Cash Prokop-Weaver
#+date: [2023-01-17 Tue 09:43]
#+filetags: :has_todo:concept:

#+begin_quote
Branch and bound (BB, B&B, or BnB) is an algorithm design paradigm for discrete and combinatorial optimization problems, as well as mathematical optimization. A branch-and-bound algorithm consists of a systematic enumeration of candidate solutions by means of state space search: the set of candidate solutions is thought of as forming a rooted tree with the full set at the root. The algorithm explores branches of this tree, which represent subsets of the solution set. Before enumerating the candidate solutions of a branch, the branch is checked against upper and lower estimated bounds on the optimal solution, and is discarded if it cannot produce a better solution than the best one found so far by the algorithm.

The algorithm depends on efficient estimation of the lower and upper bounds of regions/branches of the search space. If no bounds are available, the algorithm degenerates to an exhaustive search.

[cite:@BranchBound2023]
#+end_quote

* Flashcards
** Definition :fc:
:PROPERTIES:
:CREATED: [2023-01-17 Tue 09:44]
:FC_CREATED: 2023-01-17T17:47:41Z
:FC_TYPE:  double
:ID:       24d3bec9-ea9f-4a7e-819f-025d1212bc63
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.50 |   7 |   244.25 | 2024-03-01T07:37:02Z |
| back     | 2.80 |   6 |   134.80 | 2023-08-24T11:47:01Z |
:END:

[[id:d1f735d6-a30b-494f-a536-7042b6fd0329][Branch and bound]]

*** Back
An algorithm design paradigm which explores the [[id:1a068ad5-3e16-4ec4-b238-6fdc5904aeb4][Tree]] of solutions by excluding the paths with worse-than-current-best solutions.
*** Source
[cite:@BranchBound2023]
** Example(s) class of problem :fc:
:PROPERTIES:
:CREATED: [2023-01-17 Tue 09:47]
:FC_CREATED: 2023-01-17T17:49:53Z
:FC_TYPE:  double
:ID:       e43043e0-a978-402d-b54b-9ddbe4f2bdf6
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.65 |   6 |   123.47 | 2023-08-02T03:00:05Z |
| back     | 2.35 |   7 |   212.90 | 2024-02-29T23:02:44Z |
:END:

[[id:d1f735d6-a30b-494f-a536-7042b6fd0329][Branch and bound]]

*** Back
- [[id:668cbbcc-170b-42c8-b92b-75f6868a0138][Dijkstra's algorithm]], [[id:4d3cbeb6-ea82-4e4f-96bb-3e950ebc2087][A*]]
*** TODO [#2] Expand :noexport:
*** Source
[cite:@BranchBound2023]
#+print_bibliography: