:PROPERTIES:
:ID:       0bd96e38-6a09-4053-b5e8-cf707b03a3e5
:ROAM_REFS: [cite:@CacheComputing2023]
:LAST_MODIFIED: [2023-09-17 Sun 16:01]
:END:
#+title: Cache
#+hugo_custom_front_matter: :slug "0bd96e38-6a09-4053-b5e8-cf707b03a3e5"
#+author: Cash Prokop-Weaver
#+date: [2023-03-22 Wed 09:19]
#+filetags: :concept:

#+begin_quote
In computing, a cache is a hardware or software component that stores data so that future requests for that data can be served faster; the data stored in a cache might be the result of an earlier computation or a copy of data stored elsewhere. A cache hit occurs when the requested data can be found in a cache, while a cache miss occurs when it cannot. Cache hits are served by reading data from the cache, which is faster than recomputing a result or reading from a slower data store; thus, the more requests that can be served from the cache, the faster the system performs.

[cite:@CacheComputing2023]
#+end_quote
* Flashcards :noexport:
** Definition :fc:
:PROPERTIES:
:CREATED: [2023-03-22 Wed 09:20]
:FC_CREATED: 2023-03-22T16:21:06Z
:FC_TYPE:  double
:ID:       a031cfd1-0cdb-412d-8954-62371efa26bb
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.50 |   7 |   232.15 | 2024-05-07T02:33:49Z |
| back     | 2.50 |   7 |   224.32 | 2024-04-16T01:40:05Z |
:END:

[[id:0bd96e38-6a09-4053-b5e8-cf707b03a3e5][Cache]]

*** Back
A hardware or software component which stores data for use in responding to future requests.
*** Source
[cite:@CacheComputing2023]
* Bibliography
#+print_bibliography:
