:PROPERTIES:
:ROAM_REFS: [cite:@chinHardThingLearningExperience2021]
:ID:       6e21d350-e098-4a80-a6bf-ccc86c254f28
:LAST_MODIFIED: [2023-09-22 Fri 07:20]
:END:
#+title: Cedric Chin | The Hard Thing About Learning From Experience
#+hugo_custom_front_matter: :slug "6e21d350-e098-4a80-a6bf-ccc86c254f28"
#+author: Cash Weaver
#+date: [2023-09-11 Mon 08:42]
#+filetags: :hastodo:reference:

[[id:4c9b1bbf-2a4b-43fa-a266-b559c018d80e][Cedric Chin]], [cite:@chinHardThingLearningExperience2021]

* TODO Summary
* TODO Thoughts
* INPROGRESS Notes
#+begin_quote
Finally, we follow this line of reasoning to its logical conclusion:

You realise that you have to keep reinterpreting memories the older and wiser and more skilled you get, so you eventually learn not to hold on to any current 'lessons learnt' too tightly, but instead to treat them as contingently true things.

After all, "I was wrong about that in the past; I might be wrong about this in the future."

(I actually go beyond this and actively wait to conclude lessons from non-fiction books, or from personal experiences. "Here is a thing that's happened," I tell myself, "Let's wait and see what it all means.")

The hard thing about learning from experience is that you never know what to learn from a recently concluded event; you don't yet have the models necessary for proper interpretation.

In other words, the hard thing about learning from experience is that you don't know how to make sense of your experience.
#+end_quote

** Cognitive transformation theory

#+begin_quote
Everything I've just said is a restatement of Gary Klein and Holly Baxter's Cognitive Transformation Theory [[[id:2023ecf7-2e79-4919-a356-264eecb3034b][Cognitive transformation theory]]].
#+end_quote
* TODO [#2] Flashcards :noexport:
