:PROPERTIES:
:ROAM_REFS: [cite:@chinWhyTacitKnowledgeMoreImportantDeliberatePractice2020]
:ID:       bcba3e46-9cde-4555-accb-ec73e4f0fc4c
:LAST_MODIFIED: [2023-10-09 Mon 23:51]
:END:
#+title: Cedric Chin | Why Tacit Knowledge Is More Important Than Deliberate Practice
#+hugo_custom_front_matter: :slug "bcba3e46-9cde-4555-accb-ec73e4f0fc4c"
#+author: Cash Weaver
#+date: [2023-06-30 Fri 18:54]
#+filetags: :hastodo:reference:

[[id:4c9b1bbf-2a4b-43fa-a266-b559c018d80e][Cedric Chin]], [cite:@chinWhyTacitKnowledgeMoreImportantDeliberatePractice2020]

* Summary
An essay on [[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Tacit knowledge]] and [[id:a1d74568-61f0-4a01-8aab-184d1b7a9752][Deliberate practice]]

- Tacit knowledge is more useful than deliberate practice when the subject you're trying to learn isn't "well defined". "... deliberate practice is defined as possible /only/ in domains with a long history of well-established pedagogy. In other words, deliberate practice *can only exist in fields like music and math and chess*."
- Tacit knowledge in action looks like a long list of caveats

   #+begin_quote
   This is actually generalisable. People with expertise in any sufficiently complicated domain will always explain their expertise with things like: "Well, do X. Except when you see Y, then do Z, because A. And if you see B, then do P. But if you see A and C but not B, then do Q, because reason D. And then there are weird situations where you do Z but then see thing C emerge, then you should switch to Q."

   [...]

   [...] I realised that if you ever hear someone explaining things in terms of a long list of caveats, the odds are good that you're looking at tacit knowledge in action.
   #+end_quote

- [[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Tacit knowledge]] is more valuable than [[id:a1d74568-61f0-4a01-8aab-184d1b7a9752][Deliberate practice]] because it doesn't have the same requirements of a "long history of well-established pedagogy. [...] like music and math and chess".
* Thoughts
* Notes
** What is tacit knowledge?
See [[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Tacit knowledge]].
#+begin_quote
Think about riding a bicycle. Riding a bicycle is impossible to teach through descriptions. Sure, you can try to explain what it is you're doing when you're cycling, but this isn't going to be of much help when you're teaching a kid and they fall into the drain while you're telling them to "BALANCE! JUST IMAGINE YOU ARE ON A TIGHTROPE AND BALANCE!".

Undoubtedly there will be people who say that if you just explain better, if you could find the right words to talk to your students, you can teach them to ride bikes. If you happen to believe this … well, I urge you to test this theory yourself. Go find a couple of kids (or adults!) who haven't yet learned to ride a bike and see if you can teach them --- through the power of your explanations alone! --- how to cycle without scraping their shins. And if you are successful, be critical with yourself: how much of your success is due to the bike rider figuring it out on their own? And how much of it is due to your verbal instructions?

This explanation bit deserves some attention. In pedagogy, this is known as '[[https://andymatuschak.org/books/][transmissionism]]', and it is regarded amongst serious educators with the same sort of derision you and I might have about flat-earth theories today. It goes something like this: some people believe that it is possible to teach technique by explaining things to others. They think that if you can find just the right combinations of words with the right sorts of analogies; if you can really break things down into the right level of atomic details, things will magically click in their students's heads and they will succeed. [...]

How do you teach tacit knowledge? How do you teach bike riding, for that matter?

When I was a kid, I taught myself how to ride a bike … by accident. And then I taught my sisters and then my cousin and then another kid in the neighbourhood who was interested but a little scared. They were zooming around in about an hour each. The steps were as follows:

1. Pick a small bike, much smaller than the body of your learner, and therefore not far off the ground. This is useful for the learner because they will be able to put their feet down and save themselves at any moment. It's also less scary to be not far off the ground.
2. Have them push with their legs and go forward a short distance, again with their feet only inches off the ground. Do this repeatedly, by pushing off, putting both feet down, then stopping and repeating.
3. Make the pushes harder and the distances longer. Eventually, they will spend tens of seconds gliding with their feet held up. The goal here is have them learn how it feels like to balance on a bike.
4. On one of those glides, once they feel ready (and likely a little bored --- the point is to get them to do step 3 so many times that they're feeling secure and eager to move on) --- well, once you reach that point, tell them to start peddling.
5. Voilà. You have a bicycling kid.

Notice how little verbal instruction is involved. What is more important is emulation, and action --- that is, a focus on the embodied feelings necessary to ride a bicycle successfully. And this exercise was quite magical for me, for within the span of an hour I could watch a kid go from conscious incompetence to conscious competence and finally to unconscious competence.

In other words, tacit knowledge instruction happens through things like imitation, emulation, and apprenticeship. You learn by copying what the master does, blindly, until you internalise the principles behind the actions.
#+end_quote
** Tacit knowledge in knowledge work

#+begin_quote
In my previous job, my technical lead, Hieu, had an uncanny ability to sit in on requirements meetings and, within minutes, sketch out a program structure that would be the simplest possible solution with the fewest moving parts. That sketch was often the one we ended up implementing, and yet I noticed that Hieu always left enough wiggle room for the inevitable changes that came with any software project. (To be clear, he usually implemented a throwaway prototype to confirm the sketch, before passing on the design). When I designed implementations, something always had to be redesigned later. I simply wasn't as good. Eventually, I asked him how he did this, and tried multiple times to get it out of him over the years we worked together. Our conversations would inevitably go something like the following:

"Well" Hieu would begin, "When you hear there is an external API, you should focus your program around that because there is a lot of risk there."

"Yeah but then why didn't you worry about the calendar API?"

"Oh, because I've worked with it before and I think it is easy to implement."

"Why focus so much on Firebase?"

"Because we want to use it as a database layer. Quite risky ah."

"So always focus on a core layer first, because more important?"

"Yes. Try to focus on the most dangerous bits first."

"But how come you didn't worry about the inventory API? We've never integrated with that before."

"Ya that one not that important now I think. The client might change it later. Or maybe our feature is going to change. We do the basics first."

I thought back to my Viki days, when I was a software engineering intern and was writing software tests for the first time. A senior software engineer took a few seconds to look at about a hundred lines of code I'd written, and said "Oh, that's not good, this would be a problem later. Structure it this way."

I asked him how he knew, within five seconds, that it was bad. He gave me a long explanation about software engineering principles. I waved him away and asked how he did it in five seconds. He said "Well, it just felt right. Ok, let's go to lunch, you can fix it afterwards."

I've written about this Viki episode in my post about perceptual learning. I don't mean to say that Hieu or the senior software engineer couldn't explain their judgment, or that they couldn't make explicit the principles they used to evaluate the tradeoffs between a dozen or so variables: they could, even if terribly. My point is that their explanations would not lead me to the same ability that they had.

Why is this the case? Well, take a look at the conversation again. When I pushed these people on their judgments, they would try to explain in terms of principles or heuristics. But the more I pushed, the more exceptions and caveats and potential gotchas I unearthed.

This is actually generalisable. People with expertise in any sufficiently complicated domain will always explain their expertise with things like: "Well, do X. Except when you see Y, then do Z, because A. And if you see B, then do P. But if you see A and C but not B, then do Q, because reason D. And then there are weird situations where you do Z but then see thing C emerge, then you should switch to Q."

And if you push further, eventually they might say "Ahh, it just feels right. Do it long enough and it'll feel right to you too."

Eventually I realised that the way to learn Hieu's techniques was to copy him: to design some software and then ask for his feedback. And I realised that if you ever hear someone explaining things in terms of a long list of caveats, the odds are good that you're looking at tacit knowledge in action.

This phenomenon is actually well established in the study of expertise. It has also been written about, many times, by practitioners in other fields. As an example, here's surgeon Atul Gawande on appendicitis surgery:

#+begin_quote2
Say you've got a patient who needs surgery for appendicitis. These days, surgeons will typically do a laparoscopic appendectomy. You slide a small camera—a laparoscope—into the abdomen through a quarter-inch incision near the belly button, insert a long grasper through an incision beneath the waistline, and push a device for stapling and cutting through an incision in the left lower abdomen. Use the grasper to pick up the finger-size appendix, fire the stapler across its base and across the vessels feeding it, drop the severed organ into a plastic bag, and pull it out. Close up, and you're done. That's how you like it to go, anyway. But often it doesn't.

Even before you start, you need to make some judgments. Unusual anatomy, severe obesity, or internal scars from previous abdominal surgery could make it difficult to get the camera in safely; you don't want to poke it into a loop of intestine. You have to decide which camera-insertion method to use—there's a range of options—or whether to abandon the high-tech approach and do the operation the traditional way, with a wide-open incision that lets you see everything directly. If you do get your camera and instruments inside, you may have trouble grasping the appendix. Infection turns it into a fat, bloody, inflamed worm that sticks to everything around it—bowel, blood vessels, an ovary, the pelvic sidewall—and to free it you have to choose from a variety of tools and techniques. You can use a long cotton-tipped instrument to try to push the surrounding attachments away. You can use electrocautery, a hook, a pair of scissors, a sharp-tip dissector, a blunt-tip dissector, a right-angle dissector, or a suction device. You can adjust the operating table so that the patient's head is down and his feet are up, allowing gravity to pull the viscera in the right direction. Or you can just grab whatever part of the appendix is visible and pull really hard.

Once you have the little organ in view, you may find that appendicitis was the wrong diagnosis. It might be a tumor of the appendix, Crohn's disease, or an ovarian condition that happened to have inflamed the nearby appendix. Then you'd have to decide whether you need additional equipment or personnel—maybe it's time to enlist another surgeon.

Over time, you learn how to head off problems, and, when you can't, you arrive at solutions with less fumbling and more assurance. After eight years, I've performed more than two thousand operations. Three-quarters have involved my specialty, endocrine surgery—surgery for endocrine organs such as the thyroid, the parathyroid, and the adrenal glands. The rest have involved everything from simple biopsies to colon cancer. For my specialized cases, I've come to know most of the serious difficulties that could arise, and have worked out solutions. For the others, I've gained confidence in my ability to handle a wide range of situations, and to improvise when necessary.
#+end_quote2

Notice how Gawande includes all sorts of caveats in his explanation of his expertise. This is probably tacit knowledge in action. Learning this type of complicated judgment — this instantaneous solution selection that happens to balance dozens of considerations against each other — this is what is valuable to learn. And it is almost impossible to learn it through explanation alone.
#+end_quote
** Can tacit knowledge be made explicit?

#+begin_quote
It is worth it to re-examine that last sentence, above. /Could it --- in principle --- be possible to externalise tacit knowledge into a list of instructions?/ [...]

The consensus answer to that question seems to be: "Yes, in principle it is possible to do so. In practice it is very difficult." My take on this is that it is /so/ difficult that we shouldn't even bother; assuming that you are reading this because you want to get good in your career, you should give up on turning tacit knowledge into explicit knowledge and just go after tacit knowledge itself.

Why do we know this?

In the 1970s, a bunch of organisations --- amongst them the US military --- commissioned a number of studies to look into the possibility of building out all sorts of expert systems to augment or replace human agents. [...]

What many researchers found in the wake of that fad was that it is extremely difficult to encode /all/ the possible branches and gotchas and nuances from a human expert into an expert system.

[...]

(Wikipedia calls this problem the '[[https://en.wikipedia.org/wiki/Expert_system#Disadvantages][knowledge acquisition problem]]', which is a nice way of putting it; it was what ultimately caused expert systems to decline in popularity). As people rapidly discovered, it wasn't so easy to get the 'rules' out of experts's heads in the first place.

But there are other objections, of course. Klein --- now considered one of the pioneers of the Naturalistic Decision Making (NDM) [[[id:6eb374ad-69aa-476d-b1d8-02714ffc094f][Naturalistic decision making]]] branch of psychology --- likes to say that over-reliance on procedures makes human operators fragile (Chapter 15, /[[https://www.goodreads.com/book/show/65229.Sources_of_Power][Source of Power]]/). In other words, giving people a list of procedures to execute, blindly [or via [[id:5a824b91-5b0e-4e8e-9946-c7bd0d17d202][Learned blankness]]], denies them the ability to build expertise, which in turns prevents them from doing the sorts of creative problem solving that is common amongst expert operators. It also means that when something goes drastically wrong --- and something /always/ goes drastically wrong in the real world --- they would not be able to adapt.
#+end_quote
** Learning tacit knowledge

#+begin_quote
"But wait," I hear you say --- "What about the field of deliberate practice? Isn't /that/ the predominant subfield most concerned with the development of expertise?" And the answer to that is /no/, it is not.

In my review of Ericssons' [[https://commoncog.com/peak-book-summary/][/Peak/]] [ TODO: Add citation for peak. ], and in my summary of [[https://commoncog.com/the-problems-with-deliberate-practice/][The Problems with Deliberate Practice]] [ [cite:@chinBookSummaryPeakNewScienceExpertise2019] ], I explained that deliberate practice is defined as possible /only/ in domains with a long history of well-established pedagogy. In other words, deliberate practice *can only exist in fields like music and math and chess*.

K. Anders Ericsson lays out this narrow definition in /Peak/, and then does a cop-out, arguing that while he hasn't studied practice outside of such domains, the ideas from deliberate practice may be applied to pedagogically less established fields. But Ericsson is well aware that NDM methods exist --- he was one of the editors, alongside many names from the NDM community --- who worked on the /[[https://www.cambridge.org/my/academic/subjects/psychology/cognition/cambridge-handbook-expertise-and-expert-performance-2nd-edition?format=HB&isbn=9781316502617][Cambridge Handbook for Expertise and Expert Performance]]/.

And so if you are a programmer, or designer, or businessperson, an investor or a writer reading about deliberate practice, you may be asking: "Well, what about /my/ field? What if there are no established pedagogical techniques for me?" And if you have started to ask this question, then you have begun travelling a more interesting path; this is really the right question to ask.

The answer, of course, is that the field of NDM is a lot more useful if you find yourself in one of these fields. The process of learning tacit knowledge looks something like the following: you find a master, you work under them for a few years, and you learn the ropes through emulation, feedback, and osmosis --- /not/ through deliberate practice. (Think: Warren Buffett and the years he spent under Benjamin Graham, for instance). The field of NDM is focused on ways to make this practice more effective. And I think much of the world pays too much attention to deliberate practice and to cognitive bias research, and not enough to tacit knowledge acquisition.

If tacit knowledge exists --- and I believe it does --- then the most useful tools about skill acquisition will come out of the fields that study it. Late last year, the NDM community got together and published /[[https://www.oxfordhandbooks.com/view/10.1093/oxfordhb/9780198795872.001.0001/oxfordhb-9780198795872][The Oxford Handbook of Expertise]]./ It is the single most comprehensive overview of the field that we know today.
#+end_quote
*** TODO [#2] Add citation for peak
*** TODO [#2] Cite Cambridge handbook for expertise and expert performance
*** TODO [#2] Cite oxford handbook of expertise

* Flashcards :noexport:
** Cloze :fc:
:PROPERTIES:
:CREATED: [2023-06-30 Fri 19:09]
:FC_CREATED: 2023-07-01T02:15:32Z
:FC_TYPE:  cloze
:ID:       174eb025-d954-445d-be90-6e42faca1ea3
:FC_CLOZE_MAX: 1
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.20 |   6 |    68.42 | 2023-11-03T23:44:05Z |
|        1 | 2.35 |   6 |    61.91 | 2023-11-02T12:16:05Z |
:END:

{{[[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Tacit knowledge]]}@0} looks like {{an explanation with a list of caveats}@1}.

*** Source
[cite:@chinWhyTacitKnowledgeMoreImportantDeliberatePractice2020]
** Compare and contrast ([[id:4c9b1bbf-2a4b-43fa-a266-b559c018d80e][Cedric Chin]]) :fc:
:PROPERTIES:
:CREATED: [2023-06-30 Fri 19:31]
:FC_CREATED: 2023-07-01T02:32:59Z
:FC_TYPE:  normal
:ID:       2440a43e-02de-49cb-9232-75e0ee230818
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.20 |   5 |    30.48 | 2023-11-09T18:21:07Z |
:END:

[[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Tacit knowledge]] and [[id:a1d74568-61f0-4a01-8aab-184d1b7a9752][Deliberate practice]]

*** Back
- [[id:a1d74568-61f0-4a01-8aab-184d1b7a9752][Deliberate practice]] is only possible in domains with long pedagogical histories (e.g. math or music)
- [[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Tacit knowledge]] exists in /all/ domains, is difficult to scale, but is more useful
*** Source
[cite:@chinWhyTacitKnowledgeMoreImportantDeliberatePractice2020]
#+print_bibliography: