:PROPERTIES:
:ROAM_REFS: [cite:@chinThreeKindsTacitKnowledge2020]
:ID:       6e417a2d-0c14-4057-b022-c89d787e7fd3
:LAST_MODIFIED: [2023-09-05 Tue 20:18]
:END:
#+title: Cedric Chin | The Three Kinds of Tacit Knowledge
#+hugo_custom_front_matter: :slug "6e417a2d-0c14-4057-b022-c89d787e7fd3"
#+author: Cash Weaver
#+date: [2023-08-04 Fri 21:58]
#+filetags: :has_todo:reference:

[[id:4c9b1bbf-2a4b-43fa-a266-b559c018d80e][Cedric Chin]], [cite:@chinThreeKindsTacitKnowledge2020]

* TODO Summary
* TODO Thoughts
* INPROGRESS Notes
1. [[id:146ab42b-21a9-4d5a-85fe-2eba12347ca5][Relational tacit knowledge]]
2. [[id:42fb5f3a-ce78-4d22-86e6-0ee2bcad8908][Somatic tacit knowledge]]
3. [[id:c826a9e6-fcf5-4b94-81cb-0495f6aaa866][Collective tacit knowledge]]

#+begin_quote
Collins makes two more observations that I thought were pretty interesting.

1. In principle, relational tacit knowledge is explicable, even if challenging; somatic tacit knowledge less so, and collective tacit knowledge 'impossible'. But:
2. When it comes to human behaviour, the ease with which we pick up the three forms of tacit knowledge is reversed! It is easiest for us to pick up collective tacit knowledge — we begin socialisation from birth; we don't even notice when we absorb social context from our surroundings. In comparison, it is slightly harder to pick up somatic tacit knowledge, and it is most difficult to pick up relational tacit knowledge, since this hangs on the nature of expertise, and it the depends on the ways with which we relate to each other.
#+end_quote

* TODO [#2] Flashcards
#+print_bibliography: