:PROPERTIES:
:ROAM_REFS: [cite:@chinPersonalEpistemologyPractice2019]
:ID:       0a379fad-61c8-4e9a-96ea-62ecae152892
:LAST_MODIFIED: [2023-11-03 Fri 08:24]
:END:
#+title: Cedric Chin | A Personal Epistemology of Practice
#+hugo_custom_front_matter: :slug "0a379fad-61c8-4e9a-96ea-62ecae152892"
#+author: Cash Weaver
#+date: [2023-07-30 Sun 08:15]
#+filetags: :reference:

[[id:4c9b1bbf-2a4b-43fa-a266-b559c018d80e][Cedric Chin]], [cite:@chinPersonalEpistemologyPractice2019]

* Summary
* Thoughts
* Notes
#+begin_quote
So how do you evaluate the advice you're given? How do you know who to take seriously, and who to discount?

I'd like to propose an alternative hierarchy of evidence for practitioners. When asking for advice, judge the advice according to the following pyramid:

[in order from best to worst]
#+end_quote

1. Tested against reality

   #+begin_quote
   [...] "let reality be the teacher!" You only truly know that a piece of advice works if you have tested it [...]
   #+end_quote

2. Believable and exposed to negative outcomes

   #+begin_quote
   [...] experts who are exposed to downside risk are more prudent in their judgments and decisions compared to experts who aren't.
   #+end_quote

3. Believable

   #+begin_quote
   Believability is a technique that I've already covered in a previous part in this series: originally proposed by hedge fund manager Ray Dalio in his book Principles [[[id:c605b581-d3f9-4eed-a296-f7d72b580db3][Ray Dalio | Principles]]], believability is a method for evaluating expertise.

   The idea goes as follows — when asking people for advice, apply a suitable weight to their recommendations:

   1. The person must have had at least three successes. This reduces the probability that they are a fluke.
   2. They must have a credible explanation for their approach when probed. This increases the probability that you'll get useful information out of them.

   If an expert passes these two requirements, you may consider them 'believable'.
   #+end_quote

4. Put to practice in own life

   #+begin_quote
   This isn't as good as "believable expert who has succeeded in domain", but it's still better than "random shmuck who writes about self-help that he hasn't tried".
   #+end_quote

5. Plausible argument

   #+begin_quote
   This is the lowest-level form of evidence, because — as I've argued before — the persuasiveness of an argument should not affect your judgment of the argument's actual truth.
   #+end_quote

* Flashcards :noexport:
* Bibliography
#+print_bibliography:
