:PROPERTIES:
:ID:       f69f4ded-8216-45c1-aa9d-e883fcfc2b36
:ROAM_REFS: [cite:@PerfectionismSelfHelpResourcesInformationSheetsWorkbooks]
:LAST_MODIFIED: [2023-12-19 Tue 16:09]
:END:
#+title: Centre for Clinical Interventions: Perfectionism in Perspective
#+hugo_custom_front_matter: :slug "f69f4ded-8216-45c1-aa9d-e883fcfc2b36"
#+author: Cash Prokop-Weaver
#+date: [2023-12-19 Tue 15:56]
#+filetags: :hastodo:reference:

Centre for Clinical Interventions, [cite:@PerfectionismSelfHelpResourcesInformationSheetsWorkbooks]

* Summary
* Thoughts
* Notes
** Module 1: What is Perfectionism? :ATTACH:
*** What's good about being a perfectionist?
#+begin_quote
Researchers in the field may not be able to agree on the perfect definition, but we will be using the following definition of perfectionism, which has three key parts:

1. *The relentless striving for extremely high standards* (for yourself and/or others) that are personally demanding, in the context of the individual. (Typically, to an outsider the standards are considered to be unreasonable given the circumstances.) We will be referring to this throughout this Information Pack as 'unrelenting standards'.
2. *Judging your self-worth based largely on your ability to strive for and achieve such unrelenting standards*
3. *Experiencing negative consequences of setting such demanding standards, yet continuing to go for them despite the huge cost to you*.

   We would agree that it is generally a good idea to have high standards. Having goals helps you achieve things in life. BUT when these goals are either unachievable or only achievable at great cost, it makes it very difficult to feel good about yourself. This is when perfectionism can be problematic.
#+end_quote
*** What's so bad about being a perfectionist?
#+begin_quote
Sometimes the drive to do well can actually impair performance. What a strange idea - that having high standards and working very hard to maintain these standards can actually make things worse… This is the paradox of perfectionism!

Now, let's make sure we are clear. Without any standards people generally achieve less, so having standards is not a bad thing. But remember:

There is a big difference between the healthy and helpful pursuit of excellence and the unhealthy and unhelpful striving for perfection.
#+end_quote
* Bibliography
#+print_bibliography:
* TODO [#2] Flashcards :noexport:
