:PROPERTIES:
:ID:       a500c749-aab9-4150-876f-6f40c76bba35
:DIR:      /home/cashweaver/proj/roam/attachments/a500c749-aab9-4150-876f-6f40c76bba35
:LAST_MODIFIED: [2023-09-05 Tue 20:20]
:END:
#+title: Ceramics exercises
#+hugo_custom_front_matter: :slug "a500c749-aab9-4150-876f-6f40c76bba35"
#+author: Cash Prokop-Weaver
#+date: [2022-01-10 Mon 19:13]

#+begin_quote
If you're looking to improve quickly, the most important thing is to throw as much as possible. Prepare as many balls of clay as you think you can throw in one sitting, wrap them up in plastic, get on the wheel and throw. Like everyone else says, cylinders are a good place to start.

[cite:@sinkingjunkIfYouReLooking2016]
#+end_quote

Also see [[id:3f493f0a-aac1-43b6-be22-9711b921f6d8][Clary Illian | A Potter's Workbook]] and [[id:eefb478b-2083-4445-884d-755005a26f2f][Ceramics]].

* Improve technique and consistency

Generally speaking, the best advice is to create [[id:ce1622e0-9f93-47fd-a5b2-5acd981caabf][At least two of the same]] thing and then compare them. I recommend slicing the form in half, vertically, to judge things like wall or bottom thickness and consistency.

** Example: Walls

1. Wedge six balls of the same weight and place in a [[id:7f52f95f-c2f1-450f-b729-5738e4664c44][Damp box]]
2. Throw a ball into a cylinder and set aside; repeat for all the balls
3. Cut the cylinders top-to-bottom down the middle using a wire
4. Critique the walls:
   - Are they too thick? Too thin?
   - Are they the same thickness from top to bottom?
   - How similar are the six cylinders? Do some look different than the others? In what ways?
5. If you notice anything you want to work on, go to step 1 and focus on that aspect of the cylinders when you throw them again.

** Example: Pulls

Choose one or more of the following:

- Limit yourself to three pulls
- "Pull as high as you can" [cite:@sinkingjunkIfYouReLooking2016]
- "Pulling large amounts of clay (getting >50% of your height on your first pull)" [cite:@sinkingjunkIfYouReLooking2016]
- "Try to make 6 inch cylinders from one pound of clay. Realistically you're not going to do it (it's not easy, Idk if I could do it consistently) But it gives you a goal. You want even pulls and consistent thickness the whole way through." [cite:@youre_being_creepyTryMakeInch2016]

** Example: Intention

#+begin_quote
Another thing is to first draw a silhouette, whatever type of piece and shape you want, and try to make that shape. That will get you in the mode of visualizing before working, and also hones your skills in general so you can make the shapes you want.

[cite:@i_want_that_boatDefinitelyAgreeWit2016]
#+end_quote


[[https://www.reddit.com/r/Pottery/comments/47wf90/comment/d0g0qxj/?utm_source=share&utm_medium=web2x&context=3][... first draw a silhouette, whatever type of piece and shape you want, and try to make that shape. That will get you in the mode of visualizing before working, and also hones your skills in general so you can make the shapes you want.]]

* Creativity and experimentation

[[id:3619f0c9-baa8-44da-8667-c13b7dc3e3bd][Creativity is a product of volume]].

- Throw repeatedly for creativity: Throw 10/25/50/100/... different variations on the same form (eg: a vase). This exercise is about [[id:3619f0c9-baa8-44da-8667-c13b7dc3e3bd][pushing yourself to be creative]] and explore the form you're throwing.

* Flashcards :noexport:
