:PROPERTIES:
:ID:       75056a2e-6b7a-4764-b93c-d08aa3a99a42
:LAST_MODIFIED: [2023-11-03 Fri 16:10]
:END:
#+title: Children burn out fast
#+hugo_custom_front_matter: :slug "75056a2e-6b7a-4764-b93c-d08aa3a99a42"
#+author: Cash Prokop-Weaver
#+date: [2023-11-03 Fri 16:02]
#+filetags: :concept:

#+begin_quote
As any parent knows, toddlers are bundles of energy. Now, the first comprehensive study of energy use over the human life span has quantified their burn rate: Infants between the ages of 9 and 15 months expend a stunning 50% more energy in 1 day than adults do, adjusted for body size. These wee dynamos consume and use up energy even faster than pregnant women and teenage boys, most likely to fuel their energetically expensive brains and organs.

But children also burn out fast. Their high metabolisms make them particularly vulnerable to stunted growth and disease if they don't get the calories they need. Their cells may also metabolize drugs faster than those of adults, which means they may need more frequent doses. On the flip side, adults older than 60 begin to use less energy daily than younger people, and they may require less food or lower doses of medications, especially after age 90 when they use 26% less energy than middle-age people.

[...]

Children's metabolic rates stay high until age 5, but the rate slowly begins to glide down until it plateaus around age 20. Interestingly, adult rates are stable until age 60, when they begin to decline.

[cite:@LittleKidsBurnMuchEnergyTheyReDifferentSpeciesStudy]
#+end_quote

#+begin_quote
This is well known in emergency medicine. Not only do kids burn out quick, they also burn out completely because they, unlike adults, don't keep a reserve. This applies to homeostasis, too.

Consequently: young trauma victims that "look OK" need to be very closely attended to, because what you might be seeing is a kid burning the very last of their energy reserves just to maintain homeostasis, and they will NOT degrade gracefully once they're out of energy -- they'll just go right into the deep end of shock. Happy and talking to unconscious in 90 seconds is nothing you want to see.

[cite:@hprotagonistChildrenAlsoBurnOutFastThisWellKnownEmergencyMedicine]
#+end_quote
* Bibliography
#+print_bibliography:
* Flashcards :noexport:
