:PROPERTIES:
:ID:       e4034c34-f894-48fb-b303-41d0596589c9
:ROAM_REFS: [cite:@ChildDevelopmentStages2022]
:LAST_MODIFIED: [2023-09-05 Tue 20:14]
:END:
#+title: Child development stages
#+hugo_custom_front_matter: :slug "e4034c34-f894-48fb-b303-41d0596589c9"
#+author: Cash Prokop-Weaver
#+date: [2023-01-12 Thu 07:53]
#+filetags: :concept:

* TODO [#2] Expand and organize
- [[id:10453cfb-8266-404d-93e6-768747d30b74][Theory of mind]]

#+begin_quote
According to Jean Piaget's Theory of Cognitive Development, magical thinking [[[id:0141c9e2-e1b7-4b2f-8655-f977a9f41569][Magical thinking]]] is most prominent in children between ages 2 and 7. Due to examinations of grieving children, it is said that during this age, children strongly believe that their personal thoughts have a direct effect on the rest of the world. It is posited that their minds will create a reason to feel responsible if they experience something tragic that they do not understand, e.g. a death. Jean Piaget, a developmental psychologist, came up with a theory of four developmental stages. Children between ages 2 and 7 would be classified under his preoperational stage of development. During this stage children are still developing their use of logical thinking. A child's thinking is dominated by perceptions of physical features, meaning that if the child is told that a family pet has "gone away" when it has in fact died, then the child will have difficulty comprehending the transformation of the dog not being around anymore [see [[id:99e14785-13bb-420c-b0b5-b14bad1bd163][Freddish]] for a way of communicating with children which seeks to avoid such misunderstandings]. Magical thinking would be evident here, since the child may believe that the family pet being gone is just temporary. Their young minds in this stage do not understand the finality of death and magical thinking may bridge the gap.

[cite:@MagicalThinking2022]
#+end_quote


* TODO [#2] Flashcards :noexport:

