:PROPERTIES:
:ROAM_REFS: [cite:@tiezeCollectorFallacy0100]
:ID:       b23ffea4-e780-4d89-84ad-c0bd4f25816f
:LAST_MODIFIED: [2023-09-05 Tue 20:14]
:END:
#+title: Christian Tieze | The Collector's Fallacy
#+hugo_custom_front_matter: :slug "b23ffea4-e780-4d89-84ad-c0bd4f25816f"
#+author: Cash Weaver
#+date: [2023-08-04 Fri 17:35]
#+filetags: :reference:

[[id:278c9bc6-8e3b-4a61-8d89-b65e24ae6f84][Christian Tieze]], [cite:@tiezeCollectorFallacy0100]

* Summary
* Thoughts
* Notes
#+begin_quote
There's a tendency [[https://zettelkasten.de/posts/collectors-fallacy-confession/][in all of us]] to gather useful stuff and feel good about it. To collect is a reward in itself. As knowledge workers, we're inclined to look for the next groundbreaking thought, for intellectual stimulation: we pile up promising books and articles, and we store half the internet as bookmarks, just so we get the feeling of being on the cutting edge.

Let's call this "The Collector's Fallacy". Why fallacy? Because 'to know about something' isn't the same as 'knowing something'. Just /knowing about/ a thing is less than superficial since knowing about is merely to be certain of its existence, nothing more. Ultimately, this fake-knowledge is hindering us on our road to true excellence. Until we merge the /contents,/ the information, ideas, and thoughts of other people into our own knowledge, we haven't really learned a thing. We don't change ourselves if we don't learn, so merely filing things away doesn't lead us anywhere.
#+end_quote
** Collectors don't make progress

#+begin_quote
Preparing reading material alone doesn't get you anywhere. It's quite common that students prepare lots and lots of photocopies of the texts they have to read --- and stop just there. The copies grow to be an alibi, says Umberto Eco in his book [[https://www.amazon.com/How-Write-Thesis-MIT-Press/dp/0262527138/ref=as_li_ss_tl?ie=UTF8&linkCode=ll1&tag=ctzettelkasten-20&linkId=74f6517a8c4df9f357cf9781972b7fb1&language=en_US]["How to Write a Thesis"]]: "there's a lot someone doesn't know anything about precisely because she photocopied a text; she has given herself in to the illusion of having read the text already." (That's from page 162 of the German translation; I translated the quote from there since it precedes the publication of the official English translation.)

The worst we could do is to pile up copies until the stack grows intimidatingly high, until it becomes unmanageable. After that it will be ignored in its entirety. Because to take a photocopy of a text is so much faster than actually reading it and learning what's inside, we tend to amass days worth of deliberate reading in about half an hour standing next to the copier. We have to pay attention not to copy more texts than we may handle.

The same holds true when it comes to managing bookmarks. We stumble upon an interesting web page and don't want to lose the information, thus we keep it as a bookmark. The digital pile of bookmarks isn't any different from a tangible pile of papers we consider worth knowing. Here, too, kept isn't read, though.
#+end_quote
*** Research, read, assimilate; rinse and repeat
#+begin_quote
Collecting, just as Eco warned us, does not magically increase our knowledge. We have to read a text effectively to assimilate its ideas and learn from it. Reading effectively means the text changes our knowledge permanently. Only when we learn from it and begin to work with the ideas it presents. We need to extract what's inside and write things down.

If we read without taking notes, our knowledge increases for a short time only. Once we forget what we knew, having read the text becomes worthless. You can bet that you'll forget about the text's information one day. It's guaranteed. Thus, reading without taking notes is just a waste of time in the long run. It's as if reading never happened.

That's the reason we are used to picking up a reference text again and again when we work on our writing projects. We read and take the information from the text, put it in our short-term memory, get back to our own draft and pour in the information. We transfer information from one place to another but fail to increase our knowledge on the way. That's the usual, inefficient way.

It's only rational to take notes when you read a text because a system of notes can become [[https://zettelkasten.de/posts/extend-your-mind-and-memory-with-a-zettelkasten/][an extension to your mind and memory]]. This will integrate the text's information into our own knowledge. To increase one's knowledge is a meaningful and the only sustainable way of working with information. Instead of shoveling information from the source text into your own project with the help of your working memory, you can integrate it into your knowledge system once and have it available forever. We may expand our knowledge permanently only by storing notes permanently.

Taking notes thoroughly means you can rely on your notes alone and rarely need to look up a detail in the original text.

#+begin_quote2
I rarely consult secondary sources again. If I have to do so, it means that I did not do the job right the first time.\\

[[http://takingnotenow.blogspot.com/2013/11/devonthink-reconsidered.html][MK, of "Taking Note Now"]]
#+end_quote2

This is a first step to conquer Collector's Fallacy: to realize that having a text at hand does nothing to increase our knowledge. We have to work with it instead. Reading alone won't suffice: we have to create notes, too, to create real, sustainable knowledge.

Especially when we start to research something new, Eco recommends we read and highlight texts right after we create copies in [[https://www.amazon.com/How-Write-Thesis-MIT-Press/dp/0262527138/ref=as_li_ss_tl?ie=UTF8&linkCode=ll1&tag=ctzettelkasten-20&linkId=74f6517a8c4df9f357cf9781972b7fb1&language=en_US]["How to Write a Thesis"]].

^{[[https://zettelkasten.de/posts/collectors-fallacy/#fn1][1]]} If we train ourselves to process photocopied texts soon, we get a feeling of how much we can really handle.

Shorter cycles of research, reading, and knowledge assimilation are better than long ones. With every full cycle from research to knowledge assimilation, we learn more about the topic. When we know more, our decisions are more informed, thus our research gets more efficient. If, on the other hand, we take home a big pile of material to read and process, some of it will turn out be useless once we finished parts of the pile. To minimize waste, both of time and of paper, it's beneficial to immerse oneself step by step and learn on the way instead of making big up-front decisions based on guesswork.

The habit of keeping the cycle of research, reading, and knowledge assimilation short is a powerful way to circumvent our innate addiction to gather piles of stuff.

*Update 2014-07-17:* _More recently, I wrote about this topic and included a more elaborate schedule to form a counter-habit. It's called [[https://zettelkasten.de/posts/knowledge-cycle-efficiently-organize-writing-projects/][the Knowledge Cycle]]._

To form a habit, you have to set yourself actionable limits and keep score.

- To get started, do research for one hour and no second more. Process the collected material until the stack is empty.
- Then do a quick review of the cycle: how well did it go? Did you learn something new? Was it too much or too little you found in the amount of time?
- Afterwards, change the time limit a bit if you think it wasn't appropriate.

Repeat the cycle and keep track of your perceived productivity until you establish a feedback-supported routine which suits your needs.
#+end_quote
* Flashcards
#+print_bibliography: