:PROPERTIES:
:ID:       ed6bc3fb-c6a6-45fe-9405-e4c74b02a5bb
:LAST_MODIFIED: [2023-12-20 Wed 07:32]
:ROAM_REFS: [cite:@tiezeCollectorFallacy0100]
:ROAM_ALIASES: "Info gorging"
:END:
#+title: Collector's fallacy
#+hugo_custom_front_matter: :slug "ed6bc3fb-c6a6-45fe-9405-e4c74b02a5bb"
#+author: Cash Prokop-Weaver
#+date: [2023-08-04 Fri 17:28]
#+filetags: :concept:

The collector's fallacy is the focus collection of knowledge without internalizing or understanding the knowledge. Examples include:

- a bookshelf of books you haven't read
- accumulating links to thinkpieces, articles, blog posts, etc, that "you'll definitely read some day" (see [[id:c93c0308-2ea5-47d1-b808-b0291b092527][Unread]])

See [[id:b23ffea4-e780-4d89-84ad-c0bd4f25816f][Christian Tieze | The Collector's Fallacy]]

Related: [[id:75f5bb46-04f2-4fdd-ae12-db9607773b98][The difference between knowing the name of something and knowing something]].

#+begin_quote
Reading can be a trap, if it turns into a substitute for action.

[cite:@coagulopathReadingCanBeTra2023]
#+end_quote

* Info gorging
#+begin_quote
I have, and I called it "info gorging", and I would occasionally indulge in it. But the problem is that you don't fully integrate what you've seen with what you know or believe. At best, you've accumulated a set of superficial ideas to be fleshed out later. At worst, you've given yourself a feeling of preemptive failure, looking at all the things you could do, and yet not doing them.

>Btw. you could say, just turn off the Internet and buy a book, but can you really pretend it doesn't exist? And how long can you stick to it?

Old fashioned discipline starts in the mind. You must be ruthless with yourself, and make a determination: I'm reading this book, and if I'm not doing that, then I'm staring into space. There is no third option, no fidget spinner, no screen, not even useful distractions like cleaning. If you accept your wayward thoughts, but not indulge them, they will pass.

In many ways, information is like fast food in that it can overstimulate you, yet leave you wanting more. There is no other way out of this cycle than to acknowledge this condition and cut yourself off. You need strong faith in yourself and in the wisdom of the path you've chosen.

[cite:@javajoshCalledItInfoGorging]
#+end_quote
* Flashcards :noexport:
** Describe :fc:
:PROPERTIES:
:CREATED: [2023-08-04 Fri 17:30]
:FC_CREATED: 2023-08-05T00:31:27Z
:FC_TYPE:  double
:ID:       9b782ca5-bd0d-4368-95c8-02cb409b9b99
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.35 |   7 |   153.52 | 2024-05-18T10:12:50Z |
| back     | 2.20 |   7 |   144.07 | 2024-05-12T17:09:24Z |
:END:

[[id:ed6bc3fb-c6a6-45fe-9405-e4c74b02a5bb][Collector's fallacy]]

*** Back

The practice of collecting knowledge, or references to knowledge (links, books, articles, etc), without internalizing said knowledge.
*** Source
[cite:@tiezeCollectorFallacy0100]


* Bibliography
#+print_bibliography:
