:PROPERTIES:
:ID:       3f33e96a-915a-4561-be68-4cef17b84792
:ROAM_ALIASES: "Iterative development"
:LAST_MODIFIED: [2023-09-11 Mon 11:50]
:END:
#+title: Crawl, walk, run
#+hugo_custom_front_matter: :slug "3f33e96a-915a-4561-be68-4cef17b84792"
#+author: Cash Prokop-Weaver
#+date: [2023-06-06 Tue 08:22]
#+filetags: :concept:

Crawl, walk, run emphasizes iterative development as way to progressively build a solution as opposed to building it all-at-once. The phrase originates, as far as I can tell, from child development stages though some directly cite [cite:@kingIfYouCanFlyThenRun].

Related: [[id:36417ccc-d8cc-4116-baef-89dfb6b1924a][Shuhari]].

* Example(s)

** Product metrics

Take a hypothetical service built by your team over a year ago. The metrics for this product (latency, resource requirements, etc) were manually calculated and put into some document when the product released. Your team hasn't updated these metrics in over a year.

It's clear that some automated system or dashboard would be better as it would stay up to date over time without manual involvement. However, setting such a system up has up-front and ongoing time/resource costs.

An iterative development approach could start with re-computing the metrics manually (walk). This is likely to take much less time than building an automated monitoring solution and can serve as data for future decisions:

- Have the metrics changed since they were last run? Did we expect them to change? If we expect them to change again in the future, at what cadence?
- How much benefit do we gain by having these metrics up-to-date? Do we get all the benefits by updating them once a quarter? Do we need to have them updated in real time?

Answering these follow-up questions ensures you and your team don't burn time solving a problem that doesn't need solving; or one that has a simple solution. Perhaps it's enough to create a recurring reminder to refresh the metrics every quarter. A shared bash script could be all the "automation" necessary in that it simplifies the manual update into a [[id:1e9fa224-0c4d-4b1b-aee5-4075fe9f900a][One-click]] process.

* Flashcards :noexport:
** Describe :fc:
:PROPERTIES:
:CREATED: [2023-06-06 Tue 08:50]
:FC_CREATED: 2023-06-06T15:51:25Z
:FC_TYPE:  double
:ID:       521c790e-4fa8-47e7-a340-bdd4b8ca904c
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.50 |   6 |   109.71 | 2023-12-09T05:58:58Z |
| back     | 2.35 |   6 |    75.40 | 2023-10-20T01:30:24Z |
:END:

[[id:3f33e96a-915a-4561-be68-4cef17b84792][Crawl, walk, run]]

*** Back
A phrase for taking an iterative or progressive approach to building something.
*** Source
* Bibliography
#+print_bibliography:
