:PROPERTIES:
:ROAM_REFS: [cite:@CreativityFaucetHowBeMoreCreative]
:ID:       bbb82ce2-0bab-4746-acc1-7bb95da9bb72
:LAST_MODIFIED: [2023-09-06 Wed 08:05]
:END:
#+title: Julian Shapiro | Creativity Faucet: How to Be More Creative
#+hugo_custom_front_matter: :slug "bbb82ce2-0bab-4746-acc1-7bb95da9bb72"
#+author: Cash Prokop-Weaver
#+date: [2022-10-26 Wed 09:24]
#+filetags: :reference:

[[id:5d78b917-4138-4236-a15e-22a6ae7b19a2][Julian Shapiro]], [cite:@CreativityFaucetHowBeMoreCreative]

* Notes
#+begin_quote
One of the most valuable writing skills is the ability to generate novel ideas.

[...]

Visualize your creativity as a backed-up pipe of water. The first mile is packed with wastewater. This wastewater must be emptied before the clear water arrives.

Because your pipe has only one faucet, there's no shortcut to achieving clarity other than first emptying the wastewater.

Let's apply this to creativity: At the beginning of a writing session, write out every bad idea that unavoidably comes to mind. Instead of being self-critical and resisting them, recognize bad ideas as progress. Bad ideas are usually the clichés your brain has been overexposed to.

Once the bad ideas are emptied, strong ideas begin to arrive.

Here's my guess as to why: Once you've generated enough bad output, your mind reflexively identifies which elements caused the badness. Then it becomes good at avoiding them. You start pattern-matching interesting ideas with greater intuition.

It's easier to look at something bad then intuit how to make it better than to make something good out of thin air.

Most creators resist their bad ideas and never reach the clear water. If you've opened a blank document, scribbled a few thoughts, then walked away because you weren't struck with gold, then you too never got past it.

[...]

Your work starts as a weak imitation. You identify what makes the imitation weak. You iterate the imitation until it's original.
#+end_quote

* Flashcards
#+print_bibliography: