:PROPERTIES:
:ID:       0905eaa4-16e9-4abb-b78c-0b00f855e60d
:SERVINGS: 8
:STARS:    5
:COOK_MINUTES: 45
:LAST_MODIFIED: [2023-09-24 Sun 09:48]
:END:
#+title: Creamy vegan mushroom lasagna
#+hugo_custom_front_matter: :cook_time "45m" :total_time "45m" :servings "8" :slug "0905eaa4-16e9-4abb-b78c-0b00f855e60d" :stars "5"
#+author: Cash Prokop-Weaver
#+date: [2022-10-31 Mon 08:21]
#+filetags: :recipe:

This recipe is from [cite:@murnaneOnePartPlantSimpleGuideEatingRealOneMealTime2017] and [cite:@murnaneCreamyVeganMushroomLasagnaa].

* Ingredients

#+begin_ingredients
- Olive, grape seed, or coconut oil, or veggie broth for sautéing
- 3 garlic cloves, minced
- 16 ounces mushrooms, chopped (you can use a mix of different mushrooms)
- 1 tablespoon tamari or coconut aminos
- 1 teaspoon dried thyme
- 3/4 cup raw cashews, *soaked for a few hours (overnight is best)*, drained
- 1 cup veggie broth
- 2 big handfuls spinach
- 10 ounces lasagna noodles
- 4 cups marinara sauce, store-bought or homemade
- Nutritional yeast (optional)
#+end_ingredients

* Steps
1. Preheat the oven to 350ºF.
2. In a large skillet, heat a glug of oil or veggie broth over medium. When the pan is hot, add the garlic and sauté until it becomes fragrant. This will take about a minute. Add the mushrooms, tamari, and thyme. Cook, stirring every minute or so, for 6 to 8 minutes or until the mushrooms release their water and a little broth starts to form.
3. Combine the cashews and veggie broth in a high-speed blender and blend until the mixture is completely smooth. This might take up to 5 minutes, depending on the speed and power of your blender. Pour the cashew sauce into the pan with the mushrooms. Reduce the heat to medium-low and simmer for a couple minutes to let the sauce thicken, stirring frequently. Throw in the spinach and stir for another minute.
4. Spread a third of the marinara sauce on the bottom of an 8-by-11-inch baking dish. Add a layer of *uncooked* noodles. Cover the noodles with half of the mushroom cream. Add a layer of noodles. Use another third of the marinara to cover these noodles. Add the remaining mushroom cream. Add the last layer of noodles and cover it with the remaining marinara sauce.
5. Cover the lasagna with aluminum foil and bake for 30 minutes. Remove the foil, add a sprinkle of nutritional yeast over the top, if you like, and bake for another 15 minutes. Let the lasagna rest for 5 minutes before serving.
* Flashcards :noexport:
* Bibliography
#+print_bibliography:
