:PROPERTIES:
:ROAM_REFS: [cite:@carnegieHowWinFriendsInfluencePeopleUpdatedNextGenerationLeaders2022]
:ID:       7c19c7b0-04b6-4094-ac32-5787edf3e73b
:LAST_MODIFIED: [2024-02-15 Thu 16:59]
:END:
#+title: Dale Carnegie | How to Win Friends and Influence People
#+hugo_custom_front_matter: :slug "7c19c7b0-04b6-4094-ac32-5787edf3e73b"
#+author: Cash Weaver
#+date: [2024-02-15 Thu 16:59]
#+filetags: :hastodo:reference:

TODO_AUTHOR, [cite:@carnegieHowWinFriendsInfluencePeopleUpdatedNextGenerationLeaders2022]

* TODO Summary
* TODO Thoughts
* TODO Notes
How to Win Friends and Influence People (Dale Carnegie)
- Your Note on page 14 | Location 205 | Added on Friday, June 26, 2015 10:33:31 PM

weekly retrospective
==========
How to Win Friends and Influence People (Dale Carnegie)
- Your Highlight on page 13 | Location 198-205 | Added on Friday, June 26, 2015 10:33:31 PM

After dinner I went off by myself, opened my engagement book, and thought over all the interviews, discussions and meetings that had taken place during the week. I asked myself: 'What mistakes did I make that time?' 'What did I do that was right-and in what way could I have improved my performance?' 'What lessons can I learn from that experience?' "I often found that this weekly review made me very unhappy. I was frequently astonished at my own blunders. Of course, as the years passed, these blunders became less frequent. Sometimes I was inclined to pat myself on the back a little after one of these sessions. This system of self-analysis, self-education, continued year after year, did more for me than any other one thing I have ever attempted. "It helped me improve my ability to make decisions - and it aided me enormously in all my contacts with people. I cannot recommend it too highly."
==========
How to Win Friends and Influence People (Dale Carnegie)
- Your Highlight on page 39 | Location 594-595 | Added on Friday, June 26, 2015 10:43:39 PM

Principle 1 - Don't criticize, condemn or complain.
==========
How to Win Friends and Influence People (Dale Carnegie)
- Your Highlight on page 40 | Location 600-601 | Added on Friday, June 26, 2015 10:44:10 PM

The only way I can get you to do anything is by giving you what you want. What do you want?
==========
How to Win Friends and Influence People (Dale Carnegie)
- Your Highlight on page 40 | Location 605-608 | Added on Friday, June 26, 2015 10:44:28 PM

What do you want? Not many things, but the few that you do wish, you crave with an insistence that will not be denied. Some of the things most people want include: 1. Health and the preservation of life. 2. Food. 3. Sleep. 4. Money and the things money will buy. 5. Life in the hereafter. 6. Sexual gratification. 7. The well-being of our children. 8. A feeling of importance.
==========

* Bibliography
#+print_bibliography:
* TODO [#2] Flashcards :noexport:
