:PROPERTIES:
:ROAM_REFS: [cite:@berkeLactoFermentedMustardAnyMustardYouVeHadInsaneBrine2019]
:ID:       f25d2624-2180-4de0-b693-8cc1d73e52b1
:LAST_MODIFIED: [2024-01-07 Sun 09:00]
:END:
#+title: Danny Berke | Lacto-Fermented Mustard
#+hugo_custom_front_matter: :slug "f25d2624-2180-4de0-b693-8cc1d73e52b1"
#+author: Cash Weaver
#+date: [2024-01-07 Sun 08:27]
#+filetags: :recipe:reference:

[[id:0d929227-c2bd-47bf-8614-4b142b9a940b][Danny Berke]], [cite:@berkeLactoFermentedMustardAnyMustardYouVeHadInsaneBrine2019]

* Ingredients
** For the ferment

#+begin_ingredients
| Ingredient           | Notes                               | Quantity      |
|----------------------+-------------------------------------+---------------|
| Yellow mustard seeds |                                     | 1.25 cups     |
| Brown mustard seeds  |                                     | 1.25 cups     |
| Water                | Filtered or distilled               | 4 cups        |
| Salt                 | Additive free                       | 2 Tablespoons |
| Pineapple            | Fresh, canned, or frozen            | 150 grams     |
| Garlic cloves        | Quartered                           | 40 grams      |
| Ginger               | Thin-sliced                         | 40 grams      |
| Yellow bell pepper   | Seeds and core removed              | 0.5           |
| Hot peppers          | Orange habaneros, ghost pepper, etc | As desired    |
#+end_ingredients

** After the ferment

#+begin_ingredients
| Ingredient            | Notes                                                                                   | Quantity        |
|-----------------------+-----------------------------------------------------------------------------------------+-----------------|
| White wine vinegar    | Substiture other vinegars; may not use all                                              | 2 cups          |
| Salt                  | 1 teaspoon per cup of vinegar                                                           | Ad libitum      |
| Ground mustard powder | Optional; for heat, yellow or brown                                                     | 1.5 tablespoons |
| Cayenne pepper        | Optional; for heat                                                                      | 1.5 tablespoons |
| Fermented items       | Optional; [[https://insaneinthebrine.com/fermented-horseradish/][horseradish]], [[https://insaneinthebrine.com/honey-ferments/][honey fermented garlic]]                                           | 0.5 cups        |
| Honey                 | Optional; for sweet mustard, substitute sugar; blend in 1 tablespoon at a time to taste | Ad libitum      |
#+end_ingredients

* Steps

#+begin_quote
1. Add all the mustard seeds and prepared produce to the jar, placing the seeds in first. Add increasingly larger components, ending with the pepper half. Use the pepper half as a covering so as to prevent any floaters.
2. Prepare the brine by mixing the water and salt in a sealed container and shaking it vigorously. (Or combine warm water with salt and allow to cool.)
3. Once the pepper half is securely holding everything down (and/or using a fermentation weight), gently pour the brine over to prevent dislodging the mustard seeds & pausing periodically to allow time for the water to seep down. Use all the brine and be aware that over the next few days, the mustard seeds will absorb much of the brine and they will swell quite a bit. (The recipe includes enough brine to account for this and still allow for all veggies to be submerged.)
4. All veggies including the pepper should be submerged. As an added precaution, adding a fermentation weight on top of the pepper is advised. Then apply the fermentation airlock (or use the burp method) and allow at least one month at room temperature to ferment (longer is fine).
5. At the end of the allotted time, strain out any excess brine (if present) and blend all solids until you reach the desired consistency.
6. Add up to two cups of white wine vinegar and other additions for the final blending (this will also make the mustard suitable for a squeeze bottle).
#+end_quote

* Notes

#+begin_quote
For this mustard, I add around 1.75 cups white wine vinegar but it can also be a mix of vinegar and any reserved ferment brine, and blend for 5-10 minutes on high, to achieve the desired consistency. For each cup of liquid added, you can add up to 1 tsp of salt if you want to maintain the level of saltiness. See the ingredients list above for ideas of what to add at blending.

You're recommended to place and keep the jar in a larger bowl, as the seeds will roughly double in size. Although they're absorbing brine, you may find that everything in the jar gets pushed upwards, so a glass weight is a good addition if you can fit it. Otherwise, the yellow pepper should be cut large enough to remain firmly in place.

For the batch of mustard featured in this post, I made half with added fermented horseradish (about 1/4 cup), and one with added honey fermented garlic (1/3 cup). Note that these quantities were for half the mustard; you could double the amount (to a 1/2 cup) if it's to blend into the entire batch of mustard.

Alternately, you could consider dividing into several small variations from your main batch as well. FYI, the featured photo of this post is the horseradish mustard.

I always add the cayenne or other dried hot pepper at the final blending (mentioned in the ingredients section) to round out the flavor.
#+end_quote

* Bibliography
#+print_bibliography:
* Flashcards :noexport:
