:PROPERTIES:
:ROAM_REFS: [cite:@danskinianCostDoingBusiness2022]
:ID:       073a3833-8cf1-431e-97df-c87f448b6a12
:LAST_MODIFIED: [2023-10-09 Mon 23:58]
:END:
#+title: Ian Danskin | The Cost of Doing Business
#+hugo_custom_front_matter: :slug "073a3833-8cf1-431e-97df-c87f448b6a12"
#+author: Cash Prokop-Weaver
#+date: [2022-09-26 Mon 19:06]
#+filetags: :reference:

[[id:2e66d444-9a3a-4ed3-8fac-210bb61933fb][Ian Danskin]], [cite:@danskinianCostDoingBusiness2022]

This is an entry in the [[id:913d6ace-03ac-4d34-ae92-5bd8a519236c][Alt-right Playbook]].

* Summary

White people -- both those who profess to be non-racist and otherwise -- tend to view racism as "tolerable" or else "easy to disregard". It's okay to [[https://knowyourmeme.com/memes/some-of-you-may-die][sacrifice]] minorities in order to win. This applies to more than just racism and is termed the cost of doing business.
* Notes

#+begin_quote
[...] controversy = attention and attention = brand recognition. [...] [The] economy runs on engagement, and hate-clicks are still clicks.
#+end_quote

#+begin_quote
This is privilege. Indeed, this is part of what makes privilege privilege: it's the identity that's treated as a norm. The one you don't have to think about.
#+end_quote

#+begin_quote
The Alt-Right is the gentrification of white nationalism. Their pocket squares and MBAs and $90 haircuts short out the white moderate's brain because they still associate white supremacy with white trash.
#+end_quote

#+begin_quote
The boundaries are not policed from the inside.
#+end_quote

#+begin_quote
Now, these people frequently are self-identified, card-carrying racists. My point is, for this system of incentives and rewards to operate, they don't have to be. Any of them may, but none of them must. Racism exists and it's efficient. And, in a capitalist society, where cops are competing for promotions, private prisons are competing for contracts, and politicians are competing for votes, if an unethical behavior sees a higher return than the alternative… then ethics are a luxury. There are hundreds of examples of businesses that claim, in periods of prosperity, that they prefer to do what is right over what is profitable. But what tune do they play when prosperity ends? Every boom has a bust - since 1900, the US has spent one out of every four years in recession. And, in the lean season, not using this generations-old system built by white people to advantage their descendents is a liability. A values-based business typically goes one of three ways: compromising their values to stay competitive, getting bought by someone who compromised their values to stay competitive, or sticking to their guns and facing a higher risk of going out of business. Many choose to do the right thing, and some even survive. But that's beating the odds. The market trends toward the optimal strategy.
#+end_quote

See also:

- Specifically: [[id:3aea1e2f-dd21-4c21-a8c9-7efd610424c4][Moloch]] and [[id:4d1a0eba-1f0f-4634-b574-6d66b7afa9b8][This is the dreamtime]]
- Generally: [[id:c73b15fa-a2bc-48bc-8f3d-6edffc332da1][Systems]]

#+begin_quote
[...] white supremacy is about power.
#+end_quote

#+begin_quote
Because, I mean, what if they genuinely believe the Voting Rights Act unfairly targets Southern states? Or even if - and I'm saying if here - they did do it to suppress votes, if hurting Black people isn't their goal, and they're just trying to win elections, is that really "racist?"

Moderates are very cagey about breaking out the R-word for a fellow white person.

See, there's this other definition of racism that most white people learn in grade school: racism is when you say mean things to other kids about skin color and it hurts their feelings; racism is about cruelty. And harm done by white people, therefore, isn't racism if isn't cruel; it's merely ignorant. Or apathetic. But ignorance and apathy can be reasoned with; you just gotta sit down and hash it out. As long as it takes. Real white supremacy is about emotional distress or interpersonal violence; it's uncommon, it's unpopular, and it's a hearts and minds issue.

What this definition leaves out is any notion that white supremacy is about power. That white people who disavow racism still live longer, get paid better, get arrested less often, and are typically in position to negotiate with whomever's in power. That this society was built for The Everyman, and being The Everyman confers power upon you.

When children of white moderates get older and first brush up against this definition, wherein white supremacy is not small but all-encompassing, where it can be cruel, but is at least as often indifferent, and where every white person in the country is bound up in it and privileged by it whether they want to be or not, and will never, ever experience it themselves - where it's not about feelings but power - how often do they say, "oh, maybe the definition I grew up with was simplified for 9-year-olds"?; or, "oh, maybe the definition given to me by white grown-ups was less complete than the one a Black grown-up might've given"? And how often do they say, "you can't just redefine racism?"

Right out the gate, the white moderate is possessive not just of their whiteness but of the very definition of racism.

In the definition they know, racism exists only over here. And the white collaborator is a compatriot who shares their ultimate vision for the future, but has simply gone off course somewhere. And they don't see themselves as flawed individuals with a long way still to go; they've already arrived! They're the destination everyone else needs to get to! Living proof that white supremacy can be easily and painlessly opted out of. They can't see collaborators as opponents because there is no definition of white supremacy that includes collaborators and doesn't also include them.

And this is critically important: they don't want to start thinking of themselves as white. They don't want the constant awareness of one's race or how one's race is perceived – you know, the things the rest of humanity deals with. And who would want that? I'll tell you who wants that: Nazis and klansmen want that. They're the only ones who like thinking about whiteness every day. So, white moderates cling to the other definition, the comfortable one. They may be more or less willing to collaborate with people of color, but mostly in ways that don't foreground their whiteness. White-as-default is one concession that can never be made, in part because it's the one that can't be spoken.
#+end_quote

#+begin_quote
Racism must be understood as more than a set of individual beliefs and feelings, but as a tool for achieving political ends, first and foremost because claiming otherwise is both factually and morally wrong. But also, without this understanding, white culture can't recognize the stakes.
#+end_quote

#+begin_quote
The fascist goal is to harness and redirect class resentment towards a scapegoat.
#+end_quote

#+begin_quote
They don't care about ideas. They care about power.
#+end_quote

See [[id:8c1b0569-db17-41af-90a3-7f2c75dc8923][Realpolitik]], [[id:2e9a36f6-43e0-4f9a-af7e-64a4ef069a19][Power politics]], [[id:3aea1e2f-dd21-4c21-a8c9-7efd610424c4][Moloch]].

* Flashcards :noexport:
** The fascist goal is {{to harness and redirect class resentment toward a scapegoat}@0}. :fc:
:PROPERTIES:
:CREATED: [2022-09-27 Tue 20:27]
:FC_CREATED: 2022-09-28T03:28:09Z
:FC_TYPE:  cloze
:ID:       ef891303-53e4-4182-a7db-be48627d90b4
:FC_CLOZE_MAX: 0
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 1.75 |   8 |   128.89 | 2024-02-16T04:19:34Z |
:END:

*** Source
[cite:@danskinianCostDoingBusiness2022]
#+print_bibliography: