:PROPERTIES:
:ROAM_REFS: [cite:@chapmanDevelopingEthicalSocialCognitiveCompetence2016]
:ID:       9ffddcfd-8b32-4c07-bb86-1fed040e8e5c
:LAST_MODIFIED: [2023-09-05 Tue 20:18]
:END:
#+title: David Chapman | Developing Ethical, Social, and Cognitive Competence
#+hugo_custom_front_matter: :slug "9ffddcfd-8b32-4c07-bb86-1fed040e8e5c"
#+author: Cash Weaver
#+date: [2023-01-12 Thu 08:15]
#+filetags: :hastodo:reference:

[[id:13a2657b-425e-4a42-bd65-8b5c31a847af][David Chapman]], [cite:@chapmanDevelopingEthicalSocialCognitiveCompetence2016]

* TODO [#2] Summary
* TODO [#2] Thoughts
* TODO [#2] Notes
#+begin_quote
Robert Kegan's model of adult development has profoundly influenced my understanding of ethics, relationships, society, and thought. This page summarizes his theory.

Earlier, I've mentioned Lawrence Kohlberg's [[https://en.wikipedia.org/wiki/Lawrence_Kohlberg's_stages_of_moral_development][related model]] of moral development. He pointed out a series of increasingly sophisticated ways one can approach ethical reasoning. The capacity to reason in each of these ways develops over an individual's lifetime through a fixed sequence of developmental stages.

Kohlberg's model had strong empirical support, and it significantly advanced ethical understanding; but his approach was excessively rationalistic. Our moral being involves feeling and acting, just as much as reasoning. Moral activity is also always situated in richly textured social relationships and complex practicalities, and cannot be separated from them. Kohlberg's paradigm of ethics was sitting in an armchair, reasoning out the correct action in simple, imaginary cases that you have no personal connection with.

Kegan's model is, I believe, the most sophisticated and useful account of ethics available. It is not complete or conclusive. Like every conceptual scheme, it is not Ultimate Truth. It's a tool that's useful in many situations; inapplicable in many others; and misleading in some.

This summary of Kegan's work cannot be read as a casual blog post. It is better to approach it like a section of a textbook; you may need to read it slowly and carefully. The model is conceptually complex and difficult; to explain it properly takes a book. I hope some readers will find this summary makes sense, and that others will be motivated to read Kegan. His two relevant books are [[http://www.amazon.com/gp/product/0674272315/?tag=meaningness-20][The Evolving Self]], which covers all the stages, and [[http://www.amazon.com/gp/product/0674445880/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0674445880&linkCode=as2&tag=meaningness-20&linkId=AFL7YZE2CVEA7HQK][In Over Our Heads]], which is about the difficulty and importance of the stage 3 to 4 transition specifically.

On the other hand, it makes sense. Take General Semantics (please!). I remember reading through Korzybski's [[http://www.amazon.com/gp/product/0937298018/ref=as_li_tl?ie=UTF8&camp=1789&creative=390957&creativeASIN=0937298018&linkCode=as2&tag=slastacod-20&linkId=6BN2XOJPPQ56YTXB][giant blue book of General Semantics]], full of labyrinthine diagrams and promises that if only you understood this, you would engage with the world totally differently, you'd be a new man armed with invincible cognitive weapons. And the key insight, maybe the /only/ insight, was "the map is not the territory" [[[id:bfc5100c-d70d-4829-9798-7a90b5edea9b][The map is not the territory]]], which seems utterly banal.

But this is a self-environment distinction of exactly the sort that children learn in development. It's dividing your own representation of the world from the world itself; it's about as clear a reference to theory of mind as you could ask for. Korzybski considered it a revelation when he discovered it; thousands of other people found it helpful and started a movement around it; I conclude that these people were missing a piece of theory-of-mind and Korzybski gave it to them. Not the whole deal, of course. Just a piece. But a piece of something big and fundamental, so abstract and difficult to teach that it required that whole nine-hundred-something page book to cram it in.
#+end_quote

#+begin_quote
I remember reading [[http://thenavelobservatory.com/2015/08/25/is-there-a-principled-distinction-between-refusing-to-watch-american-sniper-and-refusing-to-read-fun-home/][this piece]] by Nathan Robinson, where he compares his own liberal principles saying that colleges shouldn't endorse war-violence-glorifying film "American Sniper" to some conservatives arguing that colleges shouldn't endorse homosexuality-glorifying book "Fun Home":

#+begin_quote2
It is hypocrisy for liberals to laugh at and criticize the Duke students who have objected to their summer reading book due to its sexual and homosexual themes. They didn't seem to react similarly when students at other universities tried to get screenings of American Sniper cancelled. If you say the Duke students should open their minds and consume things they disagree with, you should say the same thing about the students who boycotted American Sniper. Otherwise, you do not really have a principled belief that people should respect and take in other opinions, you just believe they should respect and take in your own opinions. How can you think in one case the students are close-minded and sheltered, but in the other think they are open-minded and tolerant? What principled distinction is there that allows you to condemn one and praise the other, other than believing people who agree with you are better?
#+end_quote2

He proposes a bunch of potential counterarguments, then shoots each counterargument down by admitting that the other side would have a symmetrical counterargument of their own: for example, he believes that "American Sniper" is worse because it's racist and promoting racism is genuinely dangerous to a free society, but then he admits a conservative could say that "Fun Home" is worse because in their opinion it's homosexuality that's genuinely dangerous to a free society. After three or four levels of this, he ends up concluding that he can't come up with a meta-level fundamental difference, but he's going to fight for his values anyway because they're his. I'm not sure what I think of this conclusion, but my main response to his article is /oh my gosh he gets the thing/, where "the thing" is a hard-to-describe ability to understand that other people are going to go down as many levels to defend their self-consistent values as you will to defend yours. It seems silly when I'm saying it like this, and you should probably just read the article, but I've seen /so many people/ who lack this basic mental operation that this immediately endeared him to me. I would argue Nathan Robinson has a piece of theory-of-mind that a lot of other people are missing.

Actually, I was kind of also thinking this with his [[http://thenavelobservatory.com/2015/10/31/how-do-you-get-away-with-writing-something-like-this/][most recent post]], which complains about [[https://www.washingtonpost.com/blogs/post-partisan/wp/2015/10/27/the-insiders-the-fbi-director-is-saying-something-the-democrats-need-to-hear/][a Washington Post article]]. The Post argues that because the Democrats support gun control and protest police, they are becoming the "pro-crime party". I'm not sure whether the Post genuinely believes the Democrats are pro-crime by inclination or are just arguing their policies will lead to more crime in a hyperbolic figurative way, but I've certainly seen sources further right make the "genuinely in favor of crime as a terminal value" argument. And this doesn't seem too different from the leftist sources that say Republicans can't /really/ care about the lives of the unborn, they're just "anti-woman" as a terminal value. Both proposals share this idea of not being able to understand that other people have different beliefs than you and that their actions proceed naturally from those beliefs. Instead of saying "I believe gun control would increase crime, but Democrats believe the opposite, and from their different perspective banning guns makes sense," they say "I believe gun control would increase crime, Democrats must believe the same, and therefore their demands for gun control must come from sinister motives." [related: [[id:c0564758-b90d-42a6-be58-44d8985330ad][Ian Danskin | Always a Bigger Fish]]]
#+end_quote



* TODO [#2] Flashcards :noexport:
* Bibliography
#+print_bibliography:
