:PROPERTIES:
:ID:       53f1e53a-eb4d-4cb0-bf25-1d220f6d1d82
:LAST_MODIFIED: [2023-09-06 Wed 08:12]
:ROAM_REFS: [cite:@DecisionProblem2023]
:ROAM_ALIASES: Undecidable Decidable
:END:
#+title: Decision problem
#+hugo_custom_front_matter: :slug "53f1e53a-eb4d-4cb0-bf25-1d220f6d1d82"
#+author: Cash Prokop-Weaver
#+date: [2023-01-31 Tue 09:36]
#+filetags: :concept:

#+begin_quote
In computability theory and computational complexity theory [[[id:235c1171-e8bd-4b52-820c-109f34a0bc80][Computational complexity theory]]], a decision problem is a computational problem that can be posed as a yes–no question of the input values. An example of a decision problem is deciding by means of an algorithm whether a given natural number is prime. Another is the problem "given two numbers x and y, does x evenly divide y?". The answer is either 'yes' or 'no' depending upon the values of x and y. A method for solving a decision problem, given in the form of an algorithm, is called a decision procedure for that problem. A decision procedure for the decision problem "given two numbers x and y, does x evenly divide y?" would give the steps for determining whether x evenly divides y. One such algorithm is long division. If the remainder is zero the answer is 'yes', otherwise it is 'no'. A decision problem which can be solved by an algorithm is called decidable.

[cite:@DecisionProblem2023]
#+end_quote

* Flashcards
** Definition :fc:
:PROPERTIES:
:CREATED: [2023-01-31 Tue 09:37]
:FC_CREATED: 2023-01-31T17:37:44Z
:FC_TYPE:  double
:ID:       ffc949e4-3c72-45f6-9e0e-a48d0eb0e777
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.65 |   7 |   230.50 | 2024-02-29T12:47:22Z |
| back     | 2.35 |   7 |   234.69 | 2024-03-14T20:42:41Z |
:END:

[[id:53f1e53a-eb4d-4cb0-bf25-1d220f6d1d82][Decision problem]]

*** Back
A computational problem one can pose as a yes/no question of the input values.
*** Source
[cite:@DecisionProblem2023]
** Definition :fc:
:PROPERTIES:
:CREATED: [2023-01-31 Tue 09:37]
:FC_CREATED: 2023-01-31T17:39:04Z
:FC_TYPE:  double
:ID:       9b84e3af-db19-4d34-b6f6-250e3cdac953
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   7 |   312.65 | 2024-07-08T04:21:50Z |
| back     | 2.65 |   6 |   143.25 | 2023-09-30T22:09:34Z |
:END:

A [[id:53f1e53a-eb4d-4cb0-bf25-1d220f6d1d82][Decidable]] problem.

*** Back
A [[id:53f1e53a-eb4d-4cb0-bf25-1d220f6d1d82][Decision problem]] which can be solved by an algorithm.
*** Source
[cite:@DecisionProblem2023]
#+print_bibliography: