:PROPERTIES:
:ID:       d5355c3a-2137-46b2-af5a-10f9c3a6705f
:ROAM_REFS: [cite:@DifferentialCalculus2023]
:LAST_MODIFIED: [2023-07-27 Thu 07:10]
:ROAM_ALIASES: Differentiation Differentiate
:END:
#+title: Differential calculus
#+hugo_custom_front_matter: :slug "d5355c3a-2137-46b2-af5a-10f9c3a6705f"
#+author: Cash Prokop-Weaver
#+date: [2023-01-18 Wed 07:57]
#+filetags: :concept:

#+begin_quote
In mathematics, differential calculus is a subfield of calculus that studies the rates at which quantities change. It is one of the two traditional divisions of calculus, the other being integral calculus—the study of the area beneath a curve.

The primary objects of study in differential calculus are the derivative of a function, related notions such as the differential, and their applications. The derivative of a function at a chosen input value describes the rate of change of the function near that input value. The process of finding a derivative is called differentiation. Geometrically, the derivative at a point is the slope of the tangent line to the graph of the function at that point, provided that the derivative exists and is defined at that point. For a real-valued function of a single real variable, the derivative of a function at a point generally determines the best linear approximation to the function at that point.

[cite:@DifferentialCalculus2023]
#+end_quote
* Linearity of differentiation
:PROPERTIES:
:ID:       6297f3ce-9f4f-47c7-a879-5ae10ec92f82
:ROAM_ALIASES: "Sum rule"
:END:

Differentiation is [[id:5180515a-c694-49fb-ac2e-9718fe501f38][linear]].

#+begin_quote
For any functions $f$ and $g$ and any real numbers $a$ and $b$, the derivative of the function $h(x)=af(x)+bg(x)$ with respect to $x$ is: $\displaystyle h'(x)=af'(x)+bg'(x)$.

[cite:@DifferentiationRules2022]
#+end_quote

* Flashcards
** Describe :fc:
:PROPERTIES:
:CREATED: [2023-01-23 Mon 09:15]
:FC_CREATED: 2023-01-23T17:16:32Z
:FC_TYPE:  normal
:ID:       72f0035a-426c-4a41-a991-8a34a8f56f2c
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.35 |   7 |   220.83 | 2024-03-04T09:59:13Z |
:END:

Properties of [[id:d5355c3a-2137-46b2-af5a-10f9c3a6705f][Differentiation]]

*** Back
- [[id:5180515a-c694-49fb-ac2e-9718fe501f38][Linearity]]
*** Source

** Equivalence :fc:
:PROPERTIES:
:CREATED: [2023-01-23 Mon 09:16]
:FC_CREATED: 2023-01-23T17:17:39Z
:FC_TYPE:  cloze
:ID:       79630595-e57f-42dd-94da-c876db3efeb2
:FC_CLOZE_MAX: 0
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.20 |   7 |   176.44 | 2024-01-10T00:36:50Z |
:END:

$h(x)=af(x)+bg(x)$

$h'(x)=$ {{$af'(x)+bg'(x)$}@0}

*** Source
[cite:@DifferentiationRules2022]
#+print_bibliography: