:PROPERTIES:
:ID:       ee7fcae8-6322-4b71-91b0-704b7c21ae3a
:ROAM_ALIASES: DAG
:LAST_MODIFIED: [2023-03-17 Fri 07:02]
:ROAM_REFS: [cite:@DirectedAcyclicGraph2022]
:END:
#+title: Directed acyclic graph
#+hugo_custom_front_matter: :slug "ee7fcae8-6322-4b71-91b0-704b7c21ae3a"
#+author: Cash Prokop-Weaver
#+date: [2022-11-25 Fri 10:25]
#+filetags: :concept:

#+begin_quote
In mathematics, particularly graph theory, and computer science, a directed acyclic graph (DAG) is a Directed graph [[[id:129f1b92-49f6-44af-bae3-d8a171f66f04][Directed graph]]] with no directed cycles. That is, it consists of vertices [[[id:1b2526af-676d-4c0f-aa85-1ba05b8e7a93][Vertices]]] and edges [[[id:7211246e-d3da-491e-a493-e84ba820e63f][Edges]]] (also called arcs), with each edge directed from one vertex to another, such that following those directions will never form a closed loop. A directed graph is a DAG if and only if it can be topologically ordered [[[id:518c35ac-35d7-4c12-9522-efb13e5be1e8][Topological order]]], by arranging the vertices as a linear ordering that is consistent with all edge directions. DAGs have numerous scientific and computational applications, ranging from biology (evolution, family trees, epidemiology) to information science (citation networks) to computation (scheduling).

[cite:@DirectedAcyclicGraph2022]
#+end_quote

* [[id:555129b5-299e-4605-a2cd-9f77ebcede3d][Shortest path algorithm]]

#+begin_quote
Some algorithms become simpler when used on DAGs instead of general graphs, based on the principle of topological ordering. For example, it is possible to find [[https://en.wikipedia.org/wiki/Shortest_path][shortest paths]] and [[https://en.wikipedia.org/wiki/Longest_path_problem][longest paths]] from a given starting vertex in DAGs in linear time by [[https://en.wikipedia.org/wiki/Topological_sorting#Application_to_shortest_path_finding][processing the vertices in a topological order]], and calculating the path length for each vertex to be the minimum or maximum length obtained via any of its incoming edges. In contrast, for arbitrary graphs the shortest path may require slower algorithms such as Dijkstra's algorithm [[[id:668cbbcc-170b-42c8-b92b-75f6868a0138][Dijkstra's algorithm]]] or the [[https://en.wikipedia.org/wiki/Bellman%E2%80%93Ford_algorithm][Bellman--Ford algorithm]], and longest paths in arbitrary graphs are [[https://en.wikipedia.org/wiki/NP-hard][NP-hard]] to find.

[cite:@DirectedAcyclicGraph2022]
#+end_quote

* Flashcards
** Definition :fc:
:PROPERTIES:
:CREATED: [2022-12-21 Wed 05:48]
:FC_CREATED: 2022-12-21T13:52:07Z
:FC_TYPE:  double
:ID:       c1bdcd02-ffb6-47b3-9179-174e2ecff61e
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.65 |   6 |   120.97 | 2023-07-16T13:25:15Z |
| back     | 2.80 |   6 |   121.98 | 2023-07-14T14:30:44Z |
:END:

[[id:ee7fcae8-6322-4b71-91b0-704b7c21ae3a][Directed acyclic graph]]

*** Back
A directed graph which can be topologically sorted.
*** Source
[cite:@DirectedAcyclicGraph2022]
** AKA :fc:
:PROPERTIES:
:CREATED: [2022-12-21 Wed 06:01]
:FC_CREATED: 2022-12-21T14:01:48Z
:FC_TYPE:  cloze
:ID:       1d012de0-027b-4cdc-8701-537440109f3a
:FC_CLOZE_MAX: 1
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.95 |   6 |   145.90 | 2023-08-06T12:06:42Z |
|        1 | 2.95 |   5 |    48.77 | 2023-03-20T10:44:30Z |
:END:

- {{[[id:ee7fcae8-6322-4b71-91b0-704b7c21ae3a][Directed acyclic graph]]}@0}
- {{[[id:ee7fcae8-6322-4b71-91b0-704b7c21ae3a][DAG]]}@1}

*** Source
[cite:@DirectedAcyclicGraph2022]
** Cloze :fc:
:PROPERTIES:
:FC_CREATED: 2022-12-29T17:39:55Z
:FC_TYPE:  cloze
:ID:       97957398-0e0e-4561-8b15-076b3c0890c2
:FC_CLOZE_MAX: 0
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.65 |   6 |   106.92 | 2023-06-26T03:31:03Z |
:END:

A [[id:ee7fcae8-6322-4b71-91b0-704b7c21ae3a][Directed acyclic graph]] can be {{sorted in [[id:518c35ac-35d7-4c12-9522-efb13e5be1e8][Topological order]]}@0}.

*** Source
[cite:@DirectedAcyclicGraph2022]
#+print_bibliography: