:PROPERTIES:
:ID:       80396b6d-d572-4437-ab2d-698c62a3038b
:LAST_MODIFIED: [2023-09-25 Mon 06:28]
:END:
#+title: Disorganized attachment
#+hugo_custom_front_matter: :slug "80396b6d-d572-4437-ab2d-698c62a3038b"
#+author: Cash Prokop-Weaver
#+date: [2022-06-26 Sun 13:27]
#+filetags: :concept:

#+begin_quote
It's [an [[id:5f944538-ef8c-464f-b2da-c0f973558eca][attachment]] pattern that] happens when the negative experience and the comfort come from the same place. We see it in children and adults who are mistreated by the people they trust.

According to Stein, cults foster Disorganized Attachment by being intensely unpredictable. In a cult, you may be praised for your commitment on Monday and have your commitment questioned on Tuesday, with no change in behavior. You may be assigned a romantic partner, who may, at any point, be taken away, assigned to someone else. Your children may be taken from you to be raised by a different family. You may be told the cult leader wants to sleep with you, which may make you incredibly happy or be terrifying, but you won't be given a choice. And the rules you are expected to follow will be rewritten without warning.

This creates a kind of emotional chaos, where you can't predict when you will be given good feelings and when you will be given bad ones. But you're so enmeshed in the community you have no place else to go for good feelings; hurting you just draws you in deeper, because they are also where you seek comfort. And your pain is always your fault: you wouldn't feel so shitty if you were more committed. Trying to make sense of this causes so much confusion and anguish that you eventually just stop thinking for yourself. These are the rules now? OK. He's not my brother anymore? OK. This is my life now? OK.

[cite:@danskinEndnoteHowAltrightAbusiveRelationship2019]
#+end_quote

* Flashcards :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:
** Describe :fc:
:PROPERTIES:
:ID:       f579214b-6177-4f5f-8c48-7ecb311967dd
:ANKI_NOTE_ID: 1656857372183
:FC_CREATED: 2022-07-03T14:09:32Z
:FC_TYPE:  double
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 3.10 |   9 |   659.31 | 2025-07-15T20:51:40Z |
| back     | 2.35 |   7 |   223.08 | 2023-12-21T18:05:52Z |
:END:
[[id:80396b6d-d572-4437-ab2d-698c62a3038b][Disorganized attachment]]
*** Back
- An unhealthy attachment pattern in which the individual cannot predict when or where comfort and discomfort will come from.
- They often adapt a malleable worldview which attempts to justify or retroactively explain the comfort and discomfort when it arrives.
*** Source
[cite:@danskinEndnoteHowAltrightAbusiveRelationship2019]
