:PROPERTIES:
:ROAM_REFS: [cite:@meadowsThinkingSystemsPrimer2008]
:ID:       93f9260b-c0ee-4270-b731-e31f7d3be6bb
:LAST_MODIFIED: [2024-02-18 Sun 12:20]
:END:
#+title: Donella H. Meadows and Diana Wright | Thinking in Systems: A Primer
#+hugo_custom_front_matter: :slug "93f9260b-c0ee-4270-b731-e31f7d3be6bb"
#+author: Cash Weaver
#+date: [2024-02-18 Sun 12:20]
#+filetags: :hastodo:reference:

TODO_AUTHOR, [cite:@meadowsThinkingSystemsPrimer2008]

* TODO Summary
* TODO Thoughts
* TODO [#1] Notes
Thinking in Systems: A Primer (Donella H. Meadows)
- Your Highlight on page 11 | Location 163-165 | Added on Wednesday, July 1, 2015 2:35:32 PM

what is a system? A system is a set of things—people, cells, molecules, or whatever—interconnected in such a way that they produce their own pattern of behavior over time. The system may be buffeted, constricted, triggered, or driven by outside forces. But the system's response to these forces is characteristic of itself, and that response is seldom simple in the real world.
==========
Thinking in Systems: A Primer (Donella H. Meadows)
- Your Highlight on page 14 | Location 208-212 | Added on Wednesday, July 1, 2015 2:41:40 PM

No one deliberately creates those problems, no one wants them to persist, but they persist nonetheless. That is because they are intrinsically systems problems—undesirable behaviors characteristic of the system structures that produce them. They will yield only as we reclaim our intuition, stop casting blame, see the system as the source of its own problems, and find the courage and wisdom to restructure it. Obvious. Yet subversive. An old way of seeing. Yet somehow new. Comforting, in that the solutions are in our hands. Disturbing, because we must do things, or at least see things and think about things, in a different way.
==========
Thinking in Systems: A Primer (Donella H. Meadows)
- Your Highlight on page 15 | Location 216-220 | Added on Wednesday, July 1, 2015 2:42:19 PM

there is a problem in discussing systems only with words. Words and sentences must, by necessity, come only one at a time in linear, logical order. Systems happen all at once. They are connected not just in one direction, but in many directions simultaneously. To discuss them properly, it is necessary somehow to use a language that shares some of the same properties as the phenomena under discussion. Pictures work for this language better than words, because you can see all the parts of a picture at once.
==========
Thinking in Systems: A Primer (Donella H. Meadows)
- Your Highlight on page 16 | Location 237-237 | Added on Wednesday, July 1, 2015 2:50:58 PM

"archetypes."
==========

* Bibliography
#+print_bibliography:
* TODO [#2] Flashcards :noexport:
