:PROPERTIES:
:ROAM_REFS: [cite:@yudkowskySomethingProtect2008]
:ID:       ad3762f0-6d77-4289-baa7-4c3192b9c4b1
:LAST_MODIFIED: [2024-02-18 Sun 15:36]
:END:
#+title: Eliezer Yudkowsky | Something to Protect
#+hugo_custom_front_matter: :slug "ad3762f0-6d77-4289-baa7-4c3192b9c4b1"
#+author: Cash Prokop-Weaver
#+date: [2022-11-12 Sat 17:19]
#+filetags: :reference:

[[id:614d0317-e7fc-4ee2-a68a-e93471500fa0][Eliezer Yudkowsky]], [cite:@yudkowskySomethingProtect2008]

* Thoughts

[[id:dfc647aa-89b0-400a-9669-cdf2e0650c8c][Something to protect]]

* Notes
#+begin_quote
In the gestalt of (ahem) [[https://www.lesswrong.com/lw/m7/zen_and_the_art_of_rationality/][Japanese]] [[https://www.lesswrong.com/lw/k9/the_logical_fallacy_of_generalization_from/][fiction]], one finds this oft-repeated motif: Power comes from having something to protect [[[id:dfc647aa-89b0-400a-9669-cdf2e0650c8c][Something to protect]]].

I'm not just talking about superheroes that power up when a friend is threatened, the way it works in Western fiction. In the Japanese version it runs deeper than that.

[...]

The way it works in Western superhero comics is that the good guy gets bitten by a radioactive spider; and then he needs something to do with his powers, to keep him busy, so he decides to fight crime.  And then Western superheroes are always whining about how much time their superhero duties take up, and how they'd rather be ordinary mortals so they could go fishing or something.

Similarly, in Western real life, unhappy people are told that they need a "purpose in life", so they should pick out an altruistic cause that goes well with their personality, like picking out nice living-room drapes, and this will brighten up their days by adding some color, like nice living-room drapes.  You should be careful not to pick something too expensive, though.

In Western comics, the magic comes first, then the purpose:  Acquire amazing powers, decide to protect the innocent.  In Japanese fiction, often, it works the other way around.

[...]

Historically speaking, science won because it displayed greater raw strength in the form of technology, not because science sounded more reasonable.  To this very day, magic and scripture still sound more reasonable to untrained ears than science.  That is why there is continuous social tension between the belief systems.  If science not only worked better than magic, but also sounded more intuitively reasonable, it would have won entirely by now.

[...]

What I am trying to say is that more than your own life has to be at stake, before a person becomes desperate enough to resort to math.

[...]

Where do you get the will to keep moving forward?
#+end_quote

* Flashcards :noexport:
* Bibliography
#+print_bibliography:
