:PROPERTIES:
:ID:       be380da4-4720-4978-a3f8-c99a9470f509
:LAST_MODIFIED: [2023-10-31 Tue 09:46]
:END:
#+title: Embrace discomfort
#+hugo_custom_front_matter: :slug "be380da4-4720-4978-a3f8-c99a9470f509"
#+author: Cash Prokop-Weaver
#+date: [2023-10-31 Tue 09:40]
#+filetags: :hastodo:concept:

Discomfort isn't necessarily the goal, but the goal is not to avoid discomfort altogether. Discomfort is beneficial for personal and ability growth ([[id:89eb6adc-d8f8-4033-bc46-7fed725c3c01][Desirable difficulty]]).

* On learning new skills

#+begin_quote
Kevin Burke has noted that when he coaches youth basketball, some children don't want to do drills that they think make them look foolish (e.g., avoiding learning to dribble with their off hand even during drills where everyone is dribbling poorly because they're using their off hand). When I spent a lot of time in a climbing gym with a world class coach who would regularly send a bunch of kids to nationals and some to worlds, I'd observe the same thing in his classes -- kids, even ones who are nationally or internationally competitive, would sometimes avoid doing things because they were afraid it would make them look foolish to their peers. The coach's solution in those cases was to deliberately make the kid look extremely foolish and tell them that it's better to look stupid now than at nationals.

[cite:@luu95IleIsnThatGood]
#+end_quote

* TODO [#4] Expand :noexport:
* Flashcards :noexport:

* Bibliography
#+print_bibliography:
