:PROPERTIES:
:ID:       160f50d0-4d35-4f2b-b1ab-f6b6da5a7902
:LAST_MODIFIED: [2024-02-10 Sat 19:33]
:ROAM_REFS: [cite:@collinsFlywheelEffect]
:END:
#+title: Flywheel effect
#+hugo_custom_front_matter: :slug "160f50d0-4d35-4f2b-b1ab-f6b6da5a7902"
#+author: Cash Prokop-Weaver
#+date: [2024-02-10 Sat 19:23]
#+filetags: :concept:

The flywheel effect is the idea that effort compounds and makes subsequent rewards easier and greater. In the beginning, you may need to put a lot of effort into yield a small amount of reward. However, as you continue to put effort into the system, you begin to yield greater rewards and indeed the system can continue to yield reward even without continued effort (though it'll tend downward over time).

#+begin_quote
The Flywheel effect is [the idea that] [n]o matter how dramatic the end result, good-to-great transformations never happen in one fell swoop. [...] there is no single defining action, no grand program, no one killer innovation, no solitary lucky break, no miracle moment. Rather, the process resembles relentlessly pushing a giant, heavy flywheel, turn upon turn, building momentum until a point of breakthrough, and beyond.

[cite:@collinsFlywheelEffect]
#+end_quote

* Flashcards :noexport:
** Definition :fc:
:PROPERTIES:
:CREATED: [2024-02-10 Sat 19:27]
:FC_CREATED: 2024-02-11T03:28:28Z
:FC_TYPE:  double
:ID:       4de732ab-1e28-4a6c-9cf1-2a019b87a591
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    |  2.5 |  -1 |        0 | 2024-02-11T03:28:28Z |
| back     |  2.5 |  -1 |        0 | 2024-02-18T03:28:28Z |
:END:

[[id:160f50d0-4d35-4f2b-b1ab-f6b6da5a7902][Flywheel effect]]

*** Back



*** Source
[cite:@collinsFlywheelEffect]
* Bibliography
#+print_bibliography:
