:PROPERTIES:
:ID:       f17a9096-2a81-4652-9e56-d5fe76abcbc0
:LAST_MODIFIED: [2023-10-20 Fri 17:13]
:END:
#+title: Focus as magic
#+hugo_custom_front_matter: :slug "f17a9096-2a81-4652-9e56-d5fe76abcbc0"
#+author: Cash Prokop-Weaver
#+date: [2023-09-14 Thu 15:23]
#+filetags: :hastodo:concept:

I like the idea that focus, concentration, attention, quiet, darkness, stillness, is a requirement for magic.

#+begin_quote
At age ten, Kiki had decided to become a witch and learn Kokiri's magic right away. Kokiri had two magic abilities. The first was growing herbs to make sneeze medicine, and the second was flying through the sky on a broom.

Kiki quickly got the hang of flying. But as she grew older, she often found herself distracted by all sorts of things " for example, the big pimples that started appearing on the sides of her nose, or deciding which dress she should wear to her friend's birthday party.

Whenever that happened, her broom would suddenly start to fall. One time she was so busy thinking about the scratchy new underwear she was wearing that she ran into a power line! Her broom broke into pieces, and Kiki herself ended up with bumps on her nose and both kneecaps.

Soon after, Kokiri tied bells to the tall trees of the forest. If Kiki was lost in thought and flying too low, her feet would ring the bells and the sound would bring her back to reality. Fortunately, they were ringing much less than they used to.

Meanwhile there was the sneeze-medicine-making, but Kiki didn't seem to be cut out for it. She was impatient and found it difficult to grow the herbs, finely chop the leaves and roots, and slowly simmer them.

"Will another type of magic disappear?" Kokiri lamented. In the olden days, witches could use all sorts of magic. But over the years, one type after another disappeared, until even a genuine witch like Kokiri was left with only two abilities. Now her daughter hated one of them, so it was no wonder she was upset.

[cite:@kadonoKikiDeliveryService2020]
#+end_quote

* TODO [#1] Also quote the passage that contains "Some say it's because there's no such thing as a completely dark night or perfect silence anymore" :noexport:

* TODO [#2] [[https://thewalrus.ca/noise-ethics/][Noise is all around us]] :noexport:
:PROPERTIES:
:CREATED: [2023-05-21 21:33]
:END:
* TODO [#2] Flashcards :noexport:
#+print_bibliography:
