:PROPERTIES:
:ID:       f17a9096-2a81-4652-9e56-d5fe76abcbc0
:LAST_MODIFIED: [2024-02-18 Sun 21:03]
:END:
#+title: Focus as magic
#+hugo_custom_front_matter: :slug "f17a9096-2a81-4652-9e56-d5fe76abcbc0"
#+author: Cash Prokop-Weaver
#+date: [2023-09-14 Thu 15:23]
#+filetags: :hastodo:concept:

I like the idea that focus, concentration, attention, quiet, darkness, stillness, is a requirement for magic; or that they /are/ magic themselves. Humanity has cast light into all the formerly dark places, physical and not, and thereby purged the magic held there.

* In [[id:041d3a78-05af-4a51-aff3-88f1ae415f54][Eiko Kadono | Kiki's Delivery Service]]

#+begin_quote
At age ten, Kiki had decided to become a witch and learn Kokiri's magic right away. Kokiri had two magic abilities. The first was growing herbs to make sneeze medicine, and the second was flying through the sky on a broom.

Kiki quickly got the hang of flying. But as she grew older, she often found herself distracted by all sorts of things --- for example, the big pimples that started appearing on the sides of her nose, or deciding which dress she should wear to her friend's birthday party.

Whenever that happened, her broom would suddenly start to fall. One time she was so busy thinking about the scratchy new underwear she was wearing that she ran into a power line! Her broom broke into pieces, and Kiki herself ended up with bumps on her nose and both kneecaps.

Soon after, Kokiri tied bells to the tall trees of the forest. If Kiki was lost in thought and flying too low, her feet would ring the bells and the sound would bring her back to reality. Fortunately, they were ringing much less than they used to.

Meanwhile there was the sneeze-medicine-making, but Kiki didn't seem to be cut out for it. She was impatient and found it difficult to grow the herbs, finely chop the leaves and roots, and slowly simmer them.

"Will another type of magic disappear?" Kokiri lamented. In the olden days, witches could use all sorts of magic. But over the years, one type after another disappeared, until even a genuine witch like Kokiri was left with only two abilities. Now her daughter hated one of them, so it was no wonder she was upset.

[cite:@kadonoKikiDeliveryService2020]
#+end_quote

#+begin_quote
"Now then, here's your lunch." Kokiri patted Kiki's shoulder and set a little bundle down next to her. "I used herbs so it won't go bad as fast. Don't eat it all in one place. I remember my mom did a great job making my coming-of-age lunch. She cast some spell on the herbs in the bread that kept it from going bad or even stale. It's a shame we don't know how to do that anymore."

"That seems like the sort of thing that would be easy to pass on, though," Okino chimed in, coming in from his study with a book in his hand. "I wonder why it disappeared. Maybe that's just the nature of magic?"

"It's strange that I'm a witch and even I don't know. Some say it's because there's no such thing as a completely dark night or perfect silence anymore—if there's a light on or if there's even a tiny noise, we get distracted and can't get our magic to work."

"Certainly compared to ancient times, it's gotten a lot brighter," Okino said. "Nowadays there's always a light on somewhere."

"Yes, the world sure has changed." Kokiri nodded, [...]

[cite:@kadonoKikiDeliveryService2020]
#+end_quote

* TODO [#2] [[https://thewalrus.ca/noise-ethics/][Noise is all around us]] :noexport:
:PROPERTIES:
:CREATED: [2023-05-21 21:33]
:END:
* TODO [#2] [[https://zenhabits.net/quietude/][Become Quiet So You Can Listen]] :unlabeled:
:PROPERTIES:
:CREATED: [2024-01-26 20:11]
:END:
* TODO [#2] Flashcards :noexport:

* Bibliography
#+print_bibliography:
