:PROPERTIES:
:ID:       30cb897f-4ec4-4492-b23a-ac760ed49db2
:ROAM_REFS: [cite:@FramingSocialSciences2022]
:LAST_MODIFIED: [2023-09-05 Tue 20:17]
:ROAM_ALIASES: Frames Frame
:END:
#+title: Framing
#+hugo_custom_front_matter: :slug "30cb897f-4ec4-4492-b23a-ac760ed49db2"
#+author: Cash Prokop-Weaver
#+date: [2022-12-05 Mon 16:41]
#+filetags: :has_todo:concept:

#+begin_quote
In the social sciences, framing comprises a set of concepts and theoretical perspectives on how individuals, groups, and societies organize, perceive, and communicate about reality.

Framing can manifest in thought or interpersonal communication. Frames in thought consist of the mental representations, interpretations, and simplifications of reality [similar: [[id:787214e0-5941-4c6f-9a61-e79b9b40baea][Mental model]]]. Frames in communication consist of the communication of frames between different actors. Framing is a key component of sociology, the study of social interaction among humans. Framing is an integral part of conveying and processing data on a daily basis. Successful framing techniques can be used to reduce the ambiguity of intangible topics by contextualizing the information in such a way that recipients can connect to what they already know.

[cite:@FramingSocialSciences2022]
#+end_quote

* TODO [#2] Expand :noexport:

- [cite:@raemonNoticingFrameDifferences]
- [[id:64b11ab5-7980-4af4-ba6d-c23eb3d5ad43][Aella | Frame Control]]

* TODO [#2] Flashcards
#+print_bibliography: