:PROPERTIES:
:ID:       99e14785-13bb-420c-b0b5-b14bad1bd163
:LAST_MODIFIED: [2023-07-29 Sat 08:01]
:END:
#+title: Freddish
#+hugo_custom_front_matter: :slug "99e14785-13bb-420c-b0b5-b14bad1bd163"
#+author: Cash Prokop-Weaver
#+date: [2022-03-13 Sun 17:59]
#+filetags: :concept:

Freddish refers to the way [[id:f95aa4a2-494d-49e9-aa6f-6bcd0e3e759f][Fred Rogers]] would speak with children.

#+begin_quote
Freddish anticipated the ways its listeners might misinterpret what was being said. For instance, Greenwald mentioned a scene in a hospital in which a nurse inflating a blood-pressure cuff originally said, "I'm going to blow this up." Greenwald recalls: "Fred made us redub the line, saying, 'I'm going to puff this up with some air,' because 'blow it up' might sound like there's an explosion, and he didn't want the kids to cover their ears and miss what would happen next."

The show's final cuts reflected many similarly exacting interventions. Once, Rogers provided new lyrics for the "Tomorrow" song that ended each show, to ensure that children watching on Friday wouldn't expect a show on Saturday, when the show didn't air. And Rogers's secretary, Elaine Lynch, remembered how, when one script referred to putting a pet "to sleep," he excised it for fear that children would be worried about the idea of falling asleep themselves.

Rogers was extraordinarily good at imagining where children's minds might go. For instance, in a scene in which an eye doctor uses an ophthalmoscope to peer into his eyes, he made a point of having the doctor clarify that he wasn't able to see Rogers's thoughts. Rogers also wrote a song called "You Can Never Go Down the Drain," because he knew that drains were something that, to kids, seemed to exist solely to suck things down.

[cite:@kingMisterRogersHadSimpleSetRulesTalkingChildren2018]
#+end_quote


#+begin_quote
In 1977, about a decade into the show's run, Arthur Greenwald and another writer named Barry Head cracked open a bottle of scotch while on a break, and coined the term Freddish. They later created an illustrated manual called "Let's Talk About Freddish," a loving parody of the demanding process of getting all the words just right for Rogers. "What Fred understood and was very direct and articulate about was that the inner life of children was deadly serious to them," Greenwald said.

Per the pamphlet, there were nine steps for translating into Freddish:

1. "State the idea you wish to express as clearly as possible, and in terms preschoolers can understand." Example: It is dangerous to play in the street. ​​​​​​
2. "Rephrase in a positive manner," as in It is good to play where it is safe.
3. "Rephrase the idea, bearing in mind that preschoolers cannot yet make subtle distinctions and need to be redirected to authorities they trust." As in, "Ask your parents where it is safe to play."
4. "Rephrase your idea to eliminate all elements that could be considered prescriptive, directive, or instructive." In the example, that'd mean getting rid of "ask": Your parents will tell you where it is safe to play.
5. "Rephrase any element that suggests certainty." That'd be "will": Your parents can tell you where it is safe to play.
6. "Rephrase your idea to eliminate any element that may not apply to all children." Not all children know their parents, so: Your favorite grown-ups can tell you where it is safe to play.
7. "Add a simple motivational idea that gives preschoolers a reason to follow your advice." Perhaps: Your favorite grown-ups can tell you where it is safe to play. It is good to listen to them.
8. "Rephrase your new statement, repeating the first step." "Good" represents a value judgment, so: Your favorite grown-ups can tell you where it is safe to play. It is important to try to listen to them.
9. "Rephrase your idea a ﬁnal time, relating it to some phase of development a preschooler can understand." Maybe: Your favorite grown-ups can tell you where it is safe to play. It is important to try to listen to them, and listening is an important part of growing.

[cite:@kingMisterRogersHadSimpleSetRulesTalkingChildren2018]
#+end_quote

* Flashcards
** {{[[id:99e14785-13bb-420c-b0b5-b14bad1bd163][Freddish]]}@0} is the language {{[[id:f95aa4a2-494d-49e9-aa6f-6bcd0e3e759f][Fred Rogers]]}@1} would use when speaking with children :fc:
:PROPERTIES:
:FC_CREATED: 2022-10-17T16:11:54Z
:FC_TYPE:  cloze
:ID:       5af6cca6-cc51-4c9d-ae6e-ffef40ccf37a
:FC_CLOZE_MAX: 2
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.65 |   7 |   255.06 | 2023-12-09T04:37:49Z |
|        1 | 3.10 |   7 |   440.64 | 2024-10-12T06:25:50Z |
:END:

*** Source
[cite:@kingMisterRogersHadSimpleSetRulesTalkingChildren2018]
** Definition :fc:
:PROPERTIES:
:CREATED: [2022-10-17 Mon 09:09]
:FC_CREATED: 2022-10-17T16:11:08Z
:FC_TYPE:  double
:ID:       77f60a94-7ab7-4c17-b3eb-8387eaff82f8
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.50 |   7 |   231.39 | 2023-12-16T23:40:46Z |
| back     | 3.10 |   6 |   168.39 | 2023-07-31T23:30:02Z |
:END:

[[id:99e14785-13bb-420c-b0b5-b14bad1bd163][Freddish]]

*** Back
A set of language patterns for talking with children which anticipates and protects against the ways in which the listener (the child) might misinterpret the intended message.
*** Source
[cite:@kingMisterRogersHadSimpleSetRulesTalkingChildren2018]
** Example(s) :fc:
:PROPERTIES:
:CREATED: [2022-10-17 Mon 09:12]
:FC_CREATED: 2022-10-17T16:12:51Z
:FC_TYPE:  double
:ID:       a46a3db4-3948-4c8b-9978-feb3e19f3e13
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 1.60 |  10 |   136.43 | 2023-12-10T01:21:12Z |
| back     | 2.80 |   7 |   363.73 | 2024-06-23T11:22:42Z |
:END:

[[id:99e14785-13bb-420c-b0b5-b14bad1bd163][Freddish]]

*** Back
- It is dangerous to play in the street -> Your favorite grown-ups can tell you where it is safe to play.
*** Source
[cite:@kingMisterRogersHadSimpleSetRulesTalkingChildren2018]
** The purpose of {{[[id:99e14785-13bb-420c-b0b5-b14bad1bd163][Freddish]]}@0} is to {{anticipate and protect against the ways in which a child may misinterpret the intended message}@1} :fc:
:PROPERTIES:
:CREATED: [2022-11-06 Sun 14:02]
:FC_CREATED: 2022-11-06T22:04:24Z
:FC_TYPE:  cloze
:ID:       6495f808-8b40-4801-a254-391723836bad
:FC_CLOZE_MAX: 1
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.65 |   7 |   251.93 | 2023-12-17T14:01:05Z |
|        1 | 2.20 |   7 |   197.56 | 2023-11-20T07:11:31Z |
:END:

*** Source
[cite:@kingMisterRogersHadSimpleSetRulesTalkingChildren2018]
#+print_bibliography: