:PROPERTIES:
:ID:       47895906-e123-4c10-ae95-c073abcf0c58
:LAST_MODIFIED: [2024-02-21 Wed 09:32]
:END:
#+title: Get out of your own way
#+hugo_custom_front_matter: :slug "47895906-e123-4c10-ae95-c073abcf0c58"
#+author: Cash Prokop-Weaver
#+date: [2024-02-06 Tue 11:08]
#+filetags: :concept:

Employ effective strategies to achieve your goals. This includes strategies and techniques which you may initially resist incorporating.

It is difficult to embrace these strategies because they are not currently a part of you and embracing them means changing some of who you are and how you see yourself. You may see some of these strategies as above you or beneath you, or for someone else but not for you. As an example: I have fallen into [[id:9ed16182-a4a5-4bf6-a5c7-b6196c6eca97][Smart guy productivity pitfalls]] for most of my life. I got on easily in school up until college and only now am really learning the discipline of sitting down, studying and confronting something that I want to do and that doesn't come easily.

You don't have to incorporate any of these strategies. The point is to look at them dispassionately, or at least less-passionately, rather than relying on gut reactions.

- Avoiding effective behaviors/techniques/strategies because they're are 'not for you' becau
  - don't align
- Labeling effective behaviors/techniques/strategies as off-limits (e.g. exaggerating contact to draw a foul in football (soccer)) or above/below you
- Requiring yourself to adhere to ineffective behaviors/strategies/techniques (e.g. never lie)
- Rejecting treatment for mental health conditions due to pride/etc

* Regarding acquiring power

#+begin_quote
People who see power as evil or dirty may abjure power and be unwilling to "play the game." [...]

[...] Different people are willing to do different things in order to succeed. Just because you won't network, or flatter, or self-promote, certainly does not mean that all of your competitors will be as circumspect. To the extent people opt out of doing things their colleagues are willing to do—tactics that build power—they put themselves at a disadvantage.

The fundamental point: everyone has choices, not only about how they think of themselves, but about what they are willing or unwilling to do in the contest for power. You can opt in, or out. You can self-handicap, or, like Christina Troitino, "play the game very differently."

[cite:@pfefferRulesPowerSurprisingTrueAdviceHowGetThingsDoneAdvance2022]
#+end_quote

* Related

- [[id:fb16dedc-15d0-418a-83e2-0ed84e5e2504][Just do it]], [[id:630c804a-cef5-42e6-a168-5a233a0acbed][Just start]]
- [[id:30450600-cc69-4beb-9560-c7721a04ecee][Minimum viable product]]
- [[id:eebb69ec-4bef-46e2-bf45-2b828fd9910a][Lie, sometimes]]

* Flashcards :noexport:
** Describe :fc:
:PROPERTIES:
:CREATED: [2024-02-11 Sun 12:23]
:FC_CREATED: 2024-02-11T20:26:51Z
:FC_TYPE:  double
:ID:       ca6084f5-ba61-4bbe-ab61-5636f38991e1
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.50 |   3 |     6.00 | 2024-02-25T21:52:13Z |
| back     | 2.50 |   2 |     2.00 | 2024-02-23T17:32:14Z |
:END:

[[id:47895906-e123-4c10-ae95-c073abcf0c58][Get out of your own way]]

*** Back

Employ effective strategies to achieve your goals. This includes strategies and techniques which you may initially resist incorporating.

*** Source

* Bibliography
#+print_bibliography:
