:PROPERTIES:
:ID:       91b8022c-c5ab-4305-8185-f0daab8b3e42
:LAST_MODIFIED: [2023-12-26 Tue 12:23]
:END:
#+title: How to become an expert
#+hugo_custom_front_matter: :slug "91b8022c-c5ab-4305-8185-f0daab8b3e42"
#+author: Cash Prokop-Weaver
#+date: [2023-12-26 Tue 12:01]
#+filetags: :concept:

What's the most effective way for one to become an expert in a subject?

The answer depends on the subject matter. For subjects with a "long history of well-established pedagogy" [cite:@chinWhyTacitKnowledgeMoreImportantDeliberatePractice2020] (e.g. [[id:4c407900-03c1-40f0-85c6-9852da004f16][math]], music, and chess): you can use [[id:a1d74568-61f0-4a01-8aab-184d1b7a9752][Deliberate practice]].

However, that's [[id:f7eeed27-4fdb-4ebc-8ac0-8b2c2e58dcbb][not an effective method]] for developing expertise for other subjects (e.g. business, sales, sport, art, singing, writing, poetry, etc). For these subjects: focus on [[id:2bb656cd-6834-4534-95e2-c77df28ffccb][Purposeful practice]] and acquiring [[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Tacit knowledge]].

[[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Tacit knowledge]] is the "between-the-lines" know-how. It's what separates proficient individuals from experts. Traditionally it's acquired by doing the relevant thing for a long time.

Can we accelerate the acquisition of tacit knowledge? Yes!

Expertise, and tacit knowledge by extension, boils down to [[id:b481f4e5-63b4-4455-8406-49825121b06c][pattern matching]], specifically [[id:4a42aa6f-413f-4144-86df-5c0f0b174777][Recognition-primed decision]] making via a mental library of [[id:30cb897f-4ec4-4492-b23a-ac760ed49db2][Frames]]. [[id:ba1c4d11-bcfa-4844-b65e-2c59fe7a9422][Improve]] by working through simulations ([[id:c8308617-539e-4933-adf1-9b6aab7cb714][Prefer simulations that already exist]]) or real-world experience (e.g. apprenticeship / on-the-job experience). When necessary, use [[id:31152f53-1769-454c-be11-643a5405eb5d][Applied cognitive task analysis]] to extract expertise from specific experts.

* Flashcards :noexport:

* Bibliography
#+print_bibliography:
