:PROPERTIES:
:ID:       07e3fd1d-8aa7-4fe4-9a65-bf10654c9552
:ROAM_REFS: [cite:@HungerStone2022]
:LAST_MODIFIED: [2023-07-07 Fri 17:17]
:END:
#+title: Hunger stone
#+hugo_custom_front_matter: :slug "07e3fd1d-8aa7-4fe4-9a65-bf10654c9552"
#+author: Cash Prokop-Weaver
#+date: [2022-10-12 Wed 09:05]
#+filetags: :concept:

#+begin_quote
A hunger stone is a type of hydrological landmark common in Central Europe. Hunger stones serve as famine memorials and warnings and were erected in Germany and in ethnic German settlements throughout Europe in the 15th through 19th centuries.

These stones were embedded into a river during droughts to mark the water level as a warning to future generations that they will have to endure famine-related hardships if the water sinks to this level again. One famous example in the Elbe river in Děčín, Czech Republic, has "Wenn du mich siehst, dann weine" ("[[id:c2eafd89-c3ec-43e8-9e06-f937d2b15073][If you see me, then weep]]") carved into it as a warning.

[cite:@HungerStone2022]
#+end_quote

* Flashcards
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-12 Wed 09:06]
:FC_CREATED: 2022-10-12T16:08:42Z
:FC_TYPE:  double
:ID:       1d679e97-09b5-4ff3-ba55-6beffe37d320
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.20 |   7 |   176.99 | 2023-10-23T14:28:04Z |
| back     | 3.10 |   7 |   392.75 | 2024-08-03T18:16:08Z |
:END:

[[id:07e3fd1d-8aa7-4fe4-9a65-bf10654c9552][Hunger stone]]

*** Back
A type of hydrological landmark common in Central Europe which serve as famine memorials and warnings. Past humans placed the stones into rivers to mark the water level during droughts and communicate the hardships to future generations.
*** Source
[cite:@HungerStone2022]
#+print_bibliography: