:PROPERTIES:
:ID:       61de6a28-e681-45bd-a086-fff5b924354e
:LAST_MODIFIED: [2023-04-30 Sun 11:52]
:ROAM_REFS: [cite:@Integral2023]
:ROAM_ALIASES: "Definite integral" Integration Integral
:END:
#+title: Integral calculus
#+hugo_custom_front_matter: :slug "61de6a28-e681-45bd-a086-fff5b924354e"
#+author: Cash Prokop-Weaver
#+date: [2023-01-18 Wed 07:49]
#+filetags: :concept:

#+begin_quote
In mathematics, an integral assigns numbers to functions in a way that describes displacement, area, volume, and other concepts that arise by combining infinitesimal data. The process of finding integrals is called integration. Along with differentiation, integration is a fundamental, essential operation of calculus [[[id:9dd5be35-ca4c-4c0b-8e1c-57025b2e2ba7][Calculus]]], and serves as a tool to solve problems in mathematics and physics involving the area of an arbitrary shape, the length of a curve, and the volume of a solid, among others.

The integrals enumerated here are those termed definite integrals, which can be interpreted as the signed area of the region in the plane that is bounded by the graph of a given function between two points in the real line. Conventionally, areas above the horizontal axis of the plane are positive while areas below are negative. Integrals also refer to the concept of an antiderivative [[[id:4dafe179-aeb8-4718-9eb8-ac96a27f9a58][Antiderivative]]], a function whose derivative is the given function. In this case, they are called indefinite integrals [[[id:4dafe179-aeb8-4718-9eb8-ac96a27f9a58][Indefinite integral]]]. The fundamental theorem of calculus [[[id:adda1031-550c-4f65-9384-1ee018532adc][Fundamental theorem of calculus]]] relates definite integrals with differentiation and provides a method to compute the definite integral of a function when its antiderivative is known.

[cite:@Integral2023]
#+end_quote

* Flashcards
** Denotes :fc:
:PROPERTIES:
:CREATED: [2023-01-18 Wed 07:49]
:FC_CREATED: 2023-01-18T15:50:19Z
:FC_TYPE:  double
:ID:       5bd49198-a2c3-495b-b457-9bca95326e57
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 3.10 |   6 |   135.43 | 2023-08-14T02:23:59Z |
| back     | 2.95 |   6 |   153.40 | 2023-10-01T04:23:16Z |
:END:

$\int$

*** Back
Integral
*** Source
[cite:@Integral2023]
#+print_bibliography: