:PROPERTIES:
:ROAM_REFS: [cite:@wilksItTimeBuildGood2020]
:ID:       69494a1d-7a68-48d6-87dd-3f664106e9d3
:LAST_MODIFIED: [2023-09-05 Tue 20:17]
:END:
#+title: Isaac Wilks | It's Time to Build for Good
#+hugo_custom_front_matter: :slug "69494a1d-7a68-48d6-87dd-3f664106e9d3"
#+author: Cash Weaver
#+date: [2023-01-10 Tue 14:23]
#+filetags: :reference:

TODO_AUTHOR, [cite:@wilksItTimeBuildGood2020]

* Notes

#+begin_quote
The broad thrust of Andreessen's critique rings true. When we look around us, we see a world littered with the physical and institutional detritus of past failures---with depressingly little to show for any recent action, whatsoever. Political and legal sclerosis grip our governing bodies from the national legislature to city governments, and they smother our ability to build anything at all. The only choice we seem able to make anymore is the choice not to make anything. The American built environment has ossified, preserving our stagnation in amber; those looking to the future now look elsewhere---to science fiction and fantasy, perhaps. It is undeniable that we are undergoing a crisis of will---and that nearly everything around us in America cuts against the impulse to build a future. But is there really capability to do so, strangled by our current system, waiting to be unshackled? And must we somehow transcend politics to unleash it?

If we want to succeed in rebuilding the nation, we will need not just the destruction of existing barriers but the construction of positive political goals. In this light, Andreessen's answer to the question of politics is quite strange. What does it mean to "separate the imperative to build these things from ideology and politics"? One can imagine Bay Area tech entrepreneurs nodding along to this essay, wishing that politics and the pesky state would just leave them alone to BUILD. This would be a fatal mistake.

To be sure, we must circumvent our current political paradigm. Yet this is not a separation from politics /qua/ politics---it /is/ politics. Building a new world is the most political question imaginable. Attempting to ignore the state in order to circumvent it only worsened its dysfunctionality; counterintuitively, it also led to administrative bloat, as a government replete with nonfunctional institutions is [[https://gravitylobby.club/administrationmarkets.html][compelled to expand]] as new problems emerge over time. Attempting to transcend the political with flashy Harvard Business School applied-management techniques and productivity enhancer apps is a surefire way to repeat the stagnation of the 1970s and the substance-free marketing of the 1990s. Silicon Valley must recognize that it is optimized for a dysfunctional national ecosystem, and it is in everyone's interest to realize this and push for broader /societal/ reinvigoration. Short of this, we are rearranging the deck chairs on the Titanic.

To regain the will to build for real, we must first recognize where we chose to give it up in the first place. At the end of the Cold War, still armed to the teeth with ideological weapons to fight the Soviets, we looked out blinkingly over our sprawling empire (also known as "the liberal international order" or "the global economy") and fell on our sword. The doctrines of free trade and market fundamentalism were useful ideological bludgeons against communism, but they also proved just as devastating to our own system when we unwittingly [[https://www.theatlantic.com/magazine/archive/1993/12/how-the-world-works/305854/][turned them against]] ourselves.

As a result, we chose not only to ignore the maintenance of vital production but also to intentionally disintegrate much of our advanced industrial capacity. The heady techno-optimist 1990s saw legions of McKinsey consultants setting about [[https://www.tabletmag.com/scroll/301076/the-coronavirus-didnt-cause-this-crisis-by-itself-mckinsey-helped][touting]] flashy "unbundling" schemes to dismember the supposedly archaic core of American industry. We attempted a total separation of production from the political, in the name of increased consumption and gains from trade. Questions of community well-being or geopolitical interest were waved away or even crushed. Under this ideology, no distinction can be made between a billion dollars in GDP generated from Netflix consumption and a billion dollars in GDP generated by domestic machine tool production. Nor does it permit us to discern which sectors are vital to retain and which can be safely offshored.

Once we finally set about trying to rebuild American industrial capacity, we may be in for a nasty surprise. We might not have the capability anymore to simply turn industry back on. Functional industry requires a great deal of implicit knowledge that is not easily regained once traditions of manufacturing die out—like a master dying before they can find an apprentice to teach. With the material death of advanced heavy industry comes the death of once-functional institutional ecosystems, taking with them to the grave the tacit intellectual code [[[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Tacit knowledge]]] that they run on.

[...]

There has yet to be a post-industrial society that has re-industrialized. America should be the first. But this is a much taller order than applying will to current capacity: we also must rebuild capabilities. Building [[http://www.bismarckanalysis.com/Machine_Tools_Case_Study.pdf][functional industry]] takes massive up-front investment in processes with uncertain payoffs and long time horizons. Silicon Valley VCs may continue to seed new product startups, but when it comes time to produce their products "at scale," these firms are invariably forced to move overseas. Most of these startups are far downstream of industrial fundamentals anyway. Capital's time preference has been far too short to [[https://americanaffairsjournal.org/2019/05/financing-advanced-manufacturing-why-vcs-arent-the-answer/][combat this dynamic]], and there is no reason to believe that it can or should play the primary role. In fact, every single country to industrialize has done so with the [[https://www.palladiummag.com/2020/02/12/how-state-capacity-drives-industrialization/][guidance of the state]], marshaling huge quantities of R&D funding and enforcing strict export discipline to wean the infant industries in which it invests.
#+end_quote

* Flashcards :noexport:
#+print_bibliography: