:PROPERTIES:
:ROAM_REFS: [cite:@somersSpeedMattersWhyWorkingQuicklyMoreImportantItSeems]
:ID:       b98760c3-bcd5-48e4-9434-3bae494f464c
:LAST_MODIFIED: [2024-02-15 Thu 07:25]
:END:
#+title: James Somers | Speed Matters: Why Working Quickly Is More Important than It Seems
#+hugo_custom_front_matter: :slug "b98760c3-bcd5-48e4-9434-3bae494f464c"
#+author: Cash Weaver
#+date: [2024-02-15 Thu 07:17]
#+filetags: :reference:

[[id:14709de3-09b0-4073-8879-0f3be2638790][James Somers]], [cite:@somersSpeedMattersWhyWorkingQuicklyMoreImportantItSeems]

* Summary

* Thoughts

[[id:8b79fc74-135d-42e2-849e-8272619bcd4c][Speed is a virtue]]

* Notes

#+begin_quote
The obvious benefit to working quickly is that you'll finish more stuff per unit time. But there's more to it than that. If you work quickly, the cost of doing something new will seem lower in your mind. So you'll be inclined to do more.

The converse is true, too. If every time you write a blog post it takes you six months, and you're sitting around your apartment on a Sunday afternoon thinking of stuff to do, you're probably not going to think of starting a blog post, because it'll feel too expensive.

What's worse, because you blog slowly, you're liable to continue blogging slowly—simply because the only way to learn to do something fast is by doing it lots of times.

This is true of any to-do list that gets worked off too slowly. A malaise creeps into it. You keep adding items that you never cross off. If that happens enough, you might one day stop putting stuff onto the list.

[...]

The general rule seems to be: systems which eat items quickly are fed more items. Slow systems starve.
#+end_quote

* Bibliography
#+print_bibliography:
* Flashcards :noexport:
