:PROPERTIES:
:LAST_MODIFIED: [2024-02-11 Sun 12:48]
:ROAM_REFS: [cite:@pfefferRulesPowerSurprisingTrueAdviceHowGetThingsDoneAdvance2022]
:ID:       8d42e706-7fa3-4910-a0be-db0fe90083a9
:LAST_MODIFIED: [2024-02-11 Sun 08:44]
:END:
#+title: Jeffrey Pfeffer | 7 Rules of Power
#+hugo_custom_front_matter: :slug "8d42e706-7fa3-4910-a0be-db0fe90083a9"
#+author: Cash Weaver
#+date: [2024-01-22 Mon 19:26]
#+filetags: :reference:

[[id:64117fb2-9e71-4c73-8ff2-78fa053c4d48][Jeffrey Pfeffer]], [cite:@pfefferRulesPowerSurprisingTrueAdviceHowGetThingsDoneAdvance2022]

* Summary

Power comes from playing [[id:0fd22b02-281f-4a62-b60d-eded1a423c79][The game]]. The ability to play the game comes from [[id:a1d74568-61f0-4a01-8aab-184d1b7a9752][practice]].

** Rules

1. [[id:47895906-e123-4c10-ae95-c073abcf0c58][Get out of your own way]]

2. [[id:94fabbea-ffeb-439e-bde8-9a52044bde20][Break the rules]]

3. Appear powerful

   [[id:d1fa918e-df74-43e5-b430-211129a3208e][Act the part]]. Behave in a way that others interpret as powerful. First impressions matter. Others will judge you on your appearance, use of language, behavior, body language, and what/who surrounds you (just to name a few). Also, pessimistically: con artists are effective, so study and incorporate their techniques.

4. Build a powerful [[id:11f248cb-2349-4824-aeaa-6a6b207554f5][brand]]

5. [[id:cb6b4e1a-d2d9-4316-99ae-252d8a481526][Network]] relentlessly

6. Use your power

   #+begin_quote
1. [W]hen a person is new in a position, they have time, before their opponents get a chance to coalesce, and while the incumbent is in sort of a honeymoon period, to get a lot done. This includes actions that will help perpetuate their power on the basis of their accomplishments and the changes they make to institutionalize their power.
2. [E]nemies tend to last longer and keep grudges more than friends remember favors. This means that, practically speaking, the longer someone is in a position, the more opposition they will accumulate, the more precarious their position will become, and the more difficult it will be to get things done. Thus, because their time in a powerful role will be limited, people need to act quickly to accomplish their agenda.
3. [[[id:80e39a91-d5f4-4438-af08-64121eff1695][Power begets power]]]

Formatting mine
#+end_quote

   Note that the beginning is also the time at which you have the fewest allies. [[id:753694c8-448a-4d28-82f8-ca3b2829db08][Bring in supporters and move out opponents]] to improve your position.

7. [[id:806396b3-e360-4c3d-a37c-b8f3b94cdb54][Success excuses (almost) everything]]

** On practicing the rules

#+begin_quote
The [...] advice: learn about power, and then relearn what you have learned again and again, because the material, while easy to understand, is apparently more difficult to implement than it should be

[...] as [Pant] said to me, "What you are asking us to do is unnatural—it goes against how we were raised and what we have been taught in school. What you are teaching is also inconsistent with what we are regularly told in the ubiquitous—and mostly useless— leadership trainings and books that mostly describe how people want the social world to be, rather than the empirical regularities that explain what actually works to build power and get things done." As implied by the writing of Machiavelli, and by understanding the social science of human behavior, as one person perceptively noted to me, "Leadership is not a moral pursuit." It is above all about the pragmatics of making things happen.

Doing things that are unnatural, and in some sense counter to conventional wisdom, requires reminders and constant vigilance. That's because, by definition, unnatural behaviors do not come naturally, and are therefore difficult to implement and demand conscious thought and attention.
#+end_quote

The advice directly given within the book boils down to:

- Engage with the material repeatedly; reread the rules and find other ways to bring these concepts to the top of your mind
- Find or build a small network of people with whom you can directly 'doing power'; a personal coach, personal board of directors, or a 'power posse'
- [[id:e1577e03-2bed-4209-b7bf-1399bd9dfc66][Be intentional]]; make lists of what you want to practice and then go and practice it

* Notes :ATTACH:
:PROPERTIES:
:NOTER_DOCUMENT: attachments/8d/42e706-7fa3-4910-a0be-db0fe90083a9/7-rules-power.pdf
:NOTER_PAGE: 185
:END:
** Title Page
:PROPERTIES:
:NOTER_PAGE: (9 . 0.090909)
:END:
** Copyright
:PROPERTIES:
:NOTER_PAGE: (11 . 0.161932)
:END:
** Dedication
:PROPERTIES:
:NOTER_PAGE: (12 . 0.185606)
:END:
** Contents
:PROPERTIES:
:NOTER_PAGE: (13 . 0.229167)
:END:
** In the Beginning: The Challenge of Power
:PROPERTIES:
:NOTER_PAGE: (14 . 0.230114)
:END:

#+begin_quote
I regularly suffer a form of what might be called intellectual whiplash. On the one hand, people—even a good friend and insightful editor—tell me my ideas about power don't fit the prevailing zeitgeist with its emphasis on collaboration, being nice, and enacting politically correct behavior. On the other hand, I get emails like the one from an individual enrolled in my online class on power. That person told me and his classmates that he learned that performance is not enough. Rather, he now knew he had to ask people in power in his company for what he wanted and needed to advance his career and achieve his job objectives and to flatter higher-ups; to believe in himself and act and speak with power; to build a network and support system; and, when confronting opposition and conflict, to be smart in how and when to fight his battles.
#+end_quote

Lamp-shading the complaints from those who espouse [[id:01a5a051-57c8-4d55-aca3-6da89521f5b9]['Nice' power]] against this book's subject: [[id:fd2773ca-e019-4712-a69a-6645e9d24c9b]['Mean' power]].

** Introduction: Power, Getting Things Done, and Career Success
:PROPERTIES:
:NOTER_PAGE: (24 . 0.230114)
:END:

- "...power is a tool."
** Rule 1 | Get Out of Your Own Way
:PROPERTIES:
:NOTER_PAGE: (39 . 0.230114)
:END:

#+begin_quote
How people think of themselves invariably influences what they project to others and what behaviors they will enact. The lesson: use self-descriptive adjectives that convey power, and eschew attitudes that, even if accurate, fairly or unfairly, diminish your status.
#+end_quote

#+begin_quote
Getting over imposter syndrome [[[id:0bca32c4-f7f9-416a-ab73-75025a933a36][Impostor syndrome]]] is a first step on a person's path to power.
#+end_quote


*** Be willing to do whatever it takes --- don't run away from power
:PROPERTIES:
:NOTER_PAGE: (45 . 0.270979020979021)
:END:

#+begin_quote
People who see power as evil or dirty may abjure power and be unwilling to "play the game."
#+end_quote

#+begin_quote
Different people are willing to do different things in order to succeed. Just because you won't network, or flatter, or self-promote, certainly does not mean that all of your competitors will be as circumspect. To the extent people opt out of doing things their colleagues are willing to do—tactics that build power—they put themselves at a disadvantage.

The fundamental point: everyone has choices, not only about how they think of themselves, but about what they are willing or unwilling to do in the contest for power. You can opt in, or out. You can self-handicap, or, like Christina Troitino, "play the game [[[id:0fd22b02-281f-4a62-b60d-eded1a423c79][The game]]] very differently."
#+end_quote

#+begin_quote
An important part of being "willing to do what it takes" is sticking with efforts to build power and get things done in the face of opposition, criticism, obstacles, setbacks, and failures.
#+end_quote

See [[id:b08bf4f7-76cd-41e9-973f-83d2a60de9aa][Grit]].

*** How low power perpetuates itself
:PROPERTIES:
:NOTER_PAGE: (48 . 0.47596153846153844)
:END:

#+begin_quote
Belmi and Laurin identified two prototypical ways of achieving power. One is through behaving in a prosocial fashion such as working hard, helping coworkers, and striving in other ways on behalf of the collective good. The other is through politics— basically what I teach—which entails behaving strategically, flattering higher-ups, building helpful social relationships, and promoting one's accomplishments (the subject of chapter four, taking credit as you build a strong personal brand). They found no difference by class in people's beliefs about the usefulness of the two strategies—all people, regardless of their social origins, generally believed that both approaches were helpful. However, they uncovered class differences in people's willingness to actually use the two strategies, with people from lower social-class origins being much less willing to use political strategies.

[...]

Peter Belmi believes that one (but not the only) reason social class predicts willingness to use political-power-seeking behaviors is that there is considerable evidence that lower social class is associated with a more collective versus an individualistic orientation.
#+end_quote

#+begin_quote
Some people argue that this line of argument "blames the victim" as these biases and stereotypes should not exist and people's preferences for power should not determine their career trajectories. My position, and Belmi's and Hewlett's, is that while the stereotypes and biases they represent are manifestly unfair and unjust, they exist with varying degrees of pervasiveness in many if not most organizations. Moreover, the only behavior individuals have any hope of truly controlling is their own. Therefore, the best way for people to achieve higher-level positions where they might have the leverage to change things is to recognize the rules of the game and understand what they need to do to succeed in the environment as it is presently constituted, even as they work to change that environment. And, most importantly, not to let assumptions arising from their gender, race, or social class interfere with or constrain their own definitions of who they are or what behaviors are permissible. To succeed, people need to be and feel agentic, and attempt to exercise influence and control.
#+end_quote

*** The curse of authenticity
:PROPERTIES:
:NOTER_PAGE: (53 . 0.5965909090909091)
:END:

#+begin_quote
One reason people get in their own way as they reject implementing empirically demonstrated findings on the determinants of power is their embrace of the idea of authenticity and other scientifically sketchy but uplifting leadership ideas. In their quest to be their authentic selves and display their real feelings and true opinions to others, people tell me that engaging in activities such as networking, flattering those in power, spending time ensuring that others know of their accomplishments, asking for resources, or presenting themselves to the world in a powerful fashion would not be true to who they really are. Because these behaviors often inherently entail behaving strategically in their interactions with others, building power might require people to behave inauthentically.
#+end_quote

[[id:eebb69ec-4bef-46e2-bf45-2b828fd9910a][Lie, sometimes]]

#+begin_quote
One argument for being authentic I sometimes hear is that if you are not, your attempts at deception—for instance, flattering others or providing inaccurate information about your own motives—will be discerned, and others will hold your efforts to be anything other than your true self against you. Although a nice idea, there is precious little logic or evidence to support it.

First, people believe—and see—what they want [[[id:b1a664cb-c661-4c44-bf55-fc407c528ad1][Wizard's first rule]]]. [...]

Second, the empirical evidence on uncovering lies consistently reveals that people are largely terrible at this task.
#+end_quote

#+begin_quote
Phrases like "Be true to yourself" and "Find your own true north" seem excessively self-referential and are not what leaders must do to succeed. Leaders need allies and supporters; one of the primary tasks of a leader is to recruit both. This task is more readily accomplished if the leader is true not to themselves but instead to the needs and motivations of those they seek to recruit.

[...]

If you want to have allies—always a good thing if you want influence— you obviously need to provide others with something so they will support you. [...] If you want others to support you, you need to be able to answer the question: What's in it for them if they do?
#+end_quote

Align [[id:deb3b467-3bb1-4000-9665-3a7347909ad6][Incentive]] structures such that what's good for them is also good for you.

*** The paradox of "Likability"
:PROPERTIES:
:NOTER_PAGE: (58 . 0.5131118881118881)
:END:

It's impossible to make everyone like you, by definition. Doing X will offend those who want you to do Y, or Z, or just not-X. Thus, seeking 'likability' while pursuing power puts you at best at a disadvantage and at worse out of the running entirely.

#+begin_quote
[...] The first rule of power is about acknowledging and accepting who you are but not letting that identity define who you will be forever. It is about understanding the importance of social connection but not letting the need for acceptance overwhelm what you want to get done, and the necessity of pursuing your own interests and agenda. It is, in short, about getting out of your own way and getting on with the task of building the power base that will provide you the leverage to accomplish your goals.
#+end_quote

*** Exercises

1. How do you describe yourself?

   #+begin_quote
Write down the adjectives you use to describe yourself, both to yourself and to others. Check with friends to see if your list is correct. Then ask yourself what descriptors you need to get rid of in order to project yourself in a more powerful way. Ask yourself what positive adjectives about yourself—language that gives credit to your accomplishments and credentials—you underutilize in your interactions with others.

[cite:@pfefferRulesPowerSurprisingTrueAdviceHowGetThingsDoneAdvance2022]
#+end_quote

2. [[id:9fbce18e-0a25-4876-a2e8-96acb60caab8][Record yourself]]

3. How do you diminish yourself?

   #+begin_quote
As you describe yourself to others, as you articulate a narrative of your career so far, as you create a personal brand—a topic we will explore in more detail in Rule 4— do you talk about your accomplishments, your credentials, or what you have done successfully? Or do you attempt to appear modest and self-effacing, downplay your achievements, positions you have held, honors you have achieved, and your talents?
#+end_quote
** Rule 2 | Break the Rules
:PROPERTIES:
:NOTER_PAGE: (62 . 0.230114)
:END:

- [[id:ee79bad4-e57f-4b59-973f-5a2ccc6fd0f8][It's better to ask forgiveness than permission]]

*** Why and how rule breaking works to create power
:PROPERTIES:
:NOTER_PAGE: (65 . 0.11013986013986014)
:END:

1. People associate powerful people with rule-breaking behaviors, so engaging in rule-breaking behaviors can make people think you're powerful

   #+begin_quote
[...] This heuristic association between power and rule breaking—the powerful are freer to defy social norms and conventions and get away with it, and thus, powerful people are more likely to enact socially inappropriate behavior—prompted University of Amsterdam–based social scientist Gerben van Kleef and colleagues to ask if breaking rules could actually cause the rule breakers to seem more powerful. In a series of experimental studies using multiple methods, including a scenario, a film clip, and face-to-face interaction, the answer was "yes."
#+end_quote

   Related: [[id:c5b4e591-7690-49b6-94cb-ab4ab54b68a6][Cargo cult]], [[id:d1fa918e-df74-43e5-b430-211129a3208e][Act the part]]

2. Breaking rules is a surprising behavior; it makes you stand out

   #+begin_quote
Okay, what works? Going to the top works... Everybody in between doesn't matter.

/Jason Calacanis/
#+end_quote

3. [[id:ee79bad4-e57f-4b59-973f-5a2ccc6fd0f8][It's better to ask forgiveness than permission]]

4. Rules reinforce existing power dynamics

   #+begin_quote
[...] rules and norms tend to favor those with the power to make them—who tend to be the entities in power. Why play by rules others have made that may disadvantage you?
   #+end_quote

#+begin_quote
Here's the difficulty in the advice to disregard rules and social expectations. [...] People like to play by the rules, regardless of the results. [...] Asymmetric warfare and unconventional strategies may bring success and power, but to break
the rules, people need to be able to stand the resulting social disapproval.
#+end_quote

*** The dilemma: To fit in or stand out
:PROPERTIES:
:NOTER_PAGE: (72 . 0.3995656894679696)
:END:


People want to fit in, but also they want to be distinct.

*** Break the rules by asking for things
:PROPERTIES:
:NOTER_PAGE: (73 . 0.8496199782844734)
:END:

People like to help. Ask for help and you'll get it. It'll work more often than you think, so get over your apprehensions.

*** Rule breaking and change
:PROPERTIES:
:NOTER_PAGE: (76 . 0.8398479913137894)
:END:

#+begin_quote
To follow rules and adhere to social expectations that disadvantage you in your path to power is to consign yourself to unduly limited opportunities and prospects. Thus, for those who seek power, particularly those seeking it from positions of disadvantage, breaking the rules is the only possible, sensible option. Simply put, if you are going to win given the rules in place, by all means follow and advocate for those rules. For everyone else less guaranteed of inevitable success, rule breaking [...] provides an empirically validated — and virtually the only feasible — path to success.
#+end_quote

** Rule 3 | Appear Powerful
:PROPERTIES:
:NOTER_PAGE: (79 . 0.230114)
:END:


#+begin_quote
[...] if you want to attain and maintain power [...:] appear powerful, because others will treat you and make decisions about you depending on how you show up, and those decisions will often act in ways to make the initial impressions become true.
#+end_quote

#+begin_quote
The first recommendation about showing up in a powerful way: don't use notes or a lot of other props or cues, particularly things that would cause you not to make eye contact with the person or people you are speaking with.
#+end_quote

#+begin_quote
As I make clear in this chapter, language—and body language—matters for how others judge us, and those judgments have consequences.
#+end_quote

#+begin_quote
Certain emotional displays convey strength; others do not. Therefore, it is important to convey powerful emotions and avoid expressing those that signal lower status. In this regard, many people find it counterintuitive that anger is a powerful emotion and that displaying it is often a smart power move—even when, or possibly particularly when, someone has made a mistake or has been uncovered in some malfeasance. By contrast, expressing sadness or remorse and apologizing conveys much less power— and therefore should be avoided under conditions when appearing powerful and competent is important, which is more frequently than most people think.

[...]

Social psychologist Larissa Tiedens noted that "people expressing anger are seen as dominant, strong, competent and smart" and that "people believe individuals with angry facial expressions occupy more powerful social positions than do individuals with sad facial expressions."
#+end_quote

[[id:f331c0a1-39b2-4752-84a9-f9656d1750c5][Never play defense]]

Paraphrasing a good chunk: Con men are effective. Don't embody them but do study and understand /why/ they're effective so that you can use those techniques toward better ends.

Signal power with body language:

- Gesture more
  - Use controlled arm and hand gestures
- Hold an open body posture
- Place yourself closer to others; have less interpersonal distance
- Speak loudly
- Interrupt others
- Speak more than others
- Hold others gazes

Signal power with speech:

- Speak [[id:d65fac7a-c0e4-4f53-95f2-71d7343dc0cf][plainly]] (specifically: lower on the Flesch-Kincaid scale) and simply (conceptually simple)
- Don't use qualifications (e.g. "perhaps", "sort of", "kind of")
- Repeat yourself
- Don't use hesitation words/sounds (e.g. "um", "er")

** Rule 4 | Build a Powerful Brand
:PROPERTIES:
:NOTER_PAGE: (98 . 0.230114)
:END:

#+begin_quote
[...] "in order to succeed at a fund, you need to do the best deals possible. In order to do the best deals possible, you need to maximize your chances of actually seeing those deals. There's only so much you can do one on one, and brand felt like an incredible way of marketing, where you were able to be top of mind for people."
#+end_quote

A brand can give you more opportunities. More people can hear of or interact with your brand than can interact with you directly. Then you can select the most promising interactions for follow-ups.

#+begin_quote
One way to build a powerful brand is to associate with other people and organizations that are themselves prestigious.
#+end_quote

#+begin_quote
Chau had started a podcast called WoVen, which stands for Women Who Venture. The podcast gave her "the opportunity and the right to ask women who were very senior in their careers or founders of public companies to talk for an hour." Because most people said yes to her invitations, Chau expanded her network strategically and significantly. [...]

Chau not only used her podcast to connect with and become associated with prominent others, she also blogged regularly about topics that portrayed her as a thoughtful investor in the consumer space. She wrote a chapter for a book, a long-form thesis on social media. She commented that she was the only person to help get speaking gigs for the author's book tour. She notes that the writing made it possible for her to come across as someone founders should talk to, "instead of 'Hey, I'm this random woman, Laura, at some random venture fund, and you should talk to me about your next round of fundraising.'"

Chau began running panels of about twenty people. "I'll pick a topic I'm trying to get smarter on," she says. "Then I'll find three senior operators, and I'll ask them to be a panelist. It's a way for me to build my network of operators, and then I'll go invite the twenty founders that are building companies in this space that I want to meet. In the panel, I get all of this content from the founders and the operators who are much more expert than I am, and develop it into a blog post I can put out."

Chau also published a newsletter, called Taking Stock, that was opt-in for anyone she emailed with or who came to any of the events that she hosted. She uses the newsletter "as a way to stay loosely connected with the tech community." In it she shared resources, selected blog posts she wrote, and used it as a channel for feedback and nominations for people to attend her events. In 2021, Chau launched a weekly Clubhouse show called Hot Deal Time Machine, in which she did retrospectives on some of the hottest VC-backed deals. In her conversations with the founders and the VCs who backed them, she sought to learn from their experience. As she noted in an email to me, "It's been a fun way to build an audience on a new platform while building relationships with the guests on the show. I've also been documenting the highlights from the conversations in my newsletter."

The podcast, the newsletter, the Clubhouse show, the blogging, the panels, and the conference appearances all helped Chau develop a presence in the venture community. "By being out there and having this kind of brand, it makes it much easier for people to then say, 'Come on my podcast,' or 'Will you sit on this panel, or do this keynote?' There's sort of this circuit of speakers where I think people just look at who spoke at the last conference and then invite them to their conference. It's the ones that people tend to see. So once you're in the circuit, you can stay on the circuit, and reach a much broader audience."

Chau nicely described the many aspects of the flywheel effect [[[id:160f50d0-4d35-4f2b-b1ab-f6b6da5a7902][Flywheel effect]]] of personal branding—how one thing led to another, [...]
#+end_quote

[[id:361bcdb6-86e6-47e4-8262-5ebbca46cb6e][Create positive feedback loops]]

- Have a narrative --- and tell it repeatedly

  #+begin_quote
A brand needs coherence. At its best and most effective, a brand brings together aspects of someone's personal and professional life in a way that makes it clear why they are uniquely qualified for some position or to found a company in a particular industry. [...]

[...]

Everyone needs a brand. Your task: think of a short (two-or three- sentence) way of describing yourself and your accomplishments that brings together your expertise, your experience (what you have done), and a way of integrating that with some aspect of your personal story. [...]

Once you develop a brand statement, get feedback on it from professional colleagues and friends [[[id:6a2ada0e-607b-419c-8137-cfd7fa113bfe][Seek out feedback and accept with gratitude]]]. And then think about how you are going to get that message out into the world.
#+end_quote

  1. "[...] Mark Twain's axiom "that a lie will go halfway around the world in the time it takes the truth to put on its shoes."
  2. "[get] your side of the story out early and often. Once impressions are formed, they are more difficult to change."

- Develop a 'look'

  #+begin_quote
The idea of using clothes and physical appearance as part of branding is not a new or unique idea, but that does not make it any less important.
#+end_quote

- Do as many things as possible to become known

  Increase the likelihood that someone will interact with your brand and therefore see you in the way that you want them to see you.

  [[id:64117fb2-9e71-4c73-8ff2-78fa053c4d48][Pfeffer]] recommends: speaking (podcasts, conferences) and writing (books, blogging, op-eds/articles).

- Cultivate the media

  Behave in such a way that others (media) will amplify your brand.

- Stand out by being appropriately controversial

  Controversial behavior attracts attention which you can leverage.

- Leverage prestigious affiliations whenever possible

- Take credit for your work; craft a narrative around it

  #+begin_quote
Part of brand building and creating a positive reputation is ensuring that you get credit for your work. That entails being willing to tell your story and eschewing any false sense of modesty or the belief that your work will speak for itself. Your bosses and colleagues are busy and often focused on their own objectives. Don't expect them to necessarily notice or credit your accomplishments.
#+end_quote

- Be willing to tell your story

  #+begin_quote
Many people, particularly women or those raised in cultures that inculcate the value of modesty, are reluctant to engage in what feels like self- promotion. The problem is that if you don't tell your story, you cannot be sure that anyone else will, either, or whether others in the organization will see what you have accomplished.
#+end_quote

** Rule 5 | Network Relentlessly
:PROPERTIES:
:NOTER_PAGE: (117 . 0.230114)
:END:

[[id:64117fb2-9e71-4c73-8ff2-78fa053c4d48][Pfeffer]] highlights case studies of individuals (Omid Kordestani, Ross Walker, Keith Ferrazzi, Jon Levy) who, by having an extensive network, have found (or have had others appaorch them with) opportunities they would not have otherwise found.

#+begin_quote
Humans are social creatures, so most people do spend some of their free time interacting with others. The problem from the standpoint of Rule 5 is that much of this interaction is with family and friends, not with bosses, colleagues from work, or others who might be professionally useful. [...] [P]eople should spend eight to ten hours a week building professional relationships because "the secret to getting more business through networking is ... spending more time doing it!"
#+end_quote

*** Fundamental networking principles
:PROPERTIES:
:NOTER_PAGE: (126 . 0.8409337676438654)
:END:

1. Pursue your 'weak ties'

   #+begin_quote
[...] people to whom one is strongly tied are likely to be strongly tied to each other, and therefore share mostly the same information, contacts, and perspectives. People to whom one is weakly tied are more likely to tap into different sources and social circles, and are therefore more likely to be able to provide non-redundant information and contacts. This non-redundant information has higher value because of its greater novelty.
#+end_quote

2. Become a broker

   #+begin_quote
[A broker] bring[s] together parties who could profitably benefit from interacting with or knowing each other.

[...]

[...] networking cannot be subcontracted to others. To obtain the benefits of networks and structural position, a person has to be in a favorable spot—and must do the work to get there themselves.
#+end_quote

3. Be central

   #+begin_quote
Centrality affects visibility. More people will know and know about people who are more central, and that visibility will often work to those people's advantage for becoming the focal point for information and opportunities. Centrality also affects access to information. The first network studies demonstrated that people in central positions saw more information—because more communication flowed through them—and had greater direct contact with more people. The implication: when people evaluate jobs and roles, one dimension they should account for is the centrality that will accrue to them from occupying that job or position. Other things being equal, choose more central jobs.
#+end_quote

   Brokering connections between people is a central position.

4. Create value for others

   #+begin_quote
Last, be sure to create value for others—or why would people want to be connected to you? Sometimes this idea is described as being generous. I would describe it slightly differently: as putting yourself in the other's place, having some empathetic understanding of where they are coming from and what challenges they face, so that you can provide help reasonably easily and effectively. Help taps into the norm of reciprocity— the idea that favors create an obligation for some form of repayment later on. Help also binds people together through liking; people like those who help them more than those that don't. And providing value to others through social relationships transforms networking from something dirty or transactional to something viewed much more positively by everyone, including the networker. It is now more about serving and being of service to others.
#+end_quote

*** Networking time management
:PROPERTIES:
:NOTER_PAGE: (132 . 0.11292073832790446)
:END:

#+begin_quote
Technology can help. People are used to "checking in" and updating others using email and social networking sites such as LinkedIn and Facebook. They're probably not as good as a more personal connection, but as a way of keeping in touch, better than nothing. You can also use various relationship management software to keep track of who you have been in touch with and which contacts are growing stale and need renewal. It is important to recognize that sustaining a relationship, particularly a weak tie, does not require intense or deep connections. Casual updates, sharing an interesting article about a topic of mutual interest, or letting people know you are thinking about them is often sufficient.
#+end_quote

#+begin_quote
[...] successful people allocated their time in a particular way: they spend more time with those on the periphery than at the center, more time on people distant than on those who were close.
#+end_quote

#+begin_quote
Consider how you spend your time, maybe by looking at your calendar, asking others, or some combination. Are you devoting enough time to building social relationships and engaging in social interactions? And with whom are you spending your time? Are you building brokerage relationships—connecting people or organizations who could benefit from such connections? Are you associating often enough with high-status others? Are you spending your time in professionally useful ways, at least on occasion?
#+end_quote

** Rule 6 | Use Your Power
:PROPERTIES:
:NOTER_PAGE: (135 . 0.230114)
:END:
#+begin_quote
1. [W]hen a person is new in a position, they have time, before their opponents get a chance to coalesce, and while the incumbent is in sort of a honeymoon period, to get a lot done. This includes actions that will help perpetuate their power on the basis of their accomplishments and the changes they make to institutionalize their power.
2. [E]nemies tend to last longer and keep grudges more than friends remember favors. This means that, practically speaking, the longer someone is in a position, the more opposition they will accumulate, the more precarious their position will become, and the more difficult it will be to get things done. Thus, because their time in a powerful role will be limited, people need to act quickly to accomplish their agenda.
3. [... P]ower is not some scarce, limited resource that becomes depleted by being used. Instead, the more someone uses their power to get things done—including structuring the world around them and changing who works with and for them in ways that support themselves and their objectives—the more power they will have. Using power signals that you have it, and because people are attracted to power, the more you use your power and demonstrate that you are powerful, the more allies you will accumulate. Therefore, Rule 6 is to use the power one has, maybe even using more than people think you have.

Formatting mine
#+end_quote

*** Use power quickly to get things done
:PROPERTIES:
:NOTER_PAGE: (137 . 0.21389793702497287)
:END:

#+begin_quote
Making changes quickly and improving outcomes increases a leader's power because it provides a rationale for others to support them. And using power is often necessary, as organizations are generally beset with varying degrees and forms of inertia, so improvement requires altering existing ways of doing things. Existing people and processes usually have some investment in the status quo, so it requires power to accomplish improvements. Successfully using power to make changes increases the incumbent's power, while waiting to use power or not using it at all leaves the status quo in place, thereby reducing power. Power, used effectively, increases its wielder's power.
#+end_quote

*** Use power to bring in supporters and move out opponents
:PROPERTIES:
:NOTER_PAGE: (140 . 0.28284473398479915)
:ID:       753694c8-448a-4d28-82f8-ca3b2829db08
:END:

#+begin_quote
Replacing people, then, has two positive effects on your power. First, it staffs the organization with people who have aligned perspectives and the competence to execute effectively, and that increased performance will help cement your power. And second, it provides you with allies in situations that are often challenging and politically fraught.
#+end_quote

*** Use power to signal how much power you have --- and your willingness to use it
:PROPERTIES:
:NOTER_PAGE: (144 . 0.19109663409337677)
:END:

#+begin_quote
[...] people want to associate with winners and success.
#+end_quote

#+begin_quote
Because perception helps create reality, wielding power in ways that
demonstrate power, doing things that signal power, helps to ensure that
power will be perpetuated.
#+end_quote

*** Use power to establish structures that perpetuate power
:PROPERTIES:
:NOTER_PAGE: (146 . 0.5488599348534202)
:END:

1. Structure the rules by which you hold power to favor you
2. Be irreplaceable; don't tolerate likely successors
3. Be difficult to remove by integrating yourself throughout the system (e.g. hold multiple related and powerful roles such that removing you from one only reduces rather than eliminates you)

** Rule 7 | Success Excuses (Almost) Everything
:PROPERTIES:
:NOTER_PAGE: (149 . 0.230114)
:END:

#+begin_quote
It was not just Graham who accommodated Trump as the Republican party marched "headlong ... into the far reaches of Trumpism."5 Nor are changes in people's perceptions of others once they have achieved power and renown confined to the realm of politics. Lists of most-admired CEOs often include people who have backdated stock options (Steve Jobs), had relationships outside of marriage with underlings (Bill Gates), violated SEC orders (Elon Musk), had to flee countries to avoid prosecution (Carlos Ghosn), been forced from their jobs over a scandal (John Browne of BP), and were criticized over the work environment for both blue-collar and white-collar employees (Jeff Bezos). The desire to be close to power, almost regardless of how achieved or the wielder's current behavior, implies that people should not fret too much about their path to power. Once power is achieved, everything—well, almost everything most of the time—will be all right.
#+end_quote

*** People worry about the consequences of following the rules of power
:PROPERTIES:
:NOTER_PAGE: (150 . 0.8382193268186754)
:END:

#+begin_quote
Students often describe my course on power as a "forcing function," in that it forces them—sometimes outside their comfort zone—to embark, at least temporarily, on a path to power. Even inviting people to speak in the class has an effect. Deborah Liu, the former senior executive at Facebook who is now CEO of Ancestry, told me that knowing she was coming to the class to talk made her more ambitious in what she was willing to do, so she would have more to talk about.

Many of the self-reflective projects that I use in the course have been described briefly in the relevant chapters of this book. For instance, I ask people to develop a brand that succinctly captures who they are and what they stand for. Class members determine the people to whom they should be connected and then strategize how to forge those relationships, often expanding their network during the course. I ask people to become more comfortable with pushing the rules, and to lose the scripts and self- descriptions that hold them back. I encourage them to practice acting and speaking in a more powerful fashion. These exercises "force" people to think strategically about forging a path to power.

This forcing function, along with providing people the knowledge—and the confidence—that they can actually expand their power, are some of the more important aspects of my teaching. Knowledge and confidence, turned into action by having people develop relevant behaviors, create and change people's actions and get them unstuck. This stimulus to action is important because many people remain fundamentally ambivalent about seeking power, notwithstanding the general acknowledgment that, in most social organizations, power is necessary to get things done.

This ambivalence about seeking power arises partly from the worries people have about acquiring power and what it might take to do so. For instance, people worry about the process of obtaining power. What if their actions offend people? What if they stress the bounds of propriety and push the envelope of social norms?

People also worry about the consequences of becoming more powerful. What if, in their rise to power, they create enemies and rivals of the people they outcompete? What if, as is almost inevitable, their success provokes jealousy and resentment? What if the nail that stands out does actually get hammered down, and, like the legend of Icarus, having flown too close to the sun, they fall?
#+end_quote

#+begin_quote
not everyone is equally motivated by power, and power is something that at least some people abjure, possibly because it signals too much ambition, overly individualistic, selfish behavior, or excessive Machiavellianism. To be clear, power and influence are almost invariably necessary to get things done and change lives, organizations, and the world. Yet to help rationalize their reluctance to pursue power, people find ways of worrying about the steps they may need to take to acquire it and what will happen to them upon doing so.

My response to these concerns is that people should downplay their importance or relevance, because power itself makes many problems, including what someone did to acquire that power, mostly disappear [...]
#+end_quote

#+begin_quote
[...] power and success will generally lead others to forget or forgive what you did to attain them.
#+end_quote

*** Most social processes produce consistency or amplification of advantage, not change
:PROPERTIES:
:NOTER_PAGE: (153 . 0.6031487513572205)
:END:

#+begin_quote
In the homeostatic view, if you violate social norms, you will be sanctioned, so that the normative order can be maintained. Break the law or violate rules and you will face punishment, again to maintain the inviolability of the rules and laws for the wellbeing of the collective. Underperform, or misuse resources, and you will face penalties, as social collectivities enforce rules to ensure their continued survival. Homeostatic processes restore justice and order, punishment of wrongdoing enforces the social norms, and sanctions for poor performance all operate in ways that facilitate the operation—indeed, the survival—of social systems.

Although these are nice ideas, and are even occasionally true, organizational and social processes mostly amplify existing advantages and perpetuate power and status, instead of balancing or curtailing them.
#+end_quote

#+begin_quote
In essence, the Matthew Effect ["For whoever has will be given more, and they will have an abundance. Whoever does not have, even what they have will be taken from them" (Matthew 25:29)] describes a process of cumulative advantage. "Initial comparative advantages of trained capacity, structural location and available resources make for successive increments of advantage such that the gaps between the haves and the have-nots in science (as in other domains of social life) widen."
#+end_quote

#+begin_quote
While cumulative advantage partly explains why power, once obtained, is so durable, it does not provide a full psychological account of why power often endures even in the face of subsequent failure, demonstrated incompetence, and unethical or even illegal behavior.
#+end_quote

#+begin_quote
Before arguing that power is often self-perpetuating, I first want to acknowledge that the idea that power excuses misdeeds is not an obvious, or unambiguously supported, position. Here are some mechanisms that might account for why power leads to more severe sanctioning and a more probable downfall for the powerful.

University of North Carolina professor Alison Fragale and her colleagues argued that more powerful actors were perceived to have a greater degree of agency and intentionality in their actions. First, because power permits people to get their way more often, and induces people to be more positive in their outlook and pursue their goals with more vigor, when the powerful misbehave, they are held to be more responsible for that behavior. The higher degree of perceived agency would cause others to sanction the powerful more severely. Second, the researchers argued that higher-status, more powerful individuals were seen as acting more in their own self-interest and pursuing their own wellbeing, which would also lead to more severe sanctions because there would be less attribution of prosocial motivation. In two scenario studies, Fragale and her colleagues found that the higher the wrongdoers' status, the more severe the punishment observers wanted to mete out.

Another mechanism: power leads to greater visibility and attention paid to the powerful. Therefore, misdeeds or failures of the powerful are more likely to draw greater notice and thus result in more social disapproval and sanctioning.

[...]

Notwithstanding the greater visibility that accompanies power, attributions of greater potency and agency, and the fact that observers have less sympathy for the powerful, my sense is that power generally insulates people from suffering too greatly for the consequences of their actions, both for the reasons already adduced and the additional logic I outline next.
#+end_quote

*** Some examples of power and wealth insulating wrongdoers
:PROPERTIES:
:NOTER_PAGE: (157 . 0.22475570032573292)
:END:

#+begin_quote
Let's begin with ProPublica reporter and Pulitzer Prize–winning author Jesse Eisinger's book, The Chickenshit Club,18 exploring why and how social changes have undermined the ability and motivation of prosecutors to go after white-collar criminals, with a particular focus on the absence of serious prosecutions emanating from the 2008 financial meltdown. Eisinger's argument is straightforward: many people who serve as prosecutors will subsequently go to work for the defense bar and therefore are already somewhat socially identified with their presumed adversaries. As a review of Eisinger's book argued:

#+begin_quote2
Increasingly, the prosecutors and the defense attorneys on opposite sides of the table are the same people, just at different points in their careers. Conducting a criminal investigation of an executive isn't just risky; in addition to jeopardizing a future partnership at a prestigious law firm, perhaps most important, it incurs "social discomfort," especially for the well-mannered overachievers who now populate the Justice Department. No one wants to be a class traitor, especially when the members of one's class are such nice people.
#+end_quote2
#+end_quote

#+begin_quote
People in power travel in similar circles, including social and charitable circles. They go to many of the same conferences and events, particularly with other powerful individuals from the same industry. They may serve on the same for-profit and nonprofit boards. These social connections, both direct and indirect, will invariably act to dampen not only any sense of outrage over the wrongdoing of similar others, but also the interest in sanctioning that wrongdoing. Thus, much to the surprise of outsiders, a get along–go along culture prevails and insulates the powerful from facing many, or any, consequences, almost regardless of what they have done.
#+end_quote

*** Motivated cognition provides a mechanism for ignoring misbehavior
:PROPERTIES:
:NOTER_PAGE: (163 . 0.32681867535287734)
:END:

[[id:b1a664cb-c661-4c44-bf55-fc407c528ad1][Wizard's first rule]]

#+begin_quote
The cognition "Person X is powerful, rich, and successful" has implications for other beliefs about the person, such as they are moral, competent, intelligent, hardworking, and generally someone whose association would be desirable. Importantly, the attributions of someone's traits are more malleable than the attributions of power, wealth, and success, which have stronger anchors in facts.
#+end_quote

I'd argue that one should see those traits should as warning signs. Someone who is ludicrously successful is only such based on the exploitation of others.

#+begin_quote
[...] once a person has achieved wealth, fame, status, or power—ideas that are conceptually distinct in theory but so frequently co- occur as to be not meaningfully distinguishable—people's consistency tendencies will create attributions that will reinforce beliefs in that person's power, potency, intelligence, and so forth, creating a self-reinforcing cycle.
#+end_quote

#+begin_quote
Most people want to believe that the world is a just and fair place and that folks mostly get what they deserve. As social psychologist Melvin Lerner noted when he developed the so-called just-world hypothesis, the idea of a just world provides people with a sense of predictability and control. Individuals love a feeling of certainty and influence over their environments. Believing in a just world means: follow the rules and you will prosper; break the rules—or laws—and you will suffer.

What some people do not recognize is that the reverse logic also operates. The belief that people get what they deserve implies that individuals who have suffered setbacks or reversals must have done something to deserve those things—a phenomenon that can slide into blaming the victim. Conversely, people who have prospered presumably deserve their good fortune—and this search for justifications for good (or bad) fortune extends to outcomes that occur purely by chance.
#+end_quote

*** Moral rationalization as an example of motivated cognition
:PROPERTIES:
:NOTER_PAGE: (166 . 0.10206297502714441)
:END:

#+begin_quote
The dilemma: How to resolve the potential inconsistency and tension between being a moral individual and supporting someone who has engaged in wrongdoing?

One process to resolve this inconsistency is moral rationalization. As described by the late social psychologist Albert Bandura and his colleagues, moral rationalization refers to strategies in which people redefine and reconceptualize the immoral behavior of other social actors by

1. redefining harmful conduct
2. minimizing a perpetrator's role in causing harm
3. minimizing or distorting harm caused by a perpetrator
4. dehumanizing or blaming the victim

Moral rationalization permits people to keep associating with wrongdoers by redefining the behavior as either not that bad or not really their fault.

Formatting mine
#+end_quote

#+begin_quote
Another process of resolving the inconsistency, introduced in the paper by the three marketing scholars, is called moral decoupling. In this process, observers admit that the people to whom they are attached and attracted have engaged in wrongdoing, but rationalize their continued attraction to and involvement with them by arguing that the immoral behavior is not relevant to the present context. [...] So, for instance, golfer Tiger Woods's extramarital affairs are not relevant to his skill as a golfer, Bill Clinton's dalliance with Monica Lewinsky is not relevant to his ability to effectively manage the US economy, the various sexual peccadillos of corporate executives do not reflect their skills as business strategists or operational managers, and so forth.
#+end_quote

I'm sympathetic to the first example. Knowledge of whether Woods had an affair in the past is not predictive of his ability to golf. However, the second two examples are not the same.

*** Those in power get to write—and create—history
:PROPERTIES:
:NOTER_PAGE: (169 . 0.8490770901194354)
:END:

#+begin_quote
The ability to create a narrative and then tell it repeatedly until it becomes seen as truth helps people retain their power. The fact is that venture capitalists, other investors, and even employees and customers love a nice founding myth about an enterprise, which typically elevates the role of one entrepreneur and writes their colleagues out of the picture. As long as the story "sells," inspires, and has some element of truth, observers won't care about its full veracity. They are interested in the vision, in the narrative, in creating a tale useful for attracting investment, customers, and employees, not something historically accurate. Therefore, the ability to get one's story out early, often, and convincingly creates a reality that can then perpetuate a person's power, regardless of any inconvenient disconfirming facts.
#+end_quote

#+begin_quote
The case of Jack Dorsey illustrates the dynamics of this process. As nicely described by technology reporter Nick Bilton, Dorsey contributed to the founding of Twitter but did not conceive the idea behind it, nor was he there when its predecessor company, Odeo, a maker of podcasts, was created by Evan Williams. Dorsey did become chief executive of Twitter, but he was not a great manager and was forced out of the company. What happened next was consistent with the idea of this chapter that success, or the illusion of success, can make all things right—and reconstruct an image:

#+begin_quote2
After he was stripped of his power at Twitter, Dorsey went on a media campaign to promote the idea that he and Williams had switched roles. He also began telling a more elaborate story about the founding of Twitter. In dozens of interviews, Dorsey completely erased Glass [Noah Glass, the originator of the idea] from any involvement in the genesis of the company. He changed his biography on Twitter to "inventor"; before long, he started to exclude Williams and Stone too. At an event, Dorsey complained to Barbara Walters that he had founded Twitter, a point she raised the next day on "The View" . . . Dorsey told the Los Angeles Times that "Twitter had been my life's work in many senses." He also failed to credit Glass for the company's unusual name . . . Dorsey's story evolved over the years . . . Dorsey began casting himself in the image of Steve Jobs . . . adopting a singular uniform: a white buttoned-up Dior shirt, bluejeans, and a black blazer . . . In Silicon Valley, most companies have their own Twitter story: a co-founder, always a friend, and often the person with the big idea behind the company, who is pushed out by another, hungrier co-founder. As one former Twitter employee has said, "The greatest product Jack Dorsey ever made was Jack Dorsey."

[cite:@biltonAllFairLoveTwitter2013]
#+end_quote2

In the end, the reality of Jack Dorsey, who is now worth billions of dollars, becomes the story that was made up. At this point, no one, other than maybe some journalists and professors, really cares about the actual origins of Twitter or Jack Dorsey's makeover. Power gets to write history, and in so doing, helps perpetuate the power itself, and many of the foundations on which it was built.
#+end_quote

*** Some implications
:PROPERTIES:
:NOTER_PAGE: (175 . 0.2687296416938111)
:END:

[[id:bb1c36b1-15ce-4945-9cfd-102e718dc2d1][Winning isn't everything; it's the only thing]]

** Coda: Staying on the Path to Power
:PROPERTIES:
:NOTER_PAGE: (176 . 0.230114)
:END:

#+begin_quote
[...] knowledge may be helpful, but knowledge not turned into action is of little to no value. That fact is also true about power: knowing the rules of power provides advantage only to the extent people turn that knowledge into action, and do so frequently. Furthermore, acting on knowledge facilitates learning from the experience that action provides, and much like any practice, action helps make that knowledge endure as it becomes part of people's regular behaviors. Therefore, I end the book with some advice on how to turn knowledge about the rules of power into actions that can create a path to power.

The [...] advice: learn about power, and then relearn what you have learned again and again, because the material, while easy to understand, is apparently more difficult to implement than it should be

[...] as [Pant] said to me, "What you are asking us to do is unnatural—it goes against how we were raised and what we have been taught in school. What you are teaching is also inconsistent with what we are regularly told in the ubiquitous—and mostly useless— leadership trainings and books that mostly describe how people want the social world to be, rather than the empirical regularities that explain what actually works to build power and get things done." As implied by the writing of Machiavelli, and by understanding the social science of human behavior, as one person perceptively noted to me, "Leadership is not a moral pursuit." It is above all about the pragmatics of making things happen.

Doing things that are unnatural, and in some sense counter to conventional wisdom, requires reminders and constant vigilance. That's because, by definition, unnatural behaviors do not come naturally, and are therefore difficult to implement and demand conscious thought and attention.

Precisely. Pant's analysis has some important implications. The world is hierarchical, with fewer positions at the top than at the bottom, whether you are talking about professional sports, universities, companies, political organizations, or school districts. In a hierarchical world with competition for advancement, the ability to do power becomes increasingly important as your career advances, because other differentiators among people, such as intelligence or technical skills, become more and more equal as individuals rise through the ranks. At a certain level, everybody is smart and has approximately the same technical knowledge. If doing power were easy or natural, it would not be such an important differentiating factor in people's ability to achieve higher positions or their objectives. If almost everyone could easily and readily implement the rules of power, doing so would provide an advantage to almost no one.
#+end_quote

1. Get a personal coach

   #+begin_quote
[... F]ind a coach who will nicely, constructively, but firmly push you outside of your comfort zone, and get you to think hard about your choices and your actions—the only things over which you have control—so you can prevail in power struggles.
#+end_quote

2. Set up a personal board of directors

   #+begin_quote
[A board of directors] provides fresh perspectives, different information, and, in the best of cases, holds the leadership team responsible for results. This may be precisely what you need: a set of people (maybe three or four) who don't need to meet as a group, who work in different industries and occupations and thus are in no way structurally or otherwise competitive with you. Their job is to hold you accountable for the objectives you set for yourself, to offer you different information, perspectives, and contacts than you can access on your own, and to provide you an element of personal coaching.
#+end_quote

3. Set up a 'Power posse' or organize 'Power lunches'

   #+begin_quote
The idea of a weekly lunch (or dinner) is to maintain momentum, obtain the benefits of social facilitation—the idea that people perform better and are more motivated in the presence of others—build social support, and have a pleasant social interaction even as you are thinking through tough issues about navigating organizational politics.
#+end_quote

   This [[id:064e87e5-6a2d-480f-9cab-9ae1c1cc3ba4][is and isn't]] a networking opportunity. It is primarily a space to talk plainly about the ways in which you are practicing doing power.

4. Make lists

   [[id:e1577e03-2bed-4209-b7bf-1399bd9dfc66][Be intentional]].

   #+begin_quote
Lists provide you with specific goals of what you want to achieve and the steps required. Long-standing research on the topic reports that setting goals, particularly specific and ambitious objectives, positively affects your likelihood of achieving them and your overall level of performance.
#+end_quote

   #+begin_quote
If doing power doesn't come naturally to you, practice. [...] Build what some people call your "power muscles" the same way you would build any other muscle: through practice and use. It is not that difficult. Figure out who can
be helpful to you and reach out to them, practicing the idea of Rule 5. Build
a powerful brand—Rule 4—by developing a concise statement of who you
are and why you are uniquely qualified to be doing what you're doing. Act
and speak with power—Rule 3—by understanding and then implementing
the ideas of how to convey power through your facial expressions, body
language, and words. Get out of your own way—Rule 1—by not holding
yourself back and unnecessarily worrying about what everyone else is
thinking about you. And break the rules—Rule 2—to surprise others by
being resourceful in your power strategies and tactics.
#+end_quote

** Acknowledgments
:PROPERTIES:
:NOTER_PAGE: (184 . 0.230114)
:END:
** Endnotes
:PROPERTIES:
:NOTER_PAGE: (187 . 0.230114)
:END:
** Index
:PROPERTIES:
:NOTER_PAGE: (203 . 0.230114)
:END:
** About the Author
:PROPERTIES:
:NOTER_PAGE: (219 . 0.229167)
:END:

* Bibliography
#+print_bibliography:
* Flashcards :noexport:
** Summarize :fc:
:PROPERTIES:
:CREATED: [2024-02-11 Sun 12:17]
:FC_CREATED: 2024-02-11T20:19:01Z
:FC_TYPE:  double
:ID:       64d50899-1d6b-4d02-b386-22dda629302d
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    |  2.5 |  -1 |        0 | 2024-02-11T20:19:01Z |
| back     |  2.5 |  -1 |        0 | 2024-02-18T20:19:01Z |
:END:

[[id:8d42e706-7fa3-4910-a0be-db0fe90083a9][Jeffrey Pfeffer | 7 Rules of Power]]

*** Back

An enumeration of the ways by which one can, and others do, gather and wield power with an emphasis on [[id:8c1b0569-db17-41af-90a3-7f2c75dc8923][Realpolitik]].

*** Source
[cite:@pfefferRulesPowerSurprisingTrueAdviceHowGetThingsDoneAdvance2022]
** Describe ([[id:8d42e706-7fa3-4910-a0be-db0fe90083a9][Jeffrey Pfeffer | 7 Rules of Power]]) :fc:
:PROPERTIES:
:CREATED: [2024-02-11 Sun 12:38]
:FC_CREATED: 2024-02-11T20:40:09Z
:FC_TYPE:  double
:ID:       9611980e-0b5d-4099-9530-0d81612a2d9a
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    |  2.5 |  -1 |        0 | 2024-02-11T20:40:09Z |
| back     |  2.5 |  -1 |        0 | 2024-02-18T20:40:09Z |
:END:

Appear powerful

*** Back

[[id:d1fa918e-df74-43e5-b430-211129a3208e][Act the part]]. Behave in a way that others interpret as powerful. First impressions matter. Others will judge you on your appearance, use of language, behavior, body language, and what/who surrounds you (just to name a few). Also, pessimistically: con artists are effective, so study and incorporate their techniques.

*** Source
[cite:@pfefferRulesPowerSurprisingTrueAdviceHowGetThingsDoneAdvance2022]
** Describe ([[id:8d42e706-7fa3-4910-a0be-db0fe90083a9][Jeffrey Pfeffer | 7 Rules of Power]]) :fc:
:PROPERTIES:
:CREATED: [2024-02-11 Sun 12:40]
:FC_CREATED: 2024-02-11T20:47:23Z
:FC_TYPE:  double
:ID:       3d7e9434-1ab7-4027-8850-30be3f18a182
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    |  2.5 |  -1 |        0 | 2024-02-11T20:47:23Z |
| back     |  2.5 |  -1 |        0 | 2024-02-18T20:47:23Z |
:END:

Use your power

*** Back

- Get things done. The sooner you start getting things done, the sooner you can make a strong argument for why you are the right person for the role.
- [[id:753694c8-448a-4d28-82f8-ca3b2829db08][Bring in supporters and move out opponents]]
- Intimidate opponents
- [[id:80e39a91-d5f4-4438-af08-64121eff1695][Power begets power]]

*** Source
[cite:@pfefferRulesPowerSurprisingTrueAdviceHowGetThingsDoneAdvance2022]
