:PROPERTIES:
:ROAM_REFS: [cite:@wrightLessonsVerySexyPirateCostume2012]
:ID:       43bed654-b7c3-4d5f-92fe-61c62ee79443
:LAST_MODIFIED: [2023-09-05 Tue 20:15]
:END:
#+title: Jennifer Wright | Lessons of a Very Sexy Pirate Costume
#+hugo_custom_front_matter: :slug "43bed654-b7c3-4d5f-92fe-61c62ee79443"
#+author: Cash Weaver
#+date: [2023-03-04 Sat 08:02]
#+filetags: :reference:

[[id:599c8165-24ef-4468-b4a7-3a9b2fdb8995][Jennifer Wright]], [cite:@wrightLessonsVerySexyPirateCostume2012]

* Summary
A story of the author's failure to [[id:91aae608-44c7-4dd0-94e1-512d5d5263cf][Imagine others complexly]].
* Notes
#+begin_quote
But I imagined the women working at the bar would take such a list seriously. After all, women who make a living peddling shots weren't going to be smart. They wouldn't see the humor in any of this. I assumed my co-workers would be girls who spoke very, very slowly and thought that Puccini was a type of pasta. To their credit, I also imagined they'd have great hair, and I double-conditioned accordingly.

I was in love with my own incongruity -- being a poetry-spouting college graduate in a pleather miniskirt. And I loved this notion of doing something at which I was entirely unsuited, and which seemed to go so much against my personality. I would never have said it at the time, but I very much believed I was above being a fun-loving pirate wench selling shots. I had read Meno and lived in cardigans and went to museums for fun.

I was a terrific little snob who thought she knew everything, and subsequently, I was about to learn a great deal.

As soon as I started, I realized I had no idea what I was doing. Fortunately, the other cocktail waitresses were quick to make suggestions. My first night on the job, a fellow shot girl offered practical advice. "You have to be a little cold," she explained. "Make them feel like you're doing them a favor by letting them buy shots." But it's difficult to maintain a Queen of Sheba demeanor while trying to rub globs of green glitter out of your eyes. Instead I became a level of friendly you typically only see at Disneyland, if Disneyland reeked of vomit and spilled appletinis. I doled out shots as people in cartoon costumes offer hugs. The manager would point out that I wasn't being sexy enough, which was surprising, because I was wearing 6-inch heels and less clothing than I ever had.

It quickly became clear that I was not the first literate person to don a miniskirt. Sometime during that first week, I was hiding in the backroom reading Margaret Atwood. I was sitting on the counter next to baskets of party mix because my feet hurt, which they did for the entirety of my shot-selling career. One cocktail waitress swept in, asked what I thought of Atwood's novel "Oryx and Crake," did a tricky little analysis where she compared it to "The Handmaid's Tale," mentioned some other female dystopian writers I'd never heard of, and then went out balancing a tray of shots on one hand.

As ridiculous as it sounds, that was the first time I became aware that clever people are buried in every nook and cranny of life. It is astonishing that no one pointed this out to me sooner. The girls working at the bar -- they were so bright. Another shot girl had a journal that she filled with poetry that was -- that rarest of all rare things -- crisp and clean and very, very good. This was never a bar where everyone knew your name, but the cocktail waitresses came to know one another's reading lists, and pitch letters, and audition schedules extremely well.
#+end_quote
* Flashcards :noexport:
* Bibliography
#+print_bibliography:
