:PROPERTIES:
:ROAM_REFS: [cite:@keynesEssaysPersuasion2010]
:ID:       5098c183-28fd-4392-b9c0-a95a7cb6050d
:LAST_MODIFIED: [2023-09-05 Tue 20:17]
:END:
#+title: John Maynard Keynes | Essays in Persuasion
#+hugo_custom_front_matter: :slug "5098c183-28fd-4392-b9c0-a95a7cb6050d"
#+author: Cash Weaver
#+date: [2023-06-28 Wed 15:36]
#+filetags: :has_todo:reference:

[[id:60113ecc-2128-43be-9209-6d4fdd2abb83][John Maynard Keynes]], [cite:@keynesEssaysPersuasion2010]

* TODO [#4] Summary
* TODO [#4] Thoughts
* TODO [#4] Notes

- [[id:802975de-8d22-45a7-a0fb-8751ebbce738][He does not love his cat, but his cat's kittens]]

#+begin_quote
Of course there will still be many people with intense, unsatisfied purposiveness who will blindly pursue wealth-unless they can find some plausible substitute. But the rest of us will no longer be under any obligation to applaud and encourage them. For we shall inquire more curiously than is safe to-day into the true character of this "purposiveness" with which in varying degrees Nature has endowed almost all of us. For purposiveness means that we are more concerned with the remote future results of our actions than with their own quality or their immediate effects on our own environment. The "purposive" man is always trying to secure a spurious and delusive immortality for his acts by pushing his interest in them forward into time. He does not love his cat, but his cat's kittens; nor, in truth, the kittens, but only the kittens' kittens, and so on forward forever to the end of cat-dom. For him jam is not jam unless it is a case of jam to-morrow and never jam to-day. Thus by pushing his jam always forward into the future, he strives to secure for his act of boiling it an immortality.

Let me remind you of the Professor in Sylvie and Bruno:

"Only the tailor, sir, with your little bill," said a meek voce outside the door.

"Ah, well, I can soon settle his business," the Professor said to the children, "if you'll just wait a minute. How much is it, this year, my man?" The tailor had come in while he was speaking.

"Well, it's been a-doubling so many years, you see," the tailor replied, a little grufy, "and I think I'd like the money now. It's two thousand pound, it is!"

"Oh, that's nothing!" the Professor carelessly remarked, feeling in his pocket, as if he always carried at least that amount about with him. "But wouldn't you like to wait just another year and make it four thousand? Just think how rich you'd be! Why, you might be a king, if you liked!"

"I don't know as I'd care about being a king," the man said thoughtfully. "But it dew sound a powerful sight o' money! Well, I think I'll wait-"

"Of course you will!" said the Professor. "There's good sense in you, I see. Good-day to you, my man!"

"Will you ever have to pay him that four thousand pounds?" Sylvie asked as the door closed on the departing creditor.

"Never, my child!" the Professor replied emphatically. "He'll go on doubling it till he dies. You see, it's always worth while waiting another year to get twice as much money!"
#+end_quote
* TODO [#4] Flashcards
#+print_bibliography: