:PROPERTIES:
:ID:       248e3cc9-0511-4e71-afd6-19320d3fd61d
:DIR:      /home/cashweaver/proj/roam/attachments/248e3cc9-0511-4e71-afd6-19320d3fd61d
:LAST_MODIFIED: [2023-10-11 Wed 14:21]
:END:
#+title: Julian Shapiro | Writing Well Handbook
#+hugo_custom_front_matter: :slug "248e3cc9-0511-4e71-afd6-19320d3fd61d"
#+filetags: :reference:
#+author: Cash Prokop-Weaver
#+date: [2022-02-07 Mon 16:13]

[[id:5d78b917-4138-4236-a15e-22a6ae7b19a2][Julian Shapiro]]

* Summary

A great guide to writing in [[id:5d78b917-4138-4236-a15e-22a6ae7b19a2][Julian Shapiro]]'s style. It overlaps well with my own [[id:05911fff-a79b-4462-bf6d-a3cec4e1c9f2][Style Guide]].

* Notes
** Introduction
:PROPERTIES:
:ID:       0612ee76-fa86-49ca-9aa8-509eb3bb0f4e
:END:

#+begin_quote
Why write nonfiction?

[...]

1. *Gain leverage*

   Keeping thoughts to yourself can be a disservice to the world. If you have something important to say and you say it well, you send strangers down paths badly needed.

   Writing is one of the most radical things you can do without money. Skilled writers change the world from their couch.

2. *Clarity of thought*

   Writing is a laxative for the mind. When you write, your brain can't stop itself from drawing connections between ideas—and exploring their implications. This shines a light on broken logic, which helps you gain clarity of thought.

   Writing is the act of thinking clearly with the help of paper. Writing slows down your thinking so you can play with your ideas.

3. *Human connection*

   The most efficient way to meet interesting people is to become someone they already want to meet.

   If you do interesting things then write about them publicly with an authentic voice, like-minded people want to meet the person behind that voice. Writing is a bat signal for your people.


[cite:@shapiroWritingWellHandbook], formatting mine
#+end_quote

** What to Write About
:PROPERTIES:
:ID:       729ca636-fd4f-4203-aef9-ec8211948a99
:END:
*** Choose your topic

#+begin_quote
A novel idea is one that's not just new to the reader, but also significant and not easily intuited. Think of it as new and worthwhile. I've identified five categories:

1. Counter-intuitive — "Oh, I never realized the world worked that way."
2. Counter-narrative — "Wow, that's not how I was told the world worked!"
3. Shock and awe — "That's crazy. I would have never believed it."
4. Elegant articulations — "Beautiful. I couldn't have said it better myself."
5. Make someone feel seen — "Yes! That's exactly how I feel!"

[cite:@shapiroWritingHandbookHowSourceWritingIdeas]
#+end_quote

#+begin_quote
Your objective clarifies what you're trying to accomplish, and your motivation ensures you actually see it through.

That's all that's needed to write with conviction: pair an objective with a motivation. When writers lack one of these, they tend to not finish their articles.

If the right objective and motivation combo isn't coming right away, that's okay. Start writing like you would in a diary to uncover what's in the back of your head. As you write, a clear objective will eventually emerge. At that time, do a full rewrite with your clear objective as your guiding light.

[cite:@shapiroWritingHandbookHowSourceWritingIdeas]
#+end_quote

*** Write an intro

#+begin_quote
I define an intro as the minimal information necessary to:

- Introduce the breadth of the post's contents so that readers can decide if it's for them.
- Hook readers into reading more.

It doesn't matter how you hook readers, so long as you eventually fulfill the hook.

A hook is not a gimmick. It's a fundamental psychological principle: A great intro—like an electrifying opening to a film—buys goodwill with readers. Buy enough goodwill and readers look past the weaker parts of your post—because they're chasing the high from your great opening.

[...]

A hook is a half-told story. You raise a question then tease only part of the answer:

- Questions — Pose an intriguing question, but don't give the full answer.
- Narratives — Share the start of a narrative, but withhold the conclusion.
- Research — Highlight research findings, but only a small portion.
- Arguments — Make an unexpected claim, but don't explain how it's true.

Hooks serve two purposes:

1. They compel readers to continue reading. They switch on the storytelling machinery in readers' heads.
2. They help you identify what's interesting—novel—to write about.

In a nonfiction essay that explores new ideas, an effective intro often follows this structure:

- Establish shared context.
- Surface a problem and what's at stake.
- Explore the problem's significance.
- Tease a clever solution.

[cite:@shapiroWritingHandbookHowSourceWritingIdeas]
#+end_quote

*** Combat skepticism

#+begin_quote
In your intro, consider proactively countering any major skepticisms that exist. There are five types of skepticism to counter:

- Superficial: Superficial skepticism emerges from readers not believing you'll share things they don't already know.

  Solution: Tease your original insights in your introduction.‍
- Irrelevant: Readers don't believe you'll cover key points they care about.

  Solution: List the points you'll cover.‍
- Sloppy: Readers don't want to sit through bad writing.

  Solution: Rewrite your intro to be clear, succinct, and intriguing.‍
- Implausible: Readers don't believe you'll deliver on your hooks.

  Solution: Include quotes from authorities who agree with you.
- Untrustworthy: Readers don't believe you're qualified to write about this.

  Solution: If you have relevant credentials, share them. If not, make your hooks so captivating that they can't help but continue reading. Make the rest of your post so insightful, logical, and well-researched that they believe you. Or, if you're indeed unqualified, be upfront about it and frame the post as an exploratory journey you're taking them on.

If you successfully hook readers while neutralizing their skepticism, you generate goodwill: now they're invested in reading the rest of your post.

[cite:@shapiroWritingHandbookHowSourceWritingIdeas]
#+end_quote

*** Integrate feedback

See also [[id:428fd541-a67b-4fe4-8af2-acdae574c992][Collaborate for better results]].

#+begin_quote
My favorite writing trick is to only write my introduction then ask friends who represent my audience this question:

"After reading only this intro, what are the most interesting ideas I could possibly cover in the rest of the post?"

I pick and choose the responses that resonate with me. This is how I de-risk my post from lacking novelty: Am I headed in a direction that's maximally interesting?

[cite:@shapiroWritingHandbookHowSourceWritingIdeas]
#+end_quote

#+begin_quote
The elements of a great intro

[...]

- It's a compelling hook into your topic. Readers sense forthcoming novelty.
- It conveys the importance of the idea so that readers want to hear the rest of the story. It twisted the knife enough to help readers feel the pain you're speaking to.
- It's concise. Readers don't want all the details; they want the minimum needed to be teased by your novelty in a way that resonates.

[cite:@shapiroWritingHandbookHowSourceWritingIdeas]
#+end_quote

** Writing First Drafts
:PROPERTIES:
:ID:       3a9421aa-105f-4338-a228-1c65fa5e0d99
:END:

#+begin_quote
You're a proxy for your die-hard readers.

That's the irony of self-indulgent writing: writing for yourself is the quickest path to writing something others love.

[cite:@shapiroWritingHandbookHowWriteFirstDraft]
#+end_quote

#+begin_quote
The mistake writers make is believing expertise is required to write compelling nonfiction. Nope, it's the rabid desire to indulge your curiosity.

[cite:@shapiroWritingHandbookHowWriteFirstDraft]
#+end_quote

#+begin_quote
When ideas stop flowing, ask yourself:

- How can I make this point more convincing?
- What are the interesting implications of what I just said?

[cite:@shapiroWritingHandbookHowWriteFirstDraft]
#+end_quote

#+begin_quote
I'm not convinced conclusions are necessary. But I like placing them after my resulting points to prompt readers into action. Here's how.

1. First, share a poignant takeaway
   Identify your article's significance by re-reading it and asking, "What was this really about? What was I trying to say?"

   Distill the answer into a single, punchy sentence. Make readers think, "Ahh, yes, that's why this article was profound."

2. Next, provide next steps
   Now that your wisdom has resonated with readers, ask yourself, What about the world can my readers better appreciate now that they've read my article?

   Share where they can go next to continue the journey they started here.

For a writing guide such as this, I might conclude by sharing bloggers whose work I enjoy. Then I might urge you to reverse engineer their articles and study what makes them great. That's how you continue your learning.

[cite:@shapiroWritingHandbookHowWriteFirstDraft]
#+end_quote

#+begin_quote
While writing, keep these points in mind:

- Don't feel constrained by your outline. Expect to discover most of your ideas throughout the writing process.
- Trust that what interests you is what interests your readers. If not, target an audience more like yourself.

[cite:@shapiroWritingHandbookHowWriteFirstDraft]
#+end_quote

** Rewriting and Editing
:PROPERTIES:
:ID:       b46ea6ee-5a61-47ee-81e1-163af9ff9cc4
:END:

#+begin_quote
Your favorite authors' first drafts are typically bad too. However, great authors have the discipline to aggressively rewrite their first drafts in pursuit of:

- Being clearly understood
- Persuasive reasoning
- Sustaining curiosity
- Resonance — Story, analogy, and poetry

The enemy of those objectives is being precious about what you originally said and how you originally said it.

When you first write an idea down, you do so in whatever disjointed way immediately came to mind. Rewriting is the art of finding the correct puzzle pieces within that mess and putting them together in the right order.

In short, your first draft is to extract novel ideas out of your brain. Your second draft is to rewrite those ideas so they resonate.

[cite:@shapiroWritingHandbookHowRewriteYourFirstDraft]
#+end_quote

*** Goal: Be understood

#+begin_quote
I like to write sentences that a thirteen-year-old could follow.

If they can understand, so can everyone else—including anyone who's skimming.

This isn't to say children should understand the details and nuances. Rather, I think children should be able to follow the logic of all your arguments.

You already do this intuitively. When speaking to children, you simplify:

- You use plain phrasing.
- You use fewer ideas per sentence.

[cite:@shapiroWritingHandbookHowRewriteYourFirstDraft]
#+end_quote

This reminds me of [[id:99e14785-13bb-420c-b0b5-b14bad1bd163][Freddish]], though it's aimed at a much younger audience.

**** Remove abstract phrasing

#+begin_quote
Here's a sentence with complex phrasing:

"The obstacle facing media organizations is charting an economically sustainable course through a landscape of commodity journalism."

Let's rewrite that plainly:

"News companies are struggling to stay in business because anyone with a Twitter account can report the news now. The news has never been more of a commodity than it is today."

That's how you talk to a thirteen-year-old. In fact, that's how you should talk to everyone all the time.

In the revised example, I removed abstract words like "charted" and "landscape," and I represented a concept with a specific example.

By removing this overhead, the underlying point stands out. That's our goal.

Grammatical simplification such as this doesn't make your writing worse. The complexity of your writing should emerge from the strength of its ideas, not from how those ideas are worded.

However, don't drop key information when simplifying. This, for example, would be too reductive:

"News companies are not doing well today."

That loses the point of why news companies are not doing well. Simplify your sentences without removing the nuances.

[cite:@shapiroWritingHandbookHowRewriteYourFirstDraft]
#+end_quote

I think it's possible to over-index on the "make it concrete" aspect of this advice. I worry someone reading the second sentence may walk away with the mistaken understanding that Twitter is the sole driving force behind commodity journalism.

Similarly, a double-edged sword of abstract writing is that it can have multiple correct interpretations. Consider the following rewrite:

#+begin_quote
One last example. Let's remove abstract words and talk plainly:

Bad paragraph — "Ignorance of corporate dynamics represent a persistent source of pain for a certain type of operator. Intelligent but inexperienced. I'd recommend that you avoid this pain by understanding how other people make decisions in the context that they're incentivized to do so and by appreciating the constraints they're operating within."

Rewritten — "It's common to be a smart person who's unaware of what's going on. I recommend writing down the frameworks your team uses to make big decisions. Then, when a colleague proposes an idea that doesn't intuitively make sense to you, think through their idea using their own frameworks. Work from there to build empathy and have a constructive dialogue."

[cite:@shapiroWritingHandbookHowRewriteYourFirstDraft]
#+end_quote

I read the "Bad paragraph" to be discussing how inter-personal and corporate politics influence an organization. The "Intelligent but inexperienced" operator would be one who knows how to do their tasks well but doesn't know [[id:0fd22b02-281f-4a62-b60d-eded1a423c79][The game]]. As an example: They may, without intending to, make another coworker look foolish and thereby make an enemy.

The "Rewritten" paragraph seems to discuss how to navigate a bureaucracy with an obscured decision-making process and advocates empathy.

A statement made in plain language would avoid this ambiguity.

**** Use fewer ideas per sentence

Again, I take issue with the example presented:

#+begin_quote
Consider this bad paragraph:

"There's a fast growing collection of data describing the structure and functional capacity of human gut bacteria in a variety of conditions. Ongoing efforts to further characterize the multitude of functions of gut bacteria and the mechanisms underlying its interactions will provide a better understanding of the role of the microbiome in human health and disease."

Let's rewrite that for a thirteen-year-old:

"There's plenty of research on gut bacteria. We're quickly learning which roles gut bacteria play and how they interact with each other. Researchers want to better understand how these bacteria can affect our overall health."

[cite:@shapiroWritingHandbookHowRewriteYourFirstDraft]
#+end_quote

"There's plenty of research" may read to some as "There is enough/sufficient research".

**** Provide examples

#+begin_quote
Tips for providing examples:

- Don't just provide good examples, also provide bad examples. Before-and-after comparisons—like a good paragraph versus a bad paragraph—clarify what you mean and don't mean. Help readers orient themselves on a spectrum of right to wrong.
- If you make your examples fun and topical, readers pay more attention.
- Examples with many moving parts should possibly be turned into diagrams.

[cite:@shapiroWritingHandbookHowRewriteYourFirstDraft]
#+end_quote

*** Goal: Be concise

Also see:

- [[id:436e3b6b-6b46-4173-b764-d3d902651feb][If I Had More Time, I Would Have Written A Shorter Letter]]
- [[id:f9a2d16c-2264-47a7-85ce-db8e962a3811][The Shorter and Plainer the Better]]

#+begin_quote
Succinctness—a lack of bloat—helps readers finish your post. What I've learned from asking a lot of friends for feedback is that readers often quit not because they dislike your ideas, but because they're bored.

[...]

In speech, when you say something that doesn't resonate, you can add sentences to further explain your point. Don't do that in writing. If your sentence doesn't resonate, you go back and rewrite it.

Writing is a process of deliberate thought curation—where each sentence can justify its inclusion in your final draft.

When a deliberate writer has written something down, they then ask:

- What is the purpose of the statement I just made? What effect does it have on the reader's mind?
- Is there something more useful I could have said instead?

Later, when they get stuck expanding on their ideas, they ask:

- How can I make this point more convincing?
- What are the interesting implications of what I just said?

[cite:@shapiroWritingHandbookHowRewriteYourFirstDraft]
#+end_quote

*** Feedback
:PROPERTIES:
:ID:       8590b3b6-678c-460e-be3d-eb1856d1df43
:END:

#+begin_quote
Getting feedback is the most efficient way to improve your writing. This is not optional. Giving feedback is as important: giving it to others forces you to internalize the learnings from this handbook.

[cite:@shapiroWritingHandbookHowRewriteYourFirstDraft]
#+end_quote

#+begin_quote
Ask for feedback from the audience you're writing for. Here's a template:

It would be helpful if you read my article slowly to transcribe the reactions you have while reading it. For example:

1. Tell me what to delete — When you notice your interest is fading, you can say "I'm drifting here. This isn't compelling and it isn't adding value. Get to the point quicker and hook me."

2. Tell me what to double down on — When something excites you, you can say "Dopamine hit. Go further in this direction. I have more questions."

3. Tell me what isn't clear — When you're done reading, please score this from 1-10 on how satisfying it was. Don't be afraid to give me a low score. By telling me this needs work, you're sparing me from releasing bad work to the public.

Keep asking for feedback then rewriting until you average a score of 7.5+ across a handful of respondents. That puts you in the "this was a good read" category.

Do not waste time striving for 9+. One reader's 9 is not the same as another's, so trying to satisfy everyone results in a bloated post that satisfies no one. There are many great ways to tell a story, so be happy when you've found one that works.

[cite:@shapiroWritingHandbookHowRewriteYourFirstDraft]
#+end_quote

I worry that the 1-10 scale is too wide -- that one individual's 7/10 isn't meaningfully different from their 6/10. Perhaps a 1-5 scale?

#+begin_quote
Your best source of feedback is often you with the benefit of hindsight. But you need a break to get that perspective. I've found a week is often enough time to sufficiently defamiliarize myself with my own writing.

[...]

Take it from the world's most successful hyper-prolific writer, Stephen King: he shoves his manuscript into a drawer for six weeks before writing his final draft. When he re-opens it, he sees its flaws with fresh eyes.

[cite:@shapiroWritingHandbookHowRewriteYourFirstDraft]
#+end_quote

** Writing Style
:PROPERTIES:
:ID:       372554f4-e2c2-4757-b7c5-f4e279e37e2f
:END:

#+begin_quote
What gives a world-class author their "voice?"

Well, ask your friends what it's like to talk to you. Maybe they'll mention your:

- Tone of voice
- Sense of humor
- Eccentricities
- Viewpoints

Convey those traits in your writing, and readers [will] recognize your voice. Meaning, I don't think voice is your choice of words. It's your unfiltered self reflected on paper.

In early drafts, I like to discard my reflex to self-censor. Talk vulnerably like you do with friends. In later drafts, you can remove sensitive details.

Until then, it's a confession.

[...]

The antidote to inauthenticity is reminding yourself how you talk with friends. Record yourself talking, transcribe it, and work from that.

[cite:@shapiroWritingHandbookHowWriteStyle]
#+end_quote

#+begin_quote
The more steps you can be removed while still successfully communicating the meaning, the more "elegant" your poetry feels. The more profound your underlying point, the more "deep" your poetry feels.

Let's walk through an example using a framework I devised.

1. First-order description

   In a first-order description, you directly describe how something is.

   "The day was hot."

   This is how we commonly talk.

2. Second-order description
   In a second-order description, you describe something by stating an effect it has on its environment.

   "The day melted our popsicles."

   The reader can determine that the day was therefore hot.
3. Third-order description
   In a third-order description, you describe something by stating its effect but not mentioning the cause by name.

   "Our popsicles melted."

   Above, there's ambiguity as to why our popsicles melted. But with a bit of imagination and puzzle-solving, the reader pieces it together.

[cite:@shapiroWritingHandbookHowWriteStyle]
#+end_quote

** Practicing Writing
:PROPERTIES:
:ID:       00d52261-4038-4440-99db-8214a9039f0d
:END:

#+begin_quote
To learn what a job well done looks like, dissect your favorite posts: highlight the best and worst parts of each and identify what makes them so.

I find that writers who post frequently (say, twice weekly) are rarely worth reading consistently. I read for insights. And no writer can generate profound insights on a fixed schedule. I aggregate writers who publish sporadically. When they post, they truly have something to say.

[cite:@shapiroWritingHandbookHowPracticeWriting]
#+end_quote


* Flashcards :noexport:
** [[id:5d78b917-4138-4236-a15e-22a6ae7b19a2][Julian Shapiro]] defines a {{novel idea}@0} as {{new to the reader, significant, and not easily intuited}@1}. :fc:
:PROPERTIES:
:CREATED: [2022-10-22 Sat 18:48]
:FC_CREATED: 2022-10-23T01:49:09Z
:FC_TYPE:  cloze
:ID:       889bd82c-94f2-49bb-af32-cc48bf4d0dfe
:FC_CLOZE_MAX: 1
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.65 |   7 |   362.68 | 2024-06-10T07:08:36Z |
|        1 | 1.30 |   8 |    17.84 | 2023-10-29T17:29:08Z |
:END:

*** Source
[cite:@shapiroWritingHandbookHowSourceWritingIdeas]
#+print_bibliography: