:PROPERTIES:
:ROAM_REFS: [cite:@sotalaNobodyDoesThingThatTheyAreSupposedlyDoing2017]
:ID:       ca067526-19a1-4996-a9fb-be54b7e86dd5
:LAST_MODIFIED: [2023-09-05 Tue 20:15]
:END:
#+title: Kaj Sotala | Nobody Does the Thing That They Are Supposedly Doing
#+hugo_custom_front_matter: :slug "ca067526-19a1-4996-a9fb-be54b7e86dd5"
#+author: Cash Weaver
#+date: [2023-01-12 Thu 16:09]
#+filetags: :reference:

[[id:8781430f-720f-48ae-8453-d79d6014542c][Kaj Sotala]], [cite:@sotalaNobodyDoesThingThatTheyAreSupposedlyDoing2017]

* Summary
- People do what aligns with their [[id:deb3b467-3bb1-4000-9665-3a7347909ad6][Incentives]]
- It's difficult to do what we say we want to do ([[id:cce498c6-3fd2-40e1-9aee-fbc273d7fb32][Akrasia]], [[id:6e6aa331-8dbf-4751-a896-ca5fc6c7128b][Paul Graham | What You (Want to)* Want]]), so we often don't
*In general, neither organizations nor individual people do the thing that their supposed role says they should do.* Rather they tend to do the things that align with their [[https://en.wikipedia.org/wiki/Incentive][incentives]] [[[id:deb3b467-3bb1-4000-9665-3a7347909ad6][Incentives]]] (which may sometimes be economic, but even more often they are social and psychological). If you [[http://donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system/][want to really change things]] [[[id:769516ae-54c8-4218-a70c-0d7f4a901754][Donella H. Meadows | Leverage Points: Places to Intervene in a System]]], you have to change people's incentives.
* Thoughts
* Notes
#+begin_quote
I feel like one of the most important lessons I've had about How the World Works, which has taken quite a bit of time to sink in, is:

*In general, neither organizations nor individual people do the thing that their supposed role says they should do.* Rather they tend to do the things that align with their [[https://en.wikipedia.org/wiki/Incentive][incentives]] [[[id:deb3b467-3bb1-4000-9665-3a7347909ad6][Incentives]]] (which may sometimes be economic, but even more often they are social and psychological). If you [[http://donellameadows.org/archives/leverage-points-places-to-intervene-in-a-system/][want to really change things]] [[[id:769516ae-54c8-4218-a70c-0d7f4a901754][Donella H. Meadows | Leverage Points: Places to Intervene in a System]]], you have to change people's incentives.

But I feel like I've had to gradually piece this together from a variety of places, over a long time; I've never read anything that would have laid down the whole picture. I remember that [[https://www.amazon.com/Freakonomics-Economist-Explores-Hidden-Everything/dp/0060731338][Freakonomics]] had a few chapters about how incentives cause unexpected behavior, but that was mostly about economic incentives, which are just a small part of the whole picture. And it didn't really focus on the "nothing in the world works the way you'd naively expect" thing; as I recall, it was presented more as a curiosity.

On the other hand, [[http://overcomingbias.com/][Robin Hanson]] has had a lot of stuff about "[[http://www.overcomingbias.com/2008/09/politics-isnt-a.html][X is not about Y]]" [[[id:064e87e5-6a2d-480f-9cab-9ae1c1cc3ba4][X isn't (only) about Y]]], but that has mostly been framed in terms of prestige and signaling, which is the kind of stuff that's certainly an important part of the whole picture (the psychological kind of incentives), but again just a part of the picture. (However, his [[http://elephantinthebrain.com/][upcoming book]] [[[id:fb0b2586-5705-4114-b735-7062ccd56043][Kevin Simler, Robin Hanson | The Elephant in the Brain: Hidden Motives in Everyday Life]]] goes into a lot more detail on why and how the publicly-stated motives for human or organizational behavior aren't actually the true motives.)

And then in social/evolutionary/moral psychology there's a bunch of stuff about social-psychological incentives, of [[https://www.sas.upenn.edu/psych/PLEEP/pdfs/Kurzban%20DeScioli%20mysteries.pdf][how we're motivated]] to denounce outgroups and form bonds with our ingroups; and how it can be socially costly to have accurate beliefs about outgroups and defend them to your ingroup, whereas it would be much more rewarding to [[https://www.youtube.com/watch?v=rE3j_RHkqJc][just spread inaccuracies]] or outright lies about how terrible the outgroups are, and thus increase your own social standing. And how even well-meaning ideologies will [[https://www.edge.org/response-detail/27168][by default get hijacked]] [[[id:4cb7f185-7fc0-47aa-8a6a-9454de9a999c][Tribalism]]] by these kinds of dynamics and become something quite different from what they claimed to be.

But again, that's just one piece of the whole story. And you can find more isolated pieces of the whole story scattered around in a [[https://meaningness.com/geeks-mops-sociopaths][variety]] of [[http://slatestarcodex.com/2014/07/30/meditations-on-moloch/][articles]] [[[id:1bba449a-48eb-479a-be4d-a4d7f8095b6a][Scott Alexander | Meditations On Moloch]]] and [[http://www.daviddfriedman.com/The_Machinery_of_Freedom_.pdf][books]], also stuff like the [[https://en.wikipedia.org/wiki/Iron_law_of_oligarchy][iron law of oligarchy]], [[https://en.wikipedia.org/wiki/Rational_irrationality][rational irrationality]], [[https://en.wikipedia.org/wiki/Public_choice][public choice theory]], etc etc. But no grand synthesis.

There's also a relevant strand of this in the psychology of motivation/[[https://lesswrong.com/lw/3w3/how_to_beat_procrastination/][procrastination]]/[[https://smile.amazon.com/Power-Habit-Why-What-Change-ebook/dp/B006WAIV6M/][habit-formation]], on why people keep putting off various things that they claim they /want/ to do, but then don't [[[id:cce498c6-3fd2-40e1-9aee-fbc273d7fb32][Akrasia]]]. And how small things can reshape people's behavior, like if somebody ends up as a much more healthy eater just because they /don't/ happen to have a fast food restaurant conveniently near their route home from work [[[id:d923e2b9-8907-4cbb-9874-4b638f9f0aba][How to change]]]. Which isn't necessarily so much about incentives themselves, but an important building block in understanding why our behavior tends to be so strongly shaped by things that are entirely separate from consciously-set goals.

Additionally, the things that do drive human behavior are often things like [[https://kajsotala.fi/2017/07/how-i-found-fixed-the-root-problem-behind-my-depression-and-anxiety-after-20-years/][maintaining a self-concept]], seeking feelings of [[https://en.wikipedia.org/wiki/Self-determination_theory][connection, autonomy and competence]], [[http://journals.plos.org/plosone/article?id=10.1371%2Fjournal.pone.0131613][maintaining]] [[https://web.archive.org/web/20080513074310/http://www.thestage.co.uk/connect/acblack/improkj.php][status]], enforcing [[http://www.moralpsych.net/s/haidt-2001.pdf][various moral intuitions]], etc., things that only loosely align one's behavior with one's stated goals. Often people may not even realize what exactly it is that they are trying to achieve with their behavior.

[[https://lesswrong.com/lw/15w/experiential_pica/]["Experiental pica" is a misdirected craving]] for something that doesn't actually fulfill the need behind the craving. The term originally comes from [[https://en.wikipedia.org/wiki/Pica_(disorder)][a condition]] where people with a mineral deficiency start eating things like ice, which don't actually help with the deficiency. Recently I've been shifting towards the perspective that, to a first approximation, roughly /everything/ that people do is pica for some deeper desire, with that deeper desire being something like social connection, feeling safe and accepted, or having a feeling of autonomy or competence. That is, most of the things that people will give as reasons for why they are doing something will [[https://lesswrong.com/lw/6p6/the_limits_of_introspection/][actually miss the mark]], and also that many people are engaging in things that are actually relatively inefficient ways of achieving their true desires, such as pursuing career success when the real goal is social connection. (This doesn't mean that the underlying desire would /never/ be fulfilled, just that it gets fulfilled less often than it would if people were aware of their true desires.)
#+end_quote
* Flashcards :noexport:
#+print_bibliography: