:PROPERTIES:
:ID:       62646fd0-1bf0-48fb-8f2e-eea7d1759688
:LAST_MODIFIED: [2023-10-25 Wed 12:13]
:END:
#+title: Keep a video journal for important moments
#+hugo_custom_front_matter: :slug "62646fd0-1bf0-48fb-8f2e-eea7d1759688"
#+author: Cash Prokop-Weaver
#+date: [2023-10-25 Wed 11:57]
#+filetags: :concept:

Create video journal entries (by yourself or as a group) to capture important recent experiences.

My wife's best friend recommended we try this on our honeymoon and it was the best gift she's given us. We have a half-dozen or so videos which capture details we've since forgotten and bring us right back to a particular day of travel when we watch them together!

* Guidelines

1. <4 minutes (see [[id:d077ef5b-766b-4239-a40f-f775e101e185][Write prolifically, write succinctly]])

   Take a few minutes before recording, if necessary, to think about what you want to include. Write them down if that helps!

2. Record as soon after the event as possible --- ideally while you're still on location!

* When?

I keep a written journal for daily "mundane" entries. These video journals are higher-fidelity and can easily involve more than just myself. I try to use them with that in mind. The primary way I use them is periodically, to track a particular thing over time:

- Every night while on a [[id:37ed078d-dc48-48b5-abe3-20590ecbe41b][trip]]
- Every week while you're working on a home renovation project to see how it evolved
- Every month with your children as they're growing up

I haven't done so yet, but I could see creating ad-hoc entries as well:

- You figured out a new recipe
- Finished decorating for a party
- Adopting a new pet
- Moving into a new home
- Birth in the family

* Flashcards
