:PROPERTIES:
:ROAM_REFS: [cite:@kileBusyPersonPatterns2006]
:ID:       f1882164-0604-4dd9-ae59-df0d7b9d5ca2
:LAST_MODIFIED: [2024-01-27 Sat 10:47]
:END:
#+title: James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns
#+hugo_custom_front_matter: :slug "f1882164-0604-4dd9-ae59-df0d7b9d5ca2"
#+author: Cash Prokop-Weaver
#+date: [2022-04-25 Mon 18:07]
#+filetags: :reference:

[cite:@kileBusyPersonPatterns2006]

* Thoughts
This isn't the first time I've seen these concepts (e.g. [[id:82d1d3b6-dd55-43bf-828e-b34508ac136c][Deep work]] and [[id:0c40f4d8-2ae6-4cc1-9109-f4852d3b2160][Contiguous Time Blocks]] / [[id:4bfa94bc-4894-4a33-8585-52e85c752ea2][Single-Task Important Items]]; [[id:5664432e-6bb3-4670-9669-08ee70b5ca6d][Agile]] and [[id:c8ed5ee6-7756-41d2-9134-8baf2c3abe8f][Feedback Loop]]) which gives me greater confidence in their profundity. It may be trite to say you should [[id:630c804a-cef5-42e6-a168-5a233a0acbed][Just Start]] or to [[id:d1afad48-d95d-4ea6-bce3-a3b88a28b995][Drop Unimportant Tasks]]; however, these simple truths are still true and I often forget them.
* Notes
:PROPERTIES:
:NOTER_DOCUMENT: attachments/f1/882164-0604-4dd9-ae59-df0d7b9d5ca2/busy-person-patterns.pdf
:NOTER_PAGE: 30
:END:
** Skeleton
*** Table of Contents
:PROPERTIES:
:NOTER_PAGE: (2 . 0.090909)
:END:
*** Busy Person Patterns – An Introduction
:PROPERTIES:
:NOTER_PAGE: (4 . 0.090909)
:END:
*** Just start
:PROPERTIES:
:NOTER_PAGE: (5 . 0.090909)
:ID:       630c804a-cef5-42e6-a168-5a233a0acbed
:END:

Also see [[id:fb16dedc-15d0-418a-83e2-0ed84e5e2504][Just do it]].

#+begin_quote
You have a task that cannot wait until you have all the information about it to begin. It may be time sensitive, you may have a deadline, or part of the task may be to identify its parts. Most important, you feel internal or external pressure to begin and have some level of confidence about the task's overall direction.

[Negatives]

- The initial information given with a task may not be conducive to understanding it immediately.
- Tasks may be vague in their definition.
- Just by starting a task, you do not guarantee that you can figure it out and complete it.
- You can waste time fumbling through starting the task without a clear idea what you need to do.
- While you are starting one task, you are putting off other tasks.
- Some organizations may punish initiative.
- You may be afraid to start.

[Positives]

- By not starting a task, you do not know whether you can complete it.
- If you do not start a task, you cannot complete it.
- Starting something new can be satisfying and give you a sense of accomplishment.

Therefore, when faced with a vague task, start working on it to see if the steps you need to complete it emerge.
#+end_quote

**** Commentary
:PROPERTIES:
:NOTER_PAGE: (5 . 0.551768)
:END:

#+begin_quote
Procrastination is the enemy of a busy person.
#+end_quote

**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (5 . 0.746212)
:END:
**** Examples
:PROPERTIES:
:NOTER_PAGE: (5 . 0.4989010989010989)
:END:

*** Contiguous time blocks
:PROPERTIES:
:NOTER_PAGE: (7 . 0.090909)
:ID:       0c40f4d8-2ae6-4cc1-9109-f4852d3b2160
:END:

Related: [[id:82d1d3b6-dd55-43bf-828e-b34508ac136c][Deep work]]

#+begin_quote
You have the information you need to complete a task and you are determining how you will complete it. You have several other tasks you need to complete and you frequently fragment your time. You feel that you must prevent interruptions to advance this task.

[Negatives]

- Setting aside time does not guarantee it will not be interrupted.
- It is not always possible to obtain contiguous time blocks.

[Positives]

- Complex tasks require a certain amount of think time to be completed.
- Human concentration, when broken, can cause a task to take longer than originally anticipated.
- Smaller allocated time blocks create interruptions that cause you to stop and re-start a task.

Therefore, set aside a block of time to complete the task so that you are able to perform the task without interruption until you are comfortable with how the task is progressing.
#+end_quote

**** Commentary
:PROPERTIES:
:NOTER_PAGE: (7 . 0.45202)
    :END:

#+begin_quote
This is a pattern about limiting interruptions so that you can concentrate on a complex task. Interruptions can come in at least two forms: Those you impose upon yourself through fragmenting your time and those that outside forces impose upon you. Even though there is a potential task re-start penalty when you impose interruptions upon yourself, there is a quantifiable task re-start consequence when outside influences interrupt you. When you interrupt yourself, you typically do it at a logical break point – a time when you feel comfortable you can stop the task. When outside influences cause an interruption, however, your concentration on a complex problem is broken and you need to re-establish it to continue.
#+end_quote
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (7 . 0.739899)
:END:
#+begin_quote
Be careful not to take this pattern to an extreme. If you completely de-fragment your time, you will be unable to complete important tasks that may have an earlier due date because you will not interrupt yourself to address them.
#+end_quote
**** Examples
:PROPERTIES:
:NOTER_PAGE: (8 . 0.17298)
:END:

*** Single-Task important items
:PROPERTIES:
:NOTER_PAGE: (9 . 0.090909)
:ID:       4bfa94bc-4894-4a33-8585-52e85c752ea2
:END:
#+begin_quote
You have a task to do that you and/or others consider important. Performing this task simultaneously with other tasks breaks your concentration and you find that quality is suffering. You feel that the task warrants a quality level that is impossible to produce if you perform it with other tasks.

[Negatives]

- Interruptions are an unpleasant fact. It is often impossible to find time to work on only one thing because of pressure from others though in-person visits, email, IM, telephone calls, or pages.
- Single tasking does not guarantee that the results will be better than if you multitasked.
- When you perform a single task, you may be putting off tasks that are more important or time critical.

[Positives]

- Important tasks, like complex tasks, require a certain amount of think time to be completed. What makes an important task different from a complex task is there is a need to attend to details – the output is important.
- Human concentration, when broken, can cause a task to take longer than originally anticipated and produce work that is not befitting the task.
- Working on one important task may help you solve another complex problem.
- When you fragment your time by completing multiple tasks in the same time block, you decrease the amount of concentration and attention you can give to an important task.
- There is a certain level of satisfaction knowing that you are producing high quality results.

Therefore, isolate important tasks and perform them separately so that you have the ability to concentrate and produce high quality output in the required amount of time.
#+end_quote
**** Commentary
:PROPERTIES:
:NOTER_PAGE: (9 . 0.604798)
:END:

#+begin_quote
This pattern is different from [[id:0c40f4d8-2ae6-4cc1-9109-f4852d3b2160][Contiguous Time Blocks]]. [[id:4bfa94bc-4894-4a33-8585-52e85c752ea2][Single-Task Important Items]] does not refer to blocking off time for a task, but refers to concentration on a single important task at a time.
#+end_quote


**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (10 . 0.098485)
:END:
**** Examples
:PROPERTIES:
:NOTER_PAGE: (10 . 0.296717)
:END:
*** Put it off
:PROPERTIES:
:NOTER_PAGE: (11 . 0.090909)
:ID:       0d88a3a5-3272-478a-8c9e-76e882c723cb
:END:

#+begin_quote
You have a task to complete and you are having trouble concentrating on it either because it is complex, you are fatigued, or it is large. You find that you are having difficulty advancing the task or that the task itself is becoming more confusing. Most important, you feel you do not have a good handle on how to organize the task, its output, or both.

[Negatives]

- Procrastination can make a task more difficult to complete.
- When you are extremely fatigued, setting aside a task or sleeping may or may not help you organize your thoughts.
- It may not be possible to put it off certain tasks due to pressure to complete a task.
- Putting a task off might not result in a better organization or output.

[Positives]

- When you have trouble concentrating, the work you are trying to complete takes longer.
- When you have trouble concentrating, quality suffers.
- Complex (or boring) tasks drain your mental resources.
- Setting a problem aside gives your mind time to mull over the information it has already absorbed while you are doing other things.
- By better organizing a task or its output, it may become easier complete.

Therefore, when faced with poor concentration on a boring or complex task with a somewhat flexible deadline, stop working on it temporarily so you can collect your thoughts. It may help to sleep on the problem and begin working it anew once you awaken.
#+end_quote

**** Commentary
:PROPERTIES:
:NOTER_PAGE: (11 . 0.539141)
:END:
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (12 . 0.106061)
:END:

#+begin_quote
If you put something off that will not benefit from downtime thinking, you are essentially procrastinating – an alternate, less appealing resulting context. In addition, it is possible for you to think you can put something down in order to organize your thoughts, but if there is no plan to return to it, it is probably procrastination.
#+end_quote
**** Examples
:PROPERTIES:
:NOTER_PAGE: (12 . 0.275253)
:END:
*** Seek clarification
:PROPERTIES:
:NOTER_PAGE: (13 . 0.090909)
:ID:       aa27e79d-c327-42ad-af7f-2455aaee9c48
:END:

#+begin_quote
You have a task to complete which is vague or has vague instructions. The task may have an aggressive deadline. Just starting the task to learn its direction does not appear to be an option. Most significant, you feel that you cannot begin the task unless you have clear instructions or you obtain additional information.

[Negatives]

- By requesting clarification, you could irritate the individual or organization giving the task (discretion and politeness is required).
- The time used to clarify a task may take away from the time you have to complete it.
- Some organizations view asking for help as a sign of weakness and discourage people from seeking clarification.

[Positives]

- When a timed task is vague, you need to determine what is truly required quickly.
- Vague tasks take a lot of time to figure out and you could be wrong if you guess.
- The amount of time taken to complete a vague task takes away from other tasks.
- Obtaining clarification may help you organize your thoughts and identify the information you require to complete it.

Therefore, ask the requestor for clarification so that you can focus on completing the task.
#+end_quote
**** Commentary
:PROPERTIES:
:NOTER_PAGE: (13 . 0.482323)
:END:
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (13 . 0.849747)
:END:
#+begin_quote
Seeking clarification can backfire. This depends on the personality of the person who gives you the task and, in some cases, their power and authority. If the person giving a task believes you should know how to complete it, rather than gaining additional information to perform the task you will irritate them and perhaps lose their trust in your competence.
#+end_quote
**** Examples
:PROPERTIES:
:NOTER_PAGE: (14 . 0.232323)
:END:
*** Batch the simple stuff
:PROPERTIES:
:NOTER_PAGE: (15 . 0.090909)
:ID:       8e58ac67-07ba-4bb0-afb7-5abe570fcdc5
:END:

#+begin_quote
You have many tasks to complete and a number of them are relatively small. The tasks relate to each other. You have a sense that you are not making much progress and you have a block of time to invest in completing small, simple tasks.

[Negative]

- If too much time is spent clearing small tasks, large tasks may suffer.
- The priority of small tasks may not let you batch them together.
- Small tasks may require input from others and not lend themselves to batching.
- Many small tasks can be similar to (or more complex than) a large task.

[Positive]

- Smaller tasks take less time to complete.
- Removing things from your list of things to do gives you a sense of accomplishment.
- Grouping similar small tasks into task groups may reduce the amount of total time required to complete them.

Therefore, when faced with many small tasks, the need to feel a sense of accomplishment, and an available block of time, batch these tasks together.
#+end_quote
**** Commentary
:PROPERTIES:
:NOTER_PAGE: (15 . 0.450758)
:END:
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (15 . 0.765152)
:END:
#+begin_quote
Perhaps the most harmful alternative resulting context for this pattern is if you decide to batch simple stuff instead of completing larger and more important tasks. Though you may gain some satisfaction in completing these smaller items, when a task is unimportant, you should consider using a [[id:da6d60bb-1a96-44bb-b9b5-8646a0503665][Task Jar]] instead.
#+end_quote
**** Examples
:PROPERTIES:
:NOTER_PAGE: (16 . 0.191919)
:END:
*** Task jar
:PROPERTIES:
:NOTER_PAGE: (17 . 0.090909)
:ID:       da6d60bb-1a96-44bb-b9b5-8646a0503665
:END:
#+begin_quote
You have many tasks to complete and some of them are relatively small, well known, and not urgent. You also have several larger tasks, which require larger blocks of time or are complex. You do not have a block of time to complete these small tasks, but there is time available between other more important or larger tasks.

[Negatives]

- If you dedicate too much time to completing small tasks, large tasks may suffer.
- Stopping large tasks to complete other smaller tasks can cause both to take longer.
- Simpler tasks may take more time than is available between larger or more complex
tasks.

[Positives]

- Small tasks do not take a long time to complete.
- Removing items from your list of things to do gives you a sense of accomplishment.
- Using the time between tasks to complete other tasks can free your mind temporarily before you begin the next larger or more complex task.
- There is no advantage to doing small tasks together that do not have any affinity.

Therefore, when faced with many small non-urgent tasks that do not have any affinity, the need to feel a sense of accomplishment, and no dedicated block of time to complete them, intersperse simple tasks throughout the day in between larger or more complex tasks.
#+end_quote
**** Commentary
:PROPERTIES:
:NOTER_PAGE: (17 . 0.510101)
:END:
- Tasks should be well known; no need to [[id:aa27e79d-c327-42ad-af7f-2455aaee9c48][Seek Clarification]]
- Related:
  - [[id:8e58ac67-07ba-4bb0-afb7-5abe570fcdc5][Batch the Simple Stuff]]
  - [[id:d1afad48-d95d-4ea6-bce3-a3b88a28b995][Drop Unimportant Tasks]]
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (18 . 0.17298)
:END:

#+begin_quote
Using a "task jar" allows you to intersperse small, well-known, non-urgent tasks between larger or more complex tasks.
#+end_quote
**** Examples
:PROPERTIES:
:NOTER_PAGE: (18 . 0.40404)
:END:

*** Strike when you are hot
:PROPERTIES:
:NOTER_PAGE: (19 . 0.090909)
:ID:       7644f829-ad5c-44c0-98ba-02cb0c698c75
:END:
#+begin_quote
You have a task to do and need to progress through it quickly or make significant progress. You have times of the day when you feel you are more productive – times when you are at your intellectual, emotional, or physical best. To make significant progress or complete the task, you feel that you need to be at your best to maintain your focus..

[Negatives]

- Other tasks or outside influences may interfere with your "hot" time.
- "Hot" times can occur at bizarre hours (e.g. in the middle of the night) which, if used, can affect your performance afterward.
- Using your "hot" time to complete small tasks may or may not be the best use of that time.
- You may not be able to control the schedule of a task so that you complete it when you are hot.
- Just because you are at your mental best does not mean you will be able to concentrate.
- You may not know when your "hot" time is.

[Positives]

- Everyone has a time of day where they are at their intellectual, emotional, and physical best.
- Completing tasks when you are at your best can reduce the amount of time it takes to complete it.
- When you are at your best, you may be more efficient.

Therefore, when you have a need to move quickly through many smaller tasks or make significant progress on larger tasks, take advantage of the time of day when you are most productive by striking when you are hot.
#+end_quote
**** Commentary
:PROPERTIES:
:NOTER_PAGE: (19 . 0.60101)
:END:

#+begin_quote
This pattern has its basis in our human biology. People seem to have times of day (not all the same) that they are better at completing tasks than others. For some, it is several different times a day. It has been suggested that the frequency could be as much as every 90-110 minutes. The circadian rhythm is another such biological clock.
#+end_quote
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (20 . 0.156566)
:END:
**** Examples
:PROPERTIES:
:NOTER_PAGE: (20 . 0.368687)
:END:

*** Feedback loop
:PROPERTIES:
:NOTER_PAGE: (21 . 0.090909)
:ID:       c8ed5ee6-7756-41d2-9134-8baf2c3abe8f
:END:

Related: [[id:5664432e-6bb3-4670-9669-08ee70b5ca6d][Agile]], [[id:b785c042-ed23-44c0-b25a-91294ed9b8d0][Leo Babauta | Reset Ritual to Come Back to Focus]]

#+begin_quote
You have a task and are unable to determine how long it will take to complete. You have the information you need to begin the task, but you believe there will be additional information requirements that may emerge as you perform the task. The task itself may be vague, but you do not require clarification. You feel that you need some knowledge of the task's parts to determine how long it will take to complete.

[Negatives]

- Setting a target does not mean you will achieve it.
- You may not correctly estimate the duration of a task and waste more time having to stop the task and pick it up again after you assess your results.
- Completing a portion of the task may not give you any information about other pieces of the task.
- Unknown duration tasks can be disconcerting.

[Positives]

- It is often easier to break tasks down into sub-tasks.
- Gathering information about how long it takes you to complete a step can give you valuable information on how long it will take to complete the next step (or the entire task).
- Completing a task in tight feedback cycles may improve the overall quality of the deliverable.

Therefore, when you are uncertain how long a task is going to take, set a target for how much you expect to complete by a certain time. By setting a target, you will give yourself a point in time where you can check your progress. When you reach the target, you can check the amount of work you completed and then adjust your timeline to reflect how long you are taking.
#+end_quote
**** Commentary
:PROPERTIES:
:NOTER_PAGE: (21 . 0.59596)
:END:
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (22 . 0.098485)
:END:
**** Examples
:PROPERTIES:
:NOTER_PAGE: (22 . 0.292929)
:END:

*** Prioritize
:PROPERTIES:
:NOTER_PAGE: (23 . 0.090909)
:ID:       9c55e2ff-b170-474c-81e7-670188adf303
:END:

Related: [[id:d1afad48-d95d-4ea6-bce3-a3b88a28b995][Drop Unimportant Tasks]]

#+begin_quote
You have many tasks to complete. These tasks can be large and complex or small and simple. You have the information you need to decide which tasks are more important. Each task has a different level of importance to you or someone for whom you are completing it.

[Negatives]

- Sometimes, seemingly unimportant tasks are important.
- Often tasks originate from many different people. It is difficult to obtain general agreement from them about the relative important of all of your tasks. You have to be the judge.
- Sometimes the relationship between someone else's goals and a task you are completing is not obvious.
- Prioritizing your work may cause you to focus on things you think are important versus what others think are important.

[Positives]

- A task's level of importance is somewhat dependent upon its proximity to completion (when it is due).
- Tasks typically have different levels of importance.
- Putting the most important tasks first ensures that high value tasks are given more attention than low value tasks.

Therefore, when you have several tasks with different levels of importance, prioritize the work from the most important task to the least important task. When you prioritize tasks, consider the importance of the person requesting the task; the due date of the task; the amount of time required to do the task; the relationship between the task and your goals; and the relationship between the task and the requestor's goals. By ordering the tasks, you ensure that you do the most important tasks first.
#+end_quote
**** Commentary
:PROPERTIES:
:NOTER_PAGE: (23 . 0.613636)
:END:
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (24 . 0.098485)
:END:
**** Examples
:PROPERTIES:
:NOTER_PAGE: (24 . 0.292929)
:END:

*** Delegate
:PROPERTIES:
:NOTER_PAGE: (25 . 0.090909)
:ID:       b5246b0f-685b-4408-b79e-3b2b5e0eb601
:END:
#+begin_quote
You have a task to do for which you may not have the specific domain expertise and do not have the time to complete. You have people reporting to you or who are willing to help you complete the task. Others may be able to perform the task equal to or better than you.

[Negatives]

- People may resent you dumping your work on them.
- Delegating an important task involves a measure of risk.
- People may not complete the task within the quality and time parameters you set. However, it may be GOOD ENOUGH.
- You can spend more time explaining a task to someone than you would spend doing the task yourself.

[Positives]

- You cannot complete everything yourself.
- People are usually willing to help.
- When you are busy, you cannot complete every task assigned to you and may need to [[id:d1afad48-d95d-4ea6-bce3-a3b88a28b995][Drop Unimportant Tasks]].

Therefore, when you are faced with a task that you are responsible to complete, but do not have specific domain expertise or time, but either have people reporting to you or have people that do have time, delegate the task. Never put off for tomorrow what you can have someone else do today.
#+end_quote
**** Commentary
:PROPERTIES:
:NOTER_PAGE: (25 . 0.526515)
:END:
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (25 . 0.808081)
:END:
**** Examples
:PROPERTIES:
:NOTER_PAGE: (26 . 0.275253)
:END:

*** Drop unimportant tasks
:PROPERTIES:
:NOTER_PAGE: (27 . 0.090909)
:ID:       d1afad48-d95d-4ea6-bce3-a3b88a28b995
:END:
#+begin_quote
You have several tasks you need to complete. Some of these tasks are unimportant and may never need action. The task may have been on the bottom of your list of things to do for a very long time and may no longer be required. In addition, you may have had past experience with the requestor and can judge whether it is truly required or not.

[Negatives]

- History is not always a guide as to whether someone will need the results of a task.
- Tasks that are unimportant to you may be very important to someone else.
- A seemingly unimportant task may be a test to see if you can handle more important tasks.

[Positives]

- Understanding busywork is an important component to determining whether to drop a task.
- Some tasks are just not worth doing (so do not do them).

Therefore, when you receive an unimportant task whose completion will make no difference to anyone, drop the task. This is not an opportunity for slacking. Use this when you are overwhelmed and you are sure that the task will make no difference to anyone. This often requires very detailed knowledge of another person's needs.
#+end_quote
**** Commentary
:PROPERTIES:
:NOTER_PAGE: (27 . 0.487374)
:END:
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (27 . 0.640152)
:END:
**** Examples
:PROPERTIES:
:NOTER_PAGE: (27 . 0.842172)
:END:

*** Good enough
:PROPERTIES:
:NOTER_PAGE: (29 . 0.090909)
:ID:       3dd67ed4-d1d5-47f4-982d-164f55c8a4ff
:END:
#+begin_quote
You have several tasks you need to complete. You know that not everything that you do has to be perfect. You recognize that the level of quality for a task can be reduced, and still satisfy the requestor. You may be spending time on things that add little value.

The best is the enemy of the good. (Voltaire, Dictionnaire Philosophique. Women, 1694-1778)

- You may feel unsettled by not producing your best work.
- Some people want to produce a perfect product every time.

- Time spent perfecting something that does not require perfection is time that is lost to completing other tasks.
- The requestor may expect perfect output even if the task does not warrant it.

Therefore, reduce the level of quality to a level that will satisfy the requestor and meet their expectations. You can then complete the task more quickly. That is, you work on the task only until it is good enough. Different task outputs require different levels of perfection depending on some objective criteria and the requestors' expectations. If a task does not require a high level of precision or quality, it may be possible to put just enough effort into it to complete it.
#+end_quote
**** Commentary
:PROPERTIES:
:NOTER_PAGE: (29 . 0.570707)
:END:
**** Resulting Context
:PROPERTIES:
:NOTER_PAGE: (29 . 0.757576)
:END:

#+begin_quote
Completing tasks so that they are "good enough" and satisfy the requestor allows you to devote time to those tasks that truly do need an element of perfection.
#+end_quote
**** Examples
:PROPERTIES:
:NOTER_PAGE: (30 . 0.282828)
:END:

*** Acknowledgements
:PROPERTIES:
:NOTER_PAGE: (31 . 0.090909)
:END:
*** About the Authors
:PROPERTIES:
:NOTER_PAGE: (32 . 0.090909)
:END:
*** Appendix A:  Pattern Language Reference Diagram
:PROPERTIES:
:NOTER_PAGE: (33 . 0.090909)
:END:
*** Appendix B:  Pattern Cross Reference
:PROPERTIES:
:NOTER_PAGE: (34 . 0.090909)
:END:
*** Appendix C:  Quick Access Table
:PROPERTIES:
:NOTER_PAGE: (36 . 0.090909)
:END:
*** References
:PROPERTIES:
:NOTER_PAGE: (37 . 0.090909)
:END:

* Flashcards :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-26 Wed 09:46]
:FC_CREATED: 2022-10-26T16:48:10Z
:FC_TYPE:  double
:ID:       e72ec56d-2984-43a9-9016-67f52c1fc607
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 3.10 |   7 |   475.73 | 2024-10-26T08:40:42Z |
| back     | 2.65 |   7 |   263.95 | 2024-03-09T19:36:30Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:630c804a-cef5-42e6-a168-5a233a0acbed][Just start]]

*** Back
Start work on a task if it's initially vague and see if the steps you need to take to complete it emerge.
*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-26 Wed 09:48]
:FC_CREATED: 2022-10-26T16:49:32Z
:FC_TYPE:  double
:ID:       3468b248-2915-4ffe-879c-dc57612b6103
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.35 |   8 |   654.73 | 2025-11-02T08:13:21Z |
| back     | 1.75 |   9 |   345.55 | 2025-01-01T07:04:13Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:0c40f4d8-2ae6-4cc1-9109-f4852d3b2160][Contiguous time blocks]]

*** Back

Isolate important tasks and perform them separately --- eliminating distraction as much as is possible --- so you can concentrate and produce high quality output in the required amount of time.
*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 09:36]
:FC_CREATED: 2022-10-27T16:37:47Z
:FC_TYPE:  double
:ID:       dd9ab7f6-115f-4d15-8577-889d49856770
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   7 |   378.80 | 2024-07-06T09:14:28Z |
| back     | 2.50 |   8 |   386.75 | 2024-11-30T10:37:51Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:4bfa94bc-4894-4a33-8585-52e85c752ea2][Single-task important items]]

*** Back
Isolate important tasks and perform them separately, without multitasking, so you can concentrate and produce high quality output.
*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 09:48]
:FC_CREATED: 2022-10-27T16:49:59Z
:FC_TYPE:  double
:ID:       8a6aa55b-0c7b-4d76-a83b-d344fe0e08b5
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   7 |   341.76 | 2024-05-21T19:02:09Z |
| back     | 1.30 |   9 |    89.45 | 2024-03-03T01:41:52Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:0d88a3a5-3272-478a-8c9e-76e882c723cb][Put it off]]

*** Back
- You only have so much energy. It may be better to temporarily stop working on a task so you can collect your thoughts and re-focus.
- Be careful that it doesn't become procrastination
*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 14:37]
:FC_CREATED: 2022-10-27T21:39:14Z
:FC_TYPE:  double
:ID:       80f712a3-e250-4e31-9f9d-758eb416f3bc
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   7 |   284.33 | 2024-02-22T00:26:42Z |
| back     | 1.45 |   3 |     6.00 | 2024-02-02T18:47:45Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:aa27e79d-c327-42ad-af7f-2455aaee9c48][Seek clarification]]

*** Back

Ensure you have the requisite information to start the task. This doesn't mean you'll have answers for /everything/ related to the task -- there will still be some level of ambiguity.
*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 14:42]
:FC_CREATED: 2022-10-27T21:44:34Z
:FC_TYPE:  double
:ID:       3f369430-a1cb-4d7e-8262-0830ed6d1d50
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   7 |   353.45 | 2024-05-25T01:21:02Z |
| back     | 1.75 |   8 |   228.02 | 2024-04-11T14:24:46Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:8e58ac67-07ba-4bb0-afb7-5abe570fcdc5][Batch the simple stuff]]

*** Back
Batching small related tasks together ensures you maintain context between the tasks and gives an improved sense of accomplishment when compared to a [[id:da6d60bb-1a96-44bb-b9b5-8646a0503665][Task Jar]]-style approach.
*** Source
[cite:@kileBusyPersonPatterns2006]
** Compare and contrast :fc:
:PROPERTIES:
:FC_CREATED: 2022-11-03T16:55:13Z
:FC_TYPE:  normal
:ID:       daf94756-5226-4775-95d4-c627cad0e189
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 3.10 |   7 |   496.34 | 2024-11-26T21:56:27Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:8e58ac67-07ba-4bb0-afb7-5abe570fcdc5][Batch the simple stuff]] and [[id:da6d60bb-1a96-44bb-b9b5-8646a0503665][Task jar]]

*** Back
- [[id:8e58ac67-07ba-4bb0-afb7-5abe570fcdc5][Batch the simple stuff]] groups tasks which are related and somewhat urgent
- [[id:da6d60bb-1a96-44bb-b9b5-8646a0503665][Task jar]] serves to fill the gaps between [[id:0c40f4d8-2ae6-4cc1-9109-f4852d3b2160][Contiguous time blocks]] with tasks which are neither related nor urgent
*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 14:50]
:FC_CREATED: 2022-10-27T21:52:02Z
:FC_TYPE:  double
:ID:       b709d4d7-70a1-441b-83f3-1608d1cf321d
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 3.10 |   7 |   479.00 | 2024-11-08T13:40:15Z |
| back     | 3.25 |   7 |   452.61 | 2024-09-30T18:50:06Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:da6d60bb-1a96-44bb-b9b5-8646a0503665][Task jar]]

*** Back
Intersperse simple unrelated and non-urgent tasks between larger tasks
*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 16:08]
:FC_CREATED: 2022-10-27T23:09:11Z
:FC_TYPE:  double
:ID:       4e029bac-c9ba-4162-8a20-b893eab72157
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 3.10 |   7 |   452.70 | 2024-09-17T18:22:10Z |
| back     | 2.80 |   7 |   315.69 | 2024-04-02T06:28:27Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:7644f829-ad5c-44c0-98ba-02cb0c698c75][Strike when you are hot]]

*** Back
Schedule important work for the time of day when you are most productive/alert/etc.
*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 16:30]
:FC_CREATED: 2022-10-27T23:31:27Z
:FC_TYPE:  double
:ID:       8ef123b8-c56e-463a-bf27-08a8479c6876
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 1.90 |   8 |   301.00 | 2024-07-14T23:10:41Z |
| back     | 2.50 |   8 |   561.42 | 2025-06-19T00:39:02Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:c8ed5ee6-7756-41d2-9134-8baf2c3abe8f][Feedback loop]]

*** Back

- Set a time limit, start working, and see how far you are into the task when the time limit is up
- Break a large task down and perform short sprints to assess the complexity and time requirements of the overall task.

*** Source

[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 16:38]
:FC_CREATED: 2022-10-27T23:39:25Z
:FC_TYPE:  double
:ID:       82281281-f121-4c20-b2be-ff352189910d
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.35 |   8 |   559.58 | 2025-08-01T06:03:34Z |
| back     | 2.80 |   7 |   273.00 | 2024-02-14T12:26:41Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:9c55e2ff-b170-474c-81e7-670188adf303][Prioritize]]

*** Back
When you have more than one tasks with different levels of importance: do the work from the most important to the least important.
*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 16:47]
:FC_CREATED: 2022-10-27T23:49:35Z
:FC_TYPE:  double
:ID:       41364d44-4607-4984-902d-1c4f2d94a07d
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   7 |   345.54 | 2024-05-19T04:46:15Z |
| back     | 2.50 |   8 |   549.11 | 2025-06-09T20:30:12Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:b5246b0f-685b-4408-b79e-3b2b5e0eb601][Delegate]]

*** Back
Consider [[id:673dba4f-4d5c-4f50-9adb-ba3d5f7f2b9f][Comparative advantage]] when selecting tasks to complete and [...] when advantageous.

*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 16:52]
:FC_CREATED: 2022-10-27T23:53:23Z
:FC_TYPE:  double
:ID:       ad4e533b-f41c-4e15-8d4e-3faaddec006f
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.50 |   8 |   564.99 | 2025-05-27T16:08:15Z |
| back     | 2.20 |   8 |   475.59 | 2025-04-04T06:00:42Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:d1afad48-d95d-4ea6-bce3-a3b88a28b995][Drop unimportant tasks]]

*** Back

Don't put time into tasks which will make no difference to anyone or tasks which distract or are significantly less impactful compared to others.

*** Source
[cite:@kileBusyPersonPatterns2006]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-10-27 Thu 16:56]
:FC_CREATED: 2022-10-27T23:58:09Z
:FC_TYPE:  double
:ID:       08fbe5dd-ef4d-4420-b2a2-2af5e72ac3ff
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.50 |   8 |   495.17 | 2025-03-23T19:35:19Z |
| back     | 2.50 |   8 |   512.81 | 2025-06-05T11:51:29Z |
:END:

[[id:f1882164-0604-4dd9-ae59-df0d7b9d5ca2][James F. Kile, Donald J. Little, Samir Shah | Busy Person Patterns]]

[[id:3dd67ed4-d1d5-47f4-982d-164f55c8a4ff][Good enough]]

*** Back
Reduce the quality of your output to a level that will satisfy the requestor and meet their expectations when possible to protect against perfectionism and to give yourself time to dedicate to tasks where the extra effort will reap the greatest gains.
*** Source
[cite:@kileBusyPersonPatterns2006]
* Bibliography
#+print_bibliography:
