:PROPERTIES:
:ID:       44890929-fa24-4a69-b261-04107a005903
:LAST_MODIFIED: [2023-09-05 Tue 20:13]
:ROAM_REFS: [cite:@LoadBalancingComputing2023]
:ROAM_ALIASES: "Load balancer"
:END:
#+title: Load balancing
#+hugo_custom_front_matter: :slug "44890929-fa24-4a69-b261-04107a005903"
#+author: Cash Prokop-Weaver
#+date: [2023-03-22 Wed 08:31]
#+filetags: :concept:

#+begin_quote
In computing, load balancing is the process of distributing a set of tasks over a set of resources (computing units), with the aim of making their overall processing more efficient. Load balancing can optimize the response time and avoid unevenly overloading some compute nodes while other compute nodes are left idle.

[cite:@LoadBalancingComputing2023]
#+end_quote

* Persistence ([[id:44890929-fa24-4a69-b261-04107a005903][Load balancing]])
:PROPERTIES:
:ID:       0193a9b9-dadf-4c16-b179-da61ef3ab8c7
:ROAM_ALIASES: "Stickiness (Load balancing)"
:END:

#+begin_quote
An important issue when operating a load-balanced service is how to handle information that must be kept across the multiple requests in a user's session. If this information is stored locally on one backend server, then subsequent requests going to different backend servers would not be able to find it. This might be cached information that can be recomputed, in which case load-balancing a request to a different backend server just introduces a performance issue.

Ideally, the cluster of servers behind the load balancer should not be session-aware, so that if a client connects to any backend server at any time the user experience is unaffected. This is usually achieved with a shared database or an in-memory session database like Memcached.

One basic solution to the session data issue is to send all requests in a user session consistently to the same backend server. This is known as "persistence" or "stickiness". A significant downside to this technique is its lack of automatic failover: if a backend server goes down, its per-session information becomes inaccessible, and any sessions depending on it are lost. The same problem is usually relevant to central database servers; even if web servers are "stateless" and not "sticky", the central database is (see below).

[cite:@LoadBalancingComputing2023]
#+end_quote

* Flashcards
** Describe :fc:
:PROPERTIES:
:CREATED: [2023-03-22 Wed 08:32]
:FC_CREATED: 2023-03-22T15:33:33Z
:FC_TYPE:  double
:ID:       829d554c-9b48-48cc-b10b-76d8e2961d4d
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.50 |   7 |   216.71 | 2024-04-08T06:34:07Z |
| back     | 1.90 |   7 |    79.18 | 2023-11-07T20:15:45Z |
:END:

[[id:44890929-fa24-4a69-b261-04107a005903][Load balancing]]

*** Back
The process of distributing a set of tasks over a set of resources (computing units) with the aim of making their overall processing more efficient.
*** Source
[cite:@LoadBalancingComputing2023]
** Describe :fc:
:PROPERTIES:
:CREATED: [2023-03-22 Wed 09:10]
:FC_CREATED: 2023-03-22T16:12:50Z
:FC_TYPE:  double
:ID:       c9c90102-6388-469c-bc6e-ef0169d14bc1
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.35 |   6 |    86.72 | 2023-09-23T10:19:14Z |
| back     | 2.65 |   6 |    97.84 | 2023-10-16T12:01:54Z |
:END:

[[id:0193a9b9-dadf-4c16-b179-da61ef3ab8c7][Persistence (Load balancing)]]

*** Back
Sending all of a user's requests (either entirely or for a single session) to the same backend server.
*** Source
[cite:@LoadBalancingComputing2023]
** AKA :fc:
:PROPERTIES:
:CREATED: [2023-03-22 Wed 09:12]
:FC_CREATED: 2023-03-22T16:13:10Z
:FC_TYPE:  cloze
:ID:       08c5956c-9ac7-41ad-a149-a2dad3982b46
:FC_CLOZE_MAX: 1
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.50 |   6 |   101.05 | 2023-09-16T15:56:40Z |
|        1 | 2.80 |   6 |   136.43 | 2023-12-07T14:21:37Z |
:END:

- {{[[id:0193a9b9-dadf-4c16-b179-da61ef3ab8c7][Persistence (Load balancing)]]}@0}
- {{[[id:0193a9b9-dadf-4c16-b179-da61ef3ab8c7][Stickiness (Load balancing)]]}@1}

*** Source
[cite:@LoadBalancingComputing2023]
#+print_bibliography: