:PROPERTIES:
:ROAM_REFS: [cite:@lutterBuildInstitutionsNotApps]
:ID:       a3d2b0f5-daff-4aef-9c5f-e34ab410efa6
:LAST_MODIFIED: [2023-01-11 Wed 09:33]
:END:
#+title: Mark Lutter | Build Institutions, Not Apps
#+hugo_custom_front_matter: :slug "a3d2b0f5-daff-4aef-9c5f-e34ab410efa6"
#+author: Cash Weaver
#+date: [2023-01-10 Tue 14:22]
#+filetags: :reference:

[[id:c2a678a0-c464-4708-ac18-9a3e3eab7531][Mark Lutter]], [cite:@lutterBuildInstitutionsNotApps]

* Summary
#+begin_quote
As my friend Samo Burja likes to quip, "Silicon Valley likes to think they're above politics while in fact they're below it".
#+end_quote
* Notes
#+begin_quote
As my friend Samo Burja likes to quip, "Silicon Valley likes to think they're above politics while in fact they're below it".
#+end_quote

#+begin_quote
The result is San Francisco electing a District Attorney, Chesa Boudin, who worked for [[https://www.theguardian.com/us-news/2019/nov/10/chesa-boudin-weather-underground-san-francisco-da][Hugo Chavez]].
#+end_quote

My tribal biases are showing. I recoiled at the "this person bad because they're associated with Chavez" implication. However, I don't have a deep understanding of Chavez and have only picked up a generally positive vibe based on what I tend to read. It's an opinion loosely held.

#+begin_quote
The result is San Francisco, the most innovative city in a generation, proposing a Office of Emerging Technology to require any technology that uses public space, scooters for example, to get prior permission from the city. Politics is threatening technology and progress. Builders need to take that threat seriously if they want the freedom to build.
#+end_quote

I lived in San Francisco during the rise of the scooters and the subsequent backlash. I recall, just after parking one and walking toward my apartment, hearing a crash and seeing that someone had thrown the scooter I was riding only a minute before down onto the sidewalk. The hate was palpable.

I don't know what policies I would pursue if I was in a position of power with regard to changes and innovations in the public space. I'm sympathetic to arguments against unaccountable companies dropping hundreds of scooters across the city and the disturbance.

#+begin_quote
There is an emerging political consciousness in Silicon Valley. Technologists are advancing a new way of understanding the challenges facing America and how to solve them that do not split neatly along the traditional left right axis. However, to implement change along those new lines, there must be a will.
#+end_quote

The "X isn't left or right", in my experience, tends to mean "X is mostly right, but that doesn't sound as good to our audience". Perhaps this one is different or perhaps my view is incomplete because "traditional left right axis" doesn't have a firm definition.

#+begin_quote
Institution building is a political act and needs to be understood as such. Tech giants like Google have figured out how to lobby effectively for their own interests. However, that parochial view of protecting one's domain is no longer enough. There instead needs to be a push, a demand, for a broader set of pro-innovation reforms.

It is not enough, however, to simply call for reforms. There must be specifics. How is the current regulatory environment stifling innovation? How is NEPA limiting infrastructure? How is the FDA limiting drug development? After the specifics comes politics.

The first step to politics is the same first step that a technical founder takes when hiring their first salesperson. Just call up the best political operatives you know and learn everything you can about political influence. It is possible that much of the traditional mechanisms of political influence, think tanks, lobbyists, and media, are outdated. However, there is still much value there. It's worth approaching with an open mind to figure out what can be improved and what works well.

[...]

However, part of politics will also include building new institutions. Who is creating the Y Combinator for institution builders? Who is funding their intellectual development and empowering them with a network to execute it?

[...]

Getting there, however, requires politics. It is not enough to build apps. We must build institutions.
#+end_quote

* Flashcards
#+print_bibliography: