:PROPERTIES:
:ID:       162d37be-0ce1-4ba1-baff-101ba72fa811
:ROAM_REFS: [cite:@MasteryLearning2022]
:LAST_MODIFIED: [2023-03-03 Fri 05:59]
:END:
#+title: Mastery learning
#+hugo_custom_front_matter: :slug "162d37be-0ce1-4ba1-baff-101ba72fa811"
#+author: Cash Prokop-Weaver
#+date: [2022-12-12 Mon 19:23]
#+filetags: :has_todo:concept:

#+begin_quote
Mastery learning is a set of group-based, individualized, teaching and learning strategies based on the premise that students will achieve a high level of understanding in a given domain if they are given enough time.

[cite:@MasteryLearning2022]
#+end_quote

#+begin_quote
Mastery learning (or, as it was initially called, "learning for mastery"; also known as "mastery-based learning") is an instructional strategy and educational philosophy, first formally proposed by Benjamin Bloom [[[id:d449ac76-f230-4922-ab7c-3b65c90a4ea9][Benjamin Bloom]]] in 1968. Mastery learning maintains that students must achieve a level of mastery (e.g., 90% on a knowledge test) in prerequisite knowledge before moving forward to learn subsequent information. If a student does not achieve mastery on the test, they are given additional support in learning and reviewing the information and then tested again. This cycle continues until the learner accomplishes mastery, and they may then move on to the next stage.

Mastery learning methods suggest that the focus of instruction should be the time required for different students to learn the same material and achieve the same level of mastery. This is very much in contrast with classic models of teaching that focus more on differences in students' ability and where all students are given approximately the same amount of time to learn and the same set of instructions.

In mastery learning, there is a shift in responsibilities, so that the students' failure is considered to be more due to the instruction and not necessarily their lack of ability. This also means teachers' attention to individual students is emphasised as opposed to assessing group performance. Therefore, in a mastery learning environment, the challenge becomes providing enough time and employing instructional strategies so that all students can achieve the same level of learning.

Since its conception, mastery learning has empirically been demonstrated to be effective in improving education outcomes in a variety of settings. Its effectiveness is influenced by the subject being taught, whether testing is designed locally or nationally, course pace and the amount of feedback provided to students.

[cite:@MasteryLearning2022]
#+end_quote

* TODO [#2] Expand :noexport:

- [cite:@MasteryLearning2022]

* Flashcards
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-12-12 Mon 19:27]
:FC_CREATED: 2022-12-13T03:36:00Z
:FC_TYPE:  double
:ID:       bbc3e97a-b8aa-4f19-b074-1d82a54bc81e
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.65 |   6 |   108.43 | 2023-06-20T00:22:47Z |
| back     | 2.50 |   6 |    78.71 | 2023-05-11T09:44:27Z |
:END:

[[id:162d37be-0ce1-4ba1-baff-101ba72fa811][Mastery learning]]

*** Back
... maintains that students must achieve a level of competance (e.g., 90% on a knowledge test) in prerequisite knowledge before moving forward to learn subsequent information. If a student does not achieve success on the test, they are given additional support in learning and reviewing the information and then tested again. This cycle continues until the learner can demonstrate their correct understanding of the material, and they may then move on to the next stage.
*** Source
[cite:@MasteryLearning2022]
** Cloze :fc:
:PROPERTIES:
:CREATED: [2023-02-14 Tue 20:50]
:FC_CREATED: 2023-02-15T04:50:51Z
:FC_TYPE:  cloze
:ID:       d317ce82-fcf3-4aa6-96b4-a385a00ecec3
:FC_CLOZE_MAX: 0
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.80 |   4 |    18.02 | 2023-03-20T16:24:06Z |
:END:

{{[[id:d449ac76-f230-4922-ab7c-3b65c90a4ea9][Benjamin Bloom]]}@0} developed [[id:162d37be-0ce1-4ba1-baff-101ba72fa811][Mastery learning]]

*** Source
[cite:@MasteryLearning2022]
#+print_bibliography: