:PROPERTIES:
:ROAM_REFS: [cite:@weaverAdverseImpactPolyphasicSleepPatternsHumansReportNationalSleepFoundation2021]
:ID:       018f9541-56d8-4091-8ac8-a8ebf61060d9
:LAST_MODIFIED: [2023-09-05 Tue 20:21]
:END:
#+title: Matthew D. Weaver et al. | Adverse Impact of Polyphasic Sleep Patterns in Humans
#+hugo_custom_front_matter: :slug "018f9541-56d8-4091-8ac8-a8ebf61060d9"
#+author: Cash Weaver
#+date: [2022-11-22 Tue 09:21]
#+filetags: :reference:

[cite:@weaverAdverseImpactPolyphasicSleepPatternsHumansReportNationalSleepFoundation2021]

* Summary
#+begin_quote
Based on the current evidence, the consensus opinion is that polyphasic sleep schedules, and the sleep deficiency inherent in those schedules, are associated with a variety of adverse physical health, mental health, and performance outcomes. Striving to adopt a schedule that significantly reduces the amount of sleep per 24 hours and/or fragments sleep into multiple episodes throughout the 24-hour day is not recommended.
#+end_quote
* Thoughts
Their findings align with [[id:6a214828-bea5-47be-bac7-0f0235b0ff3c][my experience]].
* Notes
** Abstract
#+begin_quote
Polyphasic sleep is the practice of distributing multiple short sleep episodes across the 24-hour day rather than having one major and possibly a minor ("nap") sleep episode each day. While the prevalence of polyphasic sleep is unknown, anecdotal reports suggest attempts to follow this practice are common, particularly among young adults. Polyphasic-sleep advocates claim to thrive on as little as 2 hours of total sleep per day. However, significant concerns have been raised that polyphasic sleep schedules can result in health and safety consequences. We reviewed the literature to identify the impact of polyphasic sleep schedules (excluding nap or siesta schedules) on health, safety, and performance outcomes. Of 40,672 potentially relevant publications, with 2,023 selected for full-text review, 22 relevant papers were retained. We found no evidence supporting benefits from following polyphasic sleep schedules. Based on the current evidence, the consensus opinion is that polyphasic sleep schedules, and the sleep deficiency inherent in those schedules, are associated with a variety of adverse physical health, mental health, and performance outcomes. Striving to adopt a schedule that significantly reduces the amount of sleep per 24 hours and/or fragments sleep into multiple episodes throughout the 24-hour day is not recommended.
#+end_quote

* Flashcards :noexport:
