:PROPERTIES:
:ROAM_REFS: [cite:@matuschakCollectingMaterialFeelsMoreUsefulItUsually]
:ID:       1e2a38fa-57f7-4159-bbbd-7dab8a12f96e
:LAST_MODIFIED: [2023-09-05 Tue 20:21]
:END:
#+title: Andy Matuschak | Collecting Material Feels More Useful than It Usually Is
#+hugo_custom_front_matter: :slug "1e2a38fa-57f7-4159-bbbd-7dab8a12f96e"
#+author: Cash Weaver
#+date: [2023-08-04 Fri 17:26]
#+filetags: :reference:

[[id:df479fb9-f7b0-4e3a-a7eb-41849fbc190e][Andy Matuschak]], [cite:@matuschakCollectingMaterialFeelsMoreUsefulItUsually]

* Summary
[[id:ed6bc3fb-c6a6-45fe-9405-e4c74b02a5bb][Collector's fallacy]]
* Thoughts
* Notes
#+begin_quote
Accumulating tabs, saving PDFs, and making bookmarks feels like progress, but we systematically overrate its value. [[https://notes.andymatuschak.org/z8ccRLda8BqJafNxjQBpzis][Understanding requires effortful engagement]]; you are not likely to draw much understanding from a folder of barely-skimmed PDFs.

We collect material because it's easy, and because it quells the anxiety that we'll never find what we're looking at again. But really, we're often just making things worse, burying important materials in tons of secondary matter we just "don't want to lose." This notion is in contrast to [[https://notes.andymatuschak.org/zTn3g4wTm1hbkNFUvLLjpev][Knowledge work should accrete]].

[[https://zettelkasten.de/posts/collectors-fallacy/][Christian Tietze suggests]]:

#+begin_quote2
This is a first step to conquer Collector's Fallacy: to *realize that having a text at hand does nothing to increase our knowledge*.
#+end_quote2

Instead, we should [[https://notes.andymatuschak.org/zB74H9CuWrosEuqve7jZyCo][Write about what you read to internalize texts deeply]], because [[https://notes.andymatuschak.org/zKiPFE1KYieeAJs3cEaCtdf][Evergreen note-writing helps reading efforts accumulate]]. And to help steer ourselves effectively (contra [[https://notes.andymatuschak.org/zUhd6Hb5dk35PPpnCHvd6bV][Note-writing practices provide weak feedback]]), we should process collected materials in short iteration cycles, rather than letting them pile up for long periods. But! Keep in mind that [[https://notes.andymatuschak.org/zVPU3jfwihojMKindkMz7Ya][Most texts aren't worth writing detailed notes about]].

Often a good compromise is to use spaced repetition to cheaply internalize a few key details; you can come back and write real notes later if the material turns out to be valuable. See e.g. [[https://notes.andymatuschak.org/z4ipbCkPaf5wwDkpgqUFgTg][Deciding to remember something with a spaced repetition system is (aspirationally) a lightweight gesture]]
#+end_quote
* Flashcards
#+print_bibliography: