:PROPERTIES:
:ID:       f38ffe48-0117-4338-8bd5-e0b05101e64f
:ROAM_REFS: [cite:@Mnemonic2022]
:LAST_MODIFIED: [2023-09-05 Tue 20:14]
:END:
#+title: Mnemonic
#+hugo_custom_front_matter: :slug "f38ffe48-0117-4338-8bd5-e0b05101e64f"
#+author: Cash Prokop-Weaver
#+date: [2022-11-04 Fri 17:38]
#+filetags: :concept:
#+begin_quote
A mnemonic device, or memory device, is any learning technique that aids information retention or retrieval (remembering) in the human memory for better understanding.

Mnemonics make use of elaborative encoding, retrieval cues, and imagery as specific tools to encode information in a way that allows for efficient storage and retrieval. Mnemonics aid original information in becoming associated with something more accessible or meaningful—which, in turn, provides better retention of the information.

Commonly encountered mnemonics are often used for lists and in auditory form, such as short poems, acronyms, initialisms, or memorable phrases, but mnemonics can also be used for other types of information and in visual or kinesthetic forms. Their use is based on the observation that the human mind more easily remembers spatial, personal, surprising, physical, sexual, humorous, or otherwise "relatable" information, rather than more abstract or impersonal forms of information.

[cite:@Mnemonic2022]
#+end_quote

* Flashcards :noexport:
** Definition :fc:
:PROPERTIES:
:CREATED: [2022-11-22 Tue 10:50]
:FC_CREATED: 2022-11-22T18:51:16Z
:FC_TYPE:  double
:ID:       8b2bd49c-a269-4b8d-a0f9-337056679176
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   7 |   326.69 | 2024-04-26T16:31:32Z |
| back     | 2.65 |   7 |   233.50 | 2024-01-13T08:30:22Z |
:END:

[[id:f38ffe48-0117-4338-8bd5-e0b05101e64f][Mnemonic]]

*** Back
A learning technique which aids information retention or retrieval. They're commonly auditory-based (e.g. acronyms, initialisms, memorable phrases).
*** Source
[cite:@Mnemonic2022]
