:PROPERTIES:
:ROAM_REFS: [cite:@ravikantAlmanackNavalRavikantGuideWealthHappiness2020]
:ID:       f82e82a9-35fc-43d0-9784-2a30302941ff
:LAST_MODIFIED: [2024-02-18 Sun 12:14]
:END:
#+title: Naval Ravikant | The Almanack of Naval Ravikant: A Guide to Wealth and Happiness
#+hugo_custom_front_matter: :slug "f82e82a9-35fc-43d0-9784-2a30302941ff"
#+author: Cash Weaver
#+date: [2024-02-18 Sun 12:14]
#+filetags: :hastodo:reference:

TODO_AUTHOR, [cite:@ravikantAlmanackNavalRavikantGuideWealthHappiness2020]

* TODO Summary
* TODO Thoughts
* TODO [#1] Notes
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 15 | Location 221-222 | Added on Tuesday, June 30, 2015 8:48:30 PM

You're not going to get rich renting out your time. You must own equity—a piece of a business—to gain your financial freedom.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 15 | Location 225-228 | Added on Tuesday, June 30, 2015 8:48:39 PM

Pick an industry where you can play long-term games with long-term people.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 16 | Location 232-233 | Added on Tuesday, June 30, 2015 8:48:50 PM

Play iterated games. All the returns in life, whether in wealth, relationships, or knowledge, come from compound interest.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 14 | Location 213-215 | Added on Tuesday, June 30, 2015 8:49:12 PM

Seek wealth, not money or status. Wealth is having assets that earn while you sleep. Money is how we transfer time and wealth. Status is your place in the social hierarchy.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 15 | Location 216-217 | Added on Tuesday, June 30, 2015 8:49:18 PM

Understand ethical wealth creation is possible. If you secretly despise wealth, it will elude you.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 15 | Location 218-219 | Added on Tuesday, June 30, 2015 8:49:21 PM

Ignore people playing status games. They gain status by attacking people playing wealth creation games.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 15 | Location 223-224 | Added on Tuesday, June 30, 2015 8:49:28 PM

You will get rich by giving society what it wants but does not yet know how to get. At scale.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 16 | Location 239-240 | Added on Tuesday, June 30, 2015 8:49:38 PM

Learn to sell. Learn to build. If you can do both, you will be unstoppable.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 16 | Location 244-245 | Added on Tuesday, June 30, 2015 8:49:52 PM

Specific knowledge is knowledge you cannot be trained for. If society can train you, it can train someone else and replace you.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Note on page 16 | Location 244 | Added on Tuesday, June 30, 2015 8:50:20 PM

read: Tacit
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 17 | Location 248-249 | Added on Tuesday, June 30, 2015 8:50:29 PM

Building specific knowledge will feel like play to you but will look like work to others.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 19 | Location 285-286 | Added on Tuesday, June 30, 2015 8:52:07 PM

Study microeconomics, game theory, psychology, persuasion, ethics, mathematics, and computers.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 19 | Location 287-288 | Added on Tuesday, June 30, 2015 8:52:13 PM

Reading is faster than listening. Doing is faster than watching.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 19 | Location 292-293 | Added on Tuesday, June 30, 2015 8:52:28 PM

Set and enforce an aspirational personal hourly rate. If fixing a problem will save less than your hourly rate, ignore it. If outsourcing a task will cost less than your hourly rate, outsource it.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 20 | Location 299-301 | Added on Tuesday, June 30, 2015 8:52:47 PM

There are no get-rich-quick schemes. Those are just someone else getting rich off you.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 24 | Location 368-369 | Added on Tuesday, June 30, 2015 9:00:08 PM

Explaining things and talking to people.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 26 | Location 389-389 | Added on Tuesday, June 30, 2015 9:01:24 PM

"Escape competition through authenticity."
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 32 | Location 477-478 | Added on Tuesday, June 30, 2015 9:05:47 PM

Without ownership, your inputs are very closely tied to your outputs.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 32 | Location 480-480 | Added on Tuesday, June 30, 2015 9:05:59 PM

And you can't earn nonlinearly.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 33 | Location 499-500 | Added on Tuesday, June 30, 2015 9:07:09 PM

If it entertains you now but will bore you someday, it's a distraction. Keep looking.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 34 | Location 513-514 | Added on Tuesday, June 30, 2015 9:07:38 PM

If they can train you to do it, then eventually they will train a computer to do it.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 34 | Location 516-518 | Added on Tuesday, June 30, 2015 9:08:23 PM

Think about what product or service society wants but does not yet know how to get. You want to become the person who delivers it and delivers it at scale. That is really the challenge of how to make money.
==========
The Almanack of Naval Ravikant: A Guide to Wealth and Happiness (Eric Jorgenson)
- Your Highlight on page 35 | Location 535-538 | Added on Tuesday, June 30, 2015 9:09:35 PM

Forget rich versus poor, white-collar versus blue. It's now leveraged versus un-leveraged.
==========

* Bibliography
#+print_bibliography:
* TODO [#2] Flashcards :noexport:
