:PROPERTIES:
:ROAM_REFS: [cite:@nandaMeaningfulRest] [cite:@nandaPost29MeaningfulRest]
:ID:       43e87bd7-89df-40b8-9c47-dc357c05fa63
:LAST_MODIFIED: [2023-09-05 Tue 20:15]
:END:
#+title: Neel Nanda | Post 29: Meaningful Rest
#+hugo_custom_front_matter: :slug "43e87bd7-89df-40b8-9c47-dc357c05fa63"
#+author: Cash Weaver
#+date: [2022-11-29 Tue 09:41]
#+filetags: :reference:

[[id:034e5d64-198b-432c-bbba-d5936f92fe4f][Neel Nanda]], [cite:@nandaPost29MeaningfulRest]

See [[id:ef6148e5-0f53-4535-89fa-1f67b3c557b7][Meaningful rest]].

* Notes

#+begin_quote
An exercise: Set a 5 minute timer, and list the things you want to do when you feel tired and low-energy. Then, set another 5 minute timer, and list the things you feel rejuvenated after having done - the things you like doing when low-energy.

If you're anything like me, these lists are basically disjoint!

[...]

My underlying model is that the problem is one of defaults. Most situations in my life have a default response, and that takes no effort to follow. To deviate from the default response, I need to spend a scarce resource - willpower. Being tired is essentially being low on willpower, and the problem is that my default actions when low willpower do not regenerate willpower.

[...]

The solution to this is two-fold - learn to take breaks before being completely drained, so I can resist the default and take rejuvenating actions. And lower the activation energy of rejuvenating actions, to shape the default - making them as close to the default as possible.

[...]

I've been deliberately vague about exactly what to do, I expect this to vary a lot between people - I recommend brainstorming the things that you feel rejuvenated after doing and building a system such that doing those is the default. But, if it helps, this was my process:

When brainstorming what rejuvenated me, I found that being outside, away from screens, and doing something that felt pleasant and virtuous was the best source of rejuvenation per unit time. And an easy way to do this was to go lie down in my garden for 10 minutes and read a physical book (which also meant I began to actually work my way through my to-read list!). And actually doing this initially had high activation energy - I needed to get up to walk to the garden, there was less of a dopamine rush than checking messages, etc. So, for a week, I made a policy of always doing this during breaks and ensured I stuck to it - locking my phone and blocking distracting websites during breaks, having brief pings at the start and end. And I shaped my environment to make it easier, making sure to always have my current book close to hand. And I didn't perfectly stick to this, and it took some energy to do. But making it a habit significantly lowered the activation energy, and built positive associations with it, to the point that it now feels way easier. And I don't stick to it religiously, but it's now much easier to do when I feel tired.

[cite:@nandaMeaningfulRest]
#+end_quote
* Flashcards :noexport:
** See [[id:ef6148e5-0f53-4535-89fa-1f67b3c557b7][Meaningful rest]]
#+print_bibliography: