:PROPERTIES:
:ID:       b4b247dc-bca3-4368-8e0d-f8bf2e0e5c0d
:LAST_MODIFIED: [2023-10-12 Thu 23:57]
:END:
#+title: No half measures
#+hugo_custom_front_matter: :slug "b4b247dc-bca3-4368-8e0d-f8bf2e0e5c0d"
#+author: Cash Prokop-Weaver
#+date: [2023-07-21 Fri 08:24]
#+filetags: :concept:

Go all-in. It's not worth doing things half-way. The result won't satisfy you, because it didn't go far enough, and it won't satisfy others because it didn't go far enough.

However, [[id:af0b4a55-1142-4894-ad74-ee3b2926284d][Keep your eye on the prize]] and do [[id:3dd67ed4-d1d5-47f4-982d-164f55c8a4ff][Good enough]] work whenever possible. Focus your effort on high-impact, high-priority, [[id:56bf2582-14f9-47dd-beeb-dd7342c910dd][Leverage points]].

#+begin_quote
In my AP Art class, there was a girl who was just starting to experiment with mixed media. At this point she was still playing around, trying to decide what direction she wanted to go with her portfolio. So one critique day, she brought in an abstract canvas with some rhinestone highlights and painted and real peacock feathers. She loved sparkles and peacock feathers so she thought she'd try introducing them a *little*. And after everyone had given some input, the teacher gave her his advice, VERY roughly paraphrased here:

"So here's the thing… I do not like this style. These are just elements that do not speak to me personally, but I see that you like them, and you're doing interesting things with them.

"My biggest critique is, I only merely *dislike* this piece. I want you to make me HATE it. Go crazy with the things that you like. Don't hold back trying to make it palatable to people like me. Because I am NEVER going to like it. And if the audience does not like it, it should drive them crazy seeing how much YOU love it."

Her portfolio was chock full of neon colors and glitter and rhinestones and splashes of peacock feathers and it was a delight. Our teacher despised every piece lol, but she got great marks and I think even won some awards. And more importantly, she was happy and proud of the results. Because she didn't limit herself by trying to appeal to people who were never going to enjoy what she enjoyed.

[cite:@switchelsweetsMyAPArtClass]
#+end_quote

Related [[id:9e9ec4a3-93b8-4e7e-ba20-dbf557d989cb][Nate Soares | Half-Assing It with Everything You've Got]]

* Flashcards :noexport:
** Describe :fc:
:PROPERTIES:
:CREATED: [2023-07-21 Fri 10:46]
:FC_CREATED: 2023-07-21T17:46:40Z
:FC_TYPE:  double
:ID:       6c58cd57-cc27-40e7-8fe8-ed917eb6b6f5
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.35 |   6 |    80.45 | 2023-12-11T00:56:11Z |
| back     | 2.50 |   6 |    98.48 | 2024-01-19T18:22:29Z |
:END:

[[id:b4b247dc-bca3-4368-8e0d-f8bf2e0e5c0d][No half measures]]

*** Back
It's not worth doing things half-way. The result won't satisfy you, because it didn't go far enough, and it won't satisfy others because it went too far.
*** Source
[[id:b4b247dc-bca3-4368-8e0d-f8bf2e0e5c0d][No half measures]]

* Bibliography
#+print_bibliography:
