:PROPERTIES:
:ID:       e826003f-a13e-4cce-9b80-30f8bd802374
:ROAM_REFS: [cite:@NoncooperativeGameTheory2022]
:LAST_MODIFIED: [2023-09-05 Tue 20:17]
:END:
#+title: Non-cooperative game
#+hugo_custom_front_matter: :slug "e826003f-a13e-4cce-9b80-30f8bd802374"
#+author: Cash Prokop-Weaver
#+date: [2022-09-28 Wed 07:41]
#+filetags: :concept:

#+begin_quote
In [[id:e157ee7b-f36c-4ff8-bcb3-643163925c20][Game theory]], a [[id:e826003f-a13e-4cce-9b80-30f8bd802374][Non-cooperative game]] is a game with competition between individual players, as opposed to cooperative games, and in which alliances can only operate if self-enforcing (e.g. through credible threats). However, 'cooperative' and 'non-cooperative' are only technical terms to describe the theory used to model a game, so it is possible to use cooperative game theory to model competition and using non-cooperative game theory to model cooperation.

The key distinguishing feature is the absence of external authority to establish rules enforcing cooperative behavior. In the absence of external authority (such as contract law), players cannot group into coalitions and must compete independently.

[cite:@NoncooperativeGameTheory2022]
#+end_quote

* Flashcards :noexport:
** Define :fc:
:PROPERTIES:
:CREATED: [2022-09-30 Fri 15:30]
:FC_CREATED: 2022-09-30T22:31:20Z
:FC_TYPE:  double
:ID:       69feae5f-83c9-4f2b-9156-13261764076c
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   7 |   288.06 | 2024-01-11T04:36:25Z |
| back     | 2.20 |   7 |   158.31 | 2023-10-31T22:08:35Z |
:END:

[[id:e826003f-a13e-4cce-9b80-30f8bd802374][Non-cooperative game]]

*** Back

A game with competition between individual players and in which alliances must be self-enforcing; there is no external authority to establish rules which enforce cooperative behavior.
*** Source
[cite:@NoncooperativeGameTheory2022]
* Bibliography
#+print_bibliography:
