:PROPERTIES:
:ID:       0839455d-cb61-49a6-b3d3-b76c23b3caa2
:LAST_MODIFIED: [2023-09-05 Tue 20:21]
:END:
#+title: November 2022
#+hugo_custom_front_matter: :slug "0839455d-cb61-49a6-b3d3-b76c23b3caa2"
#+author: Cash Prokop-Weaver
#+date: [2022-12-06 Tue 08:06]
#+filetags: :newsletter:

[[id:671006e6-3f41-4c37-9840-1a0a1c3f2496][Monthly newsletter]] for November, 2022.

* This month

- Created flashcards for all existing notes

  One of the reasons [[id:7add4362-8a4e-4148-ac25-185213327b33][Why I write notes]] is to remember what I've learned. In the past, I wasn't diligent about creating flashcards when adding a new note. As a result, there were hundreds of notes with missing or inadequate flashcards. My main goal for this month was to fill in the gaps and I succeeded!

- Assorted improvements to cashpw.com

  1. Switched the theme from [[github:adityatelange/hugo-PaperMod][PaperMod]] to [[github:reorx/hugo-PaperModX][PaperModX]] for sidebar support
  2. Fixed broken Google Analytics
  3. Dark mode by default

* Next month

- Catch up on flashcard review backlog

  I have >400 outstanding flashcards. Reviewing them all at once wouldn't just hurt now, it would hurt forever as from time to time I'd see a similarly-sized spike of due flashcards. I'll do 50-100 per day to spread them out.

  This is important as I want to review new flashcards soon after creating them. Creating a flashcard on Monday and first seeing it in review on the following Monday is a poor learning experience. I'm holding off on creating new flashcards until I get through the backlog.

* Flashcards :noexport::noexport:
* Bibliography
#+print_bibliography:
