:PROPERTIES:
:ID:       18f7f0b6-d7e3-4659-a80d-35ca6f3a9da1
:LAST_MODIFIED: [2024-01-25 Thu 07:40]
:END:
#+title: On business
#+hugo_custom_front_matter: :slug "18f7f0b6-d7e3-4659-a80d-35ca6f3a9da1"
#+author: Cash Prokop-Weaver
#+date: [2023-12-26 Tue 12:27]
#+filetags: :concept:

An [[id:2a6113b3-86e9-4e70-8b81-174c26bfeb01][On X]].

* Misc

#+begin_quote
While I like the sentiment here, I think the danger is that engineers might come to the mistaken conclusion that making pizzas is the primary limiting reagent to running a successful pizzeria. Running a successful pizzeria is more about schlepping to local hotels and leaving them 50 copies of your menu to put at the front desk, hiring drivers who will both deliver pizzas in a timely fashion and not embezzle your (razor-thin) profits while also costing next-to-nothing to employ, maintaining a kitchen in sufficient order to pass your local health inspector's annual visit (and dealing with 47 different pieces of paper related to that), being able to juggle priorities like "Do I take out a bank loan to build a new brick-oven, which will make the pizza taste better, in the knowledge that this will commit $3,000 of my cash flow every month for the next 3 years, or do I hire an extra cook?", sourcing ingredients such that they're available in quantity and quality every day for a fairly consistent price, setting prices such that they're locally competitive for your chosen clientele but generate a healthy gross margin for the business, understanding why a healthy gross margin really doesn't imply a healthy net margin and that the rent still needs to get paid, keeping good-enough records such that you know whether your business is dying before you can't make payroll and such that you can provide a reasonably accurate picture of accounts for the taxation authorities every year, balancing 50% off medium pizza promotions with the desire to not cannibalize the business of your regulars, etc etc, and by the way tomato sauce should be tangy but not sour and cheese should melt with just the faintest whisp of a crust on it.

Do you want to write software for a living? Google is hiring. Do you want to run a software business? Godspeed. Software is now 10% of your working life.

[cite:@patio11SentimentHereThinkDangerThatEngineersMightCome]
#+end_quote

* Bibliography
#+print_bibliography:
* Flashcards :noexport:
