:PROPERTIES:
:ID:       dab3f3c1-9065-40e9-ab93-a0fed22a4f25
:LAST_MODIFIED: [2024-02-08 Thu 12:30]
:END:
#+title: On interviewing
#+hugo_custom_front_matter: :slug "dab3f3c1-9065-40e9-ab93-a0fed22a4f25"
#+author: Cash Prokop-Weaver
#+date: [2024-01-14 Sun 06:41]
#+filetags: :hastodo:concept:

An [[id:2a6113b3-86e9-4e70-8b81-174c26bfeb01][On X]].

* TODO [#3] Expand
** Questions to ask interviewers

Have questions prepared ahead of your interview. Your questions [[id:162ff5b9-ad28-45b4-9ffb-4dd5f00e2c09][should accomplish two goals]]: (1) help you decide whether or not to take the job, should they make an offer, and (2) [[id:0a3904f5-1484-4c12-8abb-005c707401e1][Signal]] that you're an above-average candidate.

#+begin_quote
Understanding what this interviewer cares about

- What prompted you to post this job?
  - Trying to get a sense of how they made the decision to hire.
- How does your boss evaluate whether you've been successful in your role or not?
  - note: i am asking about how the person interviewing me is evaluated by their own boss. the answer to this will answer many questions about how the business works and what the role will most likely involve.
  - this is basically to get a sense of what they care about and what their boss cares about, which in turn hints at what I would need to care about
- What do you see as being the biggest challenges to overcome in the coming year for your department?
  - checking if anything related to this position mentioned; if not, this could be a role that won't be seen as particularly valued and will likely change significantly / could be first in line for cuts.

Understanding the business

- Help me understand how the business works, my understanding is <how they make money>; is that roughly correct?
  - Does the business plan make sense? Any obvious holes?
- What is the value proposition from the perspective of your champion clients?
  - What do the clients like about the product / business? does my interviewer seem like they genuinely know the answer to this or does it seem like they are repeating a single sentence they once heard before?
- What are the financial goals of the business for EOY 2024 & what does the path there roughly need to look like?
  - What needs to happen in the next year. does it sound doable? or like a developer death march?

Understanding the tech stack

- It's really hard to give pre-canned questions for this. Will generally ask what their tech stack looks like and why. Goal is to understand how they think about tech and how they approach selecting their infrastructure.
- Some I would almost always ask, but not as written:
  - How do you handle production issues? (aka; will I be on call?)
  - What monitoring and alerting tools do you use?
  - How does the technical department validate their software works as expected?
  - What does the release process look like?

[Q]uestions I don't ask

- "Take me through a typical day" / "Take me through a typical change"
  - generally this can vary a lot person by person within a department. the interviewer ends up describing their "ideal day" that does not actually represent what the typical day is like at all
- "What does success look like in this role?"
  - this seems like a good question but more often then not you get read back the job description.
  - the other half of the time they say what they think success will look like, but there will be additional unstated expectations and objectives for the role
- "What's a problem at your org you still feel like hasn't been solved well yet"
  - people usually say something random like "dependency management", when actually dependency management is fine for where the business is at and not a real problem at all.

[cite:@normaluserthirtyNoParticularOrd2024], formatting mine
#+end_quote

** TODO [#2] [[https://github.com/donnemartin/system-design-primer][GitHub – system-design-primer: Learn how to design large-scale systems]] :systems:software_engineering:
:PROPERTIES:
:CREATED: [2023-10-29 07:41]
:END:
** TODO [#2] [[https://www.reddit.com/r/ExperiencedDevs/comments/17dm8eg/interviewing_a_new_potential_boss/][Interviewing a new potential boss.]] :unlabeled:
:PROPERTIES:
:CREATED: [2023-10-22 05:39]
:END:

* Flashcards :noexport:

* Bibliography
#+print_bibliography:
