:PROPERTIES:
:ID:       b2910eeb-51c9-44da-99fa-b852ef70e7e6
:LAST_MODIFIED: [2023-09-05 Tue 20:18]
:END:
#+title: One-bag travel
#+hugo_custom_front_matter: :slug "b2910eeb-51c9-44da-99fa-b852ef70e7e6"
#+author: Cash Prokop-Weaver
#+date: [2023-08-14 Mon 05:39]
#+filetags: :concept:

One-bag traveling is just that --- traveling with only a single bag. Everything you bring with, aside from what you wear on your person, should fit within that one bag. The bag is usually a backpack in the 20--40 liter range, though there are some who use much smaller bags (e.g. Jeremy Maluf who, as of 2023, [[https://jeremymaluf.com/onebag/][uses a 9 liter backpack]]). It's [[id:6c52974d-5e46-46fd-bbdf-ec3d842a7860][Minimalism]] applied to the things you bring with you on a trip.

The culture associated with one-bag travel, at least as I've seen it online, overlaps with [[id:f3970b88-9d58-44fa-ade2-fee34f20a610][Digital nomadism]] and (recently) [[id:aa610825-4313-4028-8972-8f25919a73d2][Minimalist shoes]].

* Why?

#+begin_quote
Onebag travel is the best way to travel since it removes most of the pain points involved. No rushing to the airport early to check bags, no searching for an overhead compartment, no bag fees or worrying about stuff getting lost, and no adjusting plans to drop off luggage before an adventure

[cite:@malufIndefiniteBackpackTravel]
#+end_quote
* Packing lists

- [[id:545708ae-0765-4454-bb7b-11da616f0711][My one-bag packing list]]
- [[reddit:r/onebag][r/onebag]]

* Flashcards :noexport:
#+print_bibliography: