:PROPERTIES:
:ROAM_REFS: [cite:@Ozymandias2022]
:ID:       7aa8dfb5-3aba-45b6-a6b5-0e718403d237
:DIR:      /home/cashweaver/proj/roam/attachments/7aa8dfb5-3aba-45b6-a6b5-0e718403d237
:ROAM_ALIASES: "Nothing beside remains" "The lone and level sands stretch far away" "Look on my works, ye Mighty, and despair!" "Ozymandias (Poem)"
:LAST_MODIFIED: [2023-09-05 Tue 20:15]
:END:
#+title: Percy Bysshe Shelley | Ozymandias
#+hugo_custom_front_matter: :slug "7aa8dfb5-3aba-45b6-a6b5-0e718403d237"
#+author: Cash Prokop-Weaver
#+date: [2022-02-26 Sat 18:30]
#+filetags: :poem:
 
#+begin_verse
I met a traveller from an antique land
Who said: "Two vast and trunkless legs of stone
Stand in the desert. Near them, on the sand,
Half sunk, a shattered visage lies, whose frown,
And wrinkled lip, and sneer of cold command,
Tell that its sculptor well those passions read
Which yet survive, stamped on these lifeless things,
The hand that mocked them and the heart that fed:
And on the pedestal these words appear:
"My name is Ozymandias, king of kings;
Look on my works, ye Mighty, and despair!"
Nothing beside remains. Round the decay
Of that colossal wreck, boundless and bare
The lone and level sands stretch far away."
#+end_verse

[[id:0d6d106f-5a90-4dff-83ce-0eef1db38c61][Percy Bysshe Shelley]], [cite:@Ozymandias2022]

* Flashcards
** Poem :fc:
:PROPERTIES:
:FC_CREATED: 2022-09-16T03:11:06Z
:FC_TYPE:  cloze
:ID:       245870cd-834d-47b3-a7ac-053649361b30
:FC_CLOZE_MAX: 13
:FC_CLOZE_TYPE: context
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.95 |   7 |   407.85 | 2024-08-05T09:44:37Z |
|        1 | 2.80 |   7 |   356.78 | 2024-06-08T22:47:13Z |
|        2 | 1.30 |   3 |     6.00 | 2023-09-06T18:34:09Z |
|        3 | 1.30 |   4 |     7.23 | 2023-09-04T18:28:07Z |
|        4 | 1.30 |   9 |    68.42 | 2023-09-17T23:13:49Z |
|        5 | 1.30 |   7 |    20.17 | 2023-09-19T16:55:56Z |
|        6 | 1.30 |   8 |    28.99 | 2023-09-30T14:05:54Z |
|        7 | 2.05 |   5 |    25.96 | 2023-08-12T12:54:27Z |
|        8 | 1.75 |   3 |     6.00 | 2023-08-10T15:17:51Z |
|        9 | 2.50 |   4 |    15.64 | 2023-04-24T06:28:28Z |
|       10 | 2.80 |   4 |    18.10 | 2023-04-27T18:09:31Z |
|       11 | 2.50 |   2 |     2.00 | 2023-04-05T15:22:40Z |
|       12 |  2.5 |  -1 |        0 | 2022-01-01T13:00:00Z |
|       13 |  2.5 |  -1 |        0 | 2022-01-01T13:00:00Z |
:END:

[[id:7aa8dfb5-3aba-45b6-a6b5-0e718403d237][Ozymandias (Poem)]]

#+begin_verse
{{I met a traveler from an antique land}@0}
{{Who said: "Two vast and trunkless legs of stone}@1}
{{Stand in the desert. Near them, on the sand,}@2}
{{Half sunk, a shattered visage lies, whose frown,}@3}
{{And wrinkled lip, and sneer of cold command,}@4}
{{Tell that its sculptor well those passions read}@5}
{{Which yet survive, stamped on these lifeless things,}@6}
{{The hand that mocked them and the heart that fed:}@7}
{{And on the pedestal these words appear:}@8}
{{"My name is Ozymandias, king of kings;}@9}
{{Look on my works, ye Mighty, and despair!"}@10}
{{Nothing beside remains. Round the decay}@11}
{{Of that colossal wreck, boundless and bare}@12}
{{The lone and level sands stretch far away."}@13}
#+end_verse
** Poem (full) :fc:
:PROPERTIES:
:FC_CREATED: 2022-11-16T17:26:40Z
:FC_TYPE:  normal
:ID:       7eeb22b2-e4a8-4a58-93b5-c133354cc4a0
:FC_BLOCKED_BY:       245870cd-834d-47b3-a7ac-053649361b30
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    |  2.5 |  -1 |        0 | 2022-11-16T17:26:40Z |
:END:
[[id:7aa8dfb5-3aba-45b6-a6b5-0e718403d237][Ozymandias (Poem)]]

*** Back
#+begin_verse
{{I met a traveler from an antique land}@0}
{{Who said: "Two vast and trunkless legs of stone}@1}
{{Stand in the desert. Near them, on the sand,}@2}
{{Half sunk, a shattered visage lies, whose frown,}@3}
{{And wrinkled lip, and sneer of cold command,}@4}
{{Tell that its sculptor well those passions read}@5}
{{Which yet survive, stamped on these lifeless things,}@6}
{{The hand that mocked them and the heart that fed:}@7}
{{And on the pedestal these words appear:}@8}
{{"My name is Ozymandias, king of kings;}@9}
{{Look on my works, ye Mighty, and despair!"}@10}
{{Nothing beside remains. Round the decay}@11}
{{Of that colossal wreck, boundless and bare}@12}
{{The lone and level sands stretch far away."}@13}
#+end_verse
** {{[[id:0d6d106f-5a90-4dff-83ce-0eef1db38c61][Percy Bysshe Shelley]]}@0} wrote [[id:7aa8dfb5-3aba-45b6-a6b5-0e718403d237][Ozymandias]] :fc:
:PROPERTIES:
:FC_CREATED: 2022-09-21T15:43:30Z
:FC_TYPE:  cloze
:ID:       1efa1a89-7e02-448b-a3e8-f014b33cfe29
:FC_CLOZE_MAX: 1
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.20 |   7 |   148.03 | 2023-09-19T17:21:07Z |
:END:
#+print_bibliography: