:PROPERTIES:
:ROAM_REFS: [cite:@grahamWhatYouWantWant]
:ID:       6e6aa331-8dbf-4751-a896-ca5fc6c7128b
:LAST_MODIFIED: [2023-10-30 Mon 08:01]
:END:
#+title: Paul Graham | What You (Want to)* Want
#+hugo_custom_front_matter: :slug "6e6aa331-8dbf-4751-a896-ca5fc6c7128b"
#+author: Cash Weaver
#+date: [2023-01-14 Sat 07:57]
#+filetags: :reference:

[[id:8a9360e0-306a-422a-804f-e2fd6664b8fe][Paul Graham]], [cite:@grahamWhatYouWantWant]

* Summary
People can change lower-order desires (e.g. "I want to eat junk food" to "I don't want to eat junk food") based on their higher-level desires (e.g. "I want to not want to eat junk food" drives my transition away from wanting to eat junk food). This change becomes harder as you move up to higher-level desires (e.g. Can I change "I want to not want to eat junk food"?). At some point you bump up against the fundamental underlying philosophical reasons that you're you and not someone else.
* Thoughts
[[id:d923e2b9-8907-4cbb-9874-4b638f9f0aba][How to change]]
* Notes

#+begin_quote
The best way to explain the answer may be to start with a slightly wrong version, and then fix it. The wrong version is: You can do what you want, but you can't want what you want. Yes, you can control what you do, but you'll do what you want, and you can't control that.

The reason this is mistaken is that people do sometimes change what they want. People who don't want to want something — drug addicts, for example — can sometimes make themselves stop wanting it. And people who want to want something — who want to like classical music, or broccoli — sometimes succeed.

So we modify our initial statement: You can do what you want, but you can't want to want what you want.

That's still not quite true. It's possible to change what you want to want. I can imagine someone saying "I decided to stop wanting to like classical music." But we're getting closer to the truth. It's rare for people to change what they want to want, and the more "want to"s we add, the rarer it gets.
#+end_quote

* Flashcards
** Describe :fc:
:PROPERTIES:
:CREATED: [2023-01-14 Sat 08:00]
:FC_CREATED: 2023-01-14T16:05:07Z
:FC_TYPE:  double
:ID:       4b113043-9003-42eb-826f-a0140024404b
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.20 |   8 |   312.44 | 2024-09-07T01:29:43Z |
| back     | 2.35 |   8 |   356.34 | 2024-10-07T16:25:39Z |
:END:

You can't (want to)* want what you want

*** Back
People can change lower-order desires (e.g. "I want to eat junk food" to "I don't want to eat junk food") based on their higher-level desires (e.g. "I want to not want to eat junk food" drives my transition away from wanting to eat junk food). This change becomes harder as you move up to higher-level desires (e.g. Can I change "I want to not want to eat junk food"?). At some point you bump up against the fundamental underlying philosophical reasons that you're you and not someone else.
*** Source
[cite:@grahamWhatYouWantWant]
#+print_bibliography: