:PROPERTIES:
:ID:       38e99d29-6d02-4ae9-907f-2f8730ee5128
:LAST_MODIFIED: [2023-12-19 Tue 15:59]
:END:
#+title: Perfectionism
#+hugo_custom_front_matter: :slug "38e99d29-6d02-4ae9-907f-2f8730ee5128"
#+author: Cash Prokop-Weaver
#+date: [2023-12-19 Tue 15:55]
#+filetags: :concept:

#+begin_quote
Researchers in the field may not be able to agree on the perfect definition, but we will be using the
following definition of perfectionism, which has three key parts:

1. The relentless striving for extremely high standards (for yourself and/or others) that are personally demanding, in the context of the individual. (Typically, to an outsider the standards are considered to be unreasonable given the circumstances.) [...] 'unrelenting standards'.
2. Judging your self-worth based largely on your ability to strive for and achieve such unrelenting standards.
3. Experiencing negative consequences of setting such demanding standards, yet continuing to go for them despite the huge cost to you. We would agree that it is generally a good idea to have high standards. Having goals helps you achieve things in life. BUT when these goals are either unachievable or only achievable at great cost, it makes it very difficult to feel good about yourself.

/[[id:f69f4ded-8216-45c1-aa9d-e883fcfc2b36][Centre for Clinical Interventions: Perfectionism in Perspective]]/
#+end_quote
* Flashcards :noexport:
