:PROPERTIES:
:ID:       a99628b8-d0a3-4951-8234-ba96fd820950
:LAST_MODIFIED: [2023-09-05 Tue 20:17]
:END:
#+title: Pistol squat progression
#+hugo_custom_front_matter: :slug "a99628b8-d0a3-4951-8234-ba96fd820950"
#+author: Cash Prokop-Weaver
#+date: [2023-08-10 Thu 09:17]
#+filetags: :concept:

* My preferred

#+begin_quote
[[youtube:Yi0XP1ty4C0][Pistol Squat Tutorial - Single-Leg Strength & Balance]]

1. Deep Squat
   - Start by making sure you can get into a deep squat, bringing your butt close to your heels while keeping a straight back.
   - Work on that until you are ready to move on to the next step.
2. Roll Back
   - Grab your ankles in the squat position and roll back, letting your butt come off the ground a bit.
3. Roll Back Up Into the Squat
   - Holding on to your ankles, roll your body back up into a deep squat position.
   - Work on this progression until you feel comfortable enough to move on.
4. Extend One Leg
   - Roll your body up into a squat position, but this time, keep one leg straight, and pop up very slightly with your bent leg.
5. Pop Up to Standing
   - Work on popping up a little higher each time you roll up, until you can pop all the way up into a standing position.
6. Reverse Direction
   - Next, you'll go in the opposite direction: Stand up and squat back, keeping one leg straight, then roll back into a supine position.
7. Do a Full Pistol Squat
   - Work on the previous progression until you can squat down with control, and stand back up with control.
#+end_quote

* Alternatives
#+begin_quote
The single leg variations for the pistol squats itself aren't too hard to start now. Follow this progression from [[https://www.youtube.com/watch?v=t7Oj8-8Htyw][my video:]]

- Chair Pistol Squats
- Box Pistol Squats
- Lower Box Pistol Squats
- Pistol Squats with a Counterweight (arms straight out in front of you, optional but helpful for many)
- Pistol Squats

[cite:@kizirianPistolSquatProgression2023]
#+end_quote

* Flashcards :noexport:
#+print_bibliography: