:PROPERTIES:
:ID:       4398317e-6aa1-4dd4-b2a5-6334256ca2cc
:DIR:      /home/cashweaver/proj/roam/attachments/4398317e-6aa1-4dd4-b2a5-6334256ca2cc
:LAST_MODIFIED: [2024-01-10 Wed 07:39]
:END:
#+title: Play to win
#+hugo_custom_front_matter: :slug "4398317e-6aa1-4dd4-b2a5-6334256ca2cc"
#+author: Cash Prokop-Weaver
#+date: [2022-02-16 Wed 19:22]
#+filetags: :hastodo:concept:


- Involves understanding your goals and non-goals and playing the game accordingly
  - Examples
    - If your goal is to make money by selling clothing, then a non-goal could be "make the best quality clothing". You could, instead, focus on branding or marketing while producing low-quality clothing.
    - If your goal is to pass a class, then a non-goal would be to write the best essay. You need only write a good-enough essay such that you pass the class.
    - If your goal is getting promoted, then a non-goal would be doing each project to perfection. A better strategy may be to do a few things to 80% rather than one thing to 100%.
- https://commoncog.com/blog/playing-to-play-playing-to-win/
- https://news.ycombinator.com/item?id=28608436
- https://www.sirlin.net/articles/playing-to-win
  - [cite:@sirlinIntroducingScrub2014]
  - [cite:@sirlinPlayingWin]
- Greedy algorithms
- Local, rather than global, maxima
- Unwritten rules or, perhaps another way of stating it, the penumbra of the rule set
- As an extension: Play to win doesn't have to imply that you're trying to win for winning's sake. It is also reasonable to incorporate play to win strategies to serve a larger goal -- a goal that you set. Play to win strategies do not defin what "winning" is -- only you do. Yes, "scrub" playstyles can win the match but perhaps you're not trying to win the match but rather trying to win a loyal following or aclaim. Scrub playstyles, in these situations, may be sub-optimal. Play to win only requires you to identify the optimal strategies within the rule set, written or un-written, and employ those in pursuit of your goal.

This is one of my [[id:2a586a0e-eddc-4903-9c90-7e3a91e3204c][Favorites]].

* TODO [#3] Expand :noexport:
* TODO [#3] Flashcards :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:
* Bibliography
#+print_bibliography:
