:PROPERTIES:
:ID:       4398317e-6aa1-4dd4-b2a5-6334256ca2cc
:DIR:      /home/cashweaver/proj/roam/attachments/4398317e-6aa1-4dd4-b2a5-6334256ca2cc
:END:
#+title: Play to win
#+hugo_custom_front_matter: :slug "4398317e-6aa1-4dd4-b2a5-6334256ca2cc"
#+author: Cash Prokop-Weaver
#+date: [2022-02-16 Wed 19:22]
#+filetags: :has_todo:concept:


- https://commoncog.com/blog/playing-to-play-playing-to-win/
- https://news.ycombinator.com/item?id=28608436
- https://www.sirlin.net/articles/playing-to-win
- Greedy algorithms
- Local, rather than global, maxima
- Unwritten rules or, perhaps another way of stating it, the penumbra of the rule set
- As an extension: Play to win doesn't have to imply that you're trying to win for winning's sake. It is also reasonable to incorporate play to win strategies to serve a larger goal -- a goal that you set. Play to win strategies do not defin what "winning" is -- only you do. Yes, "scrub" playstyles can win the match but perhaps you're not trying to win the match but rather trying to win a loyal following or aclaim. Scrub playstyles, in these situations, may be sub-optimal. Play to win only requires you to identify the optimal strategies within the rule set, written or un-written, and employ those in pursuit of your goal.

* TODO [#3] Expand :noexport:
* TODO [#3] Flashcards
:PROPERTIES:
:ANKI_DECK: Default
:END:
