:PROPERTIES:
:ID:       ba1c8bfe-7353-4fac-9202-768763ba4692
:LAST_MODIFIED: [2023-09-05 Tue 20:17]
:END:
#+title: Project intake form
#+hugo_custom_front_matter: :slug "ba1c8bfe-7353-4fac-9202-768763ba4692"
#+author: Cash Prokop-Weaver
#+date: [2022-10-27 Thu 10:06]
#+filetags: :has_todo:concept:
* TODO [#2]

Intake form for new projects, or at least projects to which I'm new.

Include things like:

- A three-sentence description of the project
- Who are 1-3 others who (1) understand and (2) can speak to the importance of the project and (3) my importance in the project landing?
  - The opinion of these individuals should "matter". That is, ideally they're one or two promotion levels above me.
- Who are the stakeholders?
- Why is this project worth our time?
  - Why does this project matter?
  - Phrase in terms of arguing the importance of the project to a L+3 who doesn't have prior context
- What is the timeline? What are the deadlines?
  - What confidence level do we give this timeline?
  - Are there sub-timelines?
    - Assign confidence level
  - For an existing project: Have we had timelines in the past which we've already overshot?
- How do we define success for this project?
- What are the milestones?
  - Associated deadlines?
  - How do we define success for this milestone?
  - Can more than one person work on the milestones in parallel?

Also see [[id:f1e1fb6c-5dbd-45fa-85cb-6d7fc7551486][Split "Lessons learned" into nodes]].

* TODO [#2] Flashcards
