:PROPERTIES:
:ID:       0b3c28aa-ab9a-4a99-8dbf-4f22a6e7dee9
:LAST_MODIFIED: [2023-10-31 Tue 10:18]
:END:
#+title: Retrospective
#+hugo_custom_front_matter: :slug "0b3c28aa-ab9a-4a99-8dbf-4f22a6e7dee9"
#+author: Cash Prokop-Weaver
#+date: [2022-11-18 Fri 12:27]
#+filetags: :hastodo:concept:
* TODO [#4]
* TODO [#4] As a tool for improvement
:PROPERTIES:
:ID:       8d489ad2-03d1-411b-a73b-4524147fecb6
:END:

As a rough draft:

- Reflect on the past to turn it into a series of lessons and shorten [[id:c8ed5ee6-7756-41d2-9134-8baf2c3abe8f][Feedback loop]]
  - Transform one-and-done events into events-with-feedback by analyzing them soon after they occur
  - Time sensitive
    - Do the retrospective as soon as reasonably possible. Ideally immediately after the event.
- Examples
  - Video games
    - Watch your replays and identify deficiencies
      - Compare against replays from those who play better than you
  - Weight lifting
    - Record yourself on your phone to diagnose and improve your form
  - A project at your job
    - Perform retrospectives at each milestone (which should be small enough to be 1-2 weeks of effort) and again at the end of the project
  - Public speaking
    - Record yourself and critique yourself
    - Have someone be present for your talk (or watch the recording) and give notes afterward
  - Writing, drawing, art, etc
    - Have others who can write better than you can review prior to publishing. Expect to go through multiple rounds of feedback.
    - Take your ego out of it.
  - [[id:eefb478b-2083-4445-884d-755005a26f2f][Ceramics]]
    - Record yourself throwing and critique your form. Send the video to people you respect and have them critique you.
    - Produce pots and have people who know more than you critique them.

This is all coupled with [[id:be380da4-4720-4978-a3f8-c99a9470f509][Embrace discomfort]]; specifically: embrace looking foolish or like you don't know what you're doing. You have to get over that hurdle in order to progress. Yes cheff, thank you chef; etc.

Also coupled with [[id:6a2ada0e-607b-419c-8137-cfd7fa113bfe][Seek out feedback and accept with gratitude]].

* Flashcards :noexport:
