:PROPERTIES:
:ROAM_REFS: [cite:@hansonThisDreamTime]
:ID:       35ea6ba6-1937-4a70-befa-81191ff059fa
:LAST_MODIFIED: [2023-01-08 Sun 19:21]
:END:
#+title: Robin Hanson | This Is the Dream Time
#+hugo_custom_front_matter: :slug "35ea6ba6-1937-4a70-befa-81191ff059fa"
#+author: Cash Weaver
#+date: [2023-01-08 Sun 18:52]
#+filetags: :reference:

[[id:c5c893c1-84c9-4ea7-9cad-ba258e494400][Robin Hanson]], [cite:@hansonThisDreamTime]

* Summary
I've moved this into [[id:4d1a0eba-1f0f-4634-b574-6d66b7afa9b8][This is the dreamtime]].
* Notes
#+begin_quote
We will soon [[http://www.overcomingbias.com/2009/09/how-is-our-era-unique.html][enter an era]] where most anyone can at any time talk directly with most anyone else who can talk. Cheap global talk and travel continue to tie our global economy and culture more closely together. But in the distant future, our descendants will probably have spread out across space, and redesigned their minds and bodies to explode Cambrian-style into a vast space of possible creatures. If they are free enough to choose where to go and what to become, our distant descendants will fragment into diverse local economies and cultures.

Given a similar freedom of fertility, most of our distant descendants will also live near a subsistence level. Per-capita wealth has only been rising lately because income has grown faster than population. But if income only doubled every century, in a million years that would be a factor of 10^{3000}, [[http://www.overcomingbias.com/2009/09/limits-to-growth.html][which seems]] impossible to achieve with only the 10^{70} atoms of our galaxy available by then. Yes we have seen a remarkable demographic transition, wherein richer nations have fewer kids, but we already see contrarian subgroups like Hutterites, Hmongs, or Mormons that grow much faster. So unless strong central controls prevent it, over the long run such groups [[http://www.overcomingbias.com/2009/09/future-fertility.html][will easily grow]] faster than the economy, making per person income drop to near subsistence levels. Even so, they will be [[http://www.overcomingbias.com/2009/09/poor-folks-do-smile.html][basically happy]] in such a world.

Our distant descendants will also likely have hit diminishing returns to discovery; by then most everything worth knowing will be known by many; truly new and important discoveries will be quite rare. Complete introspection will be feasible, and immortality will be available to the few who can afford it. Wild nature will be mostly gone, and universal coordination and destruction will both be far harder than today.

So what will these distant descendants think of their ancestors? They will find much in common with our distant hunting ancestors, who also continued for ages at near subsistence level in a vast fragmented world with slow growth amid rare slow contact with strange distant cultures. While those ancestors were quite ignorant about their world, and immersed in a vast wild nature instead of a vast space of people, their behavior was still pretty well adapted to the world they lived in. While they suffered many misconceptions, those illusions rarely made them much worse off; their behavior was usually adaptive.

When our distant descendants think about our era, however, differences will loom larger. Yes they will see that we were more like them in knowing more things, and in having less contact with a wild nature. But our brief period of very rapid growth and discovery and our globally integrated economy and culture will be quite foreign to them. Yet even these differences will pale relative to one huge difference: our lives are far more dominated by consequential delusions: wildly false beliefs and non-adaptive values that matter. While our descendants may explore delusion-dominated virtual realities, they will well understand that such things cannot be real, and don't much influence history. In contrast, we live in the brief but important "dreamtime" when delusions drove history. Our descendants will remember our era as the one where the human capacity to sincerely believe crazy non-adaptive things, and act on those beliefs, was dialed to the max.

[...]

Perhaps most important, our descendants may remember how history hung by a precarious thread on a few crucial coordination choices that our highly integrated rapidly changing world did or might have allowed us to achieve, and the strange delusions that influenced such choices.  These choices might have been about global warming, rampaging robots, nuclear weapons, bioterror, etc.
#+end_quote

* Flashcards
#+print_bibliography: