:PROPERTIES:
:ROAM_REFS: [cite:@leandroYouReStaffNowWhat]
:ID:       b4e207cd-6c52-425c-8b60-a21e8cb1d8c6
:LAST_MODIFIED: [2023-09-05 Tue 20:17]
:END:
#+title: Sabrina Leandro | So You're Staff+ ... Now What?
#+hugo_custom_front_matter: :slug "b4e207cd-6c52-425c-8b60-a21e8cb1d8c6"
#+author: Cash Weaver
#+date: [2023-03-20 Mon 16:23]
#+filetags: :reference:

[[id:b94fc39e-6749-4fdc-ade2-0d3880d5e75e][Sabrina Leandro]], [cite:@leandroYouReStaffNowWhat]

* Notes
#+begin_quote
1. Create your backlog
   You know that you're supposed to be working on things that are impactful and valuable, but where do you find this magic backlog of high impact work? You create it! It doesn't exist and you'll need to create it.

   [...]

   A backlog starts with a list of inputs. Here's some of the inputs that you should look out for:

   - Business and product strategies

     These are your main drivers. Ask yourself:

     - Do you understand the focus area and how that fits with the wider company strategy?
     - What's coming up in the next quarter, year?
     - What are the risks and opportunities there? If you're thinking ahead a couple of quarters: Is there anything you can help prepare or disambiguate ahead of that?

   - Team needs

     - Talk to managers and see what kind of support they need for you?
     - Proactively review the team's plan for the next quarter to see if you can provide support, guidance, etc

   - Engineering org needs

     - Processes, on-boarding, hiring, etc

   - Personal growth

     - What were areas of growth identified in your last performance review? Align current and future projects to cover them.
     - What about personal goals?

2. Prioritize and trim it down
   Once you have a list of inputs, you prioritize it!

   1. Company needs
   2. Riskiest areas or projects [[[id:e7753777-506e-490e-b79e-59dede5dce2e][Zach Tellman | Senior Engineers Reduce Risk]]]
   3. Personal growth goals

   Finally, this list you've created is gold and you won't have time to tackle everything. How can you trim it down?

   - [[id:b5246b0f-685b-4408-b79e-3b2b5e0eb601][Delegate]]
   - [[id:1af39408-7a58-4e23-99dd-ade56a6bce53][Mentor]]
   - Chat with managers and share what you've identified; see if you can help others grow by delegation

3. Get feedback

   - Ask for feedback: your manager, direct peers, and cross-discipline peers (e.g. product managers, sales)

4. Break it down

   Document your list for others (including future-you) to read. Highlight:

   - Area and eng level description: Direct reference to the eng-level documentation for your role to answer "Why is this <your level here> work?"
   - Commitment: What you'll do
   - Impact: What benefits will the company see from you doing this work?
   - Role: What role will you play? Primary/Driver, Contributor, Support/Consult, etc
   - Priority: Stack rank the list

   Publish it. Others in the company may also be a bit unsure "what would you say ... you do here?" Take this opportunity to state what you'll work on, how you'll work on it (e.g. Hands on? Hands off? Which meetings will you be in?), why you're working on it, and how you plan to deliver.

5. Track progress

   Find a system that works for you to track what you've done and what you're going to do.

6. Repeat!
[formatting mine]
#+end_quote

* Flashcards :noexport:
#+print_bibliography: