:PROPERTIES:
:ROAM_REFS: [cite:@salvatierRealityHasSurprisingAmountDetail]
:ID:       16937276-fd62-4d50-90ef-cdf5ab036442
:LAST_MODIFIED: [2023-10-09 Mon 23:58]
:END:
#+title: John Salvatier | Reality Has a Surprising Amount of Detail
#+hugo_custom_front_matter: :slug "16937276-fd62-4d50-90ef-cdf5ab036442"
#+author: Cash Prokop-Weaver
#+date: [2022-03-12 Sat 04:29]
#+filetags: :reference:
 
[cite:@salvatierRealityHasSurprisingAmountDetail]

* Summary
The title summarizes the thesis well: Reality has a surprising amount of detail. Things that appear simple are often only simple on the surface and get "fiddly" if you go deeper. Salvatier proposes that this is a consistent property of the universe and isn't limited to particular domains (i.e. programming, woodworking, physics, etc).

These details are difficult to identify since they are mostly-invisible before and after you notice them. Before you notice them you're unaware of their existance, and afterward you've incorporated them into your [[id:787214e0-5941-4c6f-9a61-e79b9b40baea][Mental models]] so well as to make them disappear again! This makes it difficult to guide others past the snags you encountered.
* Notes

#+begin_quote
[...] it's that everything is fiddly, but you only notice the fiddliness when you're new [...]
#+end_quote

#+begin_quote
Consider the boiling of water. That's straightforward, water boils at 100 °C, right?

Well the stairs seemed simple too, so let's double check.

Put yourself in the shoes of someone at the start of the 1800's, with only a crude, unmarked mercury thermometer, trying to figure the physics of temperature.

Go to your stove, put some water in a pot, start heating some water, and pay attention as it heats.

(I suggest actually doing this)

The first thing you'll probably notice is a lot of small bubbles gathering on the surface of the pot. Is that boiling? The water's not that hot yet; you can still even stick your finger in. Then the bubbles will appear faster and start rising, but they somehow seem 'unboiling'. Then you'll start to see little bubble storms in patches, and you start to hear a hissing noise. Is that Boiling? Sort of? It doesn't really look like boiling. The bubble storms grow larger and start releasing bigger bubbles. Eventually the bubbles get big and the surface of the water grows turbulent as the bubbles begin to make it to the surface. Finally we seem to have reached real boiling. I guess this is the boiling point? That seems kind of weird, what were the things that happened earlier if not boiling.

To make matters worse, if you'd used a glass pot instead of a metal one, the water would boil at a higher temperature. If you cleaned the glass vessel with sulfuric acid, to remove any residue, you'd find that you can heat water substantially more before it boils and when it does boil it boils in little explosions of boiling and the temperature fluctuates unstably.

Worse still, if you trap a drop of water between two other liquids and heat it, you can raise the temperature to at least 300 °C with nothing happening. That kind of makes a mockery of the statement 'water boils at 100 °C'.

It turns out that 'boiling' is a lot more complicated than you thought.

This surprising amount of detail is is not limited to "human" or "complicated" domains, it is a near universal property of everything from space travel to sewing, to your internal experience of your own mind.
#+end_quote

#+begin_quote
It's tempting to think 'So what?' and dismiss these details as incidental or specific to stair carpentry. And they are specific to stair carpentry; that's what makes them details. But the existence of a surprising number of meaningful details is not specific to stairs. Surprising detail is a near universal property of getting up close and personal with reality.

You can see this everywhere if you look. For example, you've probably had the experience of doing something for the first time, maybe growing vegetables or using a Haskell package for the first time, and being frustrated by how many annoying snags there were. Then you got more practice and then you told yourself 'man, it was so simple all along, I don't know why I had so much trouble'. [[[id:815271e0-33b8-4c6c-bb55-24b0f6ddcda7][When people are naturally good at something]]] We run into a fundamental property of the universe and mistake it for a personal failing.
#+end_quote

#+begin_quote
The more difficult your mission, the more details there will be that are critical to understand for success.

You might hope that these surprising details are irrelevant to your mission, but not so. Some of them will end up being key. [...]

You might also hope that the important details will be obvious when you run into them, but not so. Such details aren't automatically visible, even when you're directly running up against them. Things can just seem messy and noisy instead.
#+end_quote

#+begin_quote
Another way to see that noticing the right details is hard, is that different people end up noticing different details [[[id:10453cfb-8266-404d-93e6-768747d30b74][Theory of mind]]]. My brother and I once built a set of stairs for the garage with my dad, and we ran into the problem of determining where to cut the long boards so they lie at the correct angle. After struggling with the problem for a while (and I do mean struggling, a 16' long board is heavy), we got to arguing. I remembered from trig that we could figure out angle so I wanted to go dig up my textbook and think about it. My dad said, 'no, no, no, let's just trace it', insisting that we could figure out how to do it.

I kept arguing because I thought I was right. I felt really annoyed with him and he was annoyed with me. In retrospect, I think I saw the fundamental difficulty in what we were doing and I don't think he appreciated it (look at the stairs picture and see if you can figure it out), he just heard 'let's draw some diagrams and compute the angle' and didn't think that was the solution, and if he had appreciated the thing that I saw I think he would have been more open to drawing some diagrams. But at the same time, he also understood that diagrams and math don't account for the shape of the wood, which I did not appreciate. If we had been able to get these points across, we could have come to consensus. Drawing a diagram was probably a good idea, but computing the angle was probably not. Instead we stayed annoyed at each other for the next 3 hours.
#+end_quote

#+begin_quote
Before you've noticed important details they are, of course, basically invisible. It's hard to put your attention on them because you don't even know what you're looking for. But after you see them they quickly become so integrated into your intuitive models of the world that they become essentially transparent. Do you remember the insights that were crucial in learning to ride a bike or drive? How about the details and insights you have that led you to be good at the things you're good at?

This means it's really easy to get stuck. Stuck in your current way of seeing and thinking about things. Frames are made out of the details that seem important to you. The important details you haven't noticed are invisible to you, and the details you have noticed seem completely obvious and you see right through them. This all makes makes it difficult to imagine how you could be missing something important [[[id:efe31d96-34a6-439a-a34d-fdff9df0e51a][Metacognition]], [[id:17a6fce5-cfd8-4d26-aa95-4d0b30f799f8][Scout mindset]], [[id:c19c4cf1-9304-46b7-9441-8fed0ed17a57][Growth mindset]]].
#+end_quote

#+begin_quote
This problem is not easy to fix, but it's not impossible either. I've mostly fixed it for myself. The direction for improvement is clear: seek detail you would not normally notice about the world [[[id:ac7ecc0f-8a56-48c8-ab7a-809962db31ae][Draw the rest of the owl]]]. When you go for a walk, notice the unexpected detail in a flower or what the seams in the road imply about how the road was built. When you talk to someone who is smart but just seems so wrong, figure out what details seem important to them and why. In your work, notice how that meeting actually wouldn't have accomplished much if Sarah hadn't pointed out that one thing. As you learn, notice which details actually change how you think.

If you wish to not get stuck, seek to perceive what you have not yet perceived.
#+end_quote

* Flashcards :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:

** Cloze :fc:
:PROPERTIES:
:CREATED: [2023-02-18 Sat 11:21]
:FC_CREATED: 2023-02-18T19:21:34Z
:FC_TYPE:  cloze
:ID:       8388009b-676d-426d-82ed-b0d6490d2e46
:FC_CLOZE_MAX: 0
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.20 |   7 |   169.81 | 2024-01-12T10:20:11Z |
:END:

#+begin_quote
If you wish to not get stuck, {{seek to perceive what you have not yet perceived}@0}.
#+end_quote

*** Source
[cite:@salvatierRealityHasSurprisingAmountDetail]
** Summarize :fc:
:PROPERTIES:
:CREATED: [2023-02-18 Sat 11:21]
:FC_CREATED: 2023-02-18T19:26:09Z
:FC_TYPE:  double
:ID:       06395fa2-15fb-4767-831d-84a335d3ddcc
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.50 |   7 |   203.04 | 2024-02-15T15:19:51Z |
| back     | 2.50 |   5 |    37.91 | 2023-11-17T04:53:33Z |
:END:

[[id:16937276-fd62-4d50-90ef-cdf5ab036442][John Salvatier | Reality Has a Surprising Amount of Detail]]

*** Back
- The more difficult, complex, etc, your goal, the more details there will be for which understanding them is critical to success
- Everything is "fiddly" in that there are oddities and surprising details
- It's difficult-to-impossible to retroactively identify the things that didn't make sense when you were first learning a concept
- People perceive different details in a problem
*** Source
[cite:@salvatierRealityHasSurprisingAmountDetail]
