:PROPERTIES:
:ROAM_REFS: [cite:@alexanderEpistemicLearnedHelplessness2019]
:ID:       71aa6edb-f5a1-4e8b-88b9-5e5e807edceb
:LAST_MODIFIED: [2023-10-17 Tue 01:12]
:ROAM_ALIASES: "Arguments? You can prove anything with arguments."
:END:
#+title: Scott Alexander | Epistemic Learned Helplessness
#+hugo_custom_front_matter: :slug "71aa6edb-f5a1-4e8b-88b9-5e5e807edceb"
#+author: Cash Weaver
#+date: [2023-01-10 Tue 08:59]
#+filetags: :reference:

[[id:e7e4bd59-fa63-49a8-bfca-6c767d1c2330][Scott Alexander]], [cite:@alexanderEpistemicLearnedHelplessness2019]

* Summary
#+begin_quote
Arguments? You can prove anything with arguments.
#+end_quote

Arguments in domains you're not familiar with can /sound/ convincing even if they're false. Best to ignore them. However, its useful for some people not to ignore them and instead work from something closer to [[id:0f5abcf4-ac0d-40d7-a62b-62daeac65485][First principles]] so we continue to advance as a culture.

* Notes
#+begin_quote
A friend recently complained about how many people lack the basic skill of believing arguments. That is, if you have a valid argument for something, then you should accept the conclusion. Even if the conclusion is unpopular, or inconvenient, or you don't like it. He envisioned an art of rationality that would make people believe something after it had been proven to them.

And I nodded my head, because it sounded reasonable enough, and it wasn't until a few hours later that I thought about it again and went "Wait, no, that would be a terrible idea."

[...]

When I was young I used to read pseudohistory books; Immanuel Velikovsky's Ages in Chaos is a good example of the best this genre has to offer. I read it and it seemed so obviously correct, so perfect, that I could barely bring myself to bother to search out rebuttals.

And then I read the rebuttals, and they were so obviously correct, so devastating, that I couldn't believe I had ever been so dumb as to believe Velikovsky.

And then I read the rebuttals to the rebuttals, and they were so obviously correct that I felt silly for ever doubting.

And so on for several more iterations, until the labyrinth of doubt seemed inescapable. [...]

Given a total lack of independent intellectual steering power and no desire to spend thirty years building an independent knowledge base of Near Eastern history, I choose to just accept the ideas of the prestigious people with professorships in Archaeology, rather than those of the universally reviled crackpots who write books about Venus being a comet.

You could consider this a form of epistemic learned helplessness [[[id:06b5c658-5513-4c18-a24d-9ed3fb4ad23b][Learned helplessness]]], where I know any attempt to evaluate the arguments is just going to be a bad idea so I don't even try. If you have a good argument that the Early Bronze Age worked completely differently from the way mainstream historians believe, I just don't want to hear about it. If you insist on telling me anyway, I will nod, say that your argument makes complete sense, and then totally refuse to change my mind or admit even the slightest possibility that you might be right.

(This is the correct Bayesian action: if I know that a false argument sounds just as convincing as a true argument, argument convincingness provides no evidence either way. I should ignore it and stick with my prior.)

I consider myself lucky in that my epistemic learned helplessness is circumscribed; there are still cases where I'll trust the evidence of my own reason. In fact, I trust it in most cases other than infamously deceptive arguments in fields I know little about. But I think the average uneducated person doesn't and shouldn't. Anyone anywhere – politicians, scammy businessmen, smooth-talking romantic partners – would be able to argue them into anything. And so they take the obvious and correct defensive maneuver – they will never let anyone convince them of any belief that sounds "weird".

(and remember that, if you grow up in the right circles, beliefs along the lines of "astrology doesn't work" sound "weird".)
#+end_quote

#+begin_quote
Responsible doctors are at the other end of the spectrum from terrorists here. I once heard someone rail against how doctors totally ignored all the latest and most exciting medical studies. The same person, practically in the same breath, then railed against how 50% to 90% of medical studies are wrong. These two observations are not unrelated. Not only are there so many terrible studies, but pseudomedicine (not the stupid homeopathy type, but the type that links everything to some obscure chemical on an out-of-the-way metabolic pathway) has, for me, proven much like pseudohistory – unless I am an expert in that particular subsubfield of medicine, it can sound very convincing even when it's very wrong.
#+end_quote

* Flashcards :noexport:
** Describe :fc:
:PROPERTIES:
:CREATED: [2023-01-10 Tue 09:12]
:FC_CREATED: 2023-01-10T17:13:25Z
:FC_TYPE:  double
:ID:       6c6d0c91-e114-4acd-aaff-47bba5917ce5
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.65 |   7 |   308.07 | 2024-05-26T05:29:15Z |
| back     | 1.60 |   4 |     9.37 | 2023-10-26T17:08:27Z |
:END:

Epistemic [[id:06b5c658-5513-4c18-a24d-9ed3fb4ad23b][Learned helplessness]]

*** Back
A condition in which the person is unable to discern a convincing argument from a true argument and resolves to ignore the argument, or at least its conclusions.
*** Source
[cite:@alexanderEpistemicLearnedHelplessness2019]
