:PROPERTIES:
:ID:       42be7ce6-d83b-4717-86a0-0766565b2049
:LAST_MODIFIED: [2023-08-21 Mon 06:19]
:ROAM_REFS: [cite:@SessionComputerScience2023]
:END:
#+title: Session
#+hugo_custom_front_matter: :slug "42be7ce6-d83b-4717-86a0-0766565b2049"
#+author: Cash Prokop-Weaver
#+date: [2023-03-18 Sat 08:32]
#+filetags: :concept:

#+begin_quote
In computer science and networking in particular, a session is a time-delimited two-way link, a practical (relatively high) layer in the TCP/IP protocol enabling interactive expression and information exchange between two or more communication devices or ends – be they computers, automated systems, or live active users (see login session). A session is established at a certain point in time, and then 'torn down' - brought to an end - at some later point. An established communication session may involve more than one message in each direction. A session is typically stateful, meaning that at least one of the communicating parties needs to hold current state information and save information about the session history to be able to communicate, as opposed to stateless communication, where the communication consists of independent requests with responses.

An established session is the basic requirement to perform a connection-oriented communication. A session also is the basic step to transmit in connectionless communication modes. However, any unidirectional transmission does not define a session.

Communication Transport may be implemented as part of protocols and services at the application layer, at the session layer or at the transport layer in the OSI model.

- Application layer examples:
  - HTTP sessions, which allow associating information with individual visitors
  - A telnet remote login session
- Session layer example:
  - A Session Initiation Protocol (SIP) based Internet phone call
- Transport layer example:
  - A TCP session, which is synonymous to a TCP virtual circuit, a TCP connection, or an established TCP socket.

[cite:@SessionComputerScience2023]
#+end_quote

* Flashcards
** Definition (Computers) :fc:
:PROPERTIES:
:CREATED: [2023-03-18 Sat 08:35]
:FC_CREATED: 2023-03-18T15:37:15Z
:FC_TYPE:  double
:ID:       743b4e8b-cfd7-4b9b-bac2-1ece1df7d4c9
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.35 |   7 |   170.53 | 2024-02-08T01:56:09Z |
| back     | 2.95 |   6 |   129.91 | 2023-10-24T11:52:42Z |
:END:

[[id:42be7ce6-d83b-4717-86a0-0766565b2049][Session]]

*** Back
A time-delimited two-way link which enables interactive expression and information exchange between two or more communication devices or ends – be they computers, automated systems, or live active users (see login session).
*** Source
[cite:@SessionComputerScience2023]
#+print_bibliography: