:PROPERTIES:
:ROAM_REFS: [cite:@sophiefrommarsYeWestFascistsWhoLoveHimSophieMars2023]
:ID:       722ccbe0-5bd0-4652-86dd-0ef8c6f50fa9
:LAST_MODIFIED: [2023-09-06 Wed 08:05]
:END:
#+title:  Sophie from Mars | Ye West The Fascists Who Love Him | Sophie From Mars
#+hugo_custom_front_matter: :slug "722ccbe0-5bd0-4652-86dd-0ef8c6f50fa9"
#+author: Cash Weaver
#+date: [2023-01-13 Fri 17:00]
#+filetags: :reference:

[[id:759c24f9-38c8-4b52-9a7c-7de58e8a93a3][Sophie from Mars]], [cite:@sophiefrommarsYeWestFascistsWhoLoveHimSophieMars2023]

* Notes

#+begin_quote
Either they can install Ye as the leader or they can just use the leverage he give them to bring more explicit anti-Semitism into the collective conciousness of the Cultic Milieu and doing that will set the agenda for the cult because when the reality the cult exists within defines its membership the figurehead has to adhere to the cult's agenda and the politics dictated by it no matter what their personal beliefs are. They've already succeeded in bringing anti-Semitism to the table but everything so far has been a pilot study. They want to see if the base will respond to it and if it does the people who appeal to that base will sell anti-Semitism back to them just like they already do with everything else they believe.
#+end_quote

This describes a [[id:8710324a-ceda-4590-86ee-ad11c3eb36b9][Xanatos gambit]] of political strategy at the [[id:c73b15fa-a2bc-48bc-8f3d-6edffc332da1][System]] level. You don't need to ensure a particular candidate wins in order to advance your agenda if /all/ of the candidates are onboard with your agenda. You only need to mould the culture such that any candidates who emerge will endorse your chosen agenda. Change the [[id:deb3b467-3bb1-4000-9665-3a7347909ad6][Incentives]] to align with your goals. Make it such that coming out against your position will kill a candidate's campaign.
* Flashcards :noexport:
* Bibliography
#+print_bibliography:
