:PROPERTIES:
:ID:       81546002-b401-4c6c-ae23-ebab290a72a9
:LAST_MODIFIED: [2023-05-08 Mon 10:13]
:ROAM_REFS: [cite:@StrawMan2023]
:ROAM_ALIASES: "Straw man"
:END:
#+title: Strawmanning
#+hugo_custom_front_matter: :slug "81546002-b401-4c6c-ae23-ebab290a72a9"
#+author: Cash Prokop-Weaver
#+date: [2023-02-01 Wed 08:35]
#+filetags: :concept:

#+begin_quote
A straw man fallacy (sometimes written as strawman) is a form of argument and an informal fallacy of having the impression of refuting an argument, whereas the real subject of the argument was not addressed or refuted, but instead replaced with a false one. One who engages in this fallacy is said to be "attacking a straw man".

The typical straw man argument creates the illusion of having refuted or defeated an opponent's proposition through the covert replacement of it with a different proposition (i.e., "stand up a straw man") and the subsequent refutation of that false argument ("knock down a straw man") instead of the opponent's proposition. Straw man arguments have been used throughout history in polemical debate, particularly regarding highly charged emotional subjects.

[cite:@StrawMan2023]
#+end_quote

* Flashcards
** Definition :fc:
:PROPERTIES:
:CREATED: [2023-02-01 Wed 08:34]
:FC_CREATED: 2023-02-01T16:35:39Z
:FC_TYPE:  double
:ID:       964e13e9-10dc-41d2-85a2-b3d61246f1bf
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   6 |   137.38 | 2023-09-21T02:51:36Z |
| back     | 2.80 |   6 |   127.77 | 2023-09-13T11:37:02Z |
:END:

[[id:81546002-b401-4c6c-ae23-ebab290a72a9][Strawmanning]]

*** Back
A form of argument which gives the impression of refuting an argument by instead refuting a false or poor version of said argument.
*** Source
[cite:@StrawMan2023]
#+print_bibliography: