:PROPERTIES:
:ID:       d553899d-ac5d-4ecf-bf57-9eabb3407b6e
:ROAM_REFS: [cite:@StreetlightEffect2022]
:ROAM_ALIASES: "Where the light is"
:LAST_MODIFIED: [2024-02-09 Fri 06:12]
:END:
#+title: Streetlight effect
#+hugo_custom_front_matter: :slug "d553899d-ac5d-4ecf-bf57-9eabb3407b6e"
#+author: Cash Prokop-Weaver
#+date: [2022-11-10 Thu 16:43]
#+filetags: :concept:
#+begin_quote
The streetlight effect, or the drunkard's search principle, is a type of observational bias that occurs when people only search for something where it is easiest to look. Both names refer to a well-known joke:

A policeman sees a drunk man searching for something under a streetlight and asks what the drunk has lost. He says he lost his keys and they both look under the streetlight together. After a few minutes the policeman asks if he is sure he lost them here, and the drunk replies, no, and that he lost them in the park. The policeman asks why he is searching here, and the drunk replies, "this is where the light is".

[cite:@StreetlightEffect2022]
#+end_quote

* Flashcards :noexport:
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-11-18 Fri 12:00]
:FC_CREATED: 2022-11-18T20:00:45Z
:FC_TYPE:  double
:ID:       48adfa0c-e795-44f9-8644-16ea4a8439bd
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.65 |   8 |   588.75 | 2025-07-30T16:34:14Z |
| back     | 2.95 |   7 |   338.22 | 2024-05-23T20:33:26Z |
:END:

[[id:d553899d-ac5d-4ecf-bf57-9eabb3407b6e][Streetlight effect]]

*** Back

Observational bias wherein people tend to only search for something where it is easiest to look.

*** Source
[cite:@StreetlightEffect2022]
** Describe (Joke) :fc:
:PROPERTIES:
:CREATED: [2022-11-18 Fri 12:01]
:FC_CREATED: 2022-11-18T20:01:55Z
:FC_TYPE:  normal
:ID:       ae976ec2-b8f6-4831-90f7-2cffec1f5fec
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   8 |   721.90 | 2026-01-31T11:53:53Z |
:END:

[[id:d553899d-ac5d-4ecf-bf57-9eabb3407b6e][Where the light is]]

*** Back

A policeman sees a drunk man searching for something under a streetlight and asks what the drunk has lost. He says he lost his keys and they both look under the streetlight together. After a few minutes the policeman asks if he is sure he lost them here, and the drunk replies, no, and that he lost them in the park. The policeman asks why he is searching here, and the drunk replies, "this is where the light is".

*** Source
[cite:@StreetlightEffect2022]
* Bibliography
#+print_bibliography:
