:PROPERTIES:
:ID:       30263770-541e-4e5a-acbe-f194ab7c121e
:LAST_MODIFIED: [2023-09-06 Wed 08:04]
:END:
#+title: Systems Design
#+hugo_custom_front_matter: :slug "30263770-541e-4e5a-acbe-f194ab7c121e"
#+author: Cash Prokop-Weaver
#+date: [2022-03-15 Tue 21:20]
#+filetags: :hastodo:concept:

Systems design, insofar as I understand it, is difficult to define. It's difficult not because no one has thought to define it --- they have:

#+begin_quote
Systems design is the process of defining the architecture, product design, modules, interfaces, and data for a system to satisfy specified requirements.

[cite:@SystemsDesign2021]
#+end_quote

Rather, I say it's difficult to define because the descriptions I have read (like above) have done little to help me really understand what systems design is to the point that I could explain it in my own words to another person.

My mind tends to move toward [[id:5bc61709-6612-4287-921f-3e2509bd2261][graphs]] when I think about systems design. The system being the sum of the individual nodes and the edges which connect them. The output of a system for a given input would be the result of walking the graph from some point until reaching something defined as an end.

* TODO [#2] :noexport:
* TODO [#2] Flashcards :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:

* Bibliography
#+print_bibliography:
