:PROPERTIES:
:ROAM_REFS: [cite:@greerTraditionSmarterYouAre2018]
:ID:       35669b5b-bf75-4bda-9037-42a2d3af956d
:LAST_MODIFIED: [2023-09-06 Wed 08:05]
:END:
#+title: Tanner Greer | Tradition Is Smarter Than You Are
#+hugo_custom_front_matter: :slug "35669b5b-bf75-4bda-9037-42a2d3af956d"
#+author: Cash Weaver
#+date: [2023-01-10 Tue 12:08]
#+filetags: :reference:

[[id:af527d83-0378-4f66-8b25-d7df4188b6b6][Tanner Greer]] , [cite:@greerTraditionSmarterYouAre2018]

* Summary
On [cite:@scottSeeingStateHowCertainSchemesImproveHumanConditionHaveFailed2020] and [cite:@henrichSecretOurSuccessHowCultureDrivingHumanEvolutionDomesticatingOur2016].
* Thoughts
I prefer the individual reviews of [[id:e1b0e31a-4039-4b09-8dbd-8c3587562cca][Scott Alexander | Book Review: Seeing Like A State]] and [[id:cb2c8f33-41ee-457c-805a-27ccec7ba2c3][Scott Alexander | Book Review: The Secret Of Our Success]].
* Notes
#+begin_quote
Let's talk about Henrich first. One the clearest presentations of his ideas is in his 2016 book The Secret of Our Success. The book is less a heavy scholarly tome than a poppified version of Henrich's research, but Henrich's decision to trade theoretical detail for accessibility is understandable (it is also why I don't feel bad quoting large blocks of text from the book in this post). Henrich advances the argument that brain-power alone is not enough to explain why humans are such a successful species. Humans, he argues, are not nearly as intelligent as we think they are. Remove them from the culture and environment they have learned to operate in and they fail quickly. His favorite example of this are European explorers who die in the middle of deserts, jungles, or arctic wastes even though thousands of generations of hunter-gatherers were able to survive and thrive in these same environments. If human success was due to our ability to problem solve, analyze, and rationally develop novel solutions to novel challenges, the explorers should have been fine. Their ghastly fates suggest that rationality may not be the key to human survival.
#+end_quote

#+begin_quote
Henrich makes two arguments here, both relevant to contemporary debates in politics and philosophy. The first is that customs, traditions, and the like are subject to Darwinian selection. Henrich is not always clear on exactly what is being selected for—is it individuals who follow a tradition, groups whose members all follow the tradition, or the tradition itself?—but the general gist is that traditions stick around longest when they are adaptive. This process is "blind." Those who follow the traditions do not know how they work, and in some cases (like religious rituals that build social solidarity) knowing the details of how they work might actually reduce the efficacy of the tradition [[[id:064e87e5-6a2d-480f-9cab-9ae1c1cc3ba4][X isn't (only) about Y]]]. That is the second argument of note: we do not (and often cannot) understand just how the traditions we inherit help our survival, and because of that, it is difficult to artificially create replacements [[[id:975b8bf2-d4cb-4a1d-a976-0f6d0130dbc5][Chesterton's fence]]].

I do not think Henrich is willing to extend these points to all elements of human culture. If we are to take analogies with genetic evolution seriously, then we should not be surprised if a large amount of our cultural baggage are just random accretions passed on from one generation to the next—in essence, the cultural version of genetic drift. But that is the trouble: we have no way to tell which traditions are adaptive and which are merely drift.

All of this meshes splendidly with the work of James C Scott.[5] (If you have never read anything by him before, I recommend starting with this essay). Scott has spent a large amount of his career studying the way states shape the societies they rule over, and the way societies try to resist the advance of the state. The central problem of ruler-ship, as Scott sees it, is what he calls legibility. To extract resources from a population the state must be able to understand that population. The state needs to make the people and things it rules legible to agents of the government. Legibility means uniformity. States dream up uniform weights and measures, impress national languages and ID numbers on their people, and divvy the country up into land plots and administrative districts, all to make the realm legible to the powers that be. The problem is that not all important things can be made legible. Much of what makes a society successful is knowledge of the tacit sort: rarely articulated, messy, and from the outside looking in, purposeless. These are the first things lost in the quest for legibility. Traditions, small cultural differences, odd and distinctive lifeways—in other words, the products of cultural evolution that Henrich fills his book with—are all swept aside by a rationalizing state that preserves (or in many cases, imposes) only what it can be understood and manipulated from the 2,000 foot view. The result, as Scott chronicles with example after example, are many of the greatest catastrophes of human history.

None of Scott's works are in Henrich's bibliography, but it is hard to imagine Henrich being surprised by this outcome. The social engineer is attempting to replace hundreds of traditions, norms, and nuggets of local knowledge through rational calculation. He is the functional equivalent of the European explorer starving in lands of plenty. The only difference between the rationalist explorer and the rationalist social engineer is that the engineer has the power to force the land to starve with him.
#+end_quote

* Flashcards :noexport:
#+print_bibliography: