:PROPERTIES:
:ROAM_REFS: [cite:@tellmanThoughtLeadersChickenSexers]
:ID:       89af4069-9f38-4f2b-bdb4-491c2ae85a9c
:LAST_MODIFIED: [2023-10-02 Mon 23:10]
:END:
#+title: Zach Tellman | Thought Leaders and Chicken Sexers
#+hugo_custom_front_matter: :slug "89af4069-9f38-4f2b-bdb4-491c2ae85a9c"
#+author: Cash Prokop-Weaver
#+date: [2022-02-18 Fri 16:25]
#+filetags: :reference:
 
[[id:cf4225ad-fa19-419e-90a6-bac3b45d1764][Zach Tellman]], [cite:@tellmanThoughtLeadersChickenSexers]
* Summary
- Thought leaders : [[id:19124270-bb87-450d-8726-fe6aae18716f][Explicit knowledge]] \:: Chicken sexers : [[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Implicit knowledge]]
- [[id:8a9360e0-306a-422a-804f-e2fd6664b8fe][Paul Graham]] is an unserious public intellectual who relies on [[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Implicit knowledge]] and fails to fully grapple with the models he presents as Truth; a chicken sexer
* Notes
#+begin_quote
From the moment I started paying attention to the tech industry, Paul Graham was there. My first job out of college was in SoMa, around the corner from the Justin.tv offices, and his essays were just floating around in the ether, impossible to ignore. His popularization of Lisp was a small part of why I tried Clojure, and a big part of why Clojure was successful.

I recognized that he had a tendency towards [[http://www.paulgraham.com/avg.html][self-aggrandizement]] and [[http://www.paulgraham.com/nerds.html][awkward flattery of his readers]], but at worst he seemed harmless. As his writing became increasingly focused on startups, and I became increasingly sure I didn't want to be a founder, he simply drifted out of view.

Recently, however, his writing has taken a reactionary turn which is hard to ignore. He's [[http://www.paulgraham.com/mod.html][written]] about the need to defend "moderates" from bullies on the "extreme left", [[https://twitter.com/paulg/status/1334441961147822081][asserted]] that "the truth is to the right of the median" because "the left is culturally dominant," and [[https://pbs.twimg.com/media/EjGX2-bU4AAWkUX?format=jpg&name=medium][justified]] Coinbase's policy to ban discussion of anything deemed "political" by saying that it "will push away some talent, yes, but not very talented talent."

I went back to the essays I had read a decade before, to see if I had missed something. It turned out that I had. There was a consistent intellectual framework underpinning all his writing, from his very first essays on Lisp and language design. In many ways, those early essays contained the clearest articulation of his framework; it just took me ten years to see it.

[...]

But Graham's analysis of brevity, and indeed of all language design, was fundamentally unserious. He wasn't interested in a rigorous definition of brevity, because the ultimate measure of a language's quality was still his hacker's radar. All of his essays, and Arc itself, were just spokes around that central hub. If his essays sometimes disagreed, or if Arc didn't reflect his essays, it's hardly surprising; their only connection was they all, in the moment, seemed right and true to Paul Graham.

[...]

Michael Polanyi coined the term "[[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Tacit knowledge]]" to describe something we only understand as part of something else. When we speak, for instance, we don't focus on the sounds we're making, we focus on our words. We understand how to speak, but would struggle to explain it. Tacit knowledge comprises the vast majority of what we know; we rely on it constantly.

When that knowledge begins to lead us astray, however, Polanyi tells us we that must delve into it. We must make it [[id:19124270-bb87-450d-8726-fe6aae18716f][explicit]] [[[id:8331d841-b588-4780-b730-ded8ada343f2][Make implicit knowledge explicit]]]. An explicit understanding of speech might be necessary for someone with a speech impediment, but also for a professional performer; to be at the top of your field, it's almost always necessary to transform innate talent into something more.

A rare exception to this rule is the chicken sexer, who can quickly and accurately determine whether a day-old chick is male or female. The two are indistinguishable to most, but an expert can classify a thousand chicks an hour with 98% accuracy. The knowledge underpinning this expertise has never been made explicit; a trainee is simply corrected by an expert, over and over, until their intuition is equally refined.

Held to this standard, however, we all fall short. No one's sensibilities about software design are so refined that they can teach simply through demonstration. We have to distill our intuition down to principles, and let those principles guide us beyond the bounds of our intuition. Anything less is just rentier pedagogy; maxims stripped of any context, whose true meaning within a given situation can only be judged by a single person.

This is the essence of modern "thought leadership", and it's served Graham well. His essays on language design, as well as a few on startups, brought in the first entrepreneurs to his fledgling VC fund. People applied to YCombinator because they wanted Graham to apply his intuition to their problems.

Graham's essays on startups were much the same as his essays on language design, but they served a different purpose. They were marketing content, and in that role they excelled. They tantalized the reader by reducing complex problems down to singular, nebulous concepts. They hinted at deep insights that were just out of reach. They made people want to be in the same room as Paul Graham.

[...]

A recurring theme in his essays, both [[http://www.paulgraham.com/say.html][before]] and [[http://www.paulgraham.com/conformism.html][after]] his time at YCombinator, is conformity. Graham is resolutely on the side of the non-conformist, repeatedly tracing their lineage back to Galileo's [[https://en.wikipedia.org/wiki/And_yet_it_moves][insistence that the earth moves]], even after the church had forced him to recant.

[...]

Graham writes "the call of the aggressively independent-minded is '[[id:62c2da6b-ad55-4802-a334-f984b938b498][Eppur si muove]]," but he doesn't pause to consider that it is also [[https://timecube.2enp.com/]["EARTH HAS 4 CORNER SIMULTANEOUS 4-DAY TIME CUBE"]] and, more worryingly, [[https://en.wikipedia.org/wiki/White_genocide_conspiracy_theory]["Jews will not replace us"]]. His model exists largely so he can focus on the one quadrant he finds interesting, but even that is a proxy for a much smaller group, the moral and intellectual heirs of Galileo, the people he intuits to be his peers. Graham doesn't work through the consequences of his own model because the model doesn't matter; what matters is sharing some things that feel right and true.

This is all to say that Paul Graham is an effective marketer and practitioner, but a profoundly unserious public intellectual. His attempts to grapple with the major issues of the present, especially as they intersect with his personal legacy, are so mired in intuition and incuriosity that they're at best a distraction, and worst a real obstacle to understanding our paths forward.
#+end_quote

* Flashcards
** Compare and contrast :fc:
:PROPERTIES:
:CREATED: [2022-11-12 Sat 08:44]
:FC_CREATED: 2022-11-12T16:46:10Z
:FC_TYPE:  normal
:ID:       47f2dcbb-7b7d-4005-9234-733e2a2f1953
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.05 |   8 |   335.73 | 2024-09-02T23:34:56Z |
:END:

Thought leaders and chicken sexers ([[id:cf4225ad-fa19-419e-90a6-bac3b45d1764][Zach Tellman]])

*** Back
- Thought leaders: [[id:19124270-bb87-450d-8726-fe6aae18716f][Explicit knowledge]]
- Chicken sexers: [[id:d636dfa7-428d-457c-8db6-15fa61e03bef][Implicit knowledge]]
*** Source
[cite:@tellmanThoughtLeadersChickenSexers]
#+print_bibliography: