:PROPERTIES:
:ROAM_REFS: [cite:@tellmanTrappedTechnologistFactory]
:ID:       1182a8b4-b808-47e2-92e3-f69bb9e57981
:DIR:      /home/cashweaver/proj/roam/attachments/1182a8b4-b808-47e2-92e3-f69bb9e57981
:LAST_MODIFIED: [2023-09-05 Tue 20:19]
:END:
#+title: Zach Tellman | Trapped in the Technologist Factory
#+hugo_custom_front_matter: :slug "1182a8b4-b808-47e2-92e3-f69bb9e57981"
#+author: Cash Prokop-Weaver
#+date: [2022-02-19 Sat 09:32]
#+filetags: :reference:
 
[[id:cf4225ad-fa19-419e-90a6-bac3b45d1764][Zach Tellman]], [cite:@tellmanTrappedTechnologistFactory]

* Summary
- Focused on the [[id:462b9154-2519-45e9-a4f5-35e7c32128c7][Metagame]] of software engineering
- The software development industry, as a [[id:c73b15fa-a2bc-48bc-8f3d-6edffc332da1][System]], is designed to foster technologists; people more focused on the tool than on the problem the tool solves.
- [[id:3923eefd-c5ff-455e-a107-cd5a9e9191c3][Technologist]] are:
- Startups use new technology /because/ of their immaturity rather than /despite/ it. Playing with new
  - "The only guaranteed benefit they can offer their engineers is the freedom to invent their own challenges, and learn through iterative failure."
* Notes

#+begin_quote
I learned two lessons from this time in my life. The first was personal: I am, at heart, a technologist. I like to generalize, to abstract. While I believe it's crucial to understand the context around your software, I'm happiest when that context is other people's software.

The second lesson was broader, and less obvious: our industry is designed to foster people like me.

This was surprising because it seems so clearly against our own interest. In almost every case, companies fail because they build the wrong thing. Unless your customers are themselves engineers, I'm the wrong person to help with that. You want someone comfortable at the periphery of your system, who wants to learn about the competitive landscape, who wants to talk to customers. You want a product engineer.

But consider our standard interview questions: data structures, recursion, and computational complexity. It always feels a little strange when I see someone arguing that these don't reflect "real" day-to-day software tasks; I write recursive functions all the time. But that's a consequence of the abstraction; what might be a simple nested lookup on any specific datatype becomes recursion when you try to generalize over a set of possible datatypes.

Likewise, I've seen it argued that the difference between, say, O(log N) and O(N) isn't important, because in practice N tends to be small enough. That may be true for some domains, maybe even most of them, but if you're building a general-purpose tool you have to focus on the pathological cases.

[...]

But if we want to hire product engineers, what questions should we ask instead? It's impractical, given the sprawling scope of our industry, to only consider candidates with prior experience in our exact product space. Likewise, it's unrealistic to expect that we'd have expertise in a candidate's prior product spaces. We lack a common vocabulary, a common understanding of the nuances that separate good design choices from middling ones.

And so we continue to [[id:d553899d-ac5d-4ecf-bf57-9eabb3407b6e][search for our keys under the streetlamp]]; they could be anywhere, but this is where the light is. If we're lucky, the technologists we hire will also have all the other skills necessary to make humane, useful software.

This means that even if you're not a technologist, you have to learn how to pretend. [[[id:bcc5414e-4ad7-4a7d-ac84-75e08c02b017][Be what they expect you to be]]]

[...]

[[id:81ca2b65-51ee-4244-9845-7dbbd03d31ae][As many have pointed out]], this is not a rational strategy for building a company. It is, however, a phenomenal way to train new technologists. [[id:975b8bf2-d4cb-4a1d-a976-0f6d0130dbc5][Chesterton]] notwithstanding, the fastest way to learn why a fence exists is to tear it down and see what happens.

Seen from this perspective, it doesn't seem so irrational; most startups fail before reaching a scale that has any existential technical risks. The only guaranteed benefit they can offer their engineers is the freedom to invent their own challenges, and learn through iterative failure. If the startup fails, there's no harm done. If the startup gets traction, the engineers can apply their newfound wisdom.

This means startups don't adopt new technologies despite their immaturity, they adopt them because of that immaturity. This drives a constant churn of novelty and obsolescence, which amplifies the importance of a technologist's skillset, which drives startups to adopt new technologies.

[...]

By introducing abstraction into every problem we solve, we distance ourselves from how our work is ultimately used. We tell ourselves we're in the business of building sharp knives; if we made them safer, they'd be useless for everything except spreading butter. We float above the the effects of what we've created, treating them as inexorable consequences of [[id:3bbbacc5-9f55-4ded-abf5-d76ff0b5b8e2][progress]].
#+end_quote

* Flashcards :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:
** Summarize :fc:
:PROPERTIES:
:CREATED: [2022-11-10 Thu 16:50]
:FC_CREATED: 2022-11-11T00:50:55Z
:FC_TYPE:  normal
:ID:       9e1454b4-a722-4b68-99e1-561122778486
:FC_BLOCKED_BY:       86f24130-3cc1-489c-8938-57f984b81a46,a490f777-7427-4529-a064-696cca756082
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 1.75 |   8 |   147.91 | 2023-11-01T12:25:47Z |
:END:

[[id:1182a8b4-b808-47e2-92e3-f69bb9e57981][Zach Tellman | Trapped in the Technologist Factory]]

*** Back
- The software development industry, as a [[id:c73b15fa-a2bc-48bc-8f3d-6edffc332da1][System]], is designed to foster [[id:3923eefd-c5ff-455e-a107-cd5a9e9191c3][Technologists]]; people more focused on the tool than on the problem the tool solves
** ([[id:cf4225ad-fa19-419e-90a6-bac3b45d1764][Zach Tellman]]) Why startups adopt new technologies :fc:
:PROPERTIES:
:CREATED: [2022-11-10 Thu 17:40]
:FC_CREATED: 2022-11-11T01:43:50Z
:FC_TYPE:  normal
:ID:       a490f777-7427-4529-a064-696cca756082
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.35 |   7 |   190.53 | 2023-11-10T04:29:16Z |
:END:

- [[id:783f58f7-4b80-42a0-863f-2d8d1367c30b][It's a feature, not a bug]]
- Startups attract [[id:3923eefd-c5ff-455e-a107-cd5a9e9191c3][Technologist]] types
- Not /despite/ their immaturity but rather /because/ of their immaturity
- "The only guaranteed benefit they can offer their engineers is the freedom to invent their own challenges, and learn through iterative failure."

*** Source
[cite:@tellmanTrappedTechnologistFactory]
#+print_bibliography: