:PROPERTIES:
:ID:       cb4d578c-d0d4-4056-aad1-c6ee153eb42f
:DIR:      /home/cashweaver/proj/roam/attachments/cb4d578c-d0d4-4056-aad1-c6ee153eb42f
:LAST_MODIFIED: [2023-09-05 Tue 20:18]
:END:
#+title: Theory of change
#+hugo_custom_front_matter: :slug "cb4d578c-d0d4-4056-aad1-c6ee153eb42f"
#+author: Cash Prokop-Weaver
#+date: [2021-12-03 Fri 12:28]

#+begin_quote
Theory of Change explains the process of change by outlining causal linkages in an initiative, i.e., its shorter-term, intermediate, and longer-term outcomes. The identified changes are mapped – as the "outcomes pathway" – showing each outcome in logical relationship to all the others, as well as chronological flow and feedback loops. The links between outcomes are explained by "rationales" or statements of why one outcome is thought to be a prerequisite for another.

The innovation of Theory of Change lies (1) in making the distinction between desired and actual outcomes and (2) in requiring stakeholders to model their desired outcomes before they decide on forms of intervention to achieve those outcomes.

[cite:@TheoryChange2022]
#+end_quote

#+begin_quote
Let's take a concrete example. Imagine you want to decrease the size of the defense budget. The typical way you might approach this is to look around at the things you know how to do and do them on the issue of decreasing the defense budget. So, if you have a blog, you might write a blog post about why the defense budget should be decreased and tell your friends about it on Facebook and Twitter. If you're a professional writer, you might write a book on the subject. If you're an academic, you might publish some papers. Let's call this strategy a "theory of action" [[[id:ab452878-389a-4a13-b659-903b7db10997][Theory of action]]]: you work forwards from what you know how to do to try to find things you can do that will accomplish your goal.

A theory of change is the opposite of a theory of action — it works backwards from the goal, in concrete steps, to figure out what you can do to achieve it. To develop a theory of change, you need to start at the end and repeatedly ask yourself, "Concretely, how does one achieve that?"

[cite:@swartzTheoryChange2010]
#+end_quote

* Steps

These steps are based on [cite:@HowDoesTheoryChangeWork]. The ordering, with the exception of starting from Goals, is a recommendation as opposed to a hard rule. For instance, you may need to revisit previous steps as you progress if you identify previously unknown flaws or opportunities in your reasoning.

1. Goals: Identify and agree upon long term goal(s)
2. Outcomes: Create an outcomes framework by [[id:bff6cb4c-8091-4c3d-87a9-397f54218d38][Backcasting]] from long term goal(s) and explain why these preconditions are necessary and sufficient
3. Assumptions: Make assumptions [[id:fd00fbf2-6b65-442f-90b9-b9d5d64a5fde][explicit]]
4. Evidence: Develop indicators which will measure the outcomes and assess your performance (see [[id:00886e80-e78f-4f1e-8c85-b97b27af05ac][OKR]])
5. Action: Identify your next steps based on the outcome
6. Convince: Create a narrative which explains the logic of this plan and use it to convince necessary stakeholders

* As compared to a theory of action

Based on [cite:@tyrrelTheoryChangeTheoryActionWhatDifferenceWhyDoesItMatter2019] and [cite:@swartzTheoryChange2010]:

- [[id:ab452878-389a-4a13-b659-903b7db10997][Theory of action]]
  - Works *forward* from where you are right now toward the goal
  - Focuses on what you will do to try and affect change
- [[id:cb4d578c-d0d4-4056-aad1-c6ee153eb42f][Theory of change]]
  - Works *backward* ([[id:bff6cb4c-8091-4c3d-87a9-397f54218d38][Backcast]]) from the goal to the present; not you -- the present
  - Describes how change happens in a [[id:c73b15fa-a2bc-48bc-8f3d-6edffc332da1][System]], regardless of anything you do or don't do, and then attempts to integrate you and your potential changes into that framework

* Flashcards
:PROPERTIES:
:ANKI_DECK: Default
:END:
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-11-16 Wed 08:22]
:FC_CREATED: 2022-11-16T16:22:42Z
:FC_TYPE:  double
:ID:       8d60893c-6ec4-4d05-8013-8cd725d17723
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 3.10 |   7 |   411.39 | 2024-08-25T01:02:57Z |
| back     | 2.80 |   7 |   473.19 | 2024-12-10T19:50:28Z |
:END:

[[id:cb4d578c-d0d4-4056-aad1-c6ee153eb42f][Theory of change]]

*** Back
- A model of how change in the direction of a goal or destination happens within a system
- A plan for enacting change built by [[id:bff6cb4c-8091-4c3d-87a9-397f54218d38][Backcasting]] from the desired goal to the present.
*** Source
[cite:@TheoryChange2022]
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-11-16 Wed 08:23]
:FC_CREATED: 2022-11-16T16:23:45Z
:FC_TYPE:  double
:ID:       8aad55c9-729d-4343-965b-5ef78feec13a
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.65 |   7 |   304.35 | 2024-04-11T01:39:40Z |
| back     | 2.50 |   7 |   218.53 | 2023-12-27T02:38:12Z |
:END:

Steps to create a [[id:cb4d578c-d0d4-4056-aad1-c6ee153eb42f][Theory of change]]

*** Back
1. Goals

   Identify and agree upon long term goal(s)

2. Outcomes

   Create an outcomes framework by [[id:bff6cb4c-8091-4c3d-87a9-397f54218d38][Backcasting]] from long term goal(s) and explain why these preconditions are necessary and sufficient

3. Assumptions

   Make assumptions [[id:fd00fbf2-6b65-442f-90b9-b9d5d64a5fde][explicit]]

4. Evidence

   Develop indicators which will measure the outcomes and assess your performance (see [[id:00886e80-e78f-4f1e-8c85-b97b27af05ac][OKR]])

5. Action

   Identify your next steps based on the outcome

6. Convince

   Create a narrative which explains the logic of this plan and use it to convince necessary stakeholders
*** Source
[cite:@HowDoesTheoryChangeWork]
** Compare and contrast :fc:
:PROPERTIES:
:CREATED: [2022-11-16 Wed 08:25]
:FC_CREATED: 2022-11-16T16:28:31Z
:FC_TYPE:  normal
:ID:       1a95ea33-ea93-4e1c-8463-aa7987b688aa
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 3.10 |   7 |   378.01 | 2024-07-06T13:39:10Z |
:END:

[[id:cb4d578c-d0d4-4056-aad1-c6ee153eb42f][Theory of change]] and [[id:ab452878-389a-4a13-b659-903b7db10997][Theory of action]]

*** Back
- [[id:ab452878-389a-4a13-b659-903b7db10997][Theory of action]]
  - Works forward from where you are right now toward the goal
  - Focuses on what you will do to try and affect change
- [[id:cb4d578c-d0d4-4056-aad1-c6ee153eb42f][Theory of change]]
  - Works backward from the goal to the present; not you -- the present
  - Describes how change happens in a [[id:c73b15fa-a2bc-48bc-8f3d-6edffc332da1][System]], regardless of anything you do or don't do

*** Source
[cite:@tyrrelTheoryChangeTheoryActionWhatDifferenceWhyDoesItMatter2019]
** Cloze :fc:
:PROPERTIES:
:CREATED: [2022-11-29 Tue 09:49]
:FC_CREATED: 2022-11-29T17:50:40Z
:FC_TYPE:  cloze
:ID:       073465bb-f089-4784-b1bc-8de3f2982798
:FC_CLOZE_MAX: 1
:FC_CLOZE_TYPE: deletion
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
|        0 | 2.80 |   7 |   321.17 | 2024-04-21T18:56:12Z |
|        1 | 2.65 |   7 |   283.86 | 2024-04-01T22:04:51Z |
:END:

A [[id:cb4d578c-d0d4-4056-aad1-c6ee153eb42f][Theory of change]] explicitly notes {{assumptions}@0} and {{ways to measure progress}@1}.

*** Source
[cite:@TheoryChange2022]
#+print_bibliography: