:PROPERTIES:
:ID:       812da5d9-2917-4f0c-bf2f-36acf64af2c5
:DIR:      /home/cashweaver/proj/roam/attachments/812da5d9-2917-4f0c-bf2f-36acf64af2c5
:LAST_MODIFIED: [2023-11-14 Tue 07:14]
:END:
#+title: This is extremely dangerous to our democracy
#+hugo_custom_front_matter: :slug "812da5d9-2917-4f0c-bf2f-36acf64af2c5"
#+author: Cash Prokop-Weaver
#+date: [2022-02-17 Thu 08:37]
#+filetags: :quote:

#+begin_quote
Sinclair Broadcasting Local News Script refers to the discovery that several local news stations owned by conservative-leaning Sinclair Broadcast Group are routinely forced to read scripts provided to them that push conservative talking points, particularly liberal media bias or fake news. The discovery spread after several videos were made showing dozens of news stations reading the same script.

[cite:@SinclairBroadcastingLocalNewsScript]
#+end_quote

#+begin_quote
I'm extremely proud of the quality, balanced journalism that [proper news brand name of local station] produces. But I'm concerned about the troubling trend of irresponsible, one sided news stories plaguing our country. The sharing of biased and false news has become all too common on social media. More alarming, national media outlets are publishing these same fake stories without checking facts first. Unfortunately, some members of the national media are using their platforms to push their own personal bias and agenda to control 'exactly what people think'. *This is extremely dangerous to our democracy* ...  We understand Truth is neither politically 'left or right.' Our commitment to factual reporting is the foundation of our credibility, now more than ever.

[cite:@SinclairBroadcastingLocalNewsScript], [cite:@SinclairBroadcastGroup2022]
#+end_quote

* Flashcards :noexport:
:PROPERTIES:
:ANKI_DECK: Default
:END:
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-11-15 Tue 08:18]
:FC_CREATED: 2022-11-15T16:20:59Z
:FC_TYPE:  double
:ID:       14401133-ec8e-499a-bc7c-91ae0ebe2071
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.80 |   7 |   309.67 | 2024-04-08T20:20:31Z |
| back     | 2.20 |   8 |   412.90 | 2024-12-31T12:49:57Z |
:END:

[[id:812da5d9-2917-4f0c-bf2f-36acf64af2c5][This is extremely dangerous to our democracy]]

*** Back
- A quote from a speech delivered identically, with small variations for state/local names, by news channels owned by the Sinclair Broadcast Group. The speech went viral after someone collected the videos into one larger, synchronized, video demonstrating just how many stations broadcast the same message.
- Ironic in that the thing that's ... is the system which brought about these broadcasts
*** Source
[cite:@SinclairBroadcastingLocalNewsScript]
* Bibliography
#+print_bibliography:
