:PROPERTIES:
:ID:       3e310bff-729b-429b-9e10-769422c75561
:DIR:      /home/cashweaver/proj/roam/attachments/3e310bff-729b-429b-9e10-769422c75561
:LAST_MODIFIED: [2023-09-12 Tue 05:24]
:END:
#+title: This sentence has five words
#+hugo_custom_front_matter: :slug "3e310bff-729b-429b-9e10-769422c75561"
#+author: Cash Prokop-Weaver
#+date: [2022-02-07 Mon 17:05]
#+filetags: :quote:
#+begin_quote
This sentence has five words. Here are five more words. Five-word sentences are fine. But several together become monotonous. Listen to what is happening. The writing is getting boring. The sound of it drones. It's like a stuck record. The ear demands some variety.

Now listen. I vary the sentence length, and I create music. Music. The writing sings. It has a pleasant rhythm, a lilt, a harmony. I use short sentences. And I use sentences of medium length. And sometimes, when I am certain the reader is rested, I will engage him with a sentence of considerable length, a sentence that burns with energy and builds with all the impetus of a crescendo, the roll of the drums, the crash of the cymbals–sounds that say listen to this, it is important.

So write with a combination of short, medium, and long sentences. Create a sound that pleases the reader's ear. Don't just write words. Write music."

[[id:94f3dcc8-dc62-48f1-b15e-8dbb9f23d554][Gary Provost]], [cite:@provost100WaysImproveYourWriting2014]
#+end_quote
* Flashcards
:PROPERTIES:
:ANKI_DECK: Default
:END:
** Describe :fc:
:PROPERTIES:
:CREATED: [2022-11-15 Tue 08:10]
:FC_CREATED: 2022-11-15T16:12:21Z
:FC_TYPE:  double
:ID:       b6a424de-00ca-4548-a067-48e4587e8c5a
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.95 |   7 |   559.11 | 2025-03-24T14:58:57Z |
| back     | 2.35 |   7 |   200.36 | 2023-12-19T09:59:10Z |
:END:

[[id:3e310bff-729b-429b-9e10-769422c75561][This sentence has five words]]

*** Back
A demonstration of varying sentence length to engage the reader.
*** Source
[cite:@provost100WaysImproveYourWriting2014]
#+print_bibliography: