:PROPERTIES:
:ID:       526d55d9-0b10-4385-9d87-4860f787e4d0
:LAST_MODIFIED: [2023-12-09 Sat 14:37]
:END:
#+title: Time tracking in Emacs with org-mode
#+hugo_custom_front_matter: :slug "526d55d9-0b10-4385-9d87-4860f787e4d0"
#+author: Cash Prokop-Weaver
#+date: [2023-11-28 Tue 07:57]
#+filetags: :hastodo:concept:

Tracking time is key to my [[id:0b3c28aa-ab9a-4a99-8dbf-4f22a6e7dee9][Retrospective]] habit(s). I track my personal and professional time in [[id:5ad4f07c-b06a-4dbf-afa5-176f25b0ded7][Emacs]] [[id:4c8c9bb9-7cba-4a9e-89dc-4d0095438126][org-mode]].

Key points:

- Everything is a =TODO= (or at least [[id:f49b7372-f38a-470e-8e1f-d26a64ff4992][80%]] of things)
- Different files for different flows
  - =todos.org=: Catch-all for TODOs
  - =retrospective.org=: Contains daily/weekly/etc retrospectives
- Track time with =org-clock=
- [[id:a875dc68-73f7-44c6-9ee2-09e131e2778b][Personal emacs config]] provides agenda views, customized clock-in and clock-out behavior, [[github:cashpw/clocktable-by-category][=clocktable-by-category=]] for retrospectives
- View =TODO=s with =org-agenda= and =org-super-agenda= (see [[id:a875dc68-73f7-44c6-9ee2-09e131e2778b][Personal emacs config]])

* Workflow
** Daily

Throughout the day I follow this loop:

1. Open my agenda view for today (see [[id:a875dc68-73f7-44c6-9ee2-09e131e2778b][Personal emacs config]])
2. Start work (=clock-in=) on one of:
   - what I've scheduled for this point the day
   - the top-priority unscheduled item
3. When done: =clock-out=
4. Go to step 1

Then, at the end of the day I do a brief retrospective:

1. Open retrospective file
2. Insert a new heading for the current day
3. Insert a [[github:cashpw/clocktable-by-category][=clocktable-by-category=]]
4. Review where my time went during the day
5. Reschedule any items I didn't get to (and think about why)

** Weekly

1. Open my retrospective file
2. Insert a new heading for the current week
3. Insert a [[github:cashpw/clocktable-by-category][=clocktable-by-category=]]
4. Review where my time went during the week and if I want to make any changes
5. Open my agenda view for planning the week (see [[id:a875dc68-73f7-44c6-9ee2-09e131e2778b][Personal emacs config]])
6. Schedule items such that I'm 60-80% booked each day; leave [[id:e6c3a056-5061-4152-8b12-41f001f637a5][Slack]] in my schedule for unexpected items or for those which take more time than expected

* Scheduling [[id:4c8c9bb9-7cba-4a9e-89dc-4d0095438126][org-mode]] events for different times on different days

Some of my TODOs have schedules which don't mesh with [[id:4c8c9bb9-7cba-4a9e-89dc-4d0095438126][org-mode]]'s model of deadlines and scheduling. [[id:4c8c9bb9-7cba-4a9e-89dc-4d0095438126][org-mode]] doesn't support scheduling a TODO for more than one time:

#+begin_quote
Scheduling an item in Org mode should not be understood in the same way that we understand scheduling a meeting. Setting a date for a meeting is just a simple appointment, you should mark this entry with a simple plain timestamp, to get this item shown on the date where it applies. This is a frequent misunderstanding by Org users. In Org mode, scheduling means setting a date when you want to start working on an action item.

[cite:@DeadlinesSchedulingOrgManual]
#+end_quote

Items have just the one =SCHEUDLED= property. They can have more than one timestamp; however, [[id:4c8c9bb9-7cba-4a9e-89dc-4d0095438126][org-mode]] increments all of the timestamps when you mark the item as =DONE= (see =org-auto-repeat-maybe=) --- not just today's timestamp.

My hack-ish fix is to have duplicate TODOs. That is, for an event that has a different time on weekdays and weekends:

#+begin_src org
,* Do the thing
SCHEDULED: <2023-11-27 Mon 10:00-10:30 ++1w>
,* Do the thing
SCHEDULED: <2023-11-28 Tue 10:00-10:30 ++1w>
,* Do the thing
SCHEDULED: <2023-11-29 Wed 10:00-10:30 ++1w>
,* Do the thing
SCHEDULED: <2023-11-30 Thu 10:00-10:30 ++1w>
,* Do the thing
SCHEDULED: <2023-12-01 Fri 10:00-10:30 ++1w>
,* Do the thing
SCHEDULED: <2023-12-02 Sat 08:00-08:30 ++1w>
,* Do the thing
SCHEDULED: <2023-12-03 Sun 08:00-08:30 ++1w>
#+end_src

This would be annoying if I used the built-in =clocktable= which would show a separate line-item for each TODO:

#+begin_src org
,#+BEGIN: clocktable :block "2023-W48" ...
,#+CAPTION: Clock summary at [2023-11-28 Tue 09:37], for week 2023-W48.
| File           | Headline         |   Time |
|----------------+------------------+--------|
|                | ALL *Total time* | *3:30* |
|----------------+------------------+--------|
| Personal TODOs | *File time*      | *3:30* |
|                | Do the thing     |   0:30 |
|                | Do the thing     |   0:30 |
|                | Do the thing     |   0:30 |
|                | Do the thing     |   0:30 |
|                | Do the thing     |   0:30 |
|                | Do the thing     |   0:30 |
,#+END:
#+end_src

Instead, I use [[github:cashpw/clocktable-by-category][=clocktable-by-category=]] which supports merging duplicate headings into one line-item with a duration equal to the sum of the duration of the duplicates:

#+begin_src org
,#+BEGIN: clocktable-by-category :block "2023-W48" ... :merge-duplicate-headlines t
,#+CAPTION: Clock summary at [2023-11-28 Tue 09:37], for week 2023-W48.
| Category       | Headline         | Time   |
|----------------+------------------+--------|
|                | ALL *Total time* | *3:30* |
|----------------+------------------+--------|
| Personal TODOs | *Category time*  | *3:30* |
|                | Do the thing     | 3:30   |
,#+END:
#+end_src

* TODO [#4] Expand :noexport:
* Flashcards :noexport:
* Footnotes

[fn:1] Example:

#+begin_src org
,* Foo
  <2023-11-28 Tue ++1w>
  <2023-11-29 Wed ++1w>
#+end_src
* Bibliography
#+print_bibliography:
