:PROPERTIES:
:ROAM_REFS: [cite:@tinayoungRiseTraumaEssayCollegeApplications2023]
:ID:       76be72bd-211f-4456-baef-40ba9192629e
:LAST_MODIFIED: [2024-02-15 Thu 07:14]
:END:
#+title: Tina Young | The Rise of the "Trauma Essay" in College Applications
#+hugo_custom_front_matter: :slug "76be72bd-211f-4456-baef-40ba9192629e"
#+author: Cash Weaver
#+date: [2023-08-28 Mon 16:48]
#+filetags: :reference:

[[id:8359e927-a866-4dd1-bfa5-fae9d510a21e][Tina Young]], [cite:@tinayoungRiseTraumaEssayCollegeApplications2023]

* Summary
#+begin_quote
Your story has to be sad enough to gain sympathy but not so sad that it makes you seem beyond help. Just critical enough to inspire change, but not so much that it actually criticizes systemic structures. Just honest enough to seem real, but not so unfiltered that it creates discomfort
#+end_quote
* Thoughts
An example of [[id:3e3e1507-bbc8-42eb-acea-8c73e2ff8ba9][giving the right answers]] and [[id:0a3904f5-1484-4c12-8abb-005c707401e1][Signaling]]. It's not enough to have good grades. You have to have a [[id:11f248cb-2349-4824-aeaa-6a6b207554f5][story]].
* Notes

#+begin_quote
The contents of the story may change. Instead of a difficult immigration experience, it might be the death of a loved one, a chronic illness or a racist encounter. But what remains constant is the moral: A bad thing happened to me, but it made me a good person. [...] This is part of a larger phenomenon that I'm here to talk about today. The overwhelming pressure being put on high school students to write about their deepest traumas in their college applications with the hopes that they seem resilient and interesting enough to be given a spot. [...]

Take, for example, this tip from the MIT admissions blog, where the author compares two different introductions for a potential essay. The first one reads:

"I'm honored to apply for the Master of Library Science program at the University of Okoboji. For as long as I can remember, I've had a love affair with books. Since I was 11, I've wanted to be a librarian."

The second introduction reads:

"When I was 11, my great aunt Gretchen passed away and left me something that changed my life: a library of about 5000 books. Some of my best days were spent arranging and reading her books. Since then, I've wanted to become a librarian."

The author notes that the second introduction is much more striking and leaves a much better impression.
#+end_quote

#+begin_quote
I think that this is a problem that goes much deeper than individual universities, and even perhaps the institution of higher education itself. It's rooted in the cultural obsession with appropriating trauma and making it consumable, as well as the systemic tendency to tokenize oppressed people and their experiences.
#+end_quote

#+begin_quote
But there are still things that universities can do to make things better.

First, they can be more transparent about their admissions guidelines. If it's really true that they don't want to reward trauma storytelling just for the sake of it, then they should be more forthcoming about this expectation. They could also restructure their prompts to avoid putting pressure on students to talk about past hardships and adversities and instead refocus prompts to ask students about their goals for the future and their academic interests.
#+end_quote

This doesn't seem realistic. This strategy is only effective when the university doesn't call explicit attention to it so they have no incentive. The guidelines may be intentional in that the vagueness allows for candidates to stand out through interpreting the guidelines differently.

#+begin_quote
I can't help but wonder: what would I have written about if I got the chance to apply to UBC again? This time absent the pressure to strategically use my immigrant background to gain sympathy points. Maybe I would have written about how I overcame my fear of public speaking and became comfortable with being the loudest voice in the room. Or I could have written about watching trashy reality television is what first sparked my interest in political science.

Or maybe I still would have written about my immigrant story because that was a big part of my life journey and still impacts me to this day. But I would have done it on my own terms. Instead of being written as a one-dimensional, trauma-turned-triumph trauma drama, I would have been able to tell a story that actually reflects who I am today and acknowledge the fact that my journey is ongoing and it doesn't begin or end with my racial identity.

This is the kind of ownership that I wish for everyone to one day have over their story. And now it's up for universities to decide whether they get to tell it.
#+end_quote

* Flashcards :noexport:
* Bibliography
#+print_bibliography:
