:PROPERTIES:
:ID:       d9d7eb07-0406-4290-95e7-da94837821cc
:LAST_MODIFIED: [2023-12-25 Mon 10:54]
:ROAM_REFS: [cite:@sallyHomemadeVanillaExtractIngredients2019]
:END:
#+title: Vanilla extract
#+hugo_custom_front_matter: :slug "d9d7eb07-0406-4290-95e7-da94837821cc"
#+author: Cash Prokop-Weaver
#+date: [2023-12-24 Sun 08:20]
#+filetags: :recipe:

Sally, [cite:@sallyHomemadeVanillaExtractIngredients2019]

* Ingredients

For double-fold (recommended) use twice as much vanilla bean.

#+begin_ingredients
| Ingredients        | Notes    | Quantity  |
|--------------------+----------+-----------|
| Whole vanilla bean |          | 100 grams |
| Vodka              | 80 proof | 1 liter   |
#+end_ingredients

#+begin_quote
- Madagascar Vanilla – very common and has a creamy and rich flavor
- Mexican Vanilla – has a darker, almost smoky flavor
- Tahitian Vanilla – also very common and has a rich floral flavor
#+end_quote

* Steps

1. Using a sharp knife, slit the vanilla beans so the beans are exposed. No need to completely split the bean in half, just slit down the middle. If the length of the vanilla beans don't fit into your bottle or jar, cut the vanilla beans into smaller pieces. Place beans into bottle or jar.
1. Pour vodka on top. A funnel helps. Use a little extra vodka, if needed, so the beans are fully submerged. Shake a few times.
1. Store vanilla at room temperature out of direct sunlight. Shake about once per week or once every couple weeks. Vanilla can be ready to use in as little as 8 weeks, but I recommend at least 6 months for optimal flavor. 12+ months is great!
1. As you begin to use your vanilla, you can refill with a little vodka each time. Give it a shake after you refill and give it a shake before each use, too. If you're gifting the vanilla or if you don't have any more alcohol to refill, remove the beans completely after first use. The beans will become a little slimy if they aren't almost fully submerged.
1. Unused aged vanilla extract (with the beans fully submerged) will last several years. If it still smells good, it's still good to use! Aged extract without the beans will last indefinitely. Once you begin using the vanilla and adding more alcohol after each use, the beans will eventually need to be replaced. It's hard to give a specific amount of time as some may use (and refill) the vanilla more quickly than others. After about 1 year of frequent use and refilling, you will you find the vanilla flavor less intense. Simply remove old beans, add fresh beans, shake, and continue to use/refill.

* Flashcards :noexport:

* Bibliography
#+print_bibliography:
