:PROPERTIES:
:ID:       c69643f9-5c87-4b75-8a07-3e87767a567f
:DIR:      /home/cashweaver/proj/roam/attachments/c69643f9-5c87-4b75-8a07-3e87767a567f
:LAST_MODIFIED: [2023-09-05 Tue 20:18]
:END:
#+title: We live in a society
#+hugo_custom_front_matter: :slug "c69643f9-5c87-4b75-8a07-3e87767a567f"
#+author: Cash Prokop-Weaver
#+date: [2022-02-15 Tue 09:29]
#+filetags: :concept:

#+begin_quote
Though [the Joker] never canonically said it until now, the phrase "We live in a society" was wildly popular among those who felt that they, too, were ostracized. These self-declared social rejects not only celebrated their otherness, but also mocked those who were still "in" with the rest of society as sheep. According to this edgy Joker fan logic, those who broke away from the collective were innately better than those who stayed.

And as with most edgelord thought, the meme backfired. Instead of praising them as philosophical gods, society used the meme to ridicule those who thought they were being deep. The meme returned with force in 2018 when trailers for Joker dropped. Internet users began replying to fake-profound statements with "We live in a society," or pairing the phrase with otherwise innocuous images as a Dadaist non sequitur.

[cite:@sungUnfortunatelyWeLiveSociety2021]
#+end_quote

Also used as a shorthand to imply a longer explanation when discussing actual inequities or injustices in society.

- Bob: "Why are people in the USA able to join the military at age 18 when they're not allowed to drink alcohol until they're 21?".
- Alice: "Because [[id:c69643f9-5c87-4b75-8a07-3e87767a567f][We live in a society]]."

Related: [[id:3aea1e2f-dd21-4c21-a8c9-7efd610424c4][Moloch]], [[id:5d2ca4dd-4c57-43f1-996d-f76540f45fa1][Capitalism]]
* Flashcards
:PROPERTIES:
:ANKI_DECK: Default
:END:
#+print_bibliography: