:PROPERTIES:
:ID:       9d035357-9aba-44e8-afe5-fc4f42d0722b
:LAST_MODIFIED: [2023-01-12 Thu 10:51]
:ROAM_ALIASES: "Why attend university?"
:END:
#+title: Why attend college?
#+hugo_custom_front_matter: :slug "9d035357-9aba-44e8-afe5-fc4f42d0722b"
#+author: Cash Prokop-Weaver
#+date: [2023-01-12 Thu 10:45]
#+filetags: :concept:

I may reformat this note by compressing in into a larger one or splitting it up further. It's the best place I have for the moment.

In no particular order:

- Community, social skills, comraderie, networking, friends
- Access to speicfic people, resources, tools, clubs, networks, etc
  - This can include the education itself, though most of that is available without attending a university
- [[id:0a3904f5-1484-4c12-8abb-005c707401e1][Signaling]] (see [[id:8ecb934d-da88-40f4-851b-1fd5f2efd0ad][Bryan Caplan | The Case against Education]]); employers are more interested in those with a degree
- External motivation or accountability; some people benefit more from external pressures (e.g. tests, assignments, an actual instructor who looks them in the eye) than others

Why not attend?

- Expense
- Time commitment; you can drive your own learning faster (see [[id:d737d99b-5154-41f2-8b31-7c3ba860d4e0][There's no speed limit]])

Note that there's nothing stopping you from attending a university /and/ driving your own education. It'll take more work but it's possible. You don't only have to learn things that you're told to learn.

* Flashcards
