:PROPERTIES:
:ROAM_REFS: [cite:@irvineGuideGoodLifeAncientArtStoicJoy2009]
:ID:       6008760e-bfc5-461b-a669-c2d5af58b291
:LAST_MODIFIED: [2024-02-15 Thu 17:00]
:END:
#+title: William Braxton Irvine | A Guide to the Good Life: The Ancient Art of Stoic Joy
#+hugo_custom_front_matter: :slug "6008760e-bfc5-461b-a669-c2d5af58b291"
#+author: Cash Weaver
#+date: [2024-02-15 Thu 17:00]
#+filetags: :hastodo:reference:

TODO_AUTHOR, [cite:@irvineGuideGoodLifeAncientArtStoicJoy2009]

* TODO Summary
* TODO Thoughts
* TODO Notes
A Guide to the Good Life: The Ancient Art of Stoic Joy (William Braxton Irvine)
- Your Highlight on page 7 | Location 98-100 | Added on Friday, June 26, 2015 11:27:59 PM

I saw no need to ponder a philosophy of life. I instead felt comfortable with  what is, for almost everyone, the default philosophy of life: to spend one's days seeking an interesting mix of affluence, social status, and pleasure. My philosophy of life, in other words, was what might charitably be called an enlightened form of hedonism.
==========
A Guide to the Good Life: The Ancient Art of Stoic Joy (William Braxton Irvine)
- Your Highlight on page 8 | Location 114-133 | Added on Friday, June 26, 2015 11:30:57 PM

To begin with, I knew that the dictionary defines a stoic as "one who is seemingly indifferent to or unaf-fected by joy, grief, pleasure, or pain."3 I therefore expected that the uppercase-S Stoics would be lowercase-s stoical—that they would be emotionally repressed individuals. I discovered, though, that the goal of the Stoics was not to banish emotion from life but to banish negative emotions. When I read the works of the Stoics, I encountered individuals who were cheerful and optimistic about life (even though they made it a point to spend time thinking about all the bad things that could happen to them) and who were fully capable of enjoying life's pleasures (while at the same time being careful not to be enslaved by those pleasures). I also encountered, much to my surprise, individuals who valued joy; indeed, according to Seneca, what Stoics seek to discover "is how the mind may always pursue a steady and favourable course, may be well-disposed towards itself, and may view its conditions with joy."4 He also asserts that someone who practices Stoic principles "must, whether he wills or not, necessarily be attended by constant cheerfulness and a joy that is deep and issues from deep within, since he finds delight in his own resources, and desires no joys greater than his inner joys."5 Along similar lines, the Stoic philosopher Musonius Rufus tells us that if we live in accordance with Stoic principles, "a cheerful disposition and secure joy" will automatically follow.6 Rather than being passive individuals who were grimly resigned to being on the receiving end of the world's abuse and injustice, the Stoics were fully engaged in life and worked hard to make the world a better place. Consider, for example, Cato the Younger. (Although he did not contribute to the literature of Stoicism, Cato was a practicing Stoic; indeed, Seneca refers to him as the perfect Stoic.)7 His Stoicism did not prevent Cato from fighting bravely to restore the Roman republic. Likewise, Seneca seems to have been remarkably energetic: Besides being a philosopher, he was a successful playwright, an advisor to an emperor, and the first-century equivalent of an investment banker. And Marcus Aurelius, besides being a philosopher, was a Roman emperor—indeed, arguably one of the greatest Roman emperors. As I read about the Stoics, I found myself filled with admiration for them. They were courageous, temperate, reasonable, and self-disciplined—traits I would like to possess. They also thought it important for us to fulfill our obligations and to help our fellow humans—values I happen to share.
==========
A Guide to the Good Life: The Ancient Art of Stoic Joy (William Braxton Irvine)
- Your Highlight on page 9 | Location 133-134 | Added on Friday, June 26, 2015 11:31:02 PM

we are unlikely to have a good and meaningful life unless we can overcome our insatiability.
==========
A Guide to the Good Life: The Ancient Art of Stoic Joy (William Braxton Irvine)
- Your Highlight on page 9 | Location 135-135 | Added on Friday, June 26, 2015 11:31:17 PM

persuade ourselves to want the things we already have.
==========
A Guide to the Good Life: The Ancient Art of Stoic Joy (William Braxton Irvine)
- Your Highlight on page 10 | Location 151-151 | Added on Friday, June 26, 2015 11:34:25 PM

The challenge I faced in writing this book was to construct such a plan from clues scattered throughout Stoic writings.
==========
A Guide to the Good Life: The Ancient Art of Stoic Joy (William Braxton Irvine)
- Your Highlight on page 10 | Location 153-164 | Added on Friday, June 26, 2015 11:35:30 PM

We will reconsider our goals in living. In particular, we will take to heart the Stoic claim that many of the things we desire—most notably, fame and fortune—are not worth pursuing. We will instead turn our attention to the pursuit of tranquility and what the Stoics called virtue. We will discover that Stoic virtue has very little in common with what people today mean by the word. We will also discover that the tranquility the Stoics sought is not the kind of tranquility that might be brought on by the ingestion of a tranquilizer; it is not, in other words, a zombie-like state. It is instead a state marked by the absence of negative emotions such as anger, grief, anxiety, and fear, and the presence of positive emotions—in particular, joy. We will study the various psychological techniques developed by the Stoics for attaining and maintaining tranquility, and we will employ these techniques in daily living. We will, for example, take care to distinguish between things we can control and things we can't, so that we will no longer worry about the things we can't control and will instead focus our attention on the things we can control. We will also recognize how easy it is for other people to disturb our tranquility, and we will therefore practice Stoic strategies to prevent them from upsetting us. Finally, we will become a more thoughtful observer of our own life. We will watch ourselves as we go about our daily business and will later refl ect on what we saw, trying to identify the sources of distress in our life and thinking about how to avoid that distress.
==========
A Guide to the Good Life: The Ancient Art of Stoic Joy (William Braxton Irvine)
- Your Highlight on page 12 | Location 184-186 | Added on Friday, June 26, 2015 11:39:50 PM

Although modern philosophers tend to spend their days debating esoteric topics, the primary goal of most ancient philosophers was to help ordinary people live better lives. Stoicism, as we shall see, was one of the most popular and successful of the ancient schools of philosophy.
==========
A Guide to the Good Life: The Ancient Art of Stoic Joy (William Braxton Irvine)
- Your Highlight on page 13 | Location 196-196 | Added on Friday, June 26, 2015 11:40:24 PM

philosophy of life
==========
A Guide to the Good Life: The Ancient Art of Stoic Joy (William Braxton Irvine)
- Your Highlight on page 13 | Location 196-198 | Added on Friday, June 26, 2015 11:40:50 PM

I wrote this book with the following question in mind: If the ancient Stoics had taken it upon themselves to write a guidebook for twenty-first-century individuals—a book that would tell us how to have a good life—what might that book have looked like? The pages that follow are my answer to this question.
==========

* Bibliography
#+print_bibliography:
* TODO [#2] Flashcards :noexport:
