:PROPERTIES:
:ID:       3403366f-af9a-42f8-9352-f4a7097be1f5
:LAST_MODIFIED: [2023-09-19 Tue 16:53]
:ROAM_REFS: [cite:@perlmonksXYProblem] [cite:@gregswikiXyProblem] [cite:@AnswerWhatXYProblem2010] [cite:@XYProblem2023]
:END:
#+title: XY problem
#+hugo_custom_front_matter: :slug "3403366f-af9a-42f8-9352-f4a7097be1f5"
#+author: Cash Prokop-Weaver
#+date: [2023-07-27 Thu 08:31]
#+filetags: :concept:

#+begin_quote
You want to do X, and you think Y is the best way of doing so. Instead of asking about X, you ask about Y.

[cite:@perlmonksXYProblem]
#+end_quote

#+begin_quote
The XY problem is a communication problem encountered in help desk, technical support, software engineering, or customer service situations where the question is about an end user's attempted solution (Y) rather than the root problem itself (X)

[cite:@XYProblem2023]
#+end_quote

#+begin_quote
The X-Y Problem, as it is sometimes called, occurs when a person tries to solve a problem on their own, pursues a method that seems like a promising approach, gets stuck, and then asks for help with their chosen method (instead of asking for help with the original problem).

In reality, the method on which they got stuck may be the longest/most complicated route to the answer. The best way to solve the problem is to start over.

In other words:

1. User wants to do X.
1. User doesn't know how to do X, but thinks they can fumble their way to a solution if they can just manage to do Y.
1. User doesn't know how to do Y either.
1. User asks for help with Y.
1. Others try to help user with Y, but are confused because Y seems like a strange problem to want to solve.
1. After much interaction and wasted time, it finally becomes clear that the user really wants help with X, and that Y was a dead end.

[cite:@gregswikiXyProblem]
#+end_quote

#+begin_quote
The [[http://www.perlmonks.org/index.pl?node_id=542341][XY]] [[https://mywiki.wooledge.org/XyProblem][problem]] is asking about your attempted /solution/ rather than your /actual problem./

That is, you are trying to solve problem /X/, and you think solution /Y/ would work, but instead of asking about /X/ when you run into trouble, you ask about /Y./

[cite:@AnswerWhatXYProblem2010]
#+end_quote

* Flashcards
** Definition :fc:
:PROPERTIES:
:CREATED: [2023-07-27 Thu 08:36]
:FC_CREATED: 2023-07-27T15:36:28Z
:FC_TYPE:  double
:ID:       298a035f-4d79-479e-b5d3-4dc73e3472da
:END:
:REVIEW_DATA:
| position | ease | box | interval | due                  |
|----------+------+-----+----------+----------------------|
| front    | 2.35 |   5 |    36.31 | 2023-10-01T22:06:30Z |
| back     | 2.50 |   5 |    34.01 | 2023-10-24T00:04:28Z |
:END:

[[id:3403366f-af9a-42f8-9352-f4a7097be1f5][XY problem]]

*** Back
#+begin_quote
You want to do X, and you think Y is the best way of doing so. Instead of asking about X, you ask about Y.
#+end_quote
*** Source
[cite:@perlmonksXYProblem]
#+print_bibliography: