:PROPERTIES:
:ROAM_REFS: [cite:@tellmanStandingShadowGiants]
:ID:       b6ec05a1-d6cf-4342-9d4a-7ca50521a478
:LAST_MODIFIED: [2023-09-05 Tue 20:20]
:END:
#+title: Zach Tellman | Standing in the Shadow of Giants
#+hugo_custom_front_matter: :slug "b6ec05a1-d6cf-4342-9d4a-7ca50521a478"
#+author: Cash Prokop-Weaver
#+date: [2022-11-12 Sat 08:59]
#+filetags: :reference:

[[id:cf4225ad-fa19-419e-90a6-bac3b45d1764][Zach Tellman]], [cite:@tellmanStandingShadowGiants]

* Summary
Those who want to build may not want to maintain/administer.
* Notes

#+begin_quote
Consider this excerpt from John Mason Peck's A New Guide For Emigrants to the West, written almost ten years before "manifest destiny" was invented:

First comes the pioneer, who depends for the subsistence of his family chiefly upon the natural growth of vegetation, called the "range," and the proceeds of hunting. His implements of agriculture are rude [and] chiefly of his own make…. He builds his cabin, gathers around him a few other families of similar tastes and habits, and occupies till the range is somewhat subdued, and hunting a little precarious, or, which is more frequently the case, till the neighbors crowd around, roads, bridges, and fields annoy him, and he lacks elbow room. The preëmption law enables him to dispose of his cabin and cornfield to the next class of emigrants; and, to employ his own figures, he "breaks for the high timber," "clears out for the New Purchase," or migrates to Arkansas or Texas, to work the same process over…. [T]he real Eldorado is still farther on.

A similar pattern can be seen in the open source community. There has been, for instance, a consistent migratory pattern from Ruby to node.js to Go, Rust, and Elixir. At first, each community is defined by its potential. But as that potential is realized, the community begins to be defined by its compromises. That change is felt most keenly by the people who were there first, who remember what it was like when anything seemed possible. They feel fenced in and so they move on, in search of their golden city.

[...]

For some people, creating widely used software is highly rewarding, and the administrative responsibilities it introduces are a small price to pay. For others, especially those who chase the frontiers of open source, loss of ownership leads to a loss of interest. By letting a project grow too large, they effectively chase themselves away.
#+end_quote

* Flashcards
#+print_bibliography: